### ISSUE TITLE
页面滑动时,小窗口隐藏和显示出现崩溃

### ISSUE THREAD

**Issue by darkrevier** [CarGuo/GSYVideoPlayer#1074]
出现崩溃
java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3823)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16446)
                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3844)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3824)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16446)
                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3844)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3824)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16446)
                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3844)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3824)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16446)
                                                                        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3844)
                                                                        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3824)
                                                                        at android.view.View.updateDisplayListIfDirty(View.java:16446)
                                                                        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:653)
                                                                        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:659)
                                                                        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:767)
                                                                        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3231)
                                                                        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3018)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2603)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1496)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7131)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:924)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:726)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:660)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:910)
                                                                        at android.os.Handler.handleCallback(Handler.java:836)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                        at android.os.Looper.loop(Looper.java:203)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6451)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1134)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

我的代码监听ScrollView,然后上下滑动
scrollView.setOnScrollChanged(new ScrollView.OnScrollChangedListener() {
            @Override
            public void onScrollChanged(int l, int t, int oldl, int oldt) {
               
                Rect childRect = new Rect();
                videoplayer.getGlobalVisibleRect(childRect);
                boolean newStatus = childRect.bottom < topLine;

                if(newStatus!=isComplateHided){
                    isComplateHided= newStatus;

                    if(isComplateHided){
                        //显示悬浮窗
                        if (!smallVideoHelper.isSmall()) {
                       
                            smallVideoHelper.showSmallVideo(new Point(targetWidth, targetHeight), false, true);
                        
                    }else {
                        //隐藏悬浮窗
                        if (smallVideoHelper.isSmall()) {
                            smallVideoHelper.smallVideoToNormal();
                        }
                    }
                }
            }
        });

**Comment by darkrevier** [comment]
在网上查这个问题,然后在hideSmallVideo的removeVideo方法设置handler
    /**
     * 隐藏小窗口
     */
    @SuppressWarnings("ResourceType")
    public void hideSmallVideo() {
        final ViewGroup vp = (CommonUtil.scanForActivity(getContext())).findViewById(Window.ID_ANDROID_CONTENT);
        GSYVideoPlayer gsyVideoPlayer = (GSYVideoPlayer) vp.findViewById(getSmallId());
        if (gsyVideoPlayer !=null){
            vp.post(new Runnable() {
                @Override
                public void run() {
                    removeVideo(vp, getSmallId());
                }
            });
        }
但是会出现只有声音 没有画面的现象
求救这个问题应该怎么解决

**Comment by darkrevier** [comment]
@CarGuo

**Comment by CarGuo** [comment]
demo中哪个页面复现？

**Comment by darkrevier** [comment]
@CarGuo 我是在ScrollView里监听滑动做处理,Demo中并没有这种例子

**Comment by CarGuo** [comment]
额···demo没法复现，我这边很难看出问题

**Comment by darkrevier** [comment]
@CarGuo 解决了

**Comment by LDJHXM** [comment]
我这边也是页面滑动的时候显示和隐藏小窗口会报一样的错 请问怎么解决的?也是在scrollView中监听滑动距离来显示和隐藏小窗口 @CarGuo @darkrevier
