### ISSUE TITLE
完整版引入  implementation 'com.shuyu:GSYVideoPlayer:5.0.0-beta'

### ISSUE THREAD

**Issue by ishangxue** [CarGuo/GSYVideoPlayer#1136]

**Comment by ishangxue** [comment]
构建失败 
Program type already present: android.support.v4.media.MediaDescriptionCompat
Message{kind=ERROR, text=Program type already present: android.support.v4.media.MediaDescriptionCompat, sources=[Unknown source file], tool name=Optional.of(D8)}

**Comment by CarGuo** [comment]
可以正常构建，该问题不属于库问题

**Comment by CarGuo** [comment]
单从这个log看不出来

**Comment by ishangxue** [comment]
我是新建一个工程 空的 ，什么都没做就开始引入 
module 下的 build。gradle内容如下
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.example.ufo.myvideo"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    //完整版引入
    implementation 'com.shuyu:GSYVideoPlayer:5.0.0-beta'

}


【Android issues:】报错如下
Program type already present: android.support.v4.media.MediaDescriptionCompat
Message{kind=ERROR, text=Program type already present: android.support.v4.media.MediaDescriptionCompat, sources=[Unknown source file], tool name=Optional.of(D8)}


【Build:build failed -->Run build --> Run tasks --> 

:app:transformDexArchiveWithExternalLibsDexMergerForDebug | 574ms
-- | --


】报错如下：
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\0.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\2.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\3.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\4.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\5.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\6.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\7.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\8.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\9.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\10.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\11.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\12.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\13.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\14.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\15.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\16.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\17.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\18.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\19.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\20.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\21.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\22.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\23.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\25.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\26.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\28.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\30.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\31.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\32.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\33.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\34.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\35.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\36.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\37.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\38.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\39.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\40.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\41.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\42.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\43.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\44.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\45.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\46.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\47.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\48.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\49.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\50.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\51.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\52.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\53.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\54.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\55.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\56.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\57.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\58.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\59.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\60.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\61.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\62.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\63.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\64.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\65.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\66.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\67.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\68.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\69.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\70.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\71.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\74.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\75.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\76.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\80.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\82.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\84.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\87.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\88.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\89.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\90.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\92.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\93.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\94.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\95.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\96.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\97.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\98.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\99.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\100.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\102.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\103.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\104.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\105.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\106.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\107.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\108.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\109.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\110.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\111.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\112.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\113.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\114.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\115.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\116.jar
	at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 32 more
Caused by: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\0.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\2.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\3.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\4.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\5.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\6.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\7.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\8.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\9.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\10.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\11.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\12.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\13.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\14.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\15.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\16.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\17.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\18.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\19.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\20.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\21.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\22.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\23.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\25.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\26.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\28.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\30.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\31.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\32.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\33.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\34.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\35.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\36.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\37.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\38.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\39.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\40.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\41.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\42.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\43.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\44.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\45.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\46.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\47.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\48.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\49.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\50.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\51.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\52.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\53.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\54.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\55.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\56.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\57.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\58.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\59.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\60.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\61.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\62.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\63.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\64.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\65.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\66.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\67.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\68.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\69.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\70.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\71.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\74.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\75.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\76.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\80.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\82.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\84.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\87.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\88.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\89.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\90.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\92.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\93.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\94.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\95.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\96.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\97.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\98.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\99.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\100.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\102.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\103.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\104.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\105.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\106.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\107.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\108.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\109.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\110.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\111.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\112.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\113.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\114.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\115.jar, E:\AndroidTOOL\workspace\app\build\intermediates\transforms\dexBuilder\debug\116.jar
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:124)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:109)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:101)
	at com.android.build.gradle.internal.transforms.ExternalLibsMergerTransform.transform(ExternalLibsMergerTransform.kt:123)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	... 48 more
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:76)
	at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:45)
	at com.android.tools.r8.D8.run(D8.java:67)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:107)
	... 53 more
Caused by: com.android.tools.r8.utils.AbortException
	at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:77)
	at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:58)
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:67)
	... 56 more


【ps:新手请多指教  @谢谢】

**Comment by CarGuo** [comment]
v7:27.1.1 缓存 27.0.2试试，去掉test相关的所有依赖

**Comment by ishangxue** [comment]
问题依旧  啊

**Comment by hui928636443** [comment]
我也有这个问题！！！

**Comment by hui928636443** [comment]
![image](https://user-images.githubusercontent.com/17092577/40608127-124471b2-629d-11e8-9d01-549d3e901e79.png)

**Comment by CarGuo** [comment]
@hui928636443 你这个是v4包问题

**Comment by CarGuo** [comment]
试试
compile ('com.shuyu:GSYVideoPlayer:5.0.0-beta') {
exclude group: 'com.android.support'
}
