### ISSUE TITLE
5.0.0-beta版本

### ISSUE THREAD

**Issue by sunnyamuren** [CarGuo/GSYVideoPlayer#1172]
问题描述：
在切换到后台在回来，也就是播放的时候 onResume onPause
会一直在load。
demo 是没有问题的，
我用的链接 在ijkPlayer 上一样的操作没有问题
错误的日志如下：
E/Surface: getSlotFromBufferLocked: unknown buffer: 0xee56e5e0

**Comment by CarGuo** [comment]
Demo不复现我没办法定位问题。

**Comment by CarGuo** [comment]
那应该编码和默认内核支持的一些兼容问题

**Comment by sunnyamuren** [comment]
好的，谢谢大神。
我用GSYVideoType.IJKEXOPLAYER2内核，播放一个视频
报错
06-06 21:10:57.125 5288-5394/com.axis.viedodemo E/ExoPlayerImplInternal: Source error.
                                                                         net.butterflytv.rtmp_client.RtmpClient$RtmpIOException
                                                                             at net.butterflytv.rtmp_client.RtmpClient.open(RtmpClient.java:56)
                                                                             at com.google.android.exoplayer2.ext.rtmp.RtmpDataSource.open(RtmpDataSource.java:57)
                                                                             at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:848)
                                                                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                             at java.lang.Thread.run(Thread.java:818)
06-06 21:10:57.128 5288-5330/com.axis.viedodemo E/EventLogger: playerFailed [3.46]
                                                               com.google.android.exoplayer2.ExoPlaybackException
                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:349)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                   at android.os.Looper.loop(Looper.java:227)
                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                Caused by: net.butterflytv.rtmp_client.RtmpClient$RtmpIOException
                                                                   at net.butterflytv.rtmp_client.RtmpClient.open(RtmpClient.java:56)
                                                                   at com.google.android.exoplayer2.ext.rtmp.RtmpDataSource.open(RtmpDataSource.java:57)
                                                                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:848)
                                                                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                   at java.lang.Thread.run(Thread.java:818)

然而 默认的内核 可播放。
测试视频 地址：rtmp://101.132.160.5:1935/live/labcamera10

方便帮我看看么~~~

**Comment by CarGuo** [comment]
如果设置了cache是false也不行就没什么办法了。

看起来是exoplayer的native_open的时候出了问题

**Comment by CarGuo** [comment]
https://github.com/google/ExoPlayer/issues/4200  

https://github.com/ant-media/LibRtmp-Client-for-Android/issues/65
