### ISSUE TITLE
5.0beta版本,点击全屏报错

### ISSUE THREAD

**Issue by darkrevier** [CarGuo/GSYVideoPlayer#1182]
danmakuVideoPlayer.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                danmakuVideoPlayer.startWindowFullscreen(context,false,true);

            }
        });

 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    java.lang.NoSuchFieldError: No field video_shrink of type I in class Lcom/shuyu/gsyvideoplayer/R$drawable; or its superclasses (declaration of 'com.shuyu.gsyvideoplayer.R$drawable' appears in /data/app/com.xxx.demo.beta-2/split_lib_slice_9_apk.apk)
                                                                        at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.getShrinkImageRes(GSYVideoControlView.java:1203)
                                                                        at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.setUp(GSYVideoControlView.java:547)
                                                                        at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.setUp(GSYVideoView.java:391)
                                                                        at com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer.cloneParams(GSYBaseVideoPlayer.java:242)
                                                                        at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.cloneParams(StandardGSYVideoPlayer.java:336)
                                                                        at com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer.startWindowFullscreen(GSYBaseVideoPlayer.java:631)
                                                                        at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.startWindowFullscreen(StandardGSYVideoPlayer.java:361)

**Comment by CarGuo** [comment]
demo中怎么复现
