### ISSUE TITLE
点播退出时播放器报错

### ISSUE THREAD

**Issue by lingchen52** [CarGuo/GSYVideoPlayer#1209]
## 问题描述：

使用继承StandardGSYVideoPlayer的播放器播放视频按返回键退出时，出现IllegalArgumentException，出现几率很高

## 问题机型/系统：

所有Android设备

## Demo中的复现步骤

问题代码：(如果有)
```
//使用代码
       GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKPLAYER);
                    GSYVideoType.setRenderType(GSYVideoType.TEXTURE);
        mVodPlayer.setUp(url, false, name);
        mVodPlayer.setBackgroundColor(getResources().getColor(R.color.color_181818));
        mVodPlayer.startPlayLogic();
        mVodPlayer.setIsTouchWigetFull(true);
        mVodPlayer.setVideoAllCallBack(new SimpleVideoCallBack() {
            @Override
            public void onPrepared(String url, Object... objects) {
                super.onPrepared(url, objects);
                start = App.newtime * 1000;
                starttime = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date(App.newtime * 1000));
            }

            @Override
            public void onAutoComplete(String url, Object... objects) {
                super.onAutoComplete(url, objects);
            }

            @Override
            public void onPlayError(String url, Object... objects) {
                super.onPlayError(url, objects);
            }
        });
    }

    @Override
    protected void onPause() {
        super.onPause();
        mVodPlayer.onVideoPause();
    }

    @Override
    protected void onResume() {
        super.onResume();
        mVodPlayer.onVideoResume();
        mVodPlayer.startPlayLogic();
    }

    @Override
    protected void onStop() {
        super.onStop();
        mVodPlayer.release();
//        upload();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
    }

//StandardGSYVideoPlayer  日志错误处代码
@Override
    protected void dismissBrightnessDialog() {
        if (mBrightnessDialog != null) {
            mBrightnessDialog.dismiss();
            mBrightnessDialog = null;
        }
    }
```

## 问题log（如果有）

```
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{d3e512b V.E..... R....... 0,0-1280,720} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:396)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:322)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
	at android.app.Dialog.dismissDialog(Dialog.java:341)
	at android.app.Dialog.dismiss(Dialog.java:324)
	at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.dismissProgressDialog(StandardGSYVideoPlayer.java:241)
	at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.touchSurfaceUp(GSYVideoControlView.java:714)
	at com.wanlong.iptv.player.VodVideoPlayer.access$600(VodVideoPlayer.java:24)
	at com.wanlong.iptv.player.VodVideoPlayer$1.handleMessage(VodVideoPlayer.java:259)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

```

**Comment by CarGuo** [comment]
demo中怎么复现

**Comment by lingchen52** [comment]
我在一个Android4.2.2的盒子上退出播放时总是出现崩溃，日志里有这一句，不知道是啥意思，望解答
10-27 10:32:25.580 1209-3694/com.wanlong.iptv A/libc: @@@ ABORTING: LIBC: HEAP MEMORY CORRUPTION IN dlfree
    Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 3694 (GSYVideoBaseMan)

**Comment by CarGuo** [comment]
没看明白
