### ISSUE TITLE
暂停状态下，横竖屏切换  ，播放器状态错误  

### ISSUE THREAD

**Issue by woyoudianhuai** [CarGuo/GSYVideoPlayer#1212]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

播放器状态错误 

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

暂停状态下，横竖屏切换。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）
 com.google.android.exoplayer2.ExoPlaybackException
                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:354)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                 at android.os.Looper.loop(Looper.java:166)
                                                                 at android.os.HandlerThread.run(HandlerThread.java:65)
                                                              Caused by: java.lang.IllegalArgumentException
                                                                 at android.media.MediaCodec.native_setSurface(Native Method)
                                                                 at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1967)
                                                                 at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:915)
                                                                 at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:405)
                                                                 at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:372)
                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:858)
                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:829)
                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:811)
                                                                 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:328)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                 at android.os.Looper.loop(Looper.java:166) 
                                                                 at android.os.HandlerThread.run(HandlerThread.java:65) 
```

xxxxxxx

```

**Comment by CarGuo** [comment]
Demo怎么复现

**Comment by woyoudianhuai** [comment]
detailListPlayer  直接先播放视频，点暂停，切换至全屏   我的机型是华为Mate9

**Comment by woyoudianhuai** [comment]
Playback error.
                                                                                com.google.android.exoplayer2.ExoPlaybackException
                                                                                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:441)
                                                                                    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:428)
                                                                                    at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:408)
                                                                                    at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:372)
                                                                                    at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:858)
                                                                                    at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:829)
                                                                                    at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:811)
                                                                                    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:328)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                    at android.os.Looper.loop(Looper.java:136)
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                 Caused by: com.google.android.exoplayer2.mediacodec＝＝＝＝＝＝＝这是必现的，小米手机也一样，这样的情况无法记住位置

**Comment by CarGuo** [comment]
public void setShowPauseCover(boolean showPauseCover) exoplayer模式下设置为false

**Comment by woyoudianhuai** [comment]
好的，thanks
