### ISSUE TITLE
ExoPlayer2 模式下 拖动进度条（范围大些）加载慢且会播放错误

### ISSUE THREAD

**Issue by woyoudianhuai** [CarGuo/GSYVideoPlayer#1247]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

ExoPlayer2 模式下 拖动进度条（范围大些）加载慢且会播放错误（m3u8链接）

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

Source error.
                         com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://202.102.68.149/e5b6579d37bee78b5717b587d33e0253.ts?ts_name=95&k=efee41ea6ef8e0d95180972796f78496-668f-1530113382&ppyunid=159497758&type=m3u8.web.cloudplay&ydpf_pt=1&cpn=32809
                             at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:203)
                             at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
                             at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:45)
                             at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:401)
                             at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:242)
                             at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:272)
                             at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:219)
                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317)
                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                             at java.lang.Thread.run(Thread.java:784)
                          Caused by: java.net.ProtocolException: Received HTTP_PROXY_AUTH (407) code while not using proxy
                             at com.android.okhttp.internal.http.HttpEngine.followUpRequest(HttpEngine.java:902)
                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:412)
                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
                             at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:200)
                             at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147) 
                             at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:45) 
                             at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:401) 
                             at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:242) 
                             at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:272) 
                             at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:219) 
                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:317) 
                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                             at java.lang.Thread.run(Thread.java:784) 

xxxxxxx

```

**Comment by woyoudianhuai** [comment]
设置false 的确没问题了，但是那如果加缓存的话有什么方法么

**Comment by CarGuo** [comment]
参考原来，类似demo一样可自定义playerManager

https://github.com/CarGuo/GSYVideoPlayer/tree/master/app/src/main/java/com/example/gsyvideoplayer/exo   

其中exoplayer用的缓存时SimpleCache，自定义后你可以试试修改缓存

https://github.com/CarGuo/GSYVideoPlayer/blob/master/gsyvideoplayer-exo2/src/main/java/tv/danmaku/ijk/media/exo2/ExoSourceManager.java
