### ISSUE TITLE
startProgressTimer 这里exception了

### ISSUE THREAD

**Issue by wisonic** [CarGuo/GSYVideoPlayer#1270]
model: Redmi 5
[Excetpion: ]
java.lang.OutOfMemoryError: Could not allocate JNI Env
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:729)
	at java.util.Timer.<init>(Timer.java:160)
	at java.util.Timer.<init>(Timer.java:132)
	at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.startProgressTimer(Unknown Source)
	at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.setStateAndUi(Unknown Source)
	at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.onVideoPause(Unknown Source)
	at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.startAfterPrepared(Unknown Source)

**Comment by CarGuo** [comment]
设置 setShowPauseCover 为 false

**Comment by wisonic** [comment]
@CarGuo 这里设置setShowPauseCover 为 false 还是很大概率报相同crash，请问有什么解决办法吗？多谢！

**Comment by CarGuo** [comment]
你发给我看的那个，Could not allocate JNI Env，看起来是so开辟的内存到了极限，播放过的是否有很好的释放了？？？
