### ISSUE TITLE
崩溃OOM

### ISSUE THREAD

**Issue by darkrevier** [CarGuo/GSYVideoPlayer#1306]
07-19 11:40:42.268 946-946/? E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Out of memory
        at java.lang.Thread.nativeCreate(Native Method)
        at java.lang.Thread.start(Thread.java:753)
        at java.util.Timer.<init>(Timer.java:160)
        at java.util.Timer.<init>(Timer.java:132)
        at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.startProgressTimer(GSYVideoControlView.java:861)
        at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.setStateAndUi(GSYVideoControlView.java:332)
        at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.startAfterPrepared(GSYVideoView.java:752)
        at com.video.danmusource.DanmuVideoPlayer.startAfterPrepared(DanmuVideoPlayer.java:566)
        at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.onPrepared(GSYVideoView.java:555)
        at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.onPrepared(GSYVideoControlView.java:591)
        at com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer.onPrepared(GSYBaseVideoPlayer.java:155)
        at com.video.danmusource.DanmuVideoPlayer.onPrepared(DanmuVideoPlayer.java:403)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$1.run(GSYVideoBaseManager.java:247)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

华为mate9

**Comment by CarGuo** [comment]
试试setShowPauseCover 为false

**Comment by darkrevier** [comment]
@CarGuo 还有没有别的好办法 因为我们这要求用户体验高,这样的话会出现重新进黑屏的情况啊 头疼

**Comment by darkrevier** [comment]
@CarGuo 好吧
