### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by darkrevier** [CarGuo/GSYVideoPlayer#1313]
老哥这是什么问题
java.lang.OutOfMemoryError: Failed to allocate a 12 byte allocation with 0 free bytes and 3GB until OOM
	at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView$ProgressTimerTask.run(GSYVideoControlView.java:1026)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by CarGuo** [comment]
查找下以前的issue

**Comment by darkrevier** [comment]
@CarGuo  不好意思 没有找到解决ProgressTimerTask 的问题的方法 我的版本是5.0.1

**Comment by CarGuo** [comment]
设置pausecover为false
