### ISSUE TITLE
加载视频一直处于加载状态

### ISSUE THREAD

**Issue by hy20160705** [CarGuo/GSYVideoPlayer#1329]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

在你提供的demo中播放我的视频流没有问题  但是我引入到我的项目中后 同样的视频流会出现加载失败的情况（频率很高）

## 问题机型/系统：

vivo X9 plus

## Demo中的复现步骤

我是通过demo中这个页面来加载视频的“DetailExoListPlayer” 一层不变引入到我的项目中
PS:因为我的视频流除了.hd格式的流之外 还有.m3u8的格式 所以全部采用了这个来加载
build依赖：
   compile ('com.shuyu:gsyVideoPlayer-java:5.0.1'){
            exclude module: 'support-v7'
            exclude group: 'com.android.support'
    }
    compile 'com.shuyu:gsyVideoPlayer-ex_so:5.0.1'

问题代码：(如果有)
日志：PS ：有时候这个这个错误日志不会出来 但是视频一直处于加载状态
08-01 14:48:23.957 26283-26541/com.hzfree.zhlng I/ExoPlayerImpl: Release 8a35a25 [ExoPlayerLib/2.8.2] [PD1635, vivo X9s Plus, vivo, 25] [goog.exo.core, goog.exo.rtmp]
08-01 14:48:24.003 26283-26541/com.hzfree.zhlng I/ExoPlayerImpl: Init 51fd4e1 [ExoPlayerLib/2.8.2] [PD1635, vivo X9s Plus, vivo, 25]
08-01 14:48:24.005 26283-26541/com.hzfree.zhlng D/EventLogger: state [0.01, false, B]
08-01 14:48:24.006 26283-26541/com.hzfree.zhlng D/EventLogger: sourceInfo [periodCount=3, windowCount=3
08-01 14:48:24.006 26283-26541/com.hzfree.zhlng D/EventLogger:   period [?]
08-01 14:48:24.006 26283-26541/com.hzfree.zhlng D/EventLogger:   period [?]
08-01 14:48:24.006 26283-26541/com.hzfree.zhlng D/EventLogger:   period [?]
08-01 14:48:24.006 26283-26541/com.hzfree.zhlng D/EventLogger:   window [?, false, false]
08-01 14:48:24.006 26283-26541/com.hzfree.zhlng D/EventLogger:   window [?, false, false]
08-01 14:48:24.006 26283-26541/com.hzfree.zhlng D/EventLogger:   window [?, false, false]
08-01 14:48:24.006 26283-26541/com.hzfree.zhlng D/EventLogger: ]
08-01 14:48:24.019 26283-26541/com.hzfree.zhlng D/EventLogger: loading [true]
08-01 14:48:24.872 26283-20225/com.hzfree.zhlng E/LoadTask: Unexpected exception loading stream
                                                            java.lang.IllegalArgumentException
                                                                at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:39)
                                                                at com.google.android.exoplayer2.util.ParsableByteArray.setPosition(ParsableByteArray.java:146)
                                                                at com.google.android.exoplayer2.util.ParsableByteArray.skipBytes(ParsableByteArray.java:158)
                                                                at com.google.android.exoplayer2.video.AvcConfig.buildNalUnitForChild(AvcConfig.java:93)
                                                                at com.google.android.exoplayer2.video.AvcConfig.parse(AvcConfig.java:60)
                                                                at com.google.android.exoplayer2.extractor.flv.VideoTagPayloadReader.parsePayload(VideoTagPayloadReader.java:89)
                                                                at com.google.android.exoplayer2.extractor.flv.TagPayloadReader.consume(TagPayloadReader.java:65)
                                                                at com.google.android.exoplayer2.extractor.flv.FlvExtractor.readTagData(FlvExtractor.java:265)
                                                                at com.google.android.exoplayer2.extractor.flv.FlvExtractor.read(FlvExtractor.java:167)
                                                                at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:856)
                                                                at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                at java.lang.Thread.run(Thread.java:762)

08-01 14:48:32.859 26283-20224/com.hzfree.zhlng E/ExoPlayerImplInternal: Source error.
                                                                         com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
                                                                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:342)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                             at java.lang.Thread.run(Thread.java:762)
                                                                          Caused by: java.lang.IllegalArgumentException
                                                                             at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:39)
                                                                             at com.google.android.exoplayer2.util.ParsableByteArray.setPosition(ParsableByteArray.java:146)
                                                                             at com.google.android.exoplayer2.util.ParsableByteArray.skipBytes(ParsableByteArray.java:158)
                                                                             at com.google.android.exoplayer2.video.AvcConfig.buildNalUnitForChild(AvcConfig.java:93)
                                                                             at com.google.android.exoplayer2.video.AvcConfig.parse(AvcConfig.java:60)
                                                                             at com.google.android.exoplayer2.extractor.flv.VideoTagPayloadReader.parsePayload(VideoTagPayloadReader.java:89)
                                                                             at com.google.android.exoplayer2.extractor.flv.TagPayloadReader.consume(TagPayloadReader.java:65)
                                                                             at com.google.android.exoplayer2.extractor.flv.FlvExtractor.readTagData(FlvExtractor.java:265)
                                                                             at com.google.android.exoplayer2.extractor.flv.FlvExtractor.read(FlvExtractor.java:167)
                                                                             at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:856)
                                                                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                             at java.lang.Thread.run(Thread.java:762) 
08-01 14:48:32.862 26283-26541/com.hzfree.zhlng E/EventLogger: playerFailed [8.86]
                                                               com.google.android.exoplayer2.ExoPlaybackException
                                                                   at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:349)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                   at android.os.Looper.loop(Looper.java:181)
                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: null
                                                                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:342)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                   at java.lang.Thread.run(Thread.java:762)
                                                                Caused by: java.lang.IllegalArgumentException
                                                                   at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:39)
                                                                   at com.google.android.exoplayer2.util.ParsableByteArray.setPosition(ParsableByteArray.java:146)
                                                                   at com.google.android.exoplayer2.util.ParsableByteArray.skipBytes(ParsableByteArray.java:158)
                                                                   at com.google.android.exoplayer2.video.AvcConfig.buildNalUnitForChild(AvcConfig.java:93)
                                                                   at com.google.android.exoplayer2.video.AvcConfig.parse(AvcConfig.java:60)
                                                                   at com.google.android.exoplayer2.extractor.flv.VideoTagPayloadReader.parsePayload(VideoTagPayloadReader.java:89)
                                                                   at com.google.android.exoplayer2.extractor.flv.TagPayloadReader.consume(TagPayloadReader.java:65)
                                                                   at com.google.android.exoplayer2.extractor.flv.FlvExtractor.readTagData(FlvExtractor.java:265)
                                                                   at com.google.android.exoplayer2.extractor.flv.FlvExtractor.read(FlvExtractor.java:167)
                                                                   at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:856)
                                                                   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                   at java.lang.Thread.run(Thread.java:762) 

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
DetailExoListPlayer 是exoplayer的，你试试 DetailListPlayer

**Comment by CarGuo** [comment]
播放内核都不一样。而且detailExoList用的是自定义的。
你如果想用exoplayer内核，就使用DetailListPlayer，然后使用GSYVideoManager.instance().setVideoType(this, GSYVideoType.IJKEXOPLAYER2);

**Comment by hy20160705** [comment]
可以设置进入就默认横屏展示吗

**Comment by CarGuo** [comment]
你把activity设置为横屏不就可以了

**Comment by hy20160705** [comment]
哦了哦了  我再加了这句 GSYVideoType.setShowType(GSYVideoType.SCREEN_MATCH_FULL);就全部填充了  谢谢
