### ISSUE TITLE
出现这错误，是什么原因？

### ISSUE THREAD

**Issue by PiPiCaptain** [CarGuo/GSYVideoPlayer#134]
java.lang.IllegalStateException: mpjni: start: null mp
	at tv.danmaku.ijk.media.player.IjkMediaPlayer._start(Native Method)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.start(Unknown Source)
	at com.shuyu.gsyvideoplayer.GSYVideoPlayer.onClick(Unknown Source)
	at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.onClick(Unknown Source)
	at ****.StudyVideoPlayerStandard.onClick(Unknown Source)
	at android.view.View.performClick(View.java:4444)
	at android.view.View$PerformClick.run(View.java:18440)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5014)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:805)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:621)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by CarGuo** [comment]
看起来像是so没有加载到。

**Comment by PiPiCaptain** [comment]
@CarGuo 有什么解决方法么

**Comment by CarGuo** [comment]
试试问题集锦中的ndk过滤
