### ISSUE TITLE
无法边播边缓存含Cookie的视频链接

### ISSUE THREAD

**Issue by Z-P-J** [CarGuo/GSYVideoPlayer#1407]
## 问题描述：

最近在写一个项目，里面的视频链接需要Cookie才能播放成功。在setMapHeadData()中传入含cookie的请求头，如果setCacheWithPlay()设为false，则可以播放，但效果不理想。如果setCacheWithPlay()设为true，则直接播放不了。

链接：http://pcs.baidu.com/rest/2.0/pcs/file?method=streaming&app_id=250528&type=M3U8_AUTO_480&path=%2F%EF%BC%88%E5%9B%BD%E6%BC%AB%EF%BC%89%E7%A7%A6%E6%97%B6%E6%98%8E%E6%9C%88%E4%B9%8B%E5%A4%A9%E8%A1%8C%E4%B9%9D%E6%AD%8C%EF%BC%881-50%EF%BC%89%2F08.%E5%A4%A9%E8%A1%8C%E4%B9%9D%E6%AD%8C+-+%E6%B5%81%E6%B2%99%E6%97%A0%E5%BD%A2%28Av16189428%2CP8%29.mp4

Cookie：BDUSS=FaNE1SeUJCejg5c2VHRzJWSlR6cTlJLTlTQ1lxbmRyTFQ4TGZNa09lLWE5YTFiQVFBQUFBJCQAAAAAAAAAAAEAAACE1vF7enBqYWJjZGVmZ2h6cGoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJpohluaaIZbLT; PANWEB=1; BAIDUID=D7AF23737A25CC097B61EE7C179E4440:FG=1

User-Agent：netdisk;4.6.2.0;PC;PC-Windows;10.0.10240;WindowsBaiduYunGuanJia

## 问题机型/系统：

无机型和系统限制。

## 问题log

```


09-02 10:34:22.551 28975-29104/com.zpj.baidupan V/IJKMEDIA: setDataSource: path http://127.0.0.1:40718/http%3A%2F%2Fpcs.baidu.com%2Frest%2F2.0%2Fpcs%2Ffile%3Fmethod%3Dstreaming%26app_id%3D250528%26type%3DM3U8_AUTO_480%26path%3D%252F%25EF%25BC%2588%25E5%259B%25BD%25E6%25BC%25AB%25EF%25BC%2589%25E7%25A7%25A6%25E6%2597%25B6%25E6%2598%258E%25E6%259C%2588%25E4%25B9%258B%25E5%25A4%25A9%25E8%25A1%258C%25E4%25B9%259D%25E6%25AD%258C%25EF%25BC%25881-50%25EF%25BC%2589%252F08.%25E5%25A4%25A9%25E8%25A1%258C%25E4%25B9%259D%25E6%25AD%258C%2B-%2B%25E6%25B5%2581%25E6%25B2%2599%25E6%2597%25A0%25E5%25BD%25A2%2528Av16189428%252CP8%2529.mp4
09-02 10:34:22.551 28975-29104/com.zpj.baidupan D/IJKMEDIA: ijkmp_set_data_source(url="http://127.0.0.1:40718/http%3A%2F%2Fpcs.baidu.com%2Frest%2F2.0%2Fpcs%2Ffile%3Fmethod%3Dstreaming%26app_id%3D250528%26type%3DM3U8_AUTO_480%26path%3D%252F%25EF%25BC%2588%25E5%259B%25BD%25E6%25BC%25AB%25EF%25BC%2589%25E7%25A7%25A6%25E6%2597%25B6%25E6%2598%258E%25E6%259C%2588%25E4%25B9%258B%25E5%25A4%25A9%25E8%25A1%258C%25E4%25B9%259D%25E6%25AD%258C%25EF%25BC%25881-50%25EF%25BC%2589%252F08.%25E5%25A4%25A9%25E8%25A1%258C%25E4%25B9%259D%25E6%25AD%258C%2B-%2B%25E6%25B5%2581%25E6%25B2%2599%25E6%2597%25A0%25E5%25BD%25A2%2528Av16189428%252CP8%2529.mp4")
    ijkmp_set_data_source(url="http://127.0.0.1:40718/http%3A%2F%2Fpcs.baidu.com%2Frest%2F2.0%2Fpcs%2Ffile%3Fmethod%3Dstreaming%26app_id%3D250528%26type%3DM3U8_AUTO_480%26path%3D%252F%25EF%25BC%2588%25E5%259B%25BD%25E6%25BC%25AB%25EF%25BC%2589%25E7%25A7%25A6%25E6%2597%25B6%25E6%2598%258E%25E6%259C%2588%25E4%25B9%258B%25E5%25A4%25A9%25E8%25A1%258C%25E4%25B9%259D%25E6%25AD%258C%25EF%25BC%25881-50%25EF%25BC%2589%252F08.%25E5%25A4%25A9%25E8%25A1%258C%25E4%25B9%259D%25E6%25AD%258C%2B-%2B%25E6%25B5%2581%25E6%25B2%2599%25E6%2597%25A0%25E5%25BD%25A2%2528Av16189428%252CP8%2529.mp4")=0
    IjkMediaPlayer_setOptionLong
    IjkMediaPlayer_setLoopCount
    IjkMediaPlayer_native_setLogLevel(1)
    moncleanup
    IjkMediaPlayer_setVolume
    ijkmp_android_set_volume(1.000000, 1.000000)
    ffpipeline_set_volume
    ijkmp_android_set_volume(1.000000, 1.000000)=void
09-02 10:34:22.552 28975-29104/com.zpj.baidupan W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
09-02 10:34:22.552 28975-29104/com.zpj.baidupan D/IJKMEDIA: IjkMediaPlayer_prepareAsync
    ijkmp_prepare_async()
09-02 10:34:22.552 28975-29104/com.zpj.baidupan I/IJKMEDIA: ===== versions =====
    ijkplayer    : k0.8.8
    FFmpeg       : ff3.4--ijk0.8.7--20180103--001
09-02 10:34:22.552 28975-29941/com.zpj.baidupan I/IJKMEDIA: SDL_RunThread: [29941] ff_msg_loop
09-02 10:34:22.552 28975-29104/com.zpj.baidupan I/IJKMEDIA: libavutil    : 55.78.100
09-02 10:34:22.552 28975-29941/com.zpj.baidupan D/IJKMEDIA: message_loop
09-02 10:34:22.552 28975-29104/com.zpj.baidupan I/IJKMEDIA: libavcodec   : 57.107.100
    libavformat  : 57.83.100
    libswscale   : 4.8.100
    libswresample: 2.9.100
    ===== options =====
    player-opts : loop                         = 1
    format-opts : ijkapplication               = 540428004288
    format-opts : ijkiomanager                 = 540661113984
    format-opts : headers                      = Cookie:BDUSS=FaNE1SeUJCejg5c2VHRzJWSlR6cTlJLTlTQ1lxbmRyTFQ4TGZNa09lLWE5YTFiQVFBQUFBJCQAAAAAAAAAAAEAAACE1vF7enBqYWJjZGVmZ2h6cGoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJpohluaaIZbLT; PANWEB=1; BAIDUID=D7AF23737A25CC097B61EE7C179E4440:FG=1
    User-Agent:netdisk;4.6.2.0;PC;PC-Windows;10.0.10240;WindowsBaiduYunGuanJia
    Connection:keep-alive
    format-opts : protocol_whitelist           = async,cache,crypto,file,http,https,ijkhttphook,ijkinject,ijklivehook,ijklongurl,ijksegment,ijktcphook,pipe,rtp,tcp,tls,udp,ijkurlhook,data
    ===================
09-02 10:34:22.552 28975-29941/com.zpj.baidupan D/IJKMEDIA: FFP_MSG_FLUSH:
09-02 10:34:22.553 28975-29104/com.zpj.baidupan D/IJKMEDIA: ijkmp_prepare_async()=0
09-02 10:34:22.553 28975-29942/com.zpj.baidupan I/IJKMEDIA: SDL_RunThread: [29942] ff_vout
09-02 10:34:22.553 28975-29943/com.zpj.baidupan I/IJKMEDIA: SDL_RunThread: [29943] ff_read
09-02 10:34:22.553 28975-29943/com.zpj.baidupan D/IJKMEDIA: Opening 'http://127.0.0.1:40718/http%3A%2F%2Fpcs.baidu.com%2Frest%2F2.0%2Fpcs%2Ffile%3Fmethod%3Dstreaming%26app_id%3D250528%26type%3DM3U8_AUTO_480%26path%3D%252F%25EF%25BC%2588%25E5%259B%25BD%25E6%25BC%25AB%25EF%25BC%2589%25E7%25A7%25A6%25E6%2597%25B6%25E6%2598%258E%25E6%259C%2588%25E4%25B9%258B%25E5%25A4%25A9%25E8%25A1%258C%25E4%25B9%259D%25E6%25AD%258C%25EF%25BC%25881-50%25EF%25BC%2589%252F08.%25E5%25A4%25A9%25E8%25A1%258C%25E4%25B9%259D%25E6%25AD%258C%2B-%2B%25E6%25B5%2581%25E6%25B2%2599%25E6%2597%25A0%25E5%25BD%25A2%2528Av16189428%252CP8%2529.mp4' for reading
09-02 10:34:22.554 28975-29943/com.zpj.baidupan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
09-02 10:34:22.555 28975-29943/com.zpj.baidupan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
09-02 10:34:22.556 28975-29943/com.zpj.baidupan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
09-02 10:34:22.557 28975-29943/com.zpj.baidupan D/IJKMEDIA: request: GET /http%3A%2F%2Fpcs.baidu.com%2Frest%2F2.0%2Fpcs%2Ffile%3Fmethod%3Dstreaming%26app_id%3D250528%26type%3DM3U8_AUTO_480%26path%3D%252F%25EF%25BC%2588%25E5%259B%25BD%25E6%25BC%25AB%25EF%25BC%2589%25E7%25A7%25A6%25E6%2597%25B6%25E6%2598%258E%25E6%259C%2588%25E4%25B9%258B%25E5%25A4%25A9%25E8%25A1%258C%25E4%25B9%259D%25E6%25AD%258C%25EF%25BC%25881-50%25EF%25BC%2589%252F08.%25E5%25A4%25A9%25E8%25A1%258C%25E4%25B9%259D%25E6%25AD%258C%2B-%2B%25E6%25B5%2581%25E6%25B2%2599%25E6%2597%25A0%25E5%25BD%25A2%2528Av16189428%252CP8%2529.mp4 HTTP/1.1
    User-Agent: Lavf/57.83.100
    Accept: */*
    Range: bytes=0-
    Connection: close
    Host: 127.0.0.1:40718
    Icy-MetaData: 1
    Cookie:BDUSS=FaNE1SeUJCejg5c2VHRzJWSlR6cTlJLTlTQ1lxbmRyTFQ4TGZNa09lLWE5YTFiQVFBQUFBJCQAAAAAAAAAAAEAAACE1vF7enBqYWJjZGVmZ2h6cGoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJpohluaaIZbLT; PANWEB=1; BAIDUID=D7AF23737A25CC097B61EE7C179E4440:FG=1
    User-Agent:netdisk;4.6.2.0;PC;PC-Windows;10.0.10240;WindowsBaiduYunGuanJia
    Connection:keep-a
09-02 10:34:22.817 28975-29944/com.zpj.baidupan E/HttpProxyCacheDebuger: Error fetching info from http://pcs.baidu.com/rest/2.0/pcs/file?method=streaming&app_id=250528&type=M3U8_AUTO_480&path=%2F%EF%BC%88%E5%9B%BD%E6%BC%AB%EF%BC%89%E7%A7%A6%E6%97%B6%E6%98%8E%E6%9C%88%E4%B9%8B%E5%A4%A9%E8%A1%8C%E4%B9%9D%E6%AD%8C%EF%BC%881-50%EF%BC%89%2F08.%E5%A4%A9%E8%A1%8C%E4%B9%9D%E6%AD%8C+-+%E6%B5%81%E6%B2%99%E6%97%A0%E5%BD%A2%28Av16189428%2CP8%29.mp4
09-02 10:34:22.833 28975-29944/com.zpj.baidupan W/System.err: java.io.FileNotFoundException: http://pcs.baidu.com/rest/2.0/pcs/file?method=streaming&app_id=250528&type=M3U8_AUTO_480&path=%2F%EF%BC%88%E5%9B%BD%E6%BC%AB%EF%BC%89%E7%A7%A6%E6%97%B6%E6%98%8E%E6%9C%88%E4%B9%8B%E5%A4%A9%E8%A1%8C%E4%B9%9D%E6%AD%8C%EF%BC%881-50%EF%BC%89%2F08.%E5%A4%A9%E8%A1%8C%E4%B9%9D%E6%AD%8C+-+%E6%B5%81%E6%B2%99%E6%97%A0%E5%BD%A2%28Av16189428%2CP8%29.mp4
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
        at com.danikula.videocache.HttpUrlSource.fetchContentInfo(HttpUrlSource.java:136)
09-02 10:34:22.834 28975-29944/com.zpj.baidupan W/System.err:     at com.danikula.videocache.HttpUrlSource.getMime(HttpUrlSource.java:190)
        at com.danikula.videocache.HttpProxyCache.newResponseHeaders(HttpProxyCache.java:60)
        at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:40)
        at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:230)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:51)
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:332)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
09-02 10:34:22.835 28975-29944/com.zpj.baidupan W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)


```

**Comment by CarGuo** [comment]
你用的是哪个版本，新版本应该已经修改过这个问题

**Comment by CarGuo** [comment]
那你可以看看 `ProxyCacheManager` 的  `UserAgentHeadersInjector addHeaders `是否有被调用，map是否正确。 

`HttpUrlSource` 里，`injectCustomHeaders` 是否正确
