### ISSUE TITLE
继承 StandardGSYVideoPlayer 实现自定义播放界面空指针

### ISSUE THREAD

**Issue by lmyDevs** [CarGuo/GSYVideoPlayer#1421]
## 问题描述：
继承 StandardGSYVideoPlayer 出现错误
## 问题机型/系统：
应该是所有，测试机一加三，系统 MIUI10，版本7.1
## Demo中的复现步骤
无
问题代码：(如果有)
```class AudioPlayerView(context: Context): StandardGSYVideoPlayer(context) {

    override fun init(context: Context?) {
        super.init(context)

        viewPlayer.setOnClickListener {
            if (gsyVideoManager.isPlaying){
                onVideoPause()
                release()
            }else{
                startPlayLogic()
            }
        }
    }

    override fun getLayoutId(): Int {
        return R.layout.layout_audio_player
    }
}
```

布局文件
```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:gravity="center_vertical"
    android:orientation="horizontal"
    android:padding="10dp">

    <ImageView
        android:id="@+id/viewPlayer"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/icon_player_play" />

    <SeekBar
        android:id="@+id/viewSeekBar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:progress="20" />

</LinearLayout>
```

## 问题log

```
 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.ViewGroup.getChildCount()' on a null object reference
        at com.shuyu.gsyvideoplayer.render.view.GSYTextureView.addTextureView(GSYTextureView.java:269)
        at com.shuyu.gsyvideoplayer.render.GSYRenderView.addView(GSYRenderView.java:91)
        at com.shuyu.gsyvideoplayer.video.base.GSYTextureRenderView.addTextureView(GSYTextureRenderView.java:116)
        at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.startAfterPrepared(GSYVideoView.java:791)
        at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.onPrepared(GSYVideoView.java:584)
        at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.onPrepared(GSYVideoControlView.java:591)
        at com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer.onPrepared(GSYBaseVideoPlayer.java:155)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$1.run(GSYVideoBaseManager.java:242)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6395)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

```

**Comment by lmyDevs** [comment]
是我写的布局文件不符合标准吗？

**Comment by CarGuo** [comment]
log上不是说了么，没有渲染层的控件啊

**Comment by lmyDevs** [comment]
我只是用来播放音频，应该怎么实现

**Comment by lmyDevs** [comment]
直接添加了一个 view id 为 surface_container，然后设置为 GONE 实现了，如果您不忙的话可否给个播放音频的解决方案

**Comment by CarGuo** [comment]
surface_container 没有是需要的，也只能这样了
