### ISSUE TITLE
全屏播放时下标越界

### ISSUE THREAD

**Issue by 50kg** [CarGuo/GSYVideoPlayer#143]
//这一行报错
detailPlayer.startWindowFullscreen(LivePlayerInfoActivity.this, true, true);
Process: com.liuchao.sanji.movieheaven, PID: 29856
                                                                               java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                                                                                   at java.util.ArrayList.get(ArrayList.java:411)
                                                                                   at com.shuyu.gsyvideoplayer.video.ListGSYVideoPlayer.startWindowFullscreen(ListGSYVideoPlayer.java:84)
                                                                                   at com.liuchao.sanji.movieheaven.ui.live.fragment.LivePlayerInfoActivity$1.onClick(LivePlayerInfoActivity.java:140)
                                                                                   at android.view.View.performClick(View.java:5610)
                                                                                   at android.view.View$PerformClick.run(View.java:22260)
                                                                                   at android.os.Handler.handleCallback(Handler.java:751)

**Comment by CarGuo** [comment]
请参考demo
