### ISSUE TITLE
#main(1) java.lang.IllegalStateException

### ISSUE THREAD

**Issue by clovermwliu** [CarGuo/GSYVideoPlayer#1430]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
 java.lang.IllegalStateException

## 问题机型/系统：

华为 ALP AL00

## 堆栈
```
tv.danmaku.ijk.media.player.IjkMediaPlayer._stop(Native Method)
tv.danmaku.ijk.media.player.IjkMediaPlayer.stop(IjkMediaPlayer.java:531)
com.shuyu.gsyvideoplayer.player.IjkPlayerManager.stop(IjkPlayerManager.java:201)
com.shuyu.gsyvideoplayer.GSYVideoBaseManager.stop(GSYVideoBaseManager.java:458)
cc.intimes.fulishe3.activity.MainPageActivity.doBackPressed(MainPageActivity.java:229)
cc.intimes.fulishe3.activity.BaseActivity.onBackPressed(BaseActivity.java:457)
android.app.Activity.onKeyUp(Activity.java:3140)
android.view.KeyEvent.dispatch(KeyEvent.java:2782)
android.app.Activity.dispatchKeyEvent(Activity.java:3463)
android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:418)
android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5233)
android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5105)
android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4623)
android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4676)
android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4642)
android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4769)
android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4650)
android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4826)
android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4623)
android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4676)
android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4642)
android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4650)
android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4623)
android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4676)
android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4642)
android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4802)
android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4963)
android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2597)
android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2158)
android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2149)
android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2572)
android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
android.os.MessageQueue.nativePollOnce(Native Method)
android.os.MessageQueue.next(MessageQueue.java:379)
android.os.Looper.loop(Looper.java:144)
android.app.ActivityThread.main(ActivityThread.java:7377)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
```

## 日志
```
09-09 23:56:21.751 2378 2378 D KeyEvent: obtain, mHwFlags=1048835
09-09 23:56:21.758 2378 2378 E InputEventSender: Exception dispatching finished signal.
09-09 23:56:21.758 2378 2378 E MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: java.lang.IllegalStateException: mpjni: stop: null mp
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at tv.danmaku.ijk.media.player.IjkMediaPlayer._stop(Native Method)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at tv.danmaku.ijk.media.player.IjkMediaPlayer.stop(IjkMediaPlayer.java:531)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.stop(IjkPlayerManager.java:201)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.stop(GSYVideoBaseManager.java:458)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at cc.intimes.fulishe3.activity.MainPageActivity.doBackPressed(MainPageActivity.java:229)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at cc.intimes.fulishe3.activity.BaseActivity.onBackPressed(BaseActivity.java:457)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.app.Activity.onKeyUp(Activity.java:3140)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.KeyEvent.dispatch(KeyEvent.java:2782)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.app.Activity.dispatchKeyEvent(Activity.java:3463)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:418)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5233)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5105)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4623)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4676)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4642)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4769)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4650)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4826)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4623)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4676)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4642)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4650)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4623)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4676)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4642)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4802)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4963)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2597)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2158)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2149)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2572)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.os.MessageQueue.nativePollOnce(Native Method)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.os.MessageQueue.next(MessageQueue.java:379)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.os.Looper.loop(Looper.java:144)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at android.app.ActivityThread.main(ActivityThread.java:7377)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at java.lang.reflect.Method.invoke(Native Method)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
09-09 23:56:21.762 2378 2378 E MessageQueue-JNI: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
09-09 23:56:21.763 2378 2378 D AndroidRuntime: Shutting down VM
--------- beginning of crash
09-09 23:56:21.772 2378 2378 E AndroidRuntime: FATAL EXCEPTION: main
09-09 23:56:21.772 2378 2378 E AndroidRuntime: Process: cc.intimes.fulishe3, PID: 2378
09-09 23:56:21.772 2378 2378 E AndroidRuntime: java.lang.IllegalStateException: mpjni: stop: null mp
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at tv.danmaku.ijk.media.player.IjkMediaPlayer._stop(Native Method)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at tv.danmaku.ijk.media.player.IjkMediaPlayer.stop(IjkMediaPlayer.java:531)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.stop(IjkPlayerManager.java:201)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.stop(GSYVideoBaseManager.java:458)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at cc.intimes.fulishe3.activity.MainPageActivity.doBackPressed(MainPageActivity.java:229)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at cc.intimes.fulishe3.activity.BaseActivity.onBackPressed(BaseActivity.java:457)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.app.Activity.onKeyUp(Activity.java:3140)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.KeyEvent.dispatch(KeyEvent.java:2782)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.app.Activity.dispatchKeyEvent(Activity.java:3463)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:418)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5233)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5105)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4623)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4676)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4642)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4769)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4650)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4826)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4623)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4676)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4642)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4650)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4623)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4676)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4642)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4802)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4963)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2597)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2158)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2149)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2572)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.os.MessageQueue.nativePollOnce(Native Method)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.os.MessageQueue.next(MessageQueue.java:379)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.os.Looper.loop(Looper.java:144)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:7377)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
09-09 23:56:21.772 2378 2378 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
09-09 23:56:21.774 2378 2378 D MtaSDK : [main(1): null:27] - trackBackground lastForegroundTs:1536508482252
09-09 23:56:21.775 2378 2378 W MtaSDK : [main(1): null:143] - crash happened, but MTA AutoExceptionCaught is desable.
09-09 23:56:21.775 2378 2549 I MtaSDK : [StatService(9563): null:25] - trackBackground duration:98
09-09 23:56:21.776 2378 2378 E MtaSDK :
09-09 23:56:21.776 2378 2378 E MtaSDK : java.lang.IllegalStateException: mpjni: stop: null mp
09-09 23:56:21.776 2378 2378 E MtaSDK : at tv.danmaku.ijk.media.player.IjkMediaPlayer._stop(Native Method)
09-09 23:56:21.776 2378 2378 E MtaSDK : at tv.danmaku.ijk.media.player.IjkMediaPlayer.stop(IjkMediaPlayer.java:531)
09-09 23:56:21.776 2378 2378 E MtaSDK : at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.stop(IjkPlayerManager.java:201)
09-09 23:56:21.776 2378 2378 E MtaSDK : at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.stop(GSYVideoBaseManager.java:458)
09-09 23:56:21.776 2378 2378 E MtaSDK : at cc.intimes.fulishe3.activity.MainPageActivity.doBackPressed(MainPageActivity.java:229)
09-09 23:56:21.776 2378 2378 E MtaSDK : at cc.intimes.fulishe3.activity.BaseActivity.onBackPressed(BaseActivity.java:457)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.app.Activity.onKeyUp(Activity.java:3140)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.KeyEvent.dispatch(KeyEvent.java:2782)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.app.Activity.dispatchKeyEvent(Activity.java:3463)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
09-09 23:56:21.776 2378 2378 E MtaSDK : at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:418)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5233)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5105)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4623)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4676)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4642)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4769)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4650)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4826)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4623)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4676)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4642)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4650)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4623)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4676)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4642)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4802)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4963)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2597)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2158)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2149)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2572)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.os.MessageQueue.nativePollOnce(Native Method)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.os.MessageQueue.next(MessageQueue.java:379)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.os.Looper.loop(Looper.java:144)
09-09 23:56:21.776 2378 2378 E MtaSDK : at android.app.ActivityThread.main(ActivityThread.java:7377)
09-09 23:56:21.776 2378 2378 E MtaSDK : at java.lang.reflect.Method.invoke(Native Method)
09-09 23:56:21.776 2378 2378 E MtaSDK : at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
09-09 23:56:21.776 2378 2378 E MtaSDK : at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
09-09 23:56:21.776 2378 2378 D MtaSDK : [main(1): null:100] - Call the original uncaught exception handler.
09-09 23:56:21.785 2378 2553 I MID : [StatStore(9566): null:22] - read mid from sharedPreferences key=__MTA_DEVICE_INFO__1000001
09-09 23:56:21.792 2378 2553 I MID : [StatStore(9566): null:6] - read mid from InternalStorage
09-09 23:56:21.796 2378 2553 I MID : [StatStore(9566): null:91] - read mid from InternalStorage:xjgf73dLj00g0xWI15pH4HSXJJZ46WKoSjFI6w3WyvB6cUJmi+vXgrY0Hzb7T3ERXVE7gqEZGgp8
09-09 23:56:21.796 2378 2553 W MID : [StatStore(9566): null:126] - org.json.JSONException: Expected ':' after mid at character 57 of {"imei":"868464035477198","mac":"02:00:00:00:00:00","mid"
09-09 23:56:21.801 2378 2553 D MID : [StatStore(9566): null:76] - readNewVersionMidEntity:null
09-09 23:56:21.801 2378 2553 I MtaSDK : [StatStore(9566): null:83] - insert 1 event, content:{"et":4,"ui":"2091757290","mc":"02:00:00:00:00:00","ut":0,"av":"2.1.7","ch":"应用宝","cch":"legu_","mid":"b7a8dbed07d845ef463092306e2861c3326bec23","idx":20,"si":1056823766,"ts":1536508581,"dts":0,"os":1,"midver":"3.6","pcn":"cc.intimes.fulishe3","ov":"27","md":"ALP-AL00","jb":0,"mf":"HUAWEI","ifg":1,"bc":5,"ft":1,"du":98}
09-09 23:56:21.807 2378 2553 I MID : [StatStore(9566): null:22] - read mid from sharedPreferences key=__MTA_DEVICE_INFO__1000001
09-09 23:56:21.814 2378 2553 I MID : [StatStore(9566): null:6] - read mid from InternalStorage
09-09 23:56:21.819 2378 2553 I MID : [StatStore(9566): null:91] - read mid from InternalStorage:xjgf73dLj00g0xWI15pH4HSXJJZ46WKoSjFI6w3WyvB6cUJmi+vXgrY0Hzb7T3ERXVE7gqEZGgp8
09-09 23:56:21.819 2378 2553 W MID : [StatStore(9566): null:126] - org.json.JSONException: Expected ':' after mid at character 57 of {"imei":"868464035477198","mac":"02:00:00:00:00:00","mid"
09-09 23:56:21.819 2378 2553 D MID : [StatStore(9566): null:76] - readNewVersionMidEntity:null
09-09 23:56:21.820 2378 2553 D MtaSDK : [StatStore(9566): null:195] - directStoreEvent insert event to db, event:{"et":4,"ui":"2091757290","mc":"02:00:00:00:00:00","ut":0,"av":"2.1.7","ch":"应用宝","cch":"legu_","mid":"b7a8dbed07d845ef463092306e2861c3326bec23","idx":20,"si":1056823766,"ts":1536508581,"dts":0,"os":1,"midver":"3.6","pcn":"cc.intimes.fulishe3","ov":"27","md":"ALP-AL00","jb":0,"mf":"HUAWEI","ifg":1,"bc":5,"ft":1,"du":98}
```

**Comment by CarGuo** [comment]
麻烦提供下出现问题的链接以及demo中复现步骤

**Comment by clovermwliu** [comment]
@CarGuo  抱歉，我这边是从bugly上报上来的crash，我自己测试时从未出现过该错误
所以没办法提供你需要的信息

可否麻烦你帮忙看下，可能是什么原因导致的

**Comment by clovermwliu** [comment]
@CarGuo

**Comment by clovermwliu** [comment]
对，我确实是会在App退出时，先调用了stop，在调用ReleaseVideo

**Comment by CarGuo** [comment]
退出时直接release就可以了
