### ISSUE TITLE
点击播放出现 Java.lang.ClassCastException: Android.view.ContextThemeWrapper cannot be cast to android.app.Activity

### ISSUE THREAD

**Issue by yaohf** [CarGuo/GSYVideoPlayer#144]
04-07 08:50:45.932 24566-24566/com.example.gsyvideoplayer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.example.gsyvideoplayer, PID: 24566
                                                                            java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
                                                                                at com.shuyu.gsyvideoplayer.GSYVideoPlayer.prepareVideo(GSYVideoPlayer.java:400)
                                                                                at com.shuyu.gsyvideoplayer.GSYVideoPlayer.startButtonLogic(GSYVideoPlayer.java:385)
                                                                                at com.shuyu.gsyvideoplayer.GSYVideoPlayer.onClick(GSYVideoPlayer.java:334)
                                                                                at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.onClick(StandardGSYVideoPlayer.java:290)
                                                                                at android.view.View.performClick(View.java:5207)
                                                                                at android.view.View$PerformClick.run(View.java:21177)
                                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5458)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by CarGuo** [comment]
v7支持包问题，参考demo，建议activity继承AppCompatActivity
