### ISSUE TITLE
点击启动悬浮窗口崩溃

### ISSUE THREAD

**Issue by yuchunshui0613** [CarGuo/GSYVideoPlayer#1502]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
demo哪里复现

**Comment by yuchunshui0613** [comment]
点击悬浮窗口按钮 再次点击启动悬浮窗口崩溃

**Comment by CarGuo** [comment]
我这边测试正常，请确定悬浮窗权限是否正确获取，再确定崩溃log

**Comment by yuchunshui0613** [comment]
java.lang.NoSuchMethodError: No static method canDrawOverlays(Landroid/content/Context;)Z in class Landroid/provider/Settings; or its super classes (declaration of 'android.provider.Settings' appears in /system/framework/framework.jar:classes2.dex)
        at com.example.gsyvideoplayer.utils.floatUtil.Util.hasPermission(Util.java:29)
        at com.example.gsyvideoplayer.utils.floatUtil.FloatPhone.init(FloatPhone.java:60)
        at com.example.gsyvideoplayer.utils.floatUtil.IFloatWindowImpl.show(IFloatWindowImpl.java:70)
        at com.example.gsyvideoplayer.WindowActivity.onViewClicked(WindowActivity.java:98)
        at com.example.gsyvideoplayer.WindowActivity_ViewBinding$1.doClick(WindowActivity_ViewBinding.java:30)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
        at android.view.View.performClick(View.java:4874)
        at android.view.View$PerformClick.run(View.java:20341)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:5958)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)

**Comment by CarGuo** [comment]
https://stackoverflow.com/questions/46173460/why-in-android-o-method-settings-candrawoverlays-returns-false-when-user-has
