### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by diorslau** [CarGuo/GSYVideoPlayer#1507]
就做了一个简单的视频播放页面,代码是参照demo去写的,本地机器测试也没有什么问题,但是打包后发布出去以后umeng有统计到一些空指针的奔溃日志,如下:

日志2的奔溃估计是由日志1引起的, 项目有用到databinding,  但是其他页面都没有类似的错误,就这个播放页的player 会报这个错

日志1:

java.lang.RuntimeException: Unable to resume activity {com.lmr.porn/com.lmr.porn.ui.video.VideoPlayActivity}: java.lang.NullPointerException: Attempt to read from field 'com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer com.lmr.porn.databinding.ActivityVideoPlayBinding.player' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3687)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3727)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2933)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6694)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:780)
Caused by: java.lang.NullPointerException: Attempt to read from field 'com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer com.lmr.porn.databinding.ActivityVideoPlayBinding.player' on a null object reference
	at com.lmr.porn.ui.video.VideoPlayActivity.onResume(VideoPlayActivity.java:217)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
	at android.app.Activity.performResume(Activity.java:7154)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3662)
	... 10 more
java.lang.NullPointerException: Attempt to read from field 'com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer com.lmr.porn.databinding.ActivityVideoPlayBinding.player' on a null object reference
	at com.lmr.porn.ui.video.VideoPlayActivity.onResume(VideoPlayActivity.java:217)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
	at android.app.Activity.performResume(Activity.java:7154)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3662)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3727)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2933)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1618)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6694)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:780)

日志2:

java.lang.NullPointerException: Attempt to invoke virtual method 'int com.shuyu.gsyvideoplayer.utils.OrientationUtils.getIsLand()' on a null object reference
	at com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer$2.run(GSYBaseVideoPlayer.java:313)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5907)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

**Comment by CarGuo** [comment]
```
com.lmr.porn.databinding.ActivityVideoPlayBinding.player' on a null object reference
at com.lmr.porn.ui.video.VideoPlayActivity.onResume
```
manifest配置了吗？？
还是后台回到前台的时候被回收了？？？

**Comment by diorslau** [comment]
manifest 是有配置的
 <activity
            android:name=".ui.video.VideoPlayActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="stateHidden"></activity>

也有可能如你说的是 后台回来以后被释放掉了,  如果是这种情况该如何处理比较好呢?

**Comment by diorslau** [comment]
> ```
> com.lmr.porn.databinding.ActivityVideoPlayBinding.player' on a null object reference
> at com.lmr.porn.ui.video.VideoPlayActivity.onResume
> ```
> manifest配置了吗？？
> 还是后台回到前台的时候被回收了？？？

manifest 是有配置的,跟demo中的一样
也有可能如你说的是 后台回来以后被释放掉了, 如果是这种情况该如何处理比较好呢?

**Comment by CarGuo** [comment]
```
Attempt to read from field 'com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer com.lmr.porn.databinding.ActivityVideoPlayBinding.player' on a null object reference
```
这里是因为 ActivityVideoPlayBinding 为空，要看什么情况下 DataBinding空了

**Comment by diorslau** [comment]
嗯, 这个问题我自己再看下吧, 应该是我本身代码的问题, 另外还有个问题请教下,  我监听的开始按钮事件, 然后这个事件里面做了一些逻辑判断,如果不符合要求,就不能播放,  我目前是这样去做的,但是最后视频还是开始播放了

  @Override
                    public void onClickStartIcon(String url, Object... objects) {

                        MaterialDialog.Builder builder = new MaterialDialog.Builder(mActivity);
                        builder.title("提示");

                        builder.negativeText("取消");
                        builder.onPositive(new MaterialDialog.SingleButtonCallback() {
                            @Override
                            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {

                            }
                        });

                        if(null == mUser){
                            JumpUtils.jumpTo(Router.LOGIN_ACTIVITY);
                        } else if(mVideo.isVip() && null == mUser.getVipExpireTime()){
                            builder.content("当前视频属于会员专属视频,立即加入会员可享受海量高清大片");
                            builder.positiveText("立刻开通");
                            builder.build().show();
                            mBinding.player.getCurrentPlayer().onVideoPause();
                        }else if(mVideo.isVip() && mUser.isVipExpire()){
                            builder.content("您的会员已过期,立即续费可享受海量高清大片");
                            builder.positiveText("立刻续费");
                            builder.build().show();
                            mBinding.player.getCurrentPlayer()
                        } else {
                            super.onClickStartIcon(url, objects);
                        }

                    }
