### ISSUE TITLE
空指针异常getDuration

### ISSUE THREAD

**Issue by shaogz1077** [CarGuo/GSYVideoPlayer#1509]
## 问题描述：
空指针异常 ，有些手机出现getDuration,红米手机会的概率比较多
java.lang.NullPointerException: Attempt to invoke interface method 'long tv.danmaku.ijk.media.player.IMediaPlayer.getDuration()' on a null object reference
	at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.getDuration(Unknown Source)
	at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.setTextAndProgress(Unknown Source)
	at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView$ProgressTimerTask$1.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5291)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

## 问题机型/系统：

红米4A

问题代码：

GSYVideoView.java 文件
  /**
     * 获取当前总时长
     */
    public int getDuration() {
        int duration = 0;
        try {
            duration = (int) GSYVideoManager.instance().getMediaPlayer().getDuration();
        } catch (IllegalStateException e) {
            e.printStackTrace();
            return duration;
        }
        return duration;
    }

GSYVideoManager.java
   public IMediaPlayer getMediaPlayer() {
        if (playerManager != null) {
            return playerManager.getMediaPlayer();
        }
        return null;
    }

代码上有bug，应该给 GSYVideoManager.instance().getMediaPlayer()加一个判null，这样才不会出现空指针，请问这个bug有修复么

**Comment by CarGuo** [comment]
get
