### ISSUE TITLE
全屏切换清晰度后, 退出全屏报错

### ISSUE THREAD

**Issue by zynote** [CarGuo/GSYVideoPlayer#1544]
全屏切换清晰度后, 退出全屏报错

## 问题机型/系统：

例如 真机 一加3T Android7.0 ,as自带模拟器 8.0

## Demo中的复现步骤

demo中的
SmartPickVideo我用这个实现清晰度切换,
但是demo里面的全屏是布局横屏, 所以我用了DetailPlayer类里面的点击全屏的方法, 
但是使用这个在切换清晰度后按返回键报错, 不切换的时候返回是正常的

## 问题log
    java.lang.NullPointerException: Attempt to read from null array
        at com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer.backToNormal(GSYBaseVideoPlayer.java:424)
        at com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer$3.run(GSYBaseVideoPlayer.java:400)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

xxxxxxx

```

**Comment by CarGuo** [comment]
这个你自己断点下那么为空跟踪下就可以了，毕竟不在demo复现的我也很难定位

**Comment by zynote** [comment]
debug到这个位置      
GSYBaseVideoPlayer.java:424)行
lp.setMargins(mListItemRect[0], mListItemRect[1], 0, 0);
中的mListItemRect为null 

在文件中的注释为
 //当前item框的屏幕位置
protected int[] mListItemRect;

请问这个我该怎么改呢, 谢谢

**Comment by CarGuo** [comment]
奇怪，mListItemRect 是在全屏的时候初始化赋值的，你的退出全屏调用的是？

**Comment by zynote** [comment]
override fun onBackPressed() {
        if (orientationUtils != null) {
            orientationUtils.backToProtVideo()
        }
        if (GSYVideoManager.backFromWindowFull(this)) {
            return
        }
        super.onBackPressed()
    }
调用的这个, 不切换清晰度的时候是有值的, 切换完后就没了

**Comment by zynote** [comment]
```
 protected void backToNormal() {

        final ViewGroup vp = getViewGroup();

        final View oldF = vp.findViewById(getFullId());
        final GSYVideoPlayer gsyVideoPlayer;
        if (oldF != null) {
            gsyVideoPlayer = (GSYVideoPlayer) oldF;
            //如果暂停了
            pauseFullBackCoverLogic(gsyVideoPlayer);
            if (mShowFullAnimation) {
                TransitionManager.beginDelayedTransition(vp);

                LayoutParams lp = (LayoutParams) gsyVideoPlayer.getLayoutParams();
                lp.setMargins(mListItemRect[0], mListItemRect[1], 0, 0);
                lp.width = mListItemSize[0];
                lp.height = mListItemSize[1];
                //注意配置回来，不然动画效果会不对
                lp.gravity = Gravity.NO_GRAVITY;
                gsyVideoPlayer.setLayoutParams(lp);

                postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        resolveNormalVideoShow(oldF, vp, gsyVideoPlayer);
                    }
                }, 400);
            } else {
                resolveNormalVideoShow(oldF, vp, gsyVideoPlayer);
            }

        } else {
            resolveNormalVideoShow(null, vp, null);
        }
```
我想绕过这个待动画的退出全屏, 设置不用动画, 但是估计这个类重新生成了还是咋, 切换清晰度后, 又恢复成默认的带动画了....(不过假如能设置成功的话也不会有这个bug了.....)
大佬求救, 时间很急.....

**Comment by zynote** [comment]
demo 我导入的版本是5.0.2
在PlayPickActivity类中
```
//设置全屏按键功能,这是使用的是选择屏幕，而不是全屏
        videoPlayer.getFullscreenButton().setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                orientationUtils.resolveByClick();
                videoPlayer.getCurrentPlayer().startWindowFullscreen(PlayPickActivity.this, false, true);

            }
        });
```
这里加一行全屏

修改返回代码成这样:

```
 @Override
    public void onBackPressed() {

        orientationUtils.backToProtVideo();
        if (GSYVideoManager.backFromWindowFull(this)) {
            return;
        }
        super.onBackPressed();
```

切换清晰度后返回报错, 用原有的返回,视频回不到正常位置

**Comment by zynote** [comment]
这个我试过了, 没有作用

**Comment by zynote** [comment]
> ```
>  videoPlayer.getCurrentPlayer().startWindowFullscreen(PlayPickActivity.this, false, true);
> ```
> 这一句 改为
> 
> ```
>  videoPlayer.startWindowFullscreen(PlayPickActivity.this, false, true);
> ```

这个我试了没有效果....继续求救....

**Comment by CarGuo** [comment]
再把  onSeekComplete 修改为如下的，就不会黑了

```

      @Override
        public void onSeekComplete() {
            if (mTmpManager != null) {
                GSYVideoBaseManager manager = GSYVideoManager.instance();
                GSYVideoManager.changeManager(mTmpManager);
                mTmpManager.setLastListener(manager.lastListener());
                mTmpManager.setListener(manager.listener());
                mTmpManager.setDisplay(mSurface);
                changeUiToPlayingClear();
                resolveChangedResult();
                manager.releaseMediaPlayer();
            }
        }

```
