### ISSUE TITLE
运行DEMO闪退，我什么都没动啊。

### ISSUE THREAD

**Issue by yaochangliang159** [CarGuo/GSYVideoPlayer#1604]
（请务必按照issue模板，修改后提交问题）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

下载最新的代码ZIP，然后解压，AS打开，运行到手机，闪退

## 问题机型/系统：

真机 三星GT-I9500，4.4系统

## Demo中的复现步骤

刚刚解压DEMO代码，在AS运行到真机，闪退

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）
`11-15 17:40:33.609 32169-32169/com.example.gsyvideoplayer E/dalvikvm: Could not find class 'android.support.v4.graphics.drawable.DrawableWrapper', referenced from method android.support.v7.widget.DrawableUtils.canSafelyMutateDrawable
11-15 17:40:33.639 32169-32169/com.example.gsyvideoplayer E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
11-15 17:40:33.709 32169-32169/com.example.gsyvideoplayer E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.gsyvideoplayer, PID: 32169
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.gsyvideoplayer/com.example.gsyvideoplayer.MainActivity}: android.view.InflateException: Binary XML file line #43: Error inflating class android.support.v7.widget.ActionBarContextView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
        at android.app.ActivityThread.access$900(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
        at android.os.Handler.dispatchMessage(Handler.java)
        at android.os.Looper.loop(Looper.java)
        at android.app.ActivityThread.main(ActivityThread.java)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #43: Error inflating class android.support.v7.widget.ActionBarContextView
        at android.view.LayoutInflater.createView(LayoutInflater.java)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java)
        at android.view.LayoutInflater.inflate(LayoutInflater.java)
        at android.view.LayoutInflater.inflate(LayoutInflater.java)
        at android.view.LayoutInflater.inflate(LayoutInflater.java)
        at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:406)
        at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:323)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.example.gsyvideoplayer.MainActivity.onCreate(MainActivity.java:37)
        at android.app.Activity.performCreate(Activity.java)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java) 
        at android.app.ActivityThread.access$900(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java) 
        at android.os.Handler.dispatchMessage(Handler.java) 
        at android.os.Looper.loop(Looper.java) 
        at android.app.ActivityThread.main(ActivityThread.java) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java)
        at android.view.LayoutInflater.createView(LayoutInflater.java) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java) 
        at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:406) 
        at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:323) 
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
        at com.example.gsyvideoplayer.MainActivity.onCreate(MainActivity.java:37) 
        at android.app.Activity.performCreate(Activity.java) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java) 
        at android.app.ActivityThread.access$900(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java) 
        at android.os.Handler.dispatchMessage(Handler.java) 
        at android.os.Looper.loop(Looper.java) 
        at android.app.ActivityThread.main(ActivityThread.java) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.NoClassDefFoundError: android.support.v4.graphics.drawable.DrawableWrapper
        at android.support.v7.widget.DrawableUtils.canSafelyMutateDrawable(DrawableUtils.java:149)
        at android.support.v7.widget.AppCompatDrawableManager.tintDrawableUsingColorFilter(AppCompatDrawableManager.java:468)
        at android.support.v7.widget.AppCompatDrawableManager.tintDrawable(AppCompatDrawableManager.java:294)
        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:203)
        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
        at android.support.v7.widget.AppCompatDrawableManager.createDrawableIfNeeded(AppCompatDrawableManager.java:244)
        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
        at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
        at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:75)
        at android.support.v7.widget.ActionBarContextView.<init>(ActionBarContextView.java:69)
        at android.support.v7.widget.ActionBarContextView.<init>(ActionBarContextView.java:61)
        at java.lang.reflect.Constructor.constructNative(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java) 
        at android.view.LayoutInflater.createView(LayoutInflater.java) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java) 
        at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:406) 
        at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:323) 
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
        at com.example.gsyvideoplayer.MainActivity.onCreate(MainActivity.java:37) 
        at android.app.Activity.performCreate(Activity.java) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java) 
        at android.app.ActivityThread.access$900(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java) 
        at android.os.Handler.dispatchMessage(Handler.java) 
        at android.os.Looper.loop(Looper.java) 
        at android.app.ActivityThread.main(ActivityThread.java) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java) 
        at dalvik.system.NativeStart.main(Native Method) `

**Comment by CarGuo** [comment]
目测是最低版本过低吧

**Comment by yaochangliang159** [comment]
作者要不你试试你自己下载最新ZIP DEMO跑一下试试？
我下载ZIP代码，解压后什么都没动，包括你说的最低版本过低。。
我现在是一脸懵逼啊。。。大佬也试着跑一下你的DEMO吧？~~~

**Comment by CarGuo** [comment]
我一直跑着demo啊，没啥问题
这里有apk
https://github.com/CarGuo/GSYVideoPlayer/releases/download/v6.0.1/app-release.apk

**Comment by yaochangliang159** [comment]
这个问题已经解决，将项目中的dependencies.gradle下的supportLibraryVersion版本号，由原来的27.0.2改为27.1.1，即可解决项目跑起来闪退的问题,原文链接：
[https://stackoverflow.com/questions/49026021/classnotfoundexception-android-support-v4-graphics-drawable-drawablewrapper](url)
