### ISSUE TITLE
加载so文件的时候出现java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad

### ISSUE THREAD

**Issue by wang642357** [CarGuo/GSYVideoPlayer#166]

**Comment by CarGuo** [comment]
你是用的targetSdk等版本是？完整的log？

**Comment by wang642357** [comment]
targetSdk：25
 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.zuxia.edu.zuxiaclassroom, PID: 8235
                                                                            java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.zuxia.edu.zuxiaclassroom-4/lib/x86/libijksdl.so"
                                                                                at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                                at java.lang.System.loadLibrary(System.java:1076)
                                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:175)
                                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:187)
                                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:228)
                                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:224)
                                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:215)
                                                                                at com.shuyu.gsyvideoplayer.GSYVideoManager.<init>(GSYVideoManager.java:240)
                                                                                at com.shuyu.gsyvideoplayer.GSYVideoManager.instance(GSYVideoManager.java:101)
                                                                                at com.shuyu.gsyvideoplayer.GSYVideoPlayer.isCurrentMediaListener(GSYVideoPlayer.java:1111)
                                                                                at com.shuyu.gsyvideoplayer.GSYVideoPlayer.setUp(GSYVideoPlayer.java:254)
                                                                                at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.setUp(StandardGSYVideoPlayer.java:195)
                                                                                at com.zuxia.edu.zuxiaclassroom.adapter.HeadLinesAdapter.onBindViewHolder(HeadLinesAdapter.java:124)
                                                                                at com.zuxia.edu.zuxiaclassroom.adapter.HeadLinesAdapter.onBindViewHolder(HeadLinesAdapter.java:36)
                                                                                at com.jcodecraeer.xrecyclerview.XRecyclerView$WrapAdapter.onBindViewHolder(XRecyclerView.java:419)
                                                                                at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                                                at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                                                at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                                at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:282)
                                                                                at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:336)
                                                                                at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:349)
                                                                                at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:356)
                                                                                at android.support.v7.widget.GapWorker.run(GapWorker.java:387)
                                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by CarGuo** [comment]
25太高了，可以试试23。目前so编译版本没有那么高

**Comment by wang642357** [comment]
我跑你的demo，targetSdkVersion也是设置的25，没有出现这个问题

**Comment by wang642357** [comment]
我刚刚改成25试了一下，还是会出现这个问题

**Comment by CarGuo** [comment]
请问下demo有问题还是没问题？？你是在模拟器还是真机？加了ndk过滤没有？

**Comment by wang642357** [comment]
demo跑模拟器和真机都没有出现问题，我的项目跑模拟器和真机都不行，你说的ndk过滤我没有加

**Comment by CarGuo** [comment]
看一下首页那个问题集锦，加一下ndk过滤试试

**Comment by wang642357** [comment]
ndk过滤我加了的，我用哪个Analyze Apk工具看了下，so文件是打包到了对应的文件下的

**Comment by wang642357** [comment]
但是跑出来的结果还是不行

**Comment by CarGuo** [comment]
你试着把25的那些都降低试试吧

**Comment by wang642357** [comment]
好的，非常感谢你的解答

**Comment by CarGuo** [comment]
个人感觉还有可能是ijk java和so版本不匹配问题。如果还没有解决可以依赖最终的github项目试试。先close

**Comment by matthewfang** [comment]
代码混淆的问题  要放到你的target module proguard下

**Comment by zongxiaomi** [comment]
这种情况就是 你so文件中有写死了绝对路径的包名，要按照demo的包名以及文件夹名称来写就好了，不要更改包名以及类名哦

**Comment by AlbertSnow** [comment]
嗯 release包代码混淆、优化，导致JNI反射的绝对路径、名称找不到。

在 proguard中填写
`-keep class com.test. YouJNIClasss {
    *;
}`

[具体解决的办法](https://blog.csdn.net/zhjali123/article/details/107596775)
