### ISSUE TITLE
华为荣耀V9 部分问题

### ISSUE THREAD

**Issue by Equalzys** [CarGuo/GSYVideoPlayer#1660]
1、使用ijkplayer模式，列表自动播放的时候，播放器在父framlayout里不全（不是父framlayout的宽高），切换至ijkplayer模式和系统播放器均无此问题。
2、使用exoplayer模式，列表上下来回滑动会出现ANR，切换至ijkplayer模式和系统播放器均无此问题。
3、使用默认TEXTURE渲染时，列表滑动，当遮挡着TEXTURE（没显示全）时，点击播放，播放器遮挡部分是黑屏的，切换至SUFRACE模式渲染，无此问题。

**Comment by Equalzys** [comment]
然后现在只能使用系统播放器模式+SUFRACE模式渲染。
滑动时会报IllegalStateException异常。

java.lang.IllegalStateException
     at android.media.MediaPlayer.getVideoWidth(Native Method)
     at tv.danmaku.ijk.media.player.AndroidMediaPlayer.getVideoWidth(AndroidMediaPlayer.java:196)
     at com.shuyu.gsyvideoplayer.player.SystemPlayerManager.getVideoWidth(SystemPlayerManager.java:152)
     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.getVideoWidth(GSYVideoBaseManager.java:472)
     at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.getCurrentVideoWidth(GSYVideoView.java:218)
     at com.shuyu.gsyvideoplayer.render.view.GSYSurfaceView.getCurrentVideoWidth(GSYSurfaceView.java:196)
     at com.shuyu.gsyvideoplayer.utils.MeasureHelper.prepareMeasure(MeasureHelper.java:214)
     at com.shuyu.gsyvideoplayer.render.view.GSYSurfaceView.onMeasure(GSYSurfaceView.java:54)
     at android.view.View.measure(View.java:22216)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
     at android.view.View.measure(View.java:22216)
     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
     at android.view.View.measure(View.java:22216)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
     at android.view.View.measure(View.java:22216)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
     at android.view.View.measure(View.java:22216)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6671)
     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1539)
     at android.widget.LinearLayout.measureVertical(LinearLayout.java:823)
     at android.widget.LinearLayout.onMeasure(LinearLayout.java:702)
     at android.view.View.measure(View.java:22216)
     at android.support.v7.widget.RecyclerView$i.b(RecyclerView.java:9119)
     at android.support.v7.widget.LinearLayoutManager.a(LinearLayoutManager.java:1583)
     at android.support.v7.widget.LinearLayoutManager.a(LinearLayoutManager.java:1517)
     at android.support.v7.widget.LinearLayoutManager.c(LinearLayoutManager.java:1331)
     at android.support.v7.widget.LinearLayoutManager.b(LinearLayoutManager.java:1075)
     at android.support.v7.widget.RecyclerView.a(RecyclerView.java:1832)
     at android.support.v7.widget.RecyclerView$w.run(RecyclerView.java:5067)
     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
     at android.view.Choreographer.doCallbacks(Choreographer.java:790)
     at android.view.Choreographer.doFrame(Choreographer.java:718)
     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
     at android.os.Handler.handleCallback(Handler.java:808)
     at android.os.Handler.dispatchMessage(Handler.java:101)
     at android.os.Looper.loop(Looper.java:166)
     at android.app.ActivityThread.main(ActivityThread.java:7425)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by Equalzys** [comment]
幸好项目接口有返回视频宽高，把GSYSurfaceView.getCurrentVideoWidth()，getCurrentVideohight(),替换掉，就不会崩溃和卡顿了；
上边的问题很严重啊，都感觉这库不能用了...

**Comment by CarGuo** [comment]
你的问题在demo怎么复现?
