### ISSUE TITLE
部分视频无法缓存

### ISSUE THREAD

**Issue by zhengyouhong** [CarGuo/GSYVideoPlayer#167]
每次AndroidVideoCache这个框架都报了一堆错，导致无法缓存。

Error reading ping response
                          com.danikula.videocache.ProxyCacheException: Error opening connection for http://127.0.0.1:54245/ping with offset 0
                              at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:75)
                              at com.danikula.videocache.Pinger.pingServer(Pinger.java:86)
                              at com.danikula.videocache.Pinger.access$100(Pinger.java:28)
                              at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:108)
                              at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:104)
                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                              at java.lang.Thread.run(Thread.java:818)
                           Caused by: java.net.ConnectException: failed to connect to /127.0.0.1 (port 54245): connect failed: ECONNREFUSED (Connection refused)
                              at libcore.io.IoBridge.connect(IoBridge.java:124)
                              at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                              at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
                              at java.net.Socket.connect(Socket.java:884)
                              at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
                              at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
                              at com.android.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:67)
                              at com.android.okhttp.Connection.connect(Connection.java:152)

**Comment by CarGuo** [comment]
目前m3u8，concat，hls的类型url不支持缓存，然后代理也无法缓存，确保你的url正确

**Comment by zhengyouhong** [comment]
缓存失效后， 每播放一遍，都需要重新下载， 而且有的能成功 ，  有的失败，  也不是直播流啊

**Comment by CarGuo** [comment]
你能吧缓存失败的url提供下么？
