### ISSUE TITLE
使用多任务播放时出现内存溢出

### ISSUE THREAD

**Issue by wbsen** [CarGuo/GSYVideoPlayer#1690]
## 问题描述：
使用场景：使用ViewPager播放视频列表，当ViewPager切换页面时候播放当前页面视频。
操作方法：快速滑动ViewPager，会越滑越卡顿，直至OutOfMemoryError。

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'

问题代码：()
GSYVideoBaseManager.class(166行)
protected void init() {
        HandlerThread mediaHandlerThread = new HandlerThread(TAG);
        mediaHandlerThread.start();
        mMediaHandler = new MediaHandler((mediaHandlerThread.getLooper()));
        mainThreadHandler = new Handler();
    }

## 问题log（）
java.lang.OutOfMemoryError: Could not allocate JNI Env
        at java.lang.Thread.nativeCreate(Native Method)
        at java.lang.Thread.start(Thread.java:730)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.init(GSYVideoBaseManager.java:171)
        at com.waz.zclient.pages.main.circle.videoplayer.CustomManager.<init>(CustomManager.java:56)
        at com.waz.zclient.pages.main.circle.videoplayer.CustomManager.getCustomManager(CustomManager.java:142)
        at com.waz.zclient.pages.main.circle.videoplayer.MultiSampleVideo.getGSYVideoManager(MultiSampleVideo.java:159)
        at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.isCurrentMediaListener(GSYVideoView.java:827)
        at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.setStateAndUi(GSYVideoControlView.java:326)
        at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.onError(GSYVideoView.java:673)
        at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.onError(GSYVideoControlView.java:281)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$5.run(GSYVideoBaseManager.java:325)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6385)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

**Comment by 799536960** [comment]
不是说内核只有一个嘛 为什么还要维护播放器呢
