### ISSUE TITLE
ijk内核，无法播放本地文件

### ISSUE THREAD

**Issue by zwping** [CarGuo/GSYVideoPlayer#1745]
## 问题描述：

问题代码：
```
        video_player?.release()
        videoBuilder = GSYVideoOptionBuilder()
            .setThumbImageView(VideoUtil.thumb(this))
            .setUrl(localPath)
            .setIsTouchWiget(true)
            .setRotateViewAuto(true)
            .setShowFullAnimation(false)
            .setCacheWithPlay(false)
        if (seek) videoBuilder?.setSeekOnStart(VCacheUtil.getVideoProgress(tag))
        videoBuilder?.build(video_player)
        VideoUtil.addWatermark(video_player)
```

## 问题log（如果有）

```

01-09 11:47:20.852 608-627/system_process I/WindowManager: Screen frozen for +175ms due to Window{18a5758 u0 com.sihongzj.jkzx/com.sihongzj.wk.view.ac.video.FullPlayerActivity}
01-09 11:47:21.302 608-826/system_process I/MediaFocusControl:  AudioFocus  requestAudioFocus() from android.media.AudioManager@96bb114com.shuyu.gsyvideoplayer.video.base.GSYVideoView$1@60aa02a req=2flags=0x0
01-09 11:47:21.303 9525-9731/com.sihongzj.jkzx D/IJKMEDIA: IjkMediaPlayer_release
01-09 11:47:21.303 9525-9731/com.sihongzj.jkzx D/IJKMEDIA: IjkMediaPlayer_native_setup
01-09 11:47:21.303 9525-9731/com.sihongzj.jkzx I/IJKMEDIA: av_version_info: ff3.4--ijk0.8.7--20180103--001
01-09 11:47:21.303 9525-9731/com.sihongzj.jkzx I/IJKMEDIA: ijk_version_info: k0.8.8
01-09 11:47:21.303 9525-9731/com.sihongzj.jkzx D/IJKMEDIA: ffpipeline_create_from_android()
01-09 11:47:21.303 9525-9731/com.sihongzj.jkzx D/IJKMEDIA: ijkmp_set_inject_opaque(0x200772)
01-09 11:47:21.303 9525-9731/com.sihongzj.jkzx D/IJKMEDIA: ijkmp_set_inject_opaque()=void
01-09 11:47:21.303 9525-9731/com.sihongzj.jkzx D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x200772)
01-09 11:47:21.304 9525-9731/com.sihongzj.jkzx D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
01-09 11:47:21.304 9525-9731/com.sihongzj.jkzx D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
01-09 11:47:21.304 9525-9731/com.sihongzj.jkzx D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
01-09 11:47:21.304 9525-9731/com.sihongzj.jkzx D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
01-09 11:47:21.304 9525-9731/com.sihongzj.jkzx W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
01-09 11:47:21.314 9525-9731/com.sihongzj.jkzx W/System.err:     at com.shuyu.gsyvideoplayer.e.b.a(IjkPlayerManager.java:82)
01-09 11:47:21.314 9525-9731/com.sihongzj.jkzx W/System.err:     at com.shuyu.gsyvideoplayer.b.b(GSYVideoBaseManager.java:597)
01-09 11:47:21.314 9525-9731/com.sihongzj.jkzx W/System.err:     at com.shuyu.gsyvideoplayer.b.a(GSYVideoBaseManager.java:38)
01-09 11:47:21.314 9525-9731/com.sihongzj.jkzx W/System.err:     at com.shuyu.gsyvideoplayer.b$a.handleMessage(GSYVideoBaseManager.java:561)
01-09 11:47:21.314 9525-9731/com.sihongzj.jkzx W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
01-09 11:47:21.314 9525-9731/com.sihongzj.jkzx W/System.err:     at android.os.Looper.loop(Looper.java:148)
01-09 11:47:21.314 9525-9731/com.sihongzj.jkzx W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)

```

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/1489
