### ISSUE TITLE
使用EXOPlayer作为内核，在列表页不能自动开始播放下一段视频

### ISSUE THREAD

**Issue by fenghebaiyang** [CarGuo/GSYVideoPlayer#1762]
## 问题描述：

使用EXOPlayer作为内核，在列表页不能自动开始播放下一段视频，有错误日志输出，应该是EXO缓存的问题。

## 问题机型/系统：

小米8 华为P9 OPPO等

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:6.0.2'

## Demo中的复现步骤

Demo中的RecycleView2Acitivity，在第一个视频正常开始播放后，点击第二个播放视频尝试进行播放，
无法播放，控制台有错误日志输出。并且在关闭cache后（setCacheWithPlay（false）），功能正常。

## 问题log（如果有）

```

2019-01-14 14:36:59.021 14501-14578/com.example.gsyvideoplayer E/LoadTask: Unexpected exception loading stream
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
        at com.google.android.exoplayer2.upstream.cache.SimpleCache.getContentMetadata(SimpleCache.java:358)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.getRedirectedUriOrDefault(CacheDataSource.java:509)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:286)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2019-01-14 14:36:59.022 14501-14578/com.example.gsyvideoplayer E/LoadTask: Unexpected exception loading stream
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
        at com.google.android.exoplayer2.upstream.cache.SimpleCache.getContentMetadata(SimpleCache.java:358)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.getRedirectedUriOrDefault(CacheDataSource.java:509)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:286)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2019-01-14 14:37:00.029 14501-14578/com.example.gsyvideoplayer E/LoadTask: Unexpected exception loading stream
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
        at com.google.android.exoplayer2.upstream.cache.SimpleCache.getContentMetadata(SimpleCache.java:358)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.getRedirectedUriOrDefault(CacheDataSource.java:509)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:286)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2019-01-14 14:37:02.038 14501-14578/com.example.gsyvideoplayer E/LoadTask: Unexpected exception loading stream
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
        at com.google.android.exoplayer2.upstream.cache.SimpleCache.getContentMetadata(SimpleCache.java:358)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.getRedirectedUriOrDefault(CacheDataSource.java:509)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:286)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2019-01-14 14:37:02.053 14501-14577/com.example.gsyvideoplayer E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: null
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:403)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
        at com.google.android.exoplayer2.upstream.cache.SimpleCache.getContentMetadata(SimpleCache.java:358)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.getRedirectedUriOrDefault(CacheDataSource.java:509)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:286)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2019-01-14 14:37:02.066 14501-14501/com.example.gsyvideoplayer E/EventLogger: playerFailed [3.05]
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: null
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:354)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: null
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:403)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
        at com.google.android.exoplayer2.upstream.cache.SimpleCache.getContentMetadata(SimpleCache.java:358)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.getRedirectedUriOrDefault(CacheDataSource.java:509)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:286)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 

```

**Comment by CarGuo** [comment]
我这边在最新的demo测试正常，请确定下是不是因为本地缓存导致

**Comment by fenghebaiyang** [comment]
我重新拉了一遍master代码，确保只调整GSYApplication 中的代码，替换默认的播放内核和缓存 ，也把程序卸载重新安装了，进入到RecyclerView2Activity中，点击播放第一个视频，正常播放后点击第二个视频播放，会有上面的报错日志输出，并且第二个视频不能正常播放，再次点击就可以正常播放第二个视频。
```
@Override
    public void onCreate() {
        super.onCreate();
//        if (LeakCanary.isInAnalyzerProcess(this)) {
//            // This process is dedicated to LeakCanary for heap analysis.
//            // You should not init your app in this process.
//            return;
//        }
//        LeakCanary.install(this);

        //GSYVideoType.enableMediaCodec();
        //GSYVideoType.enableMediaCodecTexture();

        PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
        //PlayerFactory.setPlayManager(SystemPlayerManager.class);//系统模式
        //PlayerFactory.setPlayManager(IjkPlayerManager.class);//ijk模式

        CacheFactory.setCacheManager(ExoPlayerCacheManager.class);//exo缓存模式，支持m3u8，只支持exo
        //CacheFactory.setCacheManager(ProxyCacheManager.class);//代理缓存模式，支持所有模式，不支持m3u8等

        //GSYVideoType.setShowType(GSYVideoType.SCREEN_MATCH_FULL);
        //GSYVideoType.setShowType(GSYVideoType.SCREEN_TYPE_FULL);
        //GSYVideoType.setShowType(GSYVideoType.SCREEN_MATCH_FULL);

        //GSYVideoType.setRenderType(GSYVideoType.SUFRACE);
        //GSYVideoType.setRenderType(GSYVideoType.GLSURFACE);

        //IjkPlayerManager.setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT);


        /*ExoSourceManager.setExoMediaSourceInterceptListener(new ExoMediaSourceInterceptListener() {
            @Override
            public MediaSource getMediaSource(String dataSource, boolean preview, boolean cacheEnable, boolean isLooping, File cacheDir) {
                return null;
            }
        });*/

    }
```

**Comment by CarGuo** [comment]
了解，之前没设置 CacheFactory.setCacheManager(ExoPlayerCacheManager.class); 看不出来。

目前看起来是 GSYVideoHelper 的问题，因为单个view在切换时没处理cache source。

**Comment by CarGuo** [comment]
6.0.3已修复
