### ISSUE TITLE
播放某些本地视频一直处于加载中

### ISSUE THREAD

**Issue by woshiqinwei** [CarGuo/GSYVideoPlayer#1771]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

播放某些本地视频一直处于加载中

## 问题机型/系统：

oppo R9sk

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.2'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后也会出现下面log日志

问题代码：(如果有)

## 问题log（如果有）

 W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.initVideoPlayer(IjkPlayerManager.java:82)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:600)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:38)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:564)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:179)
        at android.app.ActivityThread.main(ActivityThread.java:5769)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)

**Comment by CarGuo** [comment]
视频的容器协议、视频编码、音频编码是什么？能提供复现源文件么？

**Comment by woshiqinwei** [comment]
视频发你QQ了

**Comment by Chendyiwhy** [comment]
我也遇到这个问题了
