### ISSUE TITLE
gsyBaseVideoPlayer 报空指针

### ISSUE THREAD

**Issue by xyZangGit** [CarGuo/GSYVideoPlayer#1794]
## 问题描述：

android:screenOrientation="portrait" 页面不设置这个属性   再按下全屏业务逻辑的时候会报空指针

 @Override
    public GSYBaseVideoPlayer startWindowFullscreen(Context context, boolean actionBar, boolean statusBar) {

        GSYBaseVideoPlayer gsyBaseVideoPlayer = super.startWindowFullscreen(context, actionBar, statusBar);

        CoverVideo CoverVideo = (CoverVideo) gsyBaseVideoPlayer;
        CoverVideo.loadCoverImage("", mCoverOriginUrl);

        return gsyBaseVideoPlayer;
    }

gsyBaseVideoPlayer  是空

## 问题机型/系统：

真机 目前手上的测试机华为P10 华为荣耀9   android8.0系统 都会百分之百出现这个问题 
小米 安卓9.0  vivo安卓7.0 目前没有这个空指针问题

## GSY依赖版本

api 'com.shuyu:gsyVideoPlayer-java:6.0.1'

## Demo中的复现步骤

Demo中的是设置android:screenOrientation="portrait"  这个属性，我设置这个属性没有空指针问题，但是设置这个属性，就不能style里面设置背景透明，会导致进入app的时候背景黑色，不知道大大有没有解决方案，看问题里面 没有这个问题

问题代码：(如果有)
@Override
    public GSYBaseVideoPlayer startWindowFullscreen(Context context, boolean actionBar, boolean statusBar) {

        GSYBaseVideoPlayer gsyBaseVideoPlayer = super.startWindowFullscreen(context, actionBar, statusBar);

        CoverVideo CoverVideo = (CoverVideo) gsyBaseVideoPlayer;
//        CoverVideo.loadCoverImage(mCoverOriginUrl, mDefaultRes);
        CoverVideo.loadCoverImage("", mCoverOriginUrl);

        return gsyBaseVideoPlayer;
    }

## 问题log（如果有）
01-31 13:44:28.657 5580-5580/com.wlf.steward E/CrashHandler: In thread: Thread[main,5,main]
    UncaughtException detected: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.wlf.steward.video.CoverVideo.loadCoverImage(java.lang.String, java.lang.String)' on a null object reference
        at com.wlf.steward.video.CoverVideo.startWindowFullscreen(CoverVideo.java:80)
        at com.wlf.steward.adapter.recycleviewadapter.VideoTabFragmentRecycleAdapter$2.onClick(VideoTabFragmentRecycleAdapter.java:96)
        at android.view.View.performClick(View.java:6291)
        at android.view.View$PerformClick.run(View.java:24931)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by CarGuo** [comment]
android:screenOrientation="portrait" 屬性和页面透明度没关系
