### ISSUE TITLE
com.shuyu.gsyvideoplayer.utils.OrientationUtils.init

### ISSUE THREAD

**Issue by WYCang** [CarGuo/GSYVideoPlayer#1802]
## 问题描述：

com.shuyu.gsyvideoplayer.utils.OrientationUtils.init
OrientationUtils.java, line 122
java.lang.IllegalStateException: register failed, the sensor listeners size has exceeded the maximum limit 128

## 问题机型/系统：
P20 Pro/9

R15/8.1.0

vivo Y67A/6.0

## GSY依赖版本

 implementation('com.shuyu:GSYVideoPlayer:6.0.3')

**Comment by CarGuo** [comment]
demo怎么复现？

**Comment by renwfy** [comment]
无意中出现的


Build version: 1.1.7 
Build date: 1981-01-01 01:01:02 
Current date: 2021-06-11 11:31:12 
Device: Xiaomi Mi 10 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.IllegalStateException: register failed, the sensor listeners size has exceeded the maximum limit 128
 at android.hardware.SystemSensorManager.registerListenerImpl(SystemSensorManager.java:180)
 at android.hardware.SensorManager.registerListener(SensorManager.java:823)
 at android.hardware.SensorManager.registerListener(SensorManager.java:730)
 at android.view.OrientationEventListener.enable(OrientationEventListener.java:93)
 at com.shuyu.gsyvideoplayer.utils.OrientationUtils.init(OrientationUtils.java:163)
 at com.shuyu.gsyvideoplayer.utils.OrientationUtils.<init>(OrientationUtils.java:63)
 at com.shuyu.gsyvideoplayer.utils.OrientationUtils.<init>(OrientationUtils.java:51)
 at kk.adapter.VideoPlayAdapter.convert(VideoPlayAdapter.java:60)
 at kk.adapter.VideoPlayAdapter.convert(VideoPlayAdapter.java:21)
 at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.kt:376)
 at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.kt:382)
 at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.kt:75)
 at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7031)
 at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5948)
 at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6215)
 at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
 at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
 at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
 at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
 at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:236)
 at android.app.ActivityThread.main(ActivityThread.java:7876)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
