### ISSUE TITLE
项目中遇到的问题请教

### ISSUE THREAD

**Issue by woshiyizhijiao** [CarGuo/GSYVideoPlayer#1813]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

1.项目中有记录播放视频多长时间的功能，我是想在每次更新进度的时候加一秒钟，所以setProgressAndTime如何每秒钟回调一次。
2.我重载了onSurfaceUpdated(Surface surface) 和 setViewShowState(View view, int visibility)两个方法在开始播放的时候显示封面，但是添加之后视频播放完成无法显示最后一帧，显示最后一帧我做在的操作是注释onAutoCompletion();
3.接着第二个问题，视频播放完成显示最后一帧时，这个时候如果横竖屏切换，会显示黑屏，没有显示最后一帧。
4,横屏状态下，锁屏在解锁后界面状态错误(附视频)

## 问题机型/系统：

真机 华为荣耀8 android8.0   还有一个魅蓝2 android5.1   三星s9+ android9.0   手上只有这些机型，其他机型应该也会有同样的问题

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

**第2.3个问题在ListADVideoActivity2可以复现  第四个问题在WebDetailActivity复现** 

[第四个问题视频.zip](https://github.com/CarGuo/GSYVideoPlayer/files/2874488/default.zip)

**Comment by CarGuo** [comment]
1、setProgressAndTime 是通过 TaskTimer 去定时读取当前内核的播放进度的。

2、播放结束的时候留在最后一帧，具体要看你是留的，你是留在surface上还是截图保存用其他显示。

3、横竖屏切换你要通过cloneParams和showWinxxxx那两个接口做横竖排同步，类似 setPauseCover 为true 方法实现的效果。

4、webdetail这个页面应该是 getDetailOrientationRotateAuto 配置

**Comment by woshiyizhijiao** [comment]
1.我之前用饺子播放器的写法是 （这个样子是没问题的）： 
```
@Override
 public void startProgressTimer() {
        super.startProgressTimer();
        cancelProgressTimer();
        UPDATE_PROGRESS_TIMER = new Timer();
        mProgressTimerTask = new ProgressTimerTask();
        UPDATE_PROGRESS_TIMER.schedule(mProgressTimerTask, 0, 1000);
 }
```
现在，因为ProgressTimerTask 是private的，我访问不到(这样写的话， 我点击屏幕会崩溃，报错为 )

```
    @Override
    protected void startProgressTimer() {
        //        super.startProgressTimer();
        //        cancelProgressTimer();
        if (updateProcessTimer != null) {
            updateProcessTimer.cancel();
            updateProcessTimer = null;
        }
        updateProcessTimer = new Timer();
        //        mProgressTimerTask = new ProgressTimerTask();
        updateProcessTimer.schedule(mProgressTimerTask, 0, 1000);
    }
```
 java.lang.IllegalStateException: Task already scheduled or cancelled
                                                     at java.util.Timer.sched(Timer.java:401)
                                                     at java.util.Timer.schedule(Timer.java:248)
                                                     at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.startProgressTimer(StandardGSYVideoPlayer.java:171)
                                                     at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.setStateAndUi(GSYVideoControlView.java:338)
                                                     at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.onInfo(GSYVideoView.java:681)
                                                     at com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer.onInfo(GSYBaseVideoPlayer.java:162)
                                                     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$6.run(GSYVideoBaseManager.java:324)

**Comment by woshiyizhijiao** [comment]
2.我是要留在surface上，停留在最后一帧

**Comment by CarGuo** [comment]
所以问题是？

**Comment by woshiyizhijiao** [comment]
> 所以问题是？



> 所以问题是？

我的意思是想把TaskTimer设置为1秒钟一次， 我在startProgressTimer里面复习了，但是不行。

**Comment by CarGuo** [comment]
我觉得你完全可以参考源码自定义你自己的定时器
