### ISSUE TITLE
发现一个空指针。。。

### ISSUE THREAD

**Issue by qssq** [CarGuo/GSYVideoPlayer#182]
Stack trace:  
                                                  java.lang.IllegalStateException: mpjni: seekTo: null mp
                                                      at tv.danmaku.ijk.media.player.IjkMediaPlayer.seekTo(Native Method)
                                                      at com.shuyu.gsyvideoplayer.GSYVideoPlayer.onTouch(GSYVideoPlayer.java:658)
                                                      at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.onTouch(StandardGSYVideoPlayer.java:286)

**Comment by CarGuo** [comment]
mpjni 这是so没出初始化成功的或者ijk已经释放了的时候马上又seek

**Comment by qssq** [comment]
那应该如何解决了，因为不是百分之百，所以我只加了判断，getPlayer()=null我就不让seek

**Comment by qssq** [comment]
请问如何更优雅的判断，哈哈

**Comment by qssq** [comment]
没有方法判断是否已经释放或初始化了

**Comment by qssq** [comment]
另外建议加上 @SuppressWarnings("ResourceType")
 不然我有强迫症看到红色就像解决。

**Comment by CarGuo** [comment]
好的～～我内部会修改一下，貌似也是某个位置没有判空的时候seek了

**Comment by CarGuo** [comment]
try 1.6.4
