### ISSUE TITLE
不在WIFI环境下使用悬浮窗模式播放视频，弹出询问是否继续的Dialog的时候会闪退

### ISSUE THREAD

**Issue by chenyan0107** [CarGuo/GSYVideoPlayer#1823]
## 问题描述：

不在WIFI环境下使用悬浮窗模式播放视频，弹出询问是否继续的Dialog的时候会闪退

## 问题机型/系统：

真机 小米MIX2 Android8.0

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

Demo中的WindowActivity页面在4G环境下打开后点击启动悬浮窗口，点击播放，闪退

## 问题log
    android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:794)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at android.app.Dialog.show(Dialog.java:330)
        at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.showWifiDialog(StandardGSYVideoPlayer.java:165)
        at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.clickStartIcon(GSYVideoControlView.java:825)
        at com.example.dialogvideo.video.FloatingVideo.access$100(FloatingVideo.java:25)
        at com.example.dialogvideo.video.FloatingVideo$2.onClick(FloatingVideo.java:88)
        at android.view.View.performClick(View.java:6266)
        at android.view.View$PerformClick.run(View.java:24730)
        at android.os.Handler.handleCallback(Handler.java:793)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by CarGuo** [comment]
收到～～～目前可以重写 `showWifiDialog ` 方法

```
  @Override
    protected void showWifiDialog() {
        if (!NetworkUtils.isAvailable(mContext)) {
            //Toast.makeText(mContext, getResources().getString(R.string.no_net), Toast.LENGTH_LONG).show();
            startPlayLogic();
            return;
        }
        AlertDialog.Builder builder = new AlertDialog.Builder(getActivityContext());
        builder.setMessage(getResources().getString(com.shuyu.gsyvideoplayer.R.string.tips_not_wifi));
        builder.setPositiveButton(getResources().getString(com.shuyu.gsyvideoplayer.R.string.tips_not_wifi_confirm), new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialog, int which) {
                dialog.dismiss();
                startPlayLogic();
            }
        });
        builder.setNegativeButton(getResources().getString(com.shuyu.gsyvideoplayer.R.string.tips_not_wifi_cancel), new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialog, int which) {
                dialog.dismiss();
            }
        });
        AlertDialog alertDialog =  builder.create();
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            alertDialog.getWindow().setType(WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY);
        } else {
            alertDialog.getWindow().setType(WindowManager.LayoutParams.TYPE_SYSTEM_ALERT);
        }
        alertDialog.show();
    }
```

**Comment by chenyan0107** [comment]
好的
