### ISSUE TITLE
找不到so库

### ISSUE THREAD

**Issue by zhongjuncoder** [CarGuo/GSYVideoPlayer#1855]
## 问题描述：找不到so库

app正常安装的时候没有问题，但是如果把app放在/system/app目录下（有系统签名的），一点击播放就会出现异常：dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/test.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libijkffmpeg.so"。

- 我也试过把libijkffmpeg.so放在/vendor/lib和/system/lib目录下，但是仍然会出现。

- abiFilters 'armeabi-v7a'也加上了，但是还是不行。

## 问题机型/系统：

Android5.1.1

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'
 implementation 'com.shuyu:gsyVideoPlayer-armv7a:7.0.0-beta1'

## Demo中的复现步骤

用系统签名app（模拟器的系统签名就是原生的），把app放在/system/app上，点击播放就会奔溃

问题代码：(如果有)

没有

## 问题log（如果有）

```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/app/test.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libijkffmpeg.so"
                                                                 at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                 at java.lang.System.loadLibrary(System.java:988)
                                                                 at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:179)
                                                                 at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:190)
                                                                 at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:231)
                                                                 at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:227)
                                                                 at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:218)
                                                                 at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.initVideoPlayer(IjkPlayerManager.java:55)
                                                                 at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:600)
                                                                 at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:38)
                                                                 at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:564)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5280)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
03-08 17:11:12.074 1437-1449/com.zdt16.dev E/art: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
03-08 17:11:12.074 1437-1449/com.zdt16.dev E/System: Uncaught exception thrown by finalizer
03-08 17:11:12.074 1437-1449/com.zdt16.dev E/System: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
                                                         at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
                                                         at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(IjkMediaPlayer.java:950)
                                                         at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:191)
                                                         at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
                                                         at java.lang.Thread.run(Thread.java:818)

```

**Comment by CarGuo** [comment]
你可以反编译看看so是不是不在
