### ISSUE TITLE
在播放的时候没有准备好视频就滑动快进崩溃了

### ISSUE THREAD

**Issue by pricnehao** [CarGuo/GSYVideoPlayer#186]
在播放视频的时候 如果这个视频没有被缓存 第一播放 刚好断网或者网速不好的时候  视频没有准备好就滑动快进 会出现崩溃

**Comment by pricnehao** [comment]
java.lang.IllegalStateException: mpjni: pause: null mp
	at tv.danmaku.ijk.media.player.IjkMediaPlayer._pause(Native Method)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.pause(IjkMediaPlayer.java:531)
	at com.shuyu.gsyvideoplayer.GSYVideoPlayer.onVideoPause(GSYVideoPlayer.java:433)
	at PlayActivity.onPause(PlayActivity.java:104)
	at android.app.Activity.performPause(Activity.java:6215)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1310)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3335)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3308)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3283)
	at android.app.ActivityThread.access$1000(ActivityThread.java:160)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1385)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5371)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1117)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

**Comment by CarGuo** [comment]
1.6.4？

**Comment by pricnehao** [comment]
上个版本 1.6.3

**Comment by CarGuo** [comment]
可以试试现在的版本

**Comment by CarGuo** [comment]
1.6.5版本已修复，如果问题请再联系～
