### ISSUE TITLE
播放地址为直播源时会报这个错

### ISSUE THREAD

**Issue by dary123** [CarGuo/GSYVideoPlayer#1870]
![123](https://user-images.githubusercontent.com/12826258/54114870-4cd53d00-4426-11e9-834b-5c2e1f60536a.png)

设备:酷派 C107-9  系统版本:6.0.1
java.lang.UnsatisfiedLinkError: No implementation found for void e.a.a.d.nativeClose(long) (tried Java_e_a_a_d_nativeClose and Java_e_a_a_d_nativeClose__J)
    at e.a.a.d.nativeClose(Native Method)
    at e.a.a.d.b(RtmpClient.java:146)
    at com.google.android.exoplayer2.e.a.c.a(RtmpDataSource.java:84)
    at com.google.android.exoplayer2.h.ag.a(StatsDataSource.java:110)
    at com.google.android.exoplayer2.i.ai.a(Util.java:363)
    at com.google.android.exoplayer2.source.p$a.b(ExtractorMediaPeriod.java:911)
    at com.google.android.exoplayer2.h.aa$c.run(Loader.java:381)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)

直播源地址如下:
http://ivi.bupt.edu.cn/hls/cctv6hd.m3u8
http://183.207.249.15/PLTV/3/224/3221225548/index.m3u8
http://live.gansuyunshi.com:9090/live/CCTV6-HD_2000.m3u8

**Comment by CarGuo** [comment]
是否因为混淆导致 、或者没有处理ndk过滤导致

**Comment by dary123** [comment]
已经加了混淆了，#gsyvideoplayer
-keep class com.shuyu.gsyvideoplayer.video.** { *; }
-dontwarn com.shuyu.gsyvideoplayer.video.**
-keep class com.shuyu.gsyvideoplayer.video.base.** { *; }
-dontwarn com.shuyu.gsyvideoplayer.video.base.**
-keep class com.shuyu.gsyvideoplayer.utils.** { *; }
-dontwarn com.shuyu.gsyvideoplayer.utils.**
-keep class tv.danmaku.ijk.** { *; }
-dontwarn tv.danmaku.ijk.**

-keep public class * extends android.view.View{
    *** get*();
    void set*(***);
    public <init>(android.content.Context);
    public <init>(android.content.Context, android.util.AttributeSet);
    public <init>(android.content.Context, android.util.AttributeSet, int);
}

**Comment by dary123** [comment]
ndk还要处理过滤吗，怎么处理呢

**Comment by dary123** [comment]
我已经进行过滤了
ndk {

            abiFilters "armeabi","armeabi-v7a","x86"
        }

**Comment by CarGuo** [comment]
Demo会有问题吗？

**Comment by dary123** [comment]
demo没有出现过，友盟就报了四次这种错误，很偶然

**Comment by CarGuo** [comment]
因为有些crash是并发，或者二次崩溃导致，可能还不是问题的根源

**Comment by goodluckier** [comment]
> 也是用户反应的，说进直播页过几秒就会闪退到首页

我在播放rtmp时也遇到一模一样的错误
