### ISSUE TITLE
正常的列表播放出现了NoClassDefFoundError，oppor11

### ISSUE THREAD

**Issue by 15863459070** [CarGuo/GSYVideoPlayer#1873]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/shuyu/gsyvideoplayer/cache/ProxyCacheManager;
        at com.shuyu.gsyvideoplayer.cache.CacheFactory.getCacheManager(CacheFactory.java:17)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.getCacheManager(GSYVideoBaseManager.java:157)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:596)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:38)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:564)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:197)
        at android.app.ActivityThread.main(ActivityThread.java:7022)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)
     Caused by: java.lang.ClassNotFoundException: com.shuyu.gsyvideoplayer.cache.ProxyCacheManager
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.shuyu.gsyvideoplayer.cache.CacheFactory.getCacheManager(CacheFactory.java:17) 
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.getCacheManager(GSYVideoBaseManager.java:157) 
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:596) 
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:38) 
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:564) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:197) 
        at android.app.ActivityThread.main(ActivityThread.java:7022) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/danikula/videocache/CacheListener;
        at com.shuyu.gsyvideoplayer.cache.CacheFactory.getCacheManager(CacheFactory.java:17) 
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.getCacheManager(GSYVideoBaseManager.java:157) 
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:596) 
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:38) 
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:564) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:197) 
        at android.app.ActivityThread.main(ActivityThread.java:7022) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.danikula.videocache.CacheListener" on path: DexPathList[[zip file "/data/app/cn.ishiguangji.time-Vk1z4mc_zJK2qzU8vcMXSg==/base.apk"],nativeLibraryDirectories=[/data/app/cn.ishiguangji.time-Vk1z4mc_zJK2qzU8vcMXSg==/lib/arm, /data/app/cn.ishiguangji.time-Vk1z4mc_zJK2qzU8vcMXSg==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.shuyu.gsyvideoplayer.cache.CacheFactory.getCacheManager(CacheFactory.java:17) 
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.getCacheManager(GSYVideoBaseManager.java:157) 
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:596) 
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:38) 
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:564) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:197) 
        at android.app.ActivityThread.main(ActivityThread.java:7022) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)

**Comment by CarGuo** [comment]
Demo复现？
