### ISSUE TITLE
问题描述：如何在播放第一个视频后，显示多张图片轮播后，再播放第二个视频

### ISSUE THREAD

**Issue by zengfuqiang** [CarGuo/GSYVideoPlayer#1893]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by zengfuqiang** [comment]
问题机型/系统：15寸广告屏

**Comment by zengfuqiang** [comment]
GSY依赖版本:implementation 'com.shuyu:GSYVideoPlayer:6.0.3'

**Comment by zengfuqiang** [comment]
我自己配置的项目，在播放第一个视频后setup一次地址，显示多张图片轮播后，再播放第二个视频又setup一次地址，播放半小时后出现了异常 com.yjkj.adscreen E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(48000, 12, 65536)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:646)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1355)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:663)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by CarGuo** [comment]
你应该是外部覆盖一个view去做吧

**Comment by zengfuqiang** [comment]
> 你应该是外部覆盖一个view去做吧

我自定义了一个view,播放第二个视频我重新setup一个地址，再stat,播放半小时后就会变卡

**Comment by CarGuo** [comment]
半小时变卡这个有点泛了，要看下是什么导致他卡，是内存呢，还是cpu之类的，还是掉帧
