### ISSUE TITLE
HttpProxyCacheServer error com.danikula.videocache.ProxyCacheException

### ISSUE THREAD

**Issue by aresa7796** [CarGuo/GSYVideoPlayer#19]
播放这个链接

http://120.25.226.186:32812/resources/videos/minion_01.mp4
报了这个异常。

`  HttpProxyCacheServer error
                                                                                  com.danikula.videocache.ProxyCacheException: Error closing socket output stream
                                                                                      at com.danikula.videocache.HttpProxyCacheServer.closeSocketOutput(HttpProxyCacheServer.java:294)
                                                                                      at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:270)
                                                                                      at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:242)
                                                                                      at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52)
                                                                                      at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:337)
                                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                      at java.lang.Thread.run(Thread.java:818)
                                                                                   Caused by: java.net.SocketException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
                                                                                      at java.net.PlainSocketImpl.shutdownOutput(PlainSocketImpl.java:377)
                                                                                      at java.net.Socket.shutdownOutput(Socket.java:652)
                                                                                      at com.danikula.videocache.HttpProxyCacheServer.closeSocketOutput(HttpProxyCacheServer.java:291)
                                                                                      at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:270) 
                                                                                      at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:242) 
                                                                                      at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) 
                                                                                      at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:337) 
                                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                      at java.lang.Thread.run(Thread.java:818) 
                                                                                   Caused by: android.system.ErrnoException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
                                                                                      at libcore.io.Posix.shutdown(Native Method)
                                                                                      at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:149)
                                                                                      at java.net.PlainSocketImpl.shutdownOutput(PlainSocketImpl.java:375)
                                                                                      at java.net.Socket.shutdownOutput(Socket.java:652) 
                                                                                      at com.danikula.videocache.HttpProxyCacheServer.closeSocketOutput(HttpProxyCacheServer.java:291) 
                                                                                      at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:270) 
                                                                                      at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:242) 
                                                                                      at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) 
                                                                                      at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:337) 
                                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                      at java.lang.Thread.run(Thread.java:818) 
`

**Comment by CarGuo** [comment]
这个异常是正常情况的，因为它强行关闭socket，新版本已经不抱这个异常了。你链接是播放不了吗？
