### ISSUE TITLE
ExoPlayer 播放m3u8 错误，IJKplayer 正常

### ISSUE THREAD

**Issue by yang0000meng** [CarGuo/GSYVideoPlayer#1907]
## 问题描述：
播放m3u8
页面https://528.jp277.com/share/2092D4071B288BB4 里面的
https://528.jp277.com/20180922/2092D4071B288BB4/index.m3u8 如果这个地址失效可以打开上线地址获取新的
ExoPlayer 播放m3u8 错误，IJKplayer 可以播放正常

## 问题机型/系统：

例如 真机 小米  Android8.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'`

## Demo中的复现步骤

Demo中的DetailMoreTypeActivity页面。

问题代码：(如果有)
改成如下代码
//        String source1 = "http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4";
//        //String source1 = "https://res.exexm.com/cw_145225549855002";
//        String name = "普通";
//        SwitchVideoModel switchVideoModel = new SwitchVideoModel(name, source1);
//
//        String source2 = "http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f30.mp4";
//        String name2 = "清晰";
//        SwitchVideoModel switchVideoModel2 = new SwitchVideoModel(name2, source2);
        String source1 = "https://528.jp277.com/20180922/2092D4071B288BB4/index.m3u8";
        //String source1 = "https://res.exexm.com/cw_145225549855002";
        String name = "普通";
        SwitchVideoModel switchVideoModel = new SwitchVideoModel(name, source1);

        String source2 = "https://528.jp277.com/20180922/2092D4071B288BB4/index.m3u8";
        String name2 = "清晰2";
        SwitchVideoModel switchVideoModel2 = new SwitchVideoModel(name2, source2);
        PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
        //PlayerFactory.setPlayManager(SystemPlayerManager.class);//系统模式
        //PlayerFactory.setPlayManager(IjkPlayerManager.class);//ijk模式
        CacheFactory.setCacheManager(ExoPlayerCacheManager.class);

## 问题log（如果有）
03-25 17:43:55.715 31508-31508/com.example.gsyvideoplayer I/GSYVideoPlayer: onClickStartError
03-25 17:43:55.716 31508-31508/com.example.gsyvideoplayer I/GSYVideoPlayer: 111955305------------------------------ dismiss CURRENT_STATE_NORMAL
03-25 17:43:55.717 31508-31508/com.example.gsyvideoplayer I/GSYVideoPlayer: changeUiToNormal
03-25 17:43:55.720 31508-31508/com.example.gsyvideoplayer I/GSYVideoPlayer: onStartPrepared
03-25 17:43:55.720 31508-31508/com.example.gsyvideoplayer W/AudioManager: Use of stream types is deprecated for operations other than volume control
03-25 17:43:55.720 31508-31508/com.example.gsyvideoplayer W/AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-25 17:43:55.724 31508-31508/com.example.gsyvideoplayer I/GSYVideoPlayer: changeUiToPreparingShow
03-25 17:43:55.727 31508-31508/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer
03-25 17:43:55.766 31508-31676/com.example.gsyvideoplayer W/GuiExt: Cannot find GuiExtService
03-25 17:43:55.768 31508-31676/com.example.gsyvideoplayer I/BufferQueueConsumer: [unnamed-31508-3](this:0x87e18000,id:3,api:0,p:-1,c:31508) connect(C): consumer=(31508:com.example.gsyvideoplayer) controlledByApp=true
03-25 17:43:55.768 31508-31676/com.example.gsyvideoplayer I/BufferQueueConsumer: [unnamed-31508-3](this:0x87e18000,id:3,api:0,p:-1,c:31508) setConsumerName: unnamed-31508-3
03-25 17:43:55.768 31508-31676/com.example.gsyvideoplayer I/BufferQueueConsumer: [SurfaceTexture-1-31508-3](this:0x87e18000,id:3,api:0,p:-1,c:31508) setConsumerName: SurfaceTexture-1-31508-3
03-25 17:43:55.789 31508-31508/com.example.gsyvideoplayer I/ExoPlayerImpl: Init b35725 [ExoPlayerLib/2.9.3] [cereus, Redmi 6, Xiaomi, 27]
03-25 17:43:55.794 31508-31508/com.example.gsyvideoplayer D/EventLogger: state [0.02, false, B]
03-25 17:43:55.806 31508-31679/com.example.gsyvideoplayer W/System: ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
03-25 17:43:55.810 31508-31679/com.example.gsyvideoplayer I/System.out: e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
03-25 17:43:55.818 31508-31679/com.example.gsyvideoplayer W/System: ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
03-25 17:43:55.821 31508-31679/com.example.gsyvideoplayer I/System.out: e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
03-25 17:43:55.892 31508-31679/com.example.gsyvideoplayer W/System: ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
03-25 17:43:55.896 31508-31679/com.example.gsyvideoplayer I/System.out: e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
03-25 17:43:55.901 31508-31679/com.example.gsyvideoplayer W/System: ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
03-25 17:43:55.904 31508-31679/com.example.gsyvideoplayer I/System.out: e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
03-25 17:43:56.978 31508-31679/com.example.gsyvideoplayer W/System: ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
03-25 17:43:56.983 31508-31679/com.example.gsyvideoplayer I/System.out: e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
03-25 17:43:56.989 31508-31679/com.example.gsyvideoplayer W/System: ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
03-25 17:43:56.994 31508-31679/com.example.gsyvideoplayer I/System.out: e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
03-25 17:43:59.072 31508-31679/com.example.gsyvideoplayer W/System: ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
03-25 17:43:59.076 31508-31679/com.example.gsyvideoplayer I/System.out: e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
03-25 17:43:59.084 31508-31679/com.example.gsyvideoplayer W/System: ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
03-25 17:43:59.088 31508-31679/com.example.gsyvideoplayer I/System.out: e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
03-25 17:43:59.170 31508-31678/com.example.gsyvideoplayer E/ExoPlayerImplInternal: Source error.
                                                                                   com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://528.jp277.com/20180922/2092D4071B288BB4/index.m3u8
                                                                                       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:281)
                                                                                       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
                                                                                       at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:53)
                                                                                       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:479)
                                                                                       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:308)
                                                                                       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
                                                                                       at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
                                                                                       at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
                                                                                       at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156)
                                                                                       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                       at java.lang.Thread.run(Thread.java:764)
                                                                                    Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                                       at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:219)
                                                                                       at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
                                                                                       at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
                                                                                       at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
                                                                                       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
                                                                                       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
                                                                                       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
                                                                                       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:299)
                                                                                       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:237)
                                                                                       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
                                                                                       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
                                                                                       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
                                                                                       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(Unknown Source:0)
                                                                                       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:528)
                                                                                       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:436)
                                                                                       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:279)
                                                                                       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250) 
                                                                                       at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:53) 
                                                                                       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:479) 
                                                                                       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:308) 
                                                                                       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
                                                                                       at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102) 
                                                                                       at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65) 
                                                                                       at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156) 
                                                                                       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                                       at java.lang.Thread.run(Thread.java:764) 
                                                                                    Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                                       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:646)
                                                                                       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
                                                                                       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
                                                                                       at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
                                                                                       at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
                                                                                       at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
                                                                                       at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:197)
                                                                                       at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:399)
03-25 17:43:59.171 31508-31678/com.example.gsyvideoplayer E/ExoPlayerImplInternal:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                                                                                       at com.android.org.conscrypt.SslWrapper.doHandshake(SslWrapper.java:374)
                                                                                       at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:217)
                                                                                       	... 27 more
                                                                                    Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                                       	... 38 more
03-25 17:43:59.177 31508-31508/com.example.gsyvideoplayer E/EventLogger: playerFailed [3.40]
                                                                         com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://528.jp277.com/20180922/2092D4071B288BB4/index.m3u8
                                                                             at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:354)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:176)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:65)
                                                                          Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://528.jp277.com/20180922/2092D4071B288BB4/index.m3u8
                                                                             at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:281)
                                                                             at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
                                                                             at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:53)
                                                                             at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:479)
                                                                             at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:308)
                                                                             at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
                                                                             at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
                                                                             at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
                                                                             at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156)
                                                                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                             at java.lang.Thread.run(Thread.java:764)
                                                                          Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                             at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:219)
                                                                             at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
                                                                             at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
                                                                             at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
                                                                             at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
                                                                             at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
                                                                             at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
                                                                             at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:299)
                                                                             at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:237)
                                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
                                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
                                                                             at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
                                                                             at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(Unknown Source:0)
                                                                             at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:528)
                                                                             at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:436)
                                                                             at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:279)
                                                                             at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250) 
                                                                             at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:53) 
                                                                             at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:479) 
                                                                             at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:308) 
                                                                             at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
                                                                             at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102) 
                                                                             at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65) 
                                                                             at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156) 
                                                                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                             at java.lang.Thread.run(Thread.java:764) 
                                                                          Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                             at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:646)
                                                                             at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
                                                                             at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
03-25 17:43:59.177 31508-31508/com.example.gsyvideoplayer E/EventLogger:     at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
                                                                             at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
                                                                             at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
                                                                             at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:197)
                                                                             at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:399)
                                                                             at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                                                                             at com.android.org.conscrypt.SslWrapper.doHandshake(SslWrapper.java:374)
                                                                             at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:217)
                                                                             	... 27 more
                                                                          Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                             	... 38 more
03-25 17:43:59.179 31508-31508/com.example.gsyvideoplayer D/EventLogger: sourceInfo [periodCount=0, windowCount=0
03-25 17:43:59.179 31508-31508/com.example.gsyvideoplayer D/EventLogger: ]
03-25 17:43:59.180 31508-31508/com.example.gsyvideoplayer D/EventLogger: state [3.40, false, I]
03-25 17:43:59.180 31508-31508/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer
03-25 17:43:59.181 31508-31508/com.example.gsyvideoplayer I/GSYVideoPlayer: changeUiToError
03-25 17:43:59.182 31508-31508/com.example.gsyvideoplayer E/GSYVideoPlayer: Link Or mCache Error, Please Try Again https://528.jp277.com/20180922/2092D4071B288BB4/index.m3u8
03-25 17:43:59.182 31508-31508/com.example.gsyvideoplayer E/GSYVideoPlayer: mCache Link https://528.jp277.com/20180922/2092D4071B288BB4/index.m3u8
03-25 17:43:59.189 31508-31508/com.example.gsyvideoplayer I/ExoPlayerImpl: Release b35725 [ExoPlayerLib/2.9.3] [cereus, Redmi 6, Xiaomi, 27] [goog.exo.core, goog.exo.hls]
03-25 17:43:59.198 31508-31508/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer
03-25 17:43:59.198 31508-31676/com.example.gsyvideoplayer I/BufferQueueConsumer: [SurfaceTexture-1-31508-3](this:0x87e18000,id:3,api:0,p:-1,c:-1) disconnect(C)

**Comment by CarGuo** [comment]
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.   看起来是证书问题？有试过开启proxy cache 试试吗？

**Comment by yang0000meng** [comment]
proxy cache demo 里设为true 或 false 都不可以播放

**Comment by CarGuo** [comment]
应该就是http connect 的时候证书问题， 可以先参考 https://github.com/CarGuo/GSYVideoPlayer/issues/1640

**Comment by CarGuo** [comment]
刚刚更新了demo， 可以看 https://github.com/CarGuo/GSYVideoPlayer/blob/098cb882ccae14926a9f106535f8b0261df91385/app/src/main/java/com/example/gsyvideoplayer/GSYApplication.java#L56

打开这个注释，demo下的 exoplayer就可以正常了播放了。

**Comment by yang0000meng** [comment]
十分感谢，可以了

**Comment by yang0000meng** [comment]
添加这个后 ExoSourceManager.setExoMediaSourceInterceptListener
原来的传入的值  setMapHeadData就都不管用了，可否把这个也添加上。
