### ISSUE TITLE
使用exo播放，报错 ，已按照demo设置忽略校验，还是有问题，放在demo   SimplePlayer  页面播放也是有画面没有声音

### ISSUE THREAD

**Issue by xyZangGit** [CarGuo/GSYVideoPlayer#1942]
## 问题描述：

播放视频报错 ，使用的是exo模式播放，ssl校验不通过，已设置忽略校验 ，demo播放也是有画面没有声音

https://file.shftz.cn:8443/filesystem/download/10/2019/3/26/ce2c7c66-e9eb-42be-adf6-f9008385ea8c.mov/play

上面是播放地址

## GSY依赖版本

api 'com.shuyu:GSYVideoPlayer:6.0.1'

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
mActyVideoDetailCv.setUpLazy(videoUrl,
                false,
                StewardApp.getVideoCache(),
                null,
                "")
![image](https://user-images.githubusercontent.com/19574114/55458997-0340d200-5621-11e9-8acc-114e02277e5f.png)

## 问题log（如果有）
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:349)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://file.shftz.cn:8443/filesystem/download/10/2019/3/26/79d06362-1f26-4925-a663-e543e370051e.mp4/play
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:194)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:844)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:229)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:26)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:429)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:350)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:192)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147) 
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:844) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:646)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
        at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
        at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:208)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:404)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
04-03 14:58:07.633 23285-23494/com.wlf.steward E/EventLogger:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
        	... 21 more
     Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        	... 32 more

**Comment by CarGuo** [comment]
有画面没声音那就是音频编码不支持，exo你说的exo是ex_so还是exoplayer？？
如果的音频编码exoplayer不支持，说明系统的mediacodec就不支持你的音频协议

**Comment by xyZangGit** [comment]
> 有画面没声音那就是音频编码不支持，exo你说的exo是ex_so还是exoplayer？？
> 如果的音频编码exoplayer不支持，说明系统的mediacodec就不支持你的音频协议
刚才试了一下  ex_so  的也是播放没声音，  用exoplayer  也是没声音，  大大试一下我这个地址

**Comment by xyZangGit** [comment]
> 有画面没声音那就是音频编码不支持，exo你说的exo是ex_so还是exoplayer？？
> 如果的音频编码exoplayer不支持，说明系统的mediacodec就不支持你的音频协议

刚才试了一下 ex_so 的也是播放没声音， 用exoplayer 也是没声音， 大大试一下我这个地址

**Comment by xyZangGit** [comment]
> 有画面没声音那就是音频编码不支持，exo你说的exo是ex_so还是exoplayer？？
> 如果的音频编码exoplayer不支持，说明系统的mediacodec就不支持你的音频协议

我用了一下别的库播放是没问题的，但是现在项目已经成型了，换库是不可能了，大大看一下是不是有什么问题

**Comment by CarGuo** [comment]
你用的哪个库播放可以的？现在的音频应该是 pcm_s16be

**Comment by xyZangGit** [comment]
> 你用的哪个库播放可以的？现在的音频应该是 pcm_s16be

https://github.com/jiajunhui/PlayerBase     这个库

**Comment by xyZangGit** [comment]
> 你用的哪个库播放可以的？现在的音频应该是 pcm_s16be
我用QQ浏览器打开也是可以播放的

**Comment by xyZangGit** [comment]
> 你用的哪个库播放可以的？现在的音频应该是 pcm_s16be

我今天改了一天了，希望大大能解决一下这个问题，挺着急的

**Comment by CarGuo** [comment]
@xyZangGit OK了，其实你还是没明白我的意思，因为 pcm_s16be 系统不支持，所以你需编译ijk的so支持
https://github.com/jiajunhui/PlayerBase/tree/master/app/src/main/jniLibs/armeabi-v7a  不过这个库已经编译支持过，只是只有armeabi-v7a。

1、把这个 上面链接的 armeabi-v7a 整个文件夹放到你的项目的libs 下。
2、配置gradle

```

android {

    def globalConfiguration = rootProject.extensions.getByName("ext")
    compileSdkVersion globalConfiguration.androidCompileSdkVersion
    buildToolsVersion globalConfiguration.androidBuildToolsVersion

    defaultConfig {
        applicationId "com.example.gsyvideoplayer"

        multiDexEnabled true

        minSdkVersion globalConfiguration.androidMinSdkVersion
        targetSdkVersion globalConfiguration.androidTargetSdkVersion

        versionCode 6
        versionName "5.0.0"

        javaCompileOptions {
            annotationProcessorOptions.includeCompileClasspath = true
        }
       ///主要是这里！！！！！！！
        ndk  {
            //设置支持的SO库架构
            abiFilters 'armeabi-v7a'
        }

    }


    signingConfigs {
        releaseConfig {
            storeFile file("../debug.jks")
            storePassword "123456"
            keyAlias "debug"
            keyPassword "123456"
        }
    }

    buildTypes {

        release {
            minifyEnabled false
            signingConfig signingConfigs.releaseConfig
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
   ///主要是这里！！！！！！！
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }

    compileOptions { targetCompatibility JavaVersion.VERSION_1_8 }

    lintOptions {
        abortOnError false
    }

}

```

3、只依赖GSY项目的 java

4、OK了

**Comment by xyZangGit** [comment]
> @xyZangGit OK了，其实你还是没明白我的意思，因为 pcm_s16be 系统不支持，所以你需编译ijk的so支持
> https://github.com/jiajunhui/PlayerBase/tree/master/app/src/main/jniLibs/armeabi-v7a 不过这个库已经编译支持过，只是只有armeabi-v7a。
> 
> 1、把这个 上面链接的 armeabi-v7a 整个文件夹放到你的项目的libs 下。
> 2、配置gradle
> 
> ```
> 
> android {
> 
>     def globalConfiguration = rootProject.extensions.getByName("ext")
>     compileSdkVersion globalConfiguration.androidCompileSdkVersion
>     buildToolsVersion globalConfiguration.androidBuildToolsVersion
> 
>     defaultConfig {
>         applicationId "com.example.gsyvideoplayer"
> 
>         multiDexEnabled true
> 
>         minSdkVersion globalConfiguration.androidMinSdkVersion
>         targetSdkVersion globalConfiguration.androidTargetSdkVersion
> 
>         versionCode 6
>         versionName "5.0.0"
> 
>         javaCompileOptions {
>             annotationProcessorOptions.includeCompileClasspath = true
>         }
>        ///主要是这里！！！！！！！
>         ndk  {
>             //设置支持的SO库架构
>             abiFilters 'armeabi-v7a'
>         }
> 
>     }
> 
> 
>     signingConfigs {
>         releaseConfig {
>             storeFile file("../debug.jks")
>             storePassword "123456"
>             keyAlias "debug"
>             keyPassword "123456"
>         }
>     }
> 
>     buildTypes {
> 
>         release {
>             minifyEnabled false
>             signingConfig signingConfigs.releaseConfig
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>         }
> 
>         debug {
>             minifyEnabled false
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>         }
>     }
>    ///主要是这里！！！！！！！
>     sourceSets {
>         main {
>             jniLibs.srcDirs = ['libs']
>         }
>     }
> 
>     compileOptions { targetCompatibility JavaVersion.VERSION_1_8 }
> 
>     lintOptions {
>         abortOnError false
>     }
> 
> }
> ```
> 3、只依赖GSY项目的 java
> 
> 4、OK了

目前我的项目还有其他架构的包，可否多编译几个架构的so

**Comment by CarGuo** [comment]
他只提供了armv7a我目前看到。只要你配置了ndk过滤，其实是没问题的。只要armv7a都存在，那么系统会兼容查找使用，只有armv7a 一个目录的so是可以正常的。


不然的话就是你自己编译下或者找那个作者提供下～～

欧了，问题close了

**Comment by xyZangGit** [comment]
> 他只提供了armv7a我目前看到。只要你配置了ndk过滤，其实是没问题的。只要armv7a都存在，那么系统会兼容查找使用，只有armv7a 一个目录的so是可以正常的。
> 
> 不然的话就是你自己编译下或者找那个作者提供下～～
> 
> 欧了，问题close了

我的NDk配置了3个目录，有一个是必须有的，删不到的，因为是腾讯的，只支持armeabi

**Comment by CarGuo** [comment]
如果最低兼容 armeabi ,可以把 armeabi-v7a 里面的 so 拷贝到 armeabi 。

**Comment by xyZangGit** [comment]
> 如果最低兼容 armeabi ,可以把 armeabi-v7a 里面的 so 拷贝到 armeabi 。浮点和没浮点的区别

好的，谢谢大大，已经解决掉了，您可以把我这个 开放出来，让别人也能看到这个问题
