### ISSUE TITLE
视频播放403

### ISSUE THREAD

**Issue by westlinkin** [CarGuo/GSYVideoPlayer#1956]
因为auth问题，视频url 403了，应该是启用了代理，请求的ip改变了，导致403？

```
2019-04-09 16:14:16.233 9978-10717/com.****.***** D/IJKMEDIA: IjkMediaPlayer_prepareAsync
2019-04-09 16:14:16.233 9978-10717/com.****.***** D/IJKMEDIA: ijkmp_prepare_async()
2019-04-09 16:14:16.233 9978-10717/com.****.***** I/IJKMEDIA: ===== versions =====
2019-04-09 16:14:16.233 9978-10717/com.****.***** I/IJKMEDIA: ijkplayer    : k0.8.8
2019-04-09 16:14:16.233 9978-10717/com.****.***** I/IJKMEDIA: FFmpeg       : ff3.4--ijk0.8.7--20180103--001
2019-04-09 16:14:16.233 9978-10717/com.****.***** I/IJKMEDIA: libavutil    : 55.78.100
2019-04-09 16:14:16.233 9978-10725/com.****.***** I/IJKMEDIA: SDL_RunThread: [10725] ff_msg_loop
2019-04-09 16:14:16.233 9978-10717/com.****.***** I/IJKMEDIA: libavcodec   : 57.107.100
2019-04-09 16:14:16.233 9978-10725/com.****.***** D/IJKMEDIA: message_loop
2019-04-09 16:14:16.233 9978-10717/com.****.***** I/IJKMEDIA: libavformat  : 57.83.100
2019-04-09 16:14:16.233 9978-10717/com.****.***** I/IJKMEDIA: libswscale   : 4.8.100
2019-04-09 16:14:16.233 9978-10717/com.****.***** I/IJKMEDIA: libswresample: 2.9.100
2019-04-09 16:14:16.233 9978-10717/com.****.***** I/IJKMEDIA: ===== options =====
2019-04-09 16:14:16.233 9978-10717/com.****.***** I/IJKMEDIA: player-opts : loop                         = 1
2019-04-09 16:14:16.233 9978-10717/com.****.***** I/IJKMEDIA: format-opts : ijkapplication               = 486749187200
2019-04-09 16:14:16.233 9978-10717/com.****.***** I/IJKMEDIA: format-opts : ijkiomanager                 = 486804194816
2019-04-09 16:14:16.233 9978-10717/com.****.***** I/IJKMEDIA: ===================
2019-04-09 16:14:16.234 9978-10725/com.****.***** D/IJKMEDIA: FFP_MSG_FLUSH:
2019-04-09 16:14:16.235 9978-10717/com.****.***** D/IJKMEDIA: ijkmp_prepare_async()=0
2019-04-09 16:14:16.235 9978-10726/com.****.***** I/IJKMEDIA: SDL_RunThread: [10726] ff_vout
2019-04-09 16:14:16.235 9978-10727/com.****.***** I/IJKMEDIA: SDL_RunThread: [10727] ff_read
2019-04-09 16:14:16.235 9978-10727/com.****.***** D/IJKMEDIA: Opening 'https://www.dailymotion.com/cdn/H264-512x384/video/x7562mi.mp4?sec=CJxwMhHqAehU5AEYe1pzwd0a0ikOutsVI6hLtNAFiZSPSJKS9XVaGl880KDkmBgm' for reading
2019-04-09 16:14:16.235 9978-10727/com.****.***** D/IJKMEDIA: Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto,httpproxy'
2019-04-09 16:14:16.241 9978-10727/com.****.***** I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
2019-04-09 16:14:16.245 9978-10727/com.****.***** I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
2019-04-09 16:14:16.255 9978-10727/com.****.***** I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
2019-04-09 16:14:16.255 9978-10727/com.****.***** I/IJKMEDIA: Add dns cache hostname = www.dailymotion.com, ip = 195.8.215.136
2019-04-09 16:14:17.431 9978-10727/com.****.***** D/IJKMEDIA: request: GET /cdn/H264-512x384/video/x7562mi.mp4?sec=CJxwMhHqAehU5AEYe1pzwd0a0ikOutsVI6hLtNAFiZSPSJKS9XVaGl880KDkmBgm HTTP/1.1
    User-Agent: Lavf/57.83.100
    Accept: */*
    Range: bytes=0-
    Connection: close
    Host: www.dailymotion.com
    Icy-MetaData: 1
2019-04-09 16:14:17.932 9978-10727/com.****.***** V/IJKMEDIA: header='HTTP/1.1 302 Found'
2019-04-09 16:14:17.932 9978-10727/com.****.***** V/IJKMEDIA: http_code=302
2019-04-09 16:14:17.932 9978-10727/com.****.***** V/IJKMEDIA: header='Content-Security-Policy-Report-Only: default-src https: blob: wss: data: android-webview-video-poster: android-webview: chrome-extension: safari-extension: 'unsafe-eval' 'unsafe-inline'; report-uri https://www.dailymotion.com/content_security_policy_report_uri'
2019-04-09 16:14:17.932 9978-10727/com.****.***** V/IJKMEDIA: header='Server: DMS/1.0.42'
2019-04-09 16:14:17.932 9978-10727/com.****.***** V/IJKMEDIA: header='X-DM-BackNode: web-437.adm.dc3.dailymotion.com:80'
2019-04-09 16:14:17.932 9978-10727/com.****.***** V/IJKMEDIA: header='Vary: X-DM-SSL'
2019-04-09 16:14:17.932 9978-10727/com.****.***** V/IJKMEDIA: header='Cache-Control: private, max-age=60'
2019-04-09 16:14:17.932 9978-10727/com.****.***** V/IJKMEDIA: header='Content-Type: text/html; charset=utf-8'
2019-04-09 16:14:17.932 9978-10727/com.****.***** V/IJKMEDIA: header='Content-Security-Policy: upgrade-insecure-requests'
2019-04-09 16:14:17.932 9978-10727/com.****.***** V/IJKMEDIA: header='Access-Control-Expose-Headers: X-DM-BackNode-Response-Time'
2019-04-09 16:14:17.933 9978-10727/com.****.***** V/IJKMEDIA: header='Strict-Transport-Security: max-age=31708800; includeSubDomains'
2019-04-09 16:14:17.933 9978-10727/com.****.***** V/IJKMEDIA: header='Date: Tue, 09 Apr 2019 08:14:16 GMT'
2019-04-09 16:14:17.933 9978-10727/com.****.***** V/IJKMEDIA: header='Location: https://proxy-12.nyc.dailymotion.com/sec(YSrsF079hcyCFPupyozEeEkYYPEONW6YCnsQzncYAcRG4ohqM8A7f5PUq4Hh0dJBCDM_rsNFmrfYYC-hg9WVeA)/video/056/449/431944650_mp4_h264_aac_1.mp4#cell=nyc&comment=PPI&qos_vpart=1&qos_stail=1&qos_geostore=1'
2019-04-09 16:14:17.933 9978-10727/com.****.***** V/IJKMEDIA: header='Keep-Alive: timeout=60, max=4989'
2019-04-09 16:14:17.933 9978-10727/com.****.***** V/IJKMEDIA: header='X-DM-LB-IP: 195.8.215.136'
2019-04-09 16:14:17.933 9978-10727/com.****.***** V/IJKMEDIA: header='Expires: Tue, 09 Apr 2019 08:15:16 +0000'
2019-04-09 16:14:17.933 9978-10727/com.****.***** V/IJKMEDIA: header='X-DM-LB-Name: lb-08'
2019-04-09 16:14:17.933 9978-10727/com.****.***** V/IJKMEDIA: header='X-DM-BackNode-Response-Time: 21'
2019-04-09 16:14:17.933 9978-10727/com.****.***** V/IJKMEDIA: header='Connection: close'
2019-04-09 16:14:17.933 9978-10727/com.****.***** V/IJKMEDIA: header='Set-Cookie: ts=313401; expires=Sat, 09-May-2020 08:14:16 GMT; Max-Age=34214400; path=/; domain=.dailymotion.com'
2019-04-09 16:14:17.934 9978-10727/com.****.***** V/IJKMEDIA: header='Set-Cookie: sid=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/'
2019-04-09 16:14:17.934 9978-10727/com.****.***** W/IJKMEDIA: Unable to parse 'sid=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/'
2019-04-09 16:14:17.934 9978-10727/com.****.***** V/IJKMEDIA: header='Set-Cookie: sdx=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/'
2019-04-09 16:14:17.934 9978-10727/com.****.***** W/IJKMEDIA: Unable to parse 'sdx=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/'
2019-04-09 16:14:17.934 9978-10727/com.****.***** V/IJKMEDIA: header='Set-Cookie: su_user_id=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/'
2019-04-09 16:14:17.934 9978-10727/com.****.***** W/IJKMEDIA: Unable to parse 'su_user_id=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/'
2019-04-09 16:14:17.934 9978-10727/com.****.***** V/IJKMEDIA: header='Set-Cookie: su_sid=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/'
2019-04-09 16:14:17.934 9978-10727/com.****.***** W/IJKMEDIA: Unable to parse 'su_sid=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/'
2019-04-09 16:14:17.934 9978-10727/com.****.***** V/IJKMEDIA: header='Set-Cookie: su_sdx=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/'
2019-04-09 16:14:17.935 9978-10727/com.****.***** W/IJKMEDIA: Unable to parse 'su_sdx=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/'
2019-04-09 16:14:17.935 9978-10727/com.****.***** V/IJKMEDIA: header='Set-Cookie: client_token=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/'
2019-04-09 16:14:17.935 9978-10727/com.****.***** W/IJKMEDIA: Unable to parse 'client_token=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/'
2019-04-09 16:14:17.935 9978-10727/com.****.***** V/IJKMEDIA: header='Set-Cookie: access_token=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/'
2019-04-09 16:14:17.935 9978-10727/com.****.***** W/IJKMEDIA: Unable to parse 'access_token=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/'
2019-04-09 16:14:17.935 9978-10727/com.****.***** V/IJKMEDIA: header='Set-Cookie: refresh_token=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/'
2019-04-09 16:14:17.935 9978-10727/com.****.***** W/IJKMEDIA: Unable to parse 'refresh_token=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/'
2019-04-09 16:14:17.935 9978-10727/com.****.***** V/IJKMEDIA: header='Set-Cookie: dmvk=5cac54581a5ed; path=/; domain=.dailymotion.com'
2019-04-09 16:14:17.935 9978-10727/com.****.***** V/IJKMEDIA: header='Set-Cookie: v1st=6F4A62E324757929EACEB0B3D41233C4; expires=Fri, 08 May 2020 08:14:15 GMT; max-age=34128000; path=/; domain=.dailymotion.com'
2019-04-09 16:14:17.936 9978-10727/com.****.***** V/IJKMEDIA: header='X-Dm-Page: us.html.cdn_director'
2019-04-09 16:14:17.936 9978-10727/com.****.***** V/IJKMEDIA: header='X-Dm-Error: DM_RequestCompat__Stop_Exception :'
2019-04-09 16:14:17.936 9978-10727/com.****.***** V/IJKMEDIA: header='Content-Length: 0'
2019-04-09 16:14:17.936 9978-10727/com.****.***** V/IJKMEDIA: header=''
2019-04-09 16:14:18.282 9978-10727/com.****.***** I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
2019-04-09 16:14:18.342 9978-10727/com.****.***** I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
2019-04-09 16:14:18.343 9978-10727/com.****.***** I/IJKMEDIA: Add dns cache hostname = proxy-12.nyc.dailymotion.com, ip = 198.54.201.12
2019-04-09 16:14:19.366 9978-10727/com.****.***** D/IJKMEDIA: request: GET /sec(YSrsF079hcyCFPupyozEeEkYYPEONW6YCnsQzncYAcRG4ohqM8A7f5PUq4Hh0dJBCDM_rsNFmrfYYC-hg9WVeA)/video/056/449/431944650_mp4_h264_aac_1.mp4#cell=nyc&comment=PPI&qos_vpart=1&qos_stail=1&qos_geostore=1 HTTP/1.1
    User-Agent: Lavf/57.83.100
    Accept: */*
    Range: bytes=0-
    Connection: close
    Host: proxy-12.nyc.dailymotion.com
    Cookie: ts=313401; dmvk=5cac54581a5ed; v1st=6F4A62E324757929EACEB0B3D41233C4
    Icy-MetaData: 1
2019-04-09 16:14:19.852 9978-10727/com.****.***** V/IJKMEDIA: header='HTTP/1.1 403 Forbidden'
2019-04-09 16:14:19.852 9978-10727/com.****.***** V/IJKMEDIA: http_code=403
2019-04-09 16:14:19.852 9978-10727/com.****.***** W/IJKMEDIA: HTTP error 403 Forbidden
2019-04-09 16:14:19.855 9978-10727/com.****.***** I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
2019-04-09 16:14:19.856 9978-10727/com.****.***** E/IJKMEDIA: https://www.dailymotion.com/cdn/H264-512x384/video/x7562mi.mp4?sec=CJxwMhHqAehU5AEYe1pzwd0a0ikOutsVI6hLtNAFiZSPSJKS9XVaGl880KDkmBgm: Server returned 403 Forbidden (access denied)
2019-04-09 16:14:19.856 9978-10727/com.****.***** I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [10727]
2019-04-09 16:14:19.856 9978-10725/com.****.***** D/IJKMEDIA: FFP_MSG_ERROR: 0
2019-04-09 16:14:19.857 9978-10717/com.****.***** E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
2019-04-09 16:14:19.867 9978-10717/com.****.***** D/IJKMEDIA: IjkMediaPlayer_release
````

使用`SystemPlayerManager` 可以正常播放

**Comment by CarGuo** [comment]
setup或者builder是cache为false

**Comment by westlinkin** [comment]
setup里，`cacheWithPlay`已经设为`false`了：

```
videoPlayerView.setUp(currentVideoUrl, false, video.title)
```

那这是什么原因造成的呢？奇怪的是`IjkPlayerManager`就有问题，`SystemPlayerManager`就可以正常播放。

**Comment by westlinkin** [comment]
视频url 有个302的跳转，会从`currentVideoUrl` 跳转到真正的url地址去，不知道会不会有什么影响？

**Comment by CarGuo** [comment]
会的，ijk并不支持这样

**Comment by westlinkin** [comment]
那怎么才能修复这个因302引起的问题？

**Comment by CarGuo** [comment]
PlayerFactory.setPlayManager(Exo2PlayerManager.class);  cache设置为false试试

**Comment by westlinkin** [comment]
一样的，都是403

```
2019-04-12 15:08:35.195 14015-14523/com.****.**** E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2019-04-12 15:08:35.200 14015-14015/com.****.**** E/EventLogger: playerFailed [12.62]
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:354)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

```

**Comment by westlinkin** [comment]
同样一个url，在浏览器中访问，能跳转到正确的视频地址，用`HttpUrlConnection` 来抓取redirect Location，获取到的url就是403。很奇怪

大神有什么解决方案么

**Comment by tinoPeng** [comment]
我也遇到这个问题了，请问有解决的办法吗

**Comment by tinoPeng** [comment]
> 一样的，都是403
> 
> ```
> 2019-04-12 15:08:35.195 14015-14523/com.****.**** E/ExoPlayerImplInternal: Source error.
>     com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
>         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
>         at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
>         at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
>         at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
>         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
>         at java.lang.Thread.run(Thread.java:764)
> 2019-04-12 15:08:35.200 14015-14015/com.****.**** E/EventLogger: playerFailed [12.62]
>     com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
>         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:354)
>         at android.os.Handler.dispatchMessage(Handler.java:101)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.os.HandlerThread.run(HandlerThread.java:65)
>      Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
>         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
>         at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
>         at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
>         at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
>         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
>         at java.lang.Thread.run(Thread.java:764)
> ```
 请问403的问题解决了吗，我也遇到了这个问题，求指教呀

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2669#issuecomment-615104476
