### ISSUE TITLE
CommonUtil 获取网络信息空指针异常

### ISSUE THREAD

**Issue by hyhyhykw** [CarGuo/GSYVideoPlayer#1960]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

CommonUtil 获取网络信息时出现了崩溃，没有判断是否为null，还好 目前只有这个机型崩溃

## 问题机型/系统：

例如 真机 ZTE BA603 安卓7.0.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

java.lang.NullPointerException: Attempt to invoke interface method 'android.net.wifi.WifiInfo android.net.wifi.IWifiManager.getConnectionInfo()' on a null object reference
	at android.os.Parcel.readException(Parcel.java:1689)
	at android.os.Parcel.readException(Parcel.java:1636)
	at android.net.IConnectivityManager$Stub$Proxy.getNetworkInfo(IConnectivityManager.java:1183)
	at com.zte.security.ZTEIConnectivityManager.getNetworkInfo(ZTEIConnectivityManager.java:95)
	at android.net.ConnectivityManager.getNetworkInfo(ConnectivityManager.java:887)
	at com.shuyu.gsyvideoplayer.utils.CommonUtil.isWifiConnected(CommonUtil.java:52)
	at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.isShowNetConfirm(GSYVideoControlView.java:1045)
	at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.clickStartIcon(GSYVideoControlView.java:824)
	at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.onClick(GSYVideoControlView.java:382)
	at xxx.xxx.xxx.view.LandLayoutVideo.onClick(LandLayoutVideo.java:338)
	at android.view.View.performClick(View.java:5609)
	at android.view.View$PerformClick.run(View.java:22267)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6100)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

```

**Comment by CarGuo** [comment]
demo怎么浮现问题

**Comment by hyhyhykw** [comment]
> demo怎么浮现问题

sorry 这个不是demo中出现的bug，是app里极光bug追踪到的，只有ZTE BA603出现了这个问题， 系统是安卓7.0.0，你看错误追踪是CommonUtil第52行出现的

**Comment by CarGuo** [comment]
connectivityManager.getNetworkInfo(ConnectivityManager.TYPE_WIFI); 这个拿到是空的导致，这个要看为什么会是空的

**Comment by hyhyhykw** [comment]
> connectivityManager.getNetworkInfo(ConnectivityManager.TYPE_WIFI); 这个拿到是空的导致，这个要看为什么会是空的
可能是部分机型拿不到NetworkInfo吧，不过目前就这一个手机出现问题，影响不大

**Comment by lepaitianshi** [comment]
第三方定制的平板，android系统是9.0的，connectivityManager.getNetworkInfo(ConnectivityManager.TYPE_WIFI)返回值为null
