### ISSUE TITLE
异常视频流，加载后 黑屏，大概率出现

### ISSUE THREAD

**Issue by tangkoucan** [CarGuo/GSYVideoPlayer#1983]
（ps 首页问题集锦和demo请先了解一下！）
切换视频的时候
 问题机型/系统：TV机顶盒 4.4系统

GSY依赖版本
  implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'
    implementation 'com.shuyu:GSYVideoPlayer-exo2:6.0.1'
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.1'

## 问题log（如果有）
E/DefaultHttpDataSource: Unexpected error while disconnecting
    java.lang.ArrayIndexOutOfBoundsException: length=4096; regionStart=0; regionLength=-17464136
        at java.util.Arrays.checkOffsetAndCount(Arrays.java:1732)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:252)
        at com.android.okhttp.internal.http.HttpTransport$FixedLengthInputStream.read(HttpTransport.java:386)
        at libcore.io.Streams.skipByReading(Streams.java:158)
        at java.io.InputStream.skip(InputStream.java:227)
        at com.android.okhttp.internal.Util.skipAll(Util.java:249)
        at com.android.okhttp.internal.http.HttpTransport.discardStream(HttpTransport.java:190)
        at com.android.okhttp.internal.http.HttpTransport.access$200(HttpTransport.java:32)
        at com.android.okhttp.internal.http.HttpTransport$FixedLengthInputStream.close(HttpTransport.java:408)
        at com.android.okhttp.internal.Util.closeQuietly(Util.java:110)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:102)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.closeConnectionQuietly(DefaultHttpDataSource.java:638)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.close(DefaultHttpDataSource.java:286)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.close(DefaultDataSource.java:164)
        at com.google.android.exoplayer2.util.Util.closeQuietly(Util.java:265)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:870)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)

**Comment by CarGuo** [comment]
demo怎么复习，有流吗
