### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by PiPiCaptain** [CarGuo/GSYVideoPlayer#199]
java.lang.OutOfMemoryError
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:770)
	at android.view.TextureView.getBitmap(TextureView.java:561)
	at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.updatePauseCover(Unknown Source)
	at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.changeUiToPauseShow(Unknown Source)
	at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.setStateAndUi(Unknown Source)
	at com.shuyu.gsyvideoplayer.GSYVideoPlayer.onVideoPause(Unknown Source)
	at *****Activity.onPause(Unknown Source)
	at android.app.Activity.performPause(Activity.java:5466)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1235)
	at cn.jiguang.a.a.c.a.a.d.callActivityOnPause(Unknown Source)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3057)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3026)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3004)
	at android.app.ActivityThread.access$1000(ActivityThread.java:140)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5143)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
	at dalvik.system.NativeStart.main(Native Method)

机型vivo Y27，系统版本4.4

**Comment by CarGuo** [comment]
后面提供个方法，PauseCover提示是否可选

**Comment by PiPiCaptain** [comment]
@CarGuo 1.6.5版本预计什么时候发布？

**Comment by CarGuo** [comment]
已经更新

**Comment by PiPiCaptain** [comment]
@CarGuo 谢谢，辛苦了
