### ISSUE TITLE
有些播放地址，只有指定的内核才能播放

### ISSUE THREAD

**Issue by ykbjson** [CarGuo/GSYVideoPlayer#2015]
## 问题描述：

这个地址的视频，只能用系统播放内核才能播放，ijk和exo都不能播放：
https://cn3.ceomhl.com/hls/20190507/4bca31e5062553c2ac5c4e1352f5decc/1557160476/index.m3u8。
还有些地址，只有exo能播放，ijk不能播。。。

## 问题机型/系统：
 真机 小米note3 Android8.1

## GSY依赖版本

//视频播放 完整版引入 https://github.com/CarGuo/GSYVideoPlayer
    //    api 'com.shuyu:GSYVideoPlayer:6.0.3'
    api 'com.shuyu:gsyVideoPlayer-java:6.0.3'
    //是否需要ExoPlayer模式
    api 'com.shuyu:GSYVideoPlayer-exo2:6.0.3'
    //根据你的需求ijk模式的so
    api 'com.shuyu:gsyVideoPlayer-armv7a:6.0.3'

问题代码：(如果有)
```
 PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
//        PlayerFactory.setPlayManager(SystemPlayerManager.class);//系统模式
//        PlayerFactory.setPlayManager(IjkPlayerManager.class);//ijk模式
        CacheFactory.setCacheManager(ExoPlayerCacheManager.class);//exo缓存模式，支持m3u8，只支持exo
//        CacheFactory.setCacheManager(ProxyCacheManager.class);//代理缓存模式，支持所有模式，不支持m3u8等

    public void setVideoSource(String title, String frameUrl, String sourceUrl) {
        if (!TextUtils.isEmpty(sourceUrl)) {
            addHeader("Referer", frameUrl);
            mFrameUrl = frameUrl;
            title = null == title ? "" : title;
            setUp(sourceUrl, false, title);
        }
    }

```

## 问题log（如果有）

```

Couldn't open https://cn3.ceomhl.com/hls/20190507/4bca31e5062553c2ac5c4e1352f5decc/1557160476/index.m3u8: java.io.FileNotFoundException: No content provider: https://cn3.ceomhl.com/hls/20190507/4bca31e5062553c2ac5c4e1352f5decc/1557160476/index.m3u8

 E/cr_MediaResource: Unable to configure metadata extractor

E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 301
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

E/EventLogger: playerFailed [3.59]
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 301
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:354)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:173)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 301
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:156)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

 E/GSYVideoPlayer: cancelTimeOutBuffer
 I/GSYVideoPlayer: changeUiToError
 E/GSYVideoPlayer: Link Or mCache Error, Please Try Again http://cn3.78love.cn/hls/20190507/4bca31e5062553c2ac5c4e1352f5decc/1557160476/index.m3u8
I/ExoPlayerImpl: Release eba2a89 [ExoPlayerLib/2.9.3] [jason, Mi Note 3, Xiaomi, 27] [goog.exo.core, goog.exo.hls]
E/GSYVideoPlayer: cancelTimeOutBuffer


```

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2007

**Comment by ykbjson** [comment]
、、、

    private static void initMediaPlayer(Context context) {
//        IjkPlayerManager.setLogLevel(IjkMediaPlayer.IJK_LOG_SILENT);
 
        PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
//        PlayerFactory.setPlayManager(SystemPlayerManager.class);//系统模式
//        PlayerFactory.setPlayManager(IjkPlayerManager.class);//ijk模式
        CacheFactory.setCacheManager(ExoPlayerCacheManager.class);//exo缓存模式，支持m3u8，只支持exo
//        CacheFactory.setCacheManager(ProxyCacheManager.class);//代理缓存模式，支持所有模式，不支持m3u8等

        ExoSourceManager.setExoMediaSourceInterceptListener((dataSource, preview, cacheEnable, isLooping, cacheDir) -> {
            Uri contentUri = Uri.parse(dataSource);
            int contentType = inferContentType(dataSource);
            switch (contentType) {
                case C.TYPE_HLS:
                    return new HlsMediaSource.Factory(getDataSourceFactory(context, preview)).createMediaSource(contentUri);
            }
            return null;
        });
    }

    /**
     * 获取SourceFactory
     *
     * @param context
     * @param preview
     */
    public static DataSource.Factory getDataSourceFactory(Context context, boolean preview) {
        return new DefaultDataSourceFactory(context, preview ? null : new DefaultBandwidthMeter(),
                getHttpDataSourceFactory(context, preview, TAG));
    }

    /**
     * 获取自定义SourceFactory
     *
     * @param context
     * @param preview
     * @param tag
     */
    public static DataSource.Factory getHttpDataSourceFactory(Context context, boolean preview, String tag) {
        DefaultHttpDataSourceFactory dataSourceFactory = new DefaultHttpDataSourceFactory(Util.getUserAgent(context,
                tag), preview ? null : new DefaultBandwidthMeter());
        return dataSourceFactory;
    }

、、、

是要修改那个TAG才可以吗？具体传递什么值啊？

**Comment by ykbjson** [comment]
我添加了上面条评论的代码，还是不能播放，请问有解决方法么？谢谢。

**Comment by ykbjson** [comment]
已经解决了，完整代码如下
、、、

private static void initMediaPlayer(Context context) {
        PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
        CacheFactory.setCacheManager(ExoPlayerCacheManager.class);//exo缓存模式，支持m3u8，只支持exo
        ExoSourceManager.setExoMediaSourceInterceptListener((dataSource, preview, cacheEnable, isLooping, cacheDir) -> {
            Uri contentUri = Uri.parse(dataSource);
            int contentType = inferContentType(dataSource);
            switch (contentType) {
                case C.TYPE_HLS:
                    return new HlsMediaSource.Factory(getDataSourceFactory(context,true)).createMediaSource(contentUri);
            }
            return null;
        });
    }

    /**
     * 获取SourceFactory
     *
     * @param context
     * @param preview
     */
    public static DataSource.Factory getDataSourceFactory(Context context, boolean preview) {
        return new DefaultDataSourceFactory(context, preview ? null : new DefaultBandwidthMeter(),
                getHttpDataSourceFactory(context, preview, TAG));
    }

    /**
     * 获取自定义SourceFactory
     *
     * @param context
     * @param preview
     * @param tag
     */
    public static DataSource.Factory getHttpDataSourceFactory(Context context, boolean preview, String tag) {
        return new DefaultHttpDataSourceFactory(Util.getUserAgent(context,
                tag), preview ? null : new DefaultBandwidthMeter(), 30 * 1000,
                30 * 1000, true);
    }

、、、

>[参考链接](https://stackoverflow.com/questions/41517440/exoplayer2-how-can-i-make-a-http-301-redirect-work)

只需要把allowCrossProtocolRedirects设置为true

**Comment by CarGuo** [comment]
OK～我把这个需求写入下个版本支持
