### ISSUE TITLE
GSYVideoPlayer 7.0.1 API 26 闪退

### ISSUE THREAD

**Issue by asd24862486** [CarGuo/GSYVideoPlayer#2036]
## 问题描述：

我开了个新的专案，我没有修改任何的程式码，仅加入了库的依赖
`implementation 'com.shuyu:GSYVideoPlayer:7.0.1'`
它可以正常的布署到 API 28 的虚拟机上，但布署到 API 26 的虚拟机上却会闪退，APP 一启动就闪退。
DEMO 是可以正常的运行在 API 26 的虚拟上的，我不知道我需要怎么修复它。

## 问题机型/系统：

虚拟机 API 26

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/blob/bfbb2c42b01d3d068a09f4046480cb492b59875a/app/build.gradle#L24

ndk abiFilters 

![](https://camo.githubusercontent.com/379be681f36b2de2db8051155cfe1d4d492ad7f1/68747470733a2f2f6f6f6f2e306f302e6f6f6f2f323031372f30362f31352f353934316633343361333966352e706e67)

保证过滤后存在的文件夹下的 so都存在
Make sure all '.so' exists under the existing folder after `ndk abiFilters `

**Comment by asd24862486** [comment]
在我的专案里，我确认到了这些文件都是正常存在的

![image](https://user-images.githubusercontent.com/17818882/58615910-e0fcc500-82ee-11e9-92f2-77a6018b11dd.png)

**Comment by CarGuo** [comment]
你直接在AS里查看你打包出来的 apk 是否包含有这些，然后也尝试给你的项目增加 ndk abiFilters

put Your APK directly in AS, confirm final it packaged contains these, and then try to add NDK abiFilters to your project.

**Comment by asd24862486** [comment]
我在 apk 内并没有发现这些 .so ，但我不知道该如何解决它，我已添加 ndk abiFilters
`ndk 
            abiFilters 'armeabi', 'armeabi-v7a', 'x86'
        }`

**Comment by CarGuo** [comment]
尝试添加 sourceSets 到 app 的 build.gradle 脚本中 ：
Attempt to add sourceSets to app  build.gradle ：

https://github.com/CarGuo/GSYVideoPlayer/blob/bfbb2c42b01d3d068a09f4046480cb492b59875a/app/build.gradle#L55

```
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
```

**Comment by asd24862486** [comment]
添加完后，它仍然没有正常将 .so 档案放入 apk 内，这是我现在的 build.gradle 脚本

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.example.ijkplayer"
        minSdkVersion 26
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters 'armeabi', 'armeabi-v7a', 'x86'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.shuyu:GSYVideoPlayer:7.0.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}

**Comment by CarGuo** [comment]
在这里面没有？
Is there none in it?

![image](https://user-images.githubusercontent.com/10770362/58621259-8d44a880-82fb-11e9-907d-6d2e78bbe441.png)

**Comment by asd24862486** [comment]
我找到它們了

**Comment by asd24862486** [comment]
我找到它们了，但布署到模拟器上后，仍然在 APP 一启动时就闪退了
![image](https://user-images.githubusercontent.com/17818882/58621566-40ad9d00-82fc-11e9-9968-37bc5aea8200.png)

**Comment by CarGuo** [comment]
闪退的log是怎么样的？我怀疑是 androidx 冲突等问题， 7.0.1 需要 androidx 
 What's the crash log like? I guess it may cause by  androidx.  7.0.1 version needs Androidx.

**Comment by asd24862486** [comment]
闪退时拦截到的 Log 像是以下这样

2019-05-30 17:21:18.001 17825-17825/com.example.ijkplayer E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.ijkplayer, PID: 17825
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.ijkplayer/com.example.ijkplayer.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.ijkplayer.MainActivity" on path: DexPathList[[zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/base.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_resources_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/base.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_resources_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /vendor/lib]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2718)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
2019-05-30 17:21:18.015 17825-17825/com.example.ijkplayer E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.ijkplayer.MainActivity" on path: DexPathList[[zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/base.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_resources_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/base.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_resources_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1173)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708)
        	... 9 more
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/appcompat/app/AppCompatActivity;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        		... 12 more
2019-05-30 17:21:18.019 17825-17825/com.example.ijkplayer E/AndroidRuntime: 	Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.appcompat.app.AppCompatActivity" on path: DexPathList[[zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/base.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_resources_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/base.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_resources_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        		... 15 more
    		Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_dependencies_apk.apk because: Failure to verify dex file '/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_dependencies_apk.apk': Bad method handle type 7
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
2019-05-30 17:21:18.033 17825-17825/com.example.ijkplayer E/AndroidRuntime:     at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:676)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:709)
        at android.app.LoadedApk.getResources(LoadedApk.java:936)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2242)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5672)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        			... 6 more
    		Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:676)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:709)
        at android.app.LoadedApk.getResources(LoadedApk.java:936)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2242)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5672)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        			... 6 more
    	[CIRCULAR REFERENCE:java.io.IOException: Failed to open dex files from /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_dependencies_apk.apk because: Failure to verify dex file '/data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_dependencies_apk.apk': Bad method handle type 7]
    	[CIRCULAR REFERENCE:java.io.IOException: No original dex files found for dex location /data/app/com.example.ijkplayer-ZUN9lIBHsBsOa7tt2R3Uzg==/split_lib_resources_apk.apk]

**Comment by CarGuo** [comment]
关键在于 java.lang.ClassNotFoundException: Didn't find class "com.example.ijkplayer.MainActivity"

**Comment by asd24862486** [comment]
但它却可以成功在 API 28 的虚拟机上运行，​​我不知道我该从哪里理解这个错误

![image](https://user-images.githubusercontent.com/17818882/58623759-4659b180-8301-11e9-95f6-f6d439c190b0.png)

**Comment by CarGuo** [comment]
试试 
AS —>Build,Execution,Deployment—>Instant Run
将. enable instant run to hot swap code/ resource changes on deploy  取消选中

**Comment by asd24862486** [comment]
它仍然会闪退，我得到一样的 Log

**Comment by CarGuo** [comment]
那我就不知道为什么了

**Comment by asd24862486** [comment]
我尝试了历史的各个不同版本，我发现在 API 26 的机器下，6.0.1 可以正常运作，6.0.2 就会开始出现闪退。

**Comment by CarGuo** [comment]
6.0.2应该是升级了exoplayer版本

**Comment by CarGuo** [comment]
我想我只能帮助你到这了，先关了
