### ISSUE TITLE
缓存问题

### ISSUE THREAD

**Issue by NerdAnonymous** [CarGuo/GSYVideoPlayer#2043]
m3u8格式的，mExoCache是ture，没设置缓存地址，然后在测试环境下可以正常播放缓存的视频，同样的地址，切换到正式环境，然后就是
 Caused by: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: : open failed: ENOENT (No such file or directory)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:73)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:53)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:479)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:308)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by CarGuo** [comment]
同样的地址不同的流，m3u8解析出来的不同ts切片肯定会导致有问题的，生产环境中不考虑这种问题

**Comment by NerdAnonymous** [comment]
再问一个问题，设置setDataSource中的url只要有一个播放不成，整个集合中的url都无法播放，你发现这个问题了吗

**Comment by CarGuo** [comment]
不少很理解，DataSource 除非你自定义，不然现在gsy提供的应该只能一个 url

**Comment by NerdAnonymous** [comment]
我用的是demo中的GSYExo2MediaPlayer，然后有三个播放地址，前两个播放地址是空，最后一个播放地址是正确的，但是播放提示最后一个也是失败

**Comment by CarGuo** [comment]
demo 中的是几个 dataSource 嵌套的，既然是写在demo的，没放到库里，说明这个只是个示例····请为所欲为的修改它吧

**Comment by NerdAnonymous** [comment]
意思就是存在这种问题 是不

**Comment by CarGuo** [comment]
这种情况我还真没碰上

**Comment by NerdAnonymous** [comment]
。。。老哥 我碰到了 我无比难受

**Comment by NerdAnonymous** [comment]
唉 搞了个剧集切换 看来是GG了
