### ISSUE TITLE
集成到项目中各种空指针

### ISSUE THREAD

**Issue by LsFern** [CarGuo/GSYVideoPlayer#2086]
## 问题描述：

使用demo里的LandLayoutVideo extends StandardGSYVideoPlayer 运行报错

## 问题机型/系统：

例如 真机 三星s8+ Android8.0

## GSY依赖版本

    implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'
    implementation 'com.shuyu:GSYVideoPlayer-exo2:6.0.1'
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.1'

问题代码：(如果有)
```
private void resolveNormalVideoUI() {
        //增加title
        detailPlayer.getTitleTextView().setVisibility(View.GONE);
        detailPlayer.getBackButton().setVisibility(View.GONE);
    }


```

## 问题log（如果有）

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.als.myapplication/com.als.myapplication.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.TextView com.als.myapplication.LandLayoutVideo.getTitleTextView()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.TextView com.als.myapplication.LandLayoutVideo.getTitleTextView()' on a null object reference
        at com.als.myapplication.MainActivity.resolveNormalVideoUI(MainActivity.java:238)
        at com.als.myapplication.MainActivity.onCreate(MainActivity.java:91)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 



     注释掉//        resolveNormalVideoUI();又报下面这个错误
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.als.myapplication/com.als.myapplication.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer.setPlayTag(java.lang.String)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer.setPlayTag(java.lang.String)' on a null object reference
        at com.shuyu.gsyvideoplayer.builder.GSYVideoOptionBuilder.build(GSYVideoOptionBuilder.java:571)
        at com.shuyu.gsyvideoplayer.builder.GSYVideoOptionBuilder.build(GSYVideoOptionBuilder.java:567)
        at com.als.myapplication.MainActivity.onCreate(MainActivity.java:172)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
```

**Comment by CarGuo** [comment]
测试正常，类似问题一般都是集成冲突问题
