### ISSUE TITLE
暂停播放，如果是竖屏播放的视频，图会拉伸

### ISSUE THREAD

**Issue by sugarkawhi** [CarGuo/GSYVideoPlayer#21]

**Comment by sugarkawhi** [comment]
偶尔会有java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@3b8965d
                                                                  at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
                                                                  at android.graphics.Canvas.drawBitmap(Canvas.java:1404)
                                                                  at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:544)
                                                                  at android.widget.ImageView.onDraw(ImageView.java:1228)
                                                                  at android.view.View.draw(View.java:16184)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                  at android.view.View.draw(View.java:15954)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                  at android.view.View.draw(View.java:16187)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                  at android.view.View.draw(View.java:15954)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                  at android.view.View.draw(View.java:15954)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                  at android.view.View.draw(View.java:15954)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                  at android.view.View.draw(View.java:15954)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                  at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:3693)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                  at android.view.View.draw(View.java:16187)
                                                                  at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3171)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                  at android.view.View.draw(View.java:15954)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                  at android.view.View.draw(View.java:16187)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                  at android.view.View.draw(View.java:15954)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                  at android.view.View.draw(View.java:16187)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15180)
                                                                  at android.view.View.draw(View.java:15954)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                  at android.view.View.draw(View.java:15954)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                  at android.view.View.draw(View.java:15954)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                  at android.view.View.draw(View.java:15954)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                  at android.view.View.draw(View.java:15954)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                  at android.view.View.draw(View.java:15954)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                  at android.view.View.updateDisplayListIfDirty(View.java:15175)
                                                                  at android.view.View.draw(View.java:15954)
                                                                  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                  at android.view.View.draw(View.java:16187)
                                                              	at com.android.internal.policy.PhoneWindow$DecorView.draw(

这个异常

**Comment by CarGuo** [comment]
你的拉伸和出现这个问题的是最新版本吗？？？有数据的url可以提供试试没？

**Comment by CarGuo** [comment]
这个异常有定位吗？？看起来没看出来
