### ISSUE TITLE
exo模式播放不了视频，ijk模式正常

### ISSUE THREAD

**Issue by sky286753213** [CarGuo/GSYVideoPlayer#2101]
## 问题描述：

使用的是最新的demo application 里 开启了  PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
ExoSourceManager.setSkipSSLChain(true);
ExoSourceManager.setExoMediaSourceInterceptListener（）；

## 问题机型/系统：

华为P8

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）
2019-06-27 18:06:32.101 22695-23006/com.example.gsyvideoplayer E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4
        at tv.danmaku.ijk.media.exo2.source.GSYExoHttpDataSource.open(GSYExoHttpDataSource.java:167)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:251)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:934)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.io.IOException: Cleartext HTTP traffic to 9890.vod.myqcloud.com not permitted
        at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:458)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at tv.danmaku.ijk.media.exo2.source.GSYExoHttpDataSource.makeConnection(GSYExoHttpDataSource.java:402)
        at tv.danmaku.ijk.media.exo2.source.GSYExoHttpDataSource.makeConnection(GSYExoHttpDataSource.java:278)
        at tv.danmaku.ijk.media.exo2.source.GSYExoHttpDataSource.open(GSYExoHttpDataSource.java:165)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:251) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:934) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:784) 
2019-06-27 18:06:32.109 22695-22695/com.example.gsyvideoplayer E/EventLogger: playerFailed [3.05]
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:386)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:207)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4
        at tv.danmaku.ijk.media.exo2.source.GSYExoHttpDataSource.open(GSYExoHttpDataSource.java:167)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:251)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:934)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.io.IOException: Cleartext HTTP traffic to 9890.vod.myqcloud.com not permitted
        at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:458)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at tv.danmaku.ijk.media.exo2.source.GSYExoHttpDataSource.makeConnection(GSYExoHttpDataSource.java:402)
        at tv.danmaku.ijk.media.exo2.source.GSYExoHttpDataSource.makeConnection(GSYExoHttpDataSource.java:278)
        at tv.danmaku.ijk.media.exo2.source.GSYExoHttpDataSource.open(GSYExoHttpDataSource.java:165)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:251) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:934) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:784) 
2019-06-27 18:06:32.110 22695-22695/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer
2019-06-27 18:06:32.111 22695-22695/com.example.gsyvideoplayer I/GSYVideoPlayer: changeUiToError
2019-06-27 18:06:32.115 22695-22695/com.example.gsyvideoplayer E/GSYVideoPlayer: Link Or mCache Error, Please Try Again http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4
2019-06-27 18:06:32.115 22695-22695/com.example.gsyvideoplayer E/GSYVideoPlayer: mCache Link http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4
2019-06-27 18:06:32.116 22695-22695/com.example.gsyvideoplayer D/EventLogger: loading [false]
2019-06-27 18:06:32.118 22695-22695/com.example.gsyvideoplayer D/EventLogger: state [3.06, false, I]
2019-06-27 18:06:32.129 22695-22695/com.example.gsyvideoplayer I/ExoPlayerImpl: Release 162163e [ExoPlayerLib/2.10.1] [HWMHA, MHA-AL00, HUAWEI, 28] [goog.exo.core, goog.exo.hls]
2019-06-27 18:06:32.133 22695-22695/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer

**Comment by sky286753213** [comment]
使用DetailExoListPlayer播放时 只有第一个url可以播放 其他的url也是播放不了

**Comment by CarGuo** [comment]
DetailExoListPlayer  是写在 demo 里的例子，只要演示如何自定义 player 的。貌似是以为嵌套 Source 的问题哦
