### ISSUE TITLE
6.0.3无法加载so文件

### ISSUE THREAD

**Issue by baojianming88** [CarGuo/GSYVideoPlayer#2131]
## 问题描述：
6.0.3无法加载so文件

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本
video_player_version=6.0.3

"com.shuyu:gsyVideoPlayer-java:$video_player_version",
"com.shuyu:gsyVideoPlayer-armv7a:$video_player_version",

## Demo中的复现步骤

点击中间的播放按钮报如下错误

## 问题log（如果有）
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/base.apk", zip file "/data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_dependencies_apk.apk", zip file "/data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_resources_apk.apk", zip file "/data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_slice_0_apk.apk", zip file "/data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_slice_1_apk.apk", zip file "/data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_slice_2_apk.apk", zip file "/data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_slice_3_apk.apk", zip file "/data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_slice_4_apk.apk", zip file "/data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_slice_5_apk.apk", zip file "/data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_slice_6_apk.apk", zip file "/data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_slice_7_apk.apk", zip file "/data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_slice_8_apk.apk", zip file "/data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/lib/arm64, /data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/base.apk!/lib/arm64-v8a, /data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.inwil.elephantgo.teacher-ccwkpoKy-FfNx2GO2deK6g==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]] couldn't find "libijkffmpeg.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1672)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:179)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:190)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:231)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:227)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:218)
        at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.initVideoPlayer(IjkPlayerManager.java:55)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:600)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:38)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:564)

**Comment by baojianming88** [comment]
机型是 荣耀play

**Comment by baojianming88** [comment]
可以了，没有加入ndk  abifilter
