### ISSUE TITLE
6.0.1 播放视频报 Error fetching info from

### ISSUE THREAD

**Issue by vainfeng** [CarGuo/GSYVideoPlayer#2133]
## 加载视频不出来，总是在loading

视频URL ： http://ai-video.oss-cn-beijing-internal.aliyuncs.com/56cac56c69b43240005332a6/虎啸龙吟 01.mp4

## 问题描述：

加载播放的时候出的这个问题

## 问题机型/系统：

真机，小米 MIX 2S 

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:6.0.1'`

## 问题log（如果有）

```

E/HttpProxyCacheDebuger: Error fetching info from http://ai-video.oss-cn-beijing-internal.aliyuncs.com/56cac56c69b43240005332a6/虎啸龙吟 01.mp4
2019-07-12 17:43:55.386 18572-18882/both.video.venvy.com.appdemo W/System.err: java.net.SocketTimeoutException: failed to connect to ai-video.oss-cn-beijing-internal.aliyuncs.com/100.118.58.9 (port 80) from /192.168.103.16 (port 38504) after 10000ms
2019-07-12 17:43:55.388 18572-18882/both.video.venvy.com.appdemo W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
2019-07-12 17:43:55.390 18572-18882/both.video.venvy.com.appdemo W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:129)
2019-07-12 17:43:55.391 18572-18882/both.video.venvy.com.appdemo W/System.err:     at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
2019-07-12 17:43:55.393 18572-18882/both.video.venvy.com.appdemo W/System.err:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
2019-07-12 17:43:55.395 18572-18882/both.video.venvy.com.appdemo W/System.err:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
2019-07-12 17:43:55.397 18572-18882/both.video.venvy.com.appdemo W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
2019-07-12 17:43:55.398 18572-18882/both.video.venvy.com.appdemo W/System.err:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
2019-07-12 17:43:55.400 18572-18882/both.video.venvy.com.appdemo W/System.err:     at java.net.Socket.connect(Socket.java:621)
2019-07-12 17:43:55.401 18572-18882/both.video.venvy.com.appdemo W/System.err:     at com.android.okhttp.internal.Platform.connectSocket(Platform.java:145)
2019-07-12 17:43:55.403 18572-18882/both.video.venvy.com.appdemo W/System.err:     at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141)
2019-07-12 17:43:55.406 18572-18882/both.video.venvy.com.appdemo W/System.err:     at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
2019-07-12 17:43:55.407 18572-18882/both.video.venvy.com.appdemo W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
2019-07-12 17:43:55.408 18572-18882/both.video.venvy.com.appdemo W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
2019-07-12 17:43:55.409 18572-18882/both.video.venvy.com.appdemo W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
2019-07-12 17:43:55.410 18572-18882/both.video.venvy.com.appdemo W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
2019-07-12 17:43:55.410 18572-18882/both.video.venvy.com.appdemo W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
2019-07-12 17:43:55.411 18572-18882/both.video.venvy.com.appdemo W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
2019-07-12 17:43:55.412 18572-18882/both.video.venvy.com.appdemo W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
2019-07-12 17:43:55.413 18572-18882/both.video.venvy.com.appdemo W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
2019-07-12 17:43:55.414 18572-18882/both.video.venvy.com.appdemo W/System.err:     at com.danikula.videocache.HttpUrlSource.openConnection(HttpUrlSource.java:164)
2019-07-12 17:43:55.415 18572-18882/both.video.venvy.com.appdemo W/System.err:     at com.danikula.videocache.HttpUrlSource.fetchContentInfo(HttpUrlSource.java:133)
2019-07-12 17:43:55.415 18572-18882/both.video.venvy.com.appdemo W/System.err:     at com.danikula.videocache.HttpUrlSource.getMime(HttpUrlSource.java:191)
2019-07-12 17:43:55.416 18572-18882/both.video.venvy.com.appdemo W/System.err:     at com.danikula.videocache.HttpProxyCache.newResponseHeaders(HttpProxyCache.java:60)
2019-07-12 17:43:55.417 18572-18882/both.video.venvy.com.appdemo W/System.err:     at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:40)
2019-07-12 17:43:55.418 18572-18882/both.video.venvy.com.appdemo W/System.err:     at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
2019-07-12 17:43:55.418 18572-18882/both.video.venvy.com.appdemo W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:230)
2019-07-12 17:43:55.419 18572-18882/both.video.venvy.com.appdemo W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:51)
2019-07-12 17:43:55.420 18572-18882/both.video.venvy.com.appdemo W/System.err:     at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:332)
2019-07-12 17:43:55.421 18572-18882/both.video.venvy.com.appdemo W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
2019-07-12 17:43:55.422 18572-18882/both.video.venvy.com.appdemo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-07-12 17:43:55.423 18572-18882/both.video.venvy.com.appdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-07-12 17:43:55.423 18572-18882/both.video.venvy.com.appdemo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-07-12 17:43:55.424 18572-18882/both.video.venvy.com.appdemo W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-07-12 17:43:55.429 18572-18882/both.video.venvy.com.appdemo E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0

```

**Comment by vainfeng** [comment]
浏览器是可以正常访问播放的

**Comment by CarGuo** [comment]
em···你确定不把中文部分 docode 编码下？

**Comment by vainfeng** [comment]
sorry,老哥...犯了常识性的错误。我从chrome地址栏吧URL copy出来是这样：

http://ai-video.oss-cn-beijing-internal.aliyuncs.com/56cac56c69b43240005332a6/%E8%99%8E%E5%95%B8%E9%BE%99%E5%90%9F%2001.mp4

但是还是播放不了且Log是一致的

请问URL这部分我还有什么要注意的问题么？

**Comment by CarGuo** [comment]
我这边测试这个url在浏览器加载不开

**Comment by vainfeng** [comment]
额....sorry，老哥，被你这么一说，我去check了一下视频的地址。结果发现是一个内网需要VPN才能访问的地址，导致我手机上没有开对应的VPN，所以播放失败。   谢谢老哥了，祝老哥工作顺利~我这就close......
