### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by 850125665** [CarGuo/GSYVideoPlayer#2146]
## 问题描述：

内存泄漏了

## 问题机型/系统：

真机 魅蓝 A5 Android6.0

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.0.2'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

## 问题log

```

贴下友盟日志
java.lang.OutOfMemoryError: Failed to allocate a 25 byte allocation with 4008 free bytes and 3KB until OOM
	at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView$ProgressTimerTask.run(GSYVideoControlView.java:1065)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

```

**Comment by CarGuo** [comment]
OOM 不一定是库的问题导致的
