### ISSUE TITLE
Reset failed Exo提示复位失败。

### ISSUE THREAD

**Issue by CrzGitHub** [CarGuo/GSYVideoPlayer#2172]
播放.m3u8 时  频繁切换 会抛出Reset failed异常，切换之前调用release()  onVideoPause() 还是会复位失败

**Comment by CrzGitHub** [comment]
切换之前调用过 release() onVideoPause() 还是会复位失败。 QAQ

**Comment by CarGuo** [comment]
不是很理解

**Comment by CrzGitHub** [comment]
播放.m3u8时ExoPlayer会报数据流加载异常，或者复位失败的 log  在点击替它的 就会一直提示 失败。

**Comment by CrzGitHub** [comment]
08-07 18:07:30.412 8722-9538/com.Test.YingShi E/ExoPlayerImplInternal: Reset failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:1901)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:608)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:595)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onReset(MediaCodecRenderer.java:588)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onReset(MediaCodecVideoRenderer.java:460)
        at com.google.android.exoplayer2.BaseRenderer.reset(BaseRenderer.java:164)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:853)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:806)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:399)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by CrzGitHub** [comment]
08-07 18:08:42.262 8722-9781/com.Test.YingShi E/LoadTask: Unexpected exception loading stream
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
        at com.google.android.exoplayer2.upstream.cache.SimpleCache.releaseHoleSpan(SimpleCache.java:512)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.closeCurrentSource(CacheDataSource.java:527)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.close(CacheDataSource.java:351)
        at com.google.android.exoplayer2.upstream.StatsDataSource.close(StatsDataSource.java:110)
        at com.google.android.exoplayer2.util.Util.closeQuietly(Util.java:396)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:363)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:325)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:301)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

**Comment by CarGuo** [comment]
我这边没能复现问题
