### ISSUE TITLE
加入compile 依赖，出现错误

### ISSUE THREAD

**Issue by shuaimango** [CarGuo/GSYVideoPlayer#2189]
java.lang.RuntimeException: Manifest merger failed with multiple errors, see logs
	at com.android.builder.core.AndroidBuilder.mergeManifestsForApplication(AndroidBuilder.java:540)
	at com.android.build.gradle.tasks.MergeManifests.doFullTaskAction(MergeManifests.java:173)

**Comment by CarGuo** [comment]
I think you can fix it by yourself man .

**Comment by shuaimango** [comment]
androidx和support不能混合使用。我项目有support包，所以应该implementation 'com.shuyu:GSYVideoPlayer:6.0.3'，而不是implementation 'com.shuyu:GSYVideoPlayer:7.0.2'
