### ISSUE TITLE
自編繹so 導入後player無法使用

### ISSUE THREAD

**Issue by dendrocyte** [CarGuo/GSYVideoPlayer#2199]
## 问题描述：
為了導入mp2 的live hls stream, 嘗試自編繹so, 
將編譯好的so放到專案的main/libs,
也在Gradle 增加sourceSet和apifilter, (參考了#1942)
導入後開啟exoplayer 和ijkplayer 失敗, 無法播放影音。
若不選擇內核採取default ,無法播放影音。
需要exoplayer 播放mp2的live stream。
在自編繹前, 播放影音正常。

## 问题机型/系统：
Sharp Android8.0

## GSY依赖版本
 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.2'
 
 implementation 'com.shuyu:GSYVideoPlayer-exo2:7.0.2'
`

## Demo中的复现步骤
我參考了#1942
移植了自編繹的so 放入專案裡

使用
PlayerFactory.setPlayManager(IjkPlayerManager::class.java)
卻會出現error
PlayerFactory.setPlayManager(Exo2PlayerManager::class.java)
仍然沒有聲音
請問我要如何讓player可以用呢？

## 问题log（如果有）
當我用IjkPlayer, player的畫面出不來直接crash
PlayerFactory.setPlayManager(IjkPlayerManager::class.java)
`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader
couldn't find "libijkffmpeg.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:179)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:190)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:231)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:227)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:218)
        at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.initVideoPlayer(IjkPlayerManager.java:55)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:598)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:36)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:562)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
2019-08-21 15:54:38.596 28472-28472/org.noovo.tv.noovo_gsyplayer E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
`
```
當我用exoplayer 可以播mp2的live, 但仍然沒有聲音
PlayerFactory.setPlayManager(Exo2PlayerManager::class.java)

`2019-08-21 15:57:35.618 29001-29007/org.noovo.tv.noovo_gsyplayer I/zygote64: Compiler allocated 4MB to compile void android.view.View.<init>(android.content.Context, android.util.AttributeSet, int, int)
2019-08-21 15:57:35.682 29001-29001/org.noovo.tv.noovo_gsyplayer W/AudioManager: Use of stream types is deprecated for operations other than volume control
2019-08-21 15:57:35.682 29001-29001/org.noovo.tv.noovo_gsyplayer W/AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
2019-08-21 15:57:35.923 29001-29001/org.noovo.tv.noovo_gsyplayer I/ExoPlayerImpl: Init 35ca619 [ExoPlayerLib/2.10.1] [SS2, FS8010, SHARP, 26]
2019-08-21 15:57:35.940 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger: state [0.07, false, B]
2019-08-21 15:57:37.072 29001-29166/org.noovo.tv.noovo_gsyplayer W/OkHttpClient: A connection to https://googleads.g.doubleclick.net/ was leaked. Did you forget to close a response body?
2019-08-21 15:57:37.110 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger: sourceInfo [periodCount=1, windowCount=1
2019-08-21 15:57:37.110 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger:   period [?]
2019-08-21 15:57:37.110 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger:   window [79.05, true, true]
2019-08-21 15:57:37.110 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger: ]
2019-08-21 15:57:37.142 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger: loading [true]
2019-08-21 15:57:37.215 29001-29242/org.noovo.tv.noovo_gsyplayer W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2019-08-21 15:57:37.215 29001-29242/org.noovo.tv.noovo_gsyplayer W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2019-08-21 15:57:37.222 29001-29242/org.noovo.tv.noovo_gsyplayer W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2019-08-21 15:57:37.222 29001-29242/org.noovo.tv.noovo_gsyplayer W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2019-08-21 15:57:37.225 29001-29242/org.noovo.tv.noovo_gsyplayer W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
2019-08-21 15:57:37.225 29001-29242/org.noovo.tv.noovo_gsyplayer W/VideoCapabilities: Unrecognized profile 2130706434 for video/avc
2019-08-21 15:57:37.235 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger: Tracks [
2019-08-21 15:57:37.235 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger:   Renderer:0 [
2019-08-21 15:57:37.235 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger:     Group:0, adaptive_supported=N/A [
2019-08-21 15:57:37.235 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger:       [X] Track:0, id=0, mimeType=video/avc, codecs=avc1.4D401E, res=720x480, supported=YES
2019-08-21 15:57:37.235 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger:     ]
2019-08-21 15:57:37.236 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger:   ]
2019-08-21 15:57:37.236 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger:   Renderer:1 [
2019-08-21 15:57:37.236 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger:     Group:0, adaptive_supported=N/A [
2019-08-21 15:57:37.236 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger:       [ ] Track:0, id=1/3, mimeType=audio/mpeg-L2, channels=2, sample_rate=48000, supported=NO_UNSUPPORTED_TYPE
2019-08-21 15:57:37.236 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger:     ]
2019-08-21 15:57:37.236 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger:   ]
2019-08-21 15:57:37.236 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger:   Renderer:2 [
2019-08-21 15:57:37.236 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger:     Group:0, adaptive_supported=N/A [
2019-08-21 15:57:37.236 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger:       [ ] Track:0, id=1/8219, mimeType=application/cea-608, supported=YES
2019-08-21 15:57:37.236 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger:     ]
2019-08-21 15:57:37.236 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger:   ]
2019-08-21 15:57:37.236 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger:   Renderer:3 [
2019-08-21 15:57:37.236 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger:     Group:0, adaptive_supported=N/A [
2019-08-21 15:57:37.236 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger:       [X] Track:0, id=1/21, mimeType=application/id3, supported=YES
2019-08-21 15:57:37.236 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger:     ]
2019-08-21 15:57:37.236 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger:   ]
2019-08-21 15:57:37.236 29001-29001/org.noovo.tv.noovo_gsyplayer D/EventLogger: ]
2019-08-21 15:57:37.238 29001-29259/org.noovo.tv.noovo_gsyplayer I/OMXClient: Treble IOmx obtained
2019-08-21 15:57:37.269 29001-29258/org.noovo.tv.noovo_gsyplayer D/SurfaceUtils: connecting to surface 0x756bf59010, reason connectToSurface
2019-08-21 15:57:37.269 29001-29258/org.noovo.tv.noovo_gsyplayer I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 29697026
2019-08-21 15:57:37.269 29001-29258/org.noovo.tv.noovo_gsyplayer D/SurfaceUtils: disconnecting from surface 0x756bf59010, reason connectToSurface(reconnect)
2019-08-21 15:57:37.269 29001-29258/org.noovo.tv.noovo_gsyplayer D/SurfaceUtils: connecting to surface 0x756bf59010, reason connectToSurface(reconnect)
2019-08-21 15:57:37.271 29001-29259/org.noovo.tv.noovo_gsyplayer I/ExtendedACodec: setupVideoDecoder()
2019-08-21 15:57:37.277 29001-29259/org.noovo.tv.noovo_gsyplayer I/ExtendedACodec: Decoder will be in frame by frame mode
2019-08-21 15:57:37.288 29001-29259/org.noovo.tv.noovo_gsyplayer D/SurfaceUtils: set up nativeWindow 0x756bf59010 for 720x480, color 0x7fa30c06, rotation 0, usage 0x20002900
2019-08-21 15:57:37.298 29001-29259/org.noovo.tv.noovo_gsyplayer W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
2019-08-21 15:57:37.300 29001-29259/org.noovo.tv.noovo_gsyplayer W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
2019-08-21 15:57:37.303 29001-29259/org.noovo.tv.noovo_gsyplayer W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
2019-08-21 15:57:37.304 29001-29259/org.noovo.tv.noovo_gsyplayer W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
2019-08-21 15:57:37.326 29001-29259/org.noovo.tv.noovo_gsyplayer D/SurfaceUtils: set up nativeWindow 0x756bf59010 for 720x480, color 0x7fa30c06, rotation 0, usage 0x20002900
2019-08-21 15:57:37.348 29001-29259/org.noovo.tv.noovo_gsyplayer W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
2019-08-21 15:57:37.353 29001-29259/org.noovo.tv.noovo_gsyplayer W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
2019-08-21 15:57:37.355 29001-29259/org.noovo.tv.noovo_gsyplayer W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000
2019-08-21 15:57:37.356 29001-29259/org.noovo.tv.noovo_gsyplayer W/GrallocMapperPassthrough: buffer descriptor with invalid usage bits 0x2000`



```

**Comment by dendrocyte** [comment]
我找到原因了！要將so 放置到src/libs 而不是main/libs
