### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by chengww5217** [CarGuo/GSYVideoPlayer#2241]
## 问题描述：

在播放本地视频的时候发生了空指针的问题

```
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
 W/System.err:     at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.initVideoPlayer(IjkPlayerManager.java:82)
W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:607)
W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:39)
W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:567)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
W/System.err:     at android.os.Looper.loop(Looper.java:176)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6701)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
```

## 问题机型/系统：

小米6 Android 8.0

## GSY依赖版本

```
implementation 'com.shuyu:gsyVideoPlayer-java:7.1.0'
    implementation 'com.shuyu:gsyVideoPlayer-armv5:7.1.0'
    implementation 'com.shuyu:gsyVideoPlayer-armv7a:7.1.0'
    implementation 'com.shuyu:gsyVideoPlayer-arm64:7.1.0'
    implementation 'com.shuyu:gsyVideoPlayer-x86:7.1.0'
```

## Demo中的复现步骤

暂无。

## 问题代码：(如果有)
这个问题发生在： 
com.shuyu.gsyvideoplayer.player.IjkPlayerManager.initVideoPlayer(IjkPlayerManager.java:82)
```
if (!TextUtils.isEmpty(url)) {
                    Uri uri = Uri.parse(url);
                    if (uri.getScheme().equals(ContentResolver.SCHEME_ANDROID_RESOURCE)) {
                        RawDataSourceProvider rawDataSourceProvider = RawDataSourceProvider.create(context, uri);
                        mediaPlayer.setDataSource(rawDataSourceProvider);
                    } else {
                        mediaPlayer.setDataSource(url, gsyModel.getMapHeadData());
                    }
                } else {
                    mediaPlayer.setDataSource(url, gsyModel.getMapHeadData());
                }
```

通过查询 Uri.getScheme() 知该方法返回值可能为 null:
```
    /**
     * Gets the scheme of this URI. Example: "http"
     *
     * @return the scheme or null if this is a relative URI
     */
    @Nullable
    public abstract String getScheme();
```

## 问题log（如果有）

```
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
 W/System.err:     at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.initVideoPlayer(IjkPlayerManager.java:82)
W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:607)
W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:39)
W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:567)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
W/System.err:     at android.os.Looper.loop(Looper.java:176)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6701)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
```

**Comment by CarGuo** [comment]
ijk模式本地视频必须加 file://
