### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Luckylll** [CarGuo/GSYVideoPlayer#23]
java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.example.gsyvideoplayer-1/lib/x86/libijkffmpeg.so: has text relocations
                                                                                at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                                at java.lang.System.loadLibrary(System.java:1076)
                                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:163)
                                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:174)
                                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:215)
                                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:211)
                                                                                at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:202)
                                                                                at com.shuyu.gsyvideoplayer.GSYVideoManager.<init>(GSYVideoManager.java:207)
                                                                                at com.shuyu.gsyvideoplayer.GSYVideoManager.instance(GSYVideoManager.java:87)
                                                                                at com.shuyu.gsyvideoplayer.GSYVideoPlayer.isCurrentMediaListener(GSYVideoPlayer.java:1068)
                                                                                at com.shuyu.gsyvideoplayer.GSYVideoPlayer.setUp(GSYVideoPlayer.java:230)
                                                                                at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.setUp(StandardGSYVideoPlayer.java:200)
                                                                                at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.setUp(StandardGSYVideoPlayer.java:186)
                                                                                at com.example.gsyvideoplayer.video.SampleVideo.setUp(SampleVideo.java:120)
                                                                                at com.example.gsyvideoplayer.PlayActivity.init(PlayActivity.java:74)
                                                                                at com.example.gsyvideoplayer.PlayActivity.onCreate(PlayActivity.java:53)
                                                                                at android.app.Activity.performCreate(Activity.java:6237)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-23 12:43:44.594 28391-28399/com.example.gsyvideoplayer E/art: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
12-23 12:43:44.595 28391-28399/com.example.gsyvideoplayer E/System: Uncaught exception thrown by finalizer
12-23 12:43:44.595 28391-28399/com.example.gsyvideoplayer E/System: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
                                                                        at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
                                                                        at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(IjkMediaPlayer.java:893)
                                                                        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
                                                                        at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
                                                                        at java.lang.Thread.run(Thread.java:818)

**Comment by CarGuo** [comment]
这是demo里面的？还是已经导入到你的项目里面的？targetSDK是？

**Comment by Luckylll** [comment]
这个是demo的，我吧targetSDK改成最新的了，就出现这个，demo里面原来的22不会出现

**Comment by CarGuo** [comment]
是的，因为编译so的sdk应该还不支持25的或者24这种比较新的

**Comment by Luckylll** [comment]
那如果用到自己的项目，也要把sdk版本降级咯

**Comment by CarGuo** [comment]
嗯嗯，22、23应该可以
