### ISSUE TITLE
ClassCastException : ENPlayView 

### ISSUE THREAD

**Issue by wfc505059241** [CarGuo/GSYVideoPlayer#231]
日志: 

java.lang.ClassCastException: moe.codeest.enviews.ENPlayView cannot be cast to android.widget.ImageView
                                                                     at com.longhz.yoyo.ui.LandLayoutVideo.updateStartImage(LandLayoutVideo.java:44)
                                                                     at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.changeUiToPlayingShow(StandardGSYVideoPlayer.java:474)
                                                                     at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.setStateAndUi(StandardGSYVideoPlayer.java:227)
                                                                     at com.shuyu.gsyvideoplayer.GSYVideoPlayer.onPrepared(GSYVideoPlayer.java:796)
                                                                     at com.shuyu.gsyvideoplayer.GSYVideoManager$1.run(GSYVideoManager.java:369)
                                                                     at android.os.Handler.handleCallback(Handler.java:730)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                     at android.os.Looper.loop(Looper.java:137)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5162)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:525)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                     at dalvik.system.NativeStart.main(Native Method)

代码:

    @Override
    protected void updateStartImage() {
        if (mIfCurrentIsFullscreen) {
            ImageView imageView = (ImageView) mStartButton;//44行  就是这里出错  在vivo手机上
            if (mCurrentState == CURRENT_STATE_PLAYING) {
                imageView.setImageResource(R.drawable.video_click_pause_selector);
            } else if (mCurrentState == CURRENT_STATE_ERROR) {
                imageView.setImageResource(R.drawable.video_click_play_selector);
            } else {
                imageView.setImageResource(R.drawable.video_click_play_selector);
            }

        } else {
            super.updateStartImage();
        }
    }

**Comment by CarGuo** [comment]
布局文件中的类，和你使用的要对的上

**Comment by wfc505059241** [comment]
布局文件饿哦没改的 和demo里面一样     华为手机上好着   vivo  和oppo手机上报这个错  别的手机没有看

**Comment by CarGuo** [comment]
这里提示是 ENPlayView cannot be cast to android.widget.ImageView  强制转换的问题。理论上应该是和手机无关

**Comment by wfc505059241** [comment]
我也觉得和手机没有关系  是这样的   就是全屏播放能有个7-8分钟的时候就报这个错
   你没遇到过么

**Comment by wfc505059241** [comment]
如何禁止重力感应旋转呢

**Comment by CarGuo** [comment]
有旋转工具类和对应接口，可参阅接口文档wiki
