### ISSUE TITLE
暂停时，播放器的状态问题

### ISSUE THREAD

**Issue by WalkingRoy** [CarGuo/GSYVideoPlayer#237]
Caused by: java.lang.IllegalStateException: mpjni: pause: null mp
at tv.danmaku.ijk.media.player.IjkMediaPlayer._pause(Native Method)
at tv.danmaku.ijk.media.player.IjkMediaPlayer.pause(IjkMediaPlayer.java:533)
at com.shuyu.gsyvideoplayer.GSYVideoPlayer.onVideoPause(GSYVideoPlayer.java:459)

在视频播放的时候，直接退出界面，有概率性地会出现这个问题，但在调用播放器的暂停方法时，已经先判空了：
if(GSYVideoManager.instance().getMediaPlayer() != null) {
     GSYVideoManager.instance().getMediaPlayer().pause();
}
但还是会奔溃

**Comment by CarGuo** [comment]
可以加一个try catch ，这个空可能是存在于so层面的
