### ISSUE TITLE
播放视屏错误

### ISSUE THREAD

**Issue by CleverSJX** [CarGuo/GSYVideoPlayer#2381]
#问题描述：
继承ListGSYVideoPlayer播放视频错误,重写了onError方法也没有回调, 视频是本地文件,且确定存在
## GSY依赖版本
```
implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'
implementation 'com.shuyu:GSYVideoPlayer-exo2:6.0.3'
implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.3'
```

## log

```
11-05 11:56:50.567 19717-19717/com.longjing.debug W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
11-05 11:56:50.567 19717-19717/com.longjing.debug W/System.err:     at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.initVideoPlayer(IjkPlayerManager.java:82)
11-05 11:56:50.567 19717-19717/com.longjing.debug W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:600)
11-05 11:56:50.567 19717-19717/com.longjing.debug W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:38)
11-05 11:56:50.567 19717-19717/com.longjing.debug W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:564)
11-05 11:56:50.567 19717-19717/com.longjing.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-05 11:56:50.567 19717-19717/com.longjing.debug W/System.err:     at android.os.Looper.loop(Looper.java:148)
11-05 11:56:50.567 19717-19717/com.longjing.debug W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5422)
11-05 11:56:50.567 19717-19717/com.longjing.debug W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-05 11:56:50.567 19717-19717/com.longjing.debug W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:733)
11-05 11:56:50.567 19717-19717/com.longjing.debug W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623)
11-05 11:56:50.568 19717-19717/com.longjing.debug D/IJKMEDIA: IjkMediaPlayer_release
11-05 11:56:50.568 19717-19717/com.longjing.debug D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
11-05 11:56:50.568 19717-19717/com.longjing.debug D/IJKMEDIA: ffpipeline_set_surface()
11-05 11:56:50.568 19717-19717/com.longjing.debug D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
11-05 11:56:50.568 19717-19717/com.longjing.debug D/IJKMEDIA: ijkmp_shutdown_l()
11-05 11:56:50.568 19717-19717/com.longjing.debug D/IJKMEDIA: ijkmp_shutdown_l()=void
11-05 11:56:50.568 19717-19717/com.longjing.debug D/IJKMEDIA: ijkmp_dec_ref(): ref=0
11-05 11:56:50.568 19717-19717/com.longjing.debug D/IJKMEDIA: ijkmp_shutdown_l()
11-05 11:56:50.568 19717-19717/com.longjing.debug D/IJKMEDIA: ijkmp_shutdown_l()=void
11-05 11:56:50.569 19717-19717/com.longjing.debug D/IJKMEDIA: IjkMediaPlayer_setVolume
11-05 11:56:50.569 19717-19717/com.longjing.debug D/IJKMEDIA: IjkMediaPlayer_release
11-05 11:56:50.569 19717-19717/com.longjing.debug D/IJKMEDIA: IjkMediaPlayer_native_setup
11-05 11:56:50.569 19717-19717/com.longjing.debug I/IJKMEDIA: av_version_info: ff3.4--ijk0.8.7--20180103--001
11-05 11:56:50.569 19717-19717/com.longjing.debug I/IJKMEDIA: ijk_version_info: k0.8.8
11-05 11:56:50.570 19717-19717/com.longjing.debug D/IJKMEDIA: ffpipeline_create_from_android()
11-05 11:56:50.570 19717-19717/com.longjing.debug D/IJKMEDIA: ijkmp_set_inject_opaque(0x200716)
11-05 11:56:50.570 19717-19717/com.longjing.debug D/IJKMEDIA: ijkmp_set_inject_opaque()=void
11-05 11:56:50.570 19717-19717/com.longjing.debug D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x200716)
11-05 11:56:50.570 19717-19717/com.longjing.debug D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
11-05 11:56:50.571 19717-19717/com.longjing.debug D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
11-05 11:56:50.571 19717-19717/com.longjing.debug D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
11-05 11:56:50.571 19717-19717/com.longjing.debug D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
11-05 11:56:50.571 19717-19717/com.longjing.debug D/IJKMEDIA: IjkMediaPlayer_setOptionLong
11-05 11:56:50.571 19717-19717/com.longjing.debug D/IJKMEDIA: IjkMediaPlayer_setOptionLong
11-05 11:56:50.571 19717-19717/com.longjing.debug D/IJKMEDIA: IjkMediaPlayer_setOptionLong
11-05 11:56:50.571 19717-19717/com.longjing.debug W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
11-05 11:56:50.571 19717-19717/com.longjing.debug W/System.err:     at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.initVideoPlayer(IjkPlayerManager.java:82)
11-05 11:56:50.571 19717-19717/com.longjing.debug W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:600)
11-05 11:56:50.571 19717-19717/com.longjing.debug W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:38)
11-05 11:56:50.571 19717-19717/com.longjing.debug W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:564)
11-05 11:56:50.571 19717-19717/com.longjing.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-05 11:56:50.571 19717-19717/com.longjing.debug W/System.err:     at android.os.Looper.loop(Looper.java:148)
11-05 11:56:50.571 19717-19717/com.longjing.debug W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5422)
11-05 11:56:50.571 19717-19717/com.longjing.debug W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-05 11:56:50.571 19717-19717/com.longjing.debug W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:733)
11-05 11:56:50.571 19717-19717/com.longjing.debug W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623)
11-05 11:56:50.701 19717-19717/com.longjing.debug W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 19717
```

**Comment by CleverSJX** [comment]
uri.getScheme().equals(ContentResolver.SCHEME_ANDROID_RESOURCE) 空指针
uri.getScheme() 为null

**Comment by CleverSJX** [comment]
视频加 file:// 好了

**Comment by CleverSJX** [comment]
是播放起来了 播放一会 黑屏了
```
11-05 12:17:52.073 22760-23174/com.longjing.debug E/IJKMEDIA: configure acodec:0x200716 format:0x20075e: surface:0x200736
11-05 12:17:52.074 22760-23174/com.longjing.debug W/System.err: java.lang.IllegalArgumentException: The surface has been released
11-05 12:17:52.084 22760-23174/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_configure(Native Method)
11-05 12:17:52.084 22760-23174/com.longjing.debug W/System.err:     at android.media.MediaCodec.configure(MediaCodec.java:1778)
11-05 12:17:52.084 22760-23174/com.longjing.debug E/IJKMEDIA: reconfigure_codec_l:configure_surface: failed
11-05 12:17:52.084 22760-23174/com.longjing.debug E/IJKMEDIA: feed_input_buffer: reconfigure_codec failed
11-05 12:17:52.084 22760-23171/com.longjing.debug W/System.err: java.lang.IllegalStateExceptionjava.lang.IllegalStateException
11-05 12:17:52.085 22760-23171/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
11-05 12:17:52.085 22760-23171/com.longjing.debug W/System.err:     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
11-05 12:17:52.085 22760-23171/com.longjing.debug I/IJKMEDIA: SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
11-05 12:17:52.085 22760-23174/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
11-05 12:17:52.085 22760-23174/com.longjing.debug W/System.err:     at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2319)
11-05 12:17:52.085 22760-23174/com.longjing.debug E/IJKMEDIA: SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
11-05 12:17:52.085 22760-23174/com.longjing.debug W/System.err: java.lang.IllegalStateException
11-05 12:17:52.085 22760-23174/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
11-05 12:17:52.085 22760-23174/com.longjing.debug W/System.err:     at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2319)
11-05 12:17:52.085 22760-23174/com.longjing.debug E/IJKMEDIA: SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
11-05 12:17:52.086 22760-23174/com.longjing.debug W/System.err: java.lang.IllegalStateException
11-05 12:17:52.086 22760-23174/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
11-05 12:17:52.086 22760-23174/com.longjing.debug W/System.err:     at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2319)
11-05 12:17:52.086 22760-23174/com.longjing.debug E/IJKMEDIA: SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
```
