### ISSUE TITLE
使用ListGSYVideoPlayer开启硬解码playNext失败

### ISSUE THREAD

**Issue by CleverSJX** [CarGuo/GSYVideoPlayer#2386]
## 问题描述： 
继承使用ListGSYVideoPlayer开启了硬解码, 第一次播放成功,播放完成后回调 playNext 播放失败黑屏

##  GSY依赖版本
```
implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'
implementation 'com.shuyu:GSYVideoPlayer-exo2:6.0.3'
implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.3'
```
## 代码
```
     GSYVideoType.enableMediaCodec();
     GSYVideoType.enableMediaCodecTexture();

    @Override
    public boolean playNext() {
        loadCoverImage();
        if (mPlayPosition < (mUriList.size() - 1)) {
            mPlayPosition += 1;
        }else {
            mPlayPosition = 0;
        }

        GSYVideoModel gsyVideoModel = mUriList.get(mPlayPosition);
        mSaveChangeViewTIme = 0;
        setUp(mUriList, mCache, mPlayPosition, null, mMapHeadData, false);
        if (!TextUtils.isEmpty(gsyVideoModel.getTitle())) {
            mTitleTextView.setText(gsyVideoModel.getTitle());
        }
        startPlayLogic();
        showQrCode(qrCodeResourceList.get(mPlayPosition));
        return true;
    }

```

## 问题log

```
11-05 12:17:52.073 22760-23174/com.longjing.debug E/IJKMEDIA: configure acodec:0x200716 format:0x20075e: surface:0x200736
11-05 12:17:52.074 22760-23174/com.longjing.debug W/System.err: java.lang.IllegalArgumentException: The surface has been released
11-05 12:17:52.084 22760-23174/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_configure(Native Method)
11-05 12:17:52.084 22760-23174/com.longjing.debug W/System.err:     at android.media.MediaCodec.configure(MediaCodec.java:1778)
11-05 12:17:52.084 22760-23174/com.longjing.debug E/IJKMEDIA: reconfigure_codec_l:configure_surface: failed
11-05 12:17:52.084 22760-23174/com.longjing.debug E/IJKMEDIA: feed_input_buffer: reconfigure_codec failed
11-05 12:17:52.084 22760-23171/com.longjing.debug W/System.err: java.lang.IllegalStateExceptionjava.lang.IllegalStateException
11-05 12:17:52.085 22760-23171/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
11-05 12:17:52.085 22760-23171/com.longjing.debug W/System.err:     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
11-05 12:17:52.085 22760-23171/com.longjing.debug I/IJKMEDIA: SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
11-05 12:17:52.085 22760-23174/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
11-05 12:17:52.085 22760-23174/com.longjing.debug W/System.err:     at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2319)
11-05 12:17:52.085 22760-23174/com.longjing.debug E/IJKMEDIA: SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
11-05 12:17:52.085 22760-23174/com.longjing.debug W/System.err: java.lang.IllegalStateException
11-05 12:17:52.085 22760-23174/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
11-05 12:17:52.085 22760-23174/com.longjing.debug W/System.err:     at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2319)
11-05 12:17:52.085 22760-23174/com.longjing.debug E/IJKMEDIA: SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
11-05 12:17:52.086 22760-23174/com.longjing.debug W/System.err: java.lang.IllegalStateException
11-05 12:17:52.086 22760-23174/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
11-05 12:17:52.086 22760-23174/com.longjing.debug W/System.err:     at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2319)
11-05 12:17:52.086 22760-23174/com.longjing.debug E/IJKMEDIA: SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
```

**Comment by CarGuo** [comment]
请尝试最新 demo 看是否复现

**Comment by CleverSJX** [comment]
> 请尝试最新 demo 看是否复现

一样的,同样的错误

**Comment by CleverSJX** [comment]
> 请尝试最新 demo 看是否复现

切换成EXO就不会报错了,为什么?

**Comment by CarGuo** [comment]
因为exo player 不存在硬解码的说法，本来就是用了 mediacodec

**Comment by CleverSJX** [comment]
> 因为exo player 不存在硬解码的说法，本来就是用了 mediacodec

那就是IJK模式 播放下一个视频是有问题的如上, exo 模式没有上述问题, 为什么呢?

**Comment by CarGuo** [comment]
ijk 用的是 ffmpeg 的硬解码模式，它需要特殊处理切换时surface黑屏花屏的问题

**Comment by CleverSJX** [comment]
> ijk 用的是 ffmpeg 的硬解码模式，它需要特殊处理切换时surface黑屏花屏的问题

用exo也有问题了
## 日志
```
11-11 15:10:17.607 10700-11067/com.longjing.debug W/ACodec: Allocating component 'OMX.amlogic.avc.decoder.awesome' failed, try next one.
11-11 15:10:17.607 10700-11067/com.longjing.debug E/ACodec: Unable to instantiate codec 'OMX.amlogic.avc.decoder.awesome' with err 0xfffffff4.
11-11 15:10:17.607 10700-11067/com.longjing.debug E/ACodec: signalError(omxError 0xfffffff4, internalError -12)
11-11 15:10:17.607 10700-11066/com.longjing.debug E/MediaCodec: Codec reported err 0xfffffff4, actionCode 0, while in state 1
11-11 15:10:17.612 10700-11062/com.longjing.debug W/MediaCodec-JNI: try to release MediaCodec from JMediaCodec::~JMediaCodec()...
11-11 15:10:17.612 10700-11062/com.longjing.debug W/MediaCodec-JNI: done releasing MediaCodec from JMediaCodec::~JMediaCodec().
11-11 15:10:17.614 10700-11062/com.longjing.debug W/MediaCodecRenderer: Failed to initialize decoder: OMX.amlogic.avc.decoder.awesome
    android.media.MediaCodec$CodecException: Failed to initialize OMX.amlogic.avc.decoder.awesome, error 0xfffffff4
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:1670)
        at android.media.MediaCodec.createByCodecName(MediaCodec.java:1651)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
11-11 15:10:17.615 10700-11062/com.longjing.debug E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome, Format(1, null, null, video/avc, null, -1, null, [3840, 2160, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome, Format(1, null, null, video/avc, null, -1, null, [3840, 2160, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.amlogic.avc.decoder.awesome, error 0xfffffff4
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:1670)
        at android.media.MediaCodec.createByCodecName(MediaCodec.java:1651)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
11-11 15:10:17.615 10700-11065/com.longjing.debug I/MediaCodec: [OMX.amlogic.avc.decoder.awesome] setting surface generation to 10956801
11-11 15:10:17.617 10700-11065/com.longjing.debug V/MediaCodec: Found 2 pieces of codec specific data.
11-11 15:10:17.618 10700-10700/com.longjing.debug E/EventLogger: playerFailed [0.20]
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome, Format(1, null, null, video/avc, null, -1, null, [3840, 2160, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome, Format(1, null, null, video/avc, null, -1, null, [3840, 2160, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.amlogic.avc.decoder.awesome, error 0xfffffff4
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:1670)
        at android.media.MediaCodec.createByCodecName(MediaCodec.java:1651)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
11-11 15:10:17.618 10700-10700/com.longjing.debug D/EventLogger: loading [false]
11-11 15:10:17.618 10700-10700/com.longjing.debug D/EventLogger: state [0.20, false, I]
11-11 15:10:17.619 10700-11068/com.longjing.debug E/ACodec: [OMX.amlogic.avc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
11-11 15:10:17.619 10700-10700/com.longjing.debug E/LJ-ListGSYVideoComponent: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
11-11 15:10:17.619 10700-10700/com.longjing.debug E/LJ-ListGSYVideoComponent: │ Thread: main
11-11 15:10:17.619 10700-10700/com.longjing.debug E/LJ-ListGSYVideoComponent: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
11-11 15:10:17.620 10700-10700/com.longjing.debug E/LJ-ListGSYVideoComponent: │ GSYVideoBaseManager$5.run  (GSYVideoBaseManager.java:302)
11-11 15:10:17.620 10700-10700/com.longjing.debug E/LJ-ListGSYVideoComponent: │    ListGSYVideoComponent.onError  (ListGSYVideoComponent.java:180)
11-11 15:10:17.620 10700-10700/com.longjing.debug E/LJ-ListGSYVideoComponent: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
11-11 15:10:17.620 10700-10700/com.longjing.debug E/LJ-ListGSYVideoComponent: │ 视频播放错误 path=file:///data/user/0/com.longjing.debug/files/download/41641109ff6d97b134dbd8ea54e14a07, what=1, extra=1 
11-11 15:10:17.620 10700-10700/com.longjing.debug E/LJ-ListGSYVideoComponent: └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
11-11 15:10:17.621 10700-10700/com.longjing.debug I/ExoPlayerImpl: Release 922ec99 [ExoPlayerLib/2.9.3] [queenchristina, MiBOX3S, Xiaomi, 23] [goog.exo.core]
11-11 15:10:17.624 10700-11068/com.longjing.debug I/ACodec: codec does not support config priority (err -1010)
```

**Comment by CarGuo** [comment]
看起来是编码格式不支持，mkv容器，视频编码和音频编码是什么？

**Comment by CleverSJX** [comment]
> 看起来是编码格式不支持，mkv容器，视频编码和音频编码是什么？

视频 x264
音频 ac-3

**Comment by CarGuo** [comment]
https://developer.android.google.cn/guide/topics/media/media-formats.html MediaCodec 暂时看不到 x264 的支持

**Comment by CleverSJX** [comment]
> https://developer.android.google.cn/guide/topics/media/media-formats.html MediaCodec 暂时看不到 x264 的支持

原生的播放器是可以播放的
http://dianxiu-dev.oss-cn-hangzhou.aliyuncs.com/4k.mp4
http://dianxiu-dev.oss-cn-hangzhou.aliyuncs.com/4k.mkv
我是下载后 离线播放的 
MP4格式我是用 ffmpeg 自己转码的 exo模式也播放失败

**Comment by CleverSJX** [comment]
当前视频用ijk模式 gsy:6.0.3
1. 在小米盒子Android版本 6.0.1上可以播放但是播放下一个视频就黑屏,
2. 再另一款盒子Android版本5.1.1上直接黑屏

另外我之前用的 gsy:2.1.3版本 ijk模式 播放下一个视频都是正常,可以对比一下ijk版本差异吗

**Comment by CarGuo** [comment]
> > https://developer.android.google.cn/guide/topics/media/media-formats.html MediaCodec 暂时看不到 x264 的支持
> 
> 原生的播放器是可以播放的
> http://dianxiu-dev.oss-cn-hangzhou.aliyuncs.com/4k.mp4
> http://dianxiu-dev.oss-cn-hangzhou.aliyuncs.com/4k.mkv
> 我是下载后 离线播放的
> MP4格式我是用 ffmpeg 自己转码的 exo模式也播放失败

我这边测试在demo 用 exo 和默认 ijk 都可以播放，exo 默认流畅运行，如果是低版本上播放不了，可以切换到 GSYVideoType.setRenderType(GSYVideoType.SUFRACE); 或者配置 AndroidManifset 中的硬件加速渲染

**Comment by xiaokele** [comment]
网上有资料显示是MediaCodec实例没有释放的问题，楼主核实下   https://www.meiwen.com.cn/subject/doefcqtx.html
