### ISSUE TITLE
无法播放https视频链接

### ISSUE THREAD

**Issue by qet119** [CarGuo/GSYVideoPlayer#2395]
华为畅想 安卓7.0

9.0系统没问题

无法播放https视频链接，控制台打印找不到证书

`2019-11-09 20:58:01.965 8786-9168/csdn.shimiso.eim W/System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2019-11-09 20:58:01.965 8786-9168/csdn.shimiso.eim W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:361)
2019-11-09 20:58:01.965 8786-9168/csdn.shimiso.eim W/System.err:     at com.android.okhttp.Connection.connectTls(Connection.java:235)
2019-11-09 20:58:01.966 8786-9168/csdn.shimiso.eim W/System.err:     at com.android.okhttp.Connection.connectSocket(Connection.java:199)
2019-11-09 20:58:01.966 8786-9168/csdn.shimiso.eim W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:172)
2019-11-09 20:58:01.966 8786-9168/csdn.shimiso.eim W/System.err:     at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
2019-11-09 20:58:01.966 8786-9168/csdn.shimiso.eim W/System.err:     at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
2019-11-09 20:58:01.966 8786-9168/csdn.shimiso.eim W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
2019-11-09 20:58:01.966 8786-9168/csdn.shimiso.eim W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
2019-11-09 20:58:01.966 8786-9168/csdn.shimiso.eim W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
2019-11-09 20:58:01.966 8786-9168/csdn.shimiso.eim W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
2019-11-09 20:58:01.966 8786-9168/csdn.shimiso.eim W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
2019-11-09 20:58:01.966 8786-9168/csdn.shimiso.eim W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
2019-11-09 20:58:01.966 8786-9168/csdn.shimiso.eim W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
2019-11-09 20:58:01.966 8786-9168/csdn.shimiso.eim W/System.err:     at com.danikula.videocache.HttpUrlSource.openConnection(HttpUrlSource.java:164)
2019-11-09 20:58:01.967 8786-9168/csdn.shimiso.eim W/System.err:     at com.danikula.videocache.HttpUrlSource.fetchContentInfo(HttpUrlSource.java:133)
2019-11-09 20:58:01.967 8786-9168/csdn.shimiso.eim W/System.err:     at com.danikula.videocache.HttpUrlSource.length(HttpUrlSource.java:66)
2019-11-09 20:58:01.967 8786-9168/csdn.shimiso.eim W/System.err:     at com.danikula.videocache.HttpProxyCache.isUseCache(HttpProxyCache.java:52)
2019-11-09 20:58:01.967 8786-9168/csdn.shimiso.eim W/System.err:     at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:44)
2019-11-09 20:58:01.967 8786-9168/csdn.shimiso.eim W/System.err:     at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
2019-11-09 20:58:01.967 8786-9168/csdn.shimiso.eim W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:230)
2019-11-09 20:58:01.967 8786-9168/csdn.shimiso.eim W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:51)
2019-11-09 20:58:01.967 8786-9168/csdn.shimiso.eim W/System.err:     at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:332)
2019-11-09 20:58:01.967 8786-9168/csdn.shimiso.eim W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
2019-11-09 20:58:01.967 8786-9168/csdn.shimiso.eim W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
2019-11-09 20:58:01.967 8786-9168/csdn.shimiso.eim W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2019-11-09 20:58:01.967 8786-9168/csdn.shimiso.eim W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2019-11-09 20:58:01.967 8786-9168/csdn.shimiso.eim W/System.err:     at java.lang.Thread.run(Thread.java:776)
2019-11-09 20:58:01.968 8786-9168/csdn.shimiso.eim W/System.err: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2019-11-09 20:58:01.968 8786-9168/csdn.shimiso.eim W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:549)
2019-11-09 20:58:01.968 8786-9168/csdn.shimiso.eim W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:401)
2019-11-09 20:58:01.968 8786-9168/csdn.shimiso.eim W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375)
2019-11-09 20:58:01.968 8786-9168/csdn.shimiso.eim W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:304)
2019-11-09 20:58:01.968 8786-9168/csdn.shimiso.eim W/System.err:     at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
2019-11-09 20:58:01.968 8786-9168/csdn.shimiso.eim W/System.err:     at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
2019-11-09 20:58:01.968 8786-9168/csdn.shimiso.eim W/System.err:     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:178)
2019-11-09 20:58:01.968 8786-9168/csdn.shimiso.eim W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:596)
2019-11-09 20:58:01.969 8786-9168/csdn.shimiso.eim W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
2019-11-09 20:58:01.969 8786-9168/csdn.shimiso.eim W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
2019-11-09 20:58:01.969 8786-9168/csdn.shimiso.eim W/System.err: 	... 26 more
2019-11-09 20:58:01.969 8786-9168/csdn.shimiso.eim W/System.err: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2019-11-09 20:58:01.969 8786-9168/csdn.shimiso.eim W/System.err: 	... 36 more`

**Comment by CarGuo** [comment]
先在demo试试是否复现，然后确定链接证书是否有问题，或者设置证书忽略，看首页版本更新链接

**Comment by qet119** [comment]
> 先在demo试试是否要复现，然后确定链接证书是否有问题，或者设置证书忽略，看首页版本更新链接

解决了, 发现openfire没导错证书，没导入证书链，多谢!
