### ISSUE TITLE
红米note2，3 报错..

### ISSUE THREAD

**Issue by CherryLu** [CarGuo/GSYVideoPlayer#24]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.apps.android.news.news-2/base.apk"],nativeLibraryDirectories=[/data/app/com.apps.android.news.news-2/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:366)
	at java.lang.System.loadLibrary(System.java:988)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:163)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:174)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:215)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:211)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:202)
	at com.shuyu.gsyvideoplayer.GSYVideoManager.<init>(GSYVideoManager.java:204)
	at com.shuyu.gsyvideoplayer.GSYVideoManager.instance(GSYVideoManager.java:84)
	at com.shuyu.gsyvideoplayer.GSYVideoPlayer.isCurrentMediaListener(GSYVideoPlayer.java:1064)
	at com.shuyu.gsyvideoplayer.GSYVideoPlayer.setUp(GSYVideoPlayer.java:227)
	at com.apps.android.news.news.ui.widget.MyVideoPlayer.setUp(MyVideoPlayer.java:179)
	at com.apps.android.news.news.ui.activity.VideoDetailActivity.setVideo(VideoDetailActivity.java:144)
	at com.apps.android.news.news.ui.activity.VideoDetailActivity.onCreate(VideoDetailActivity.java:117)
	at android.app.Activity.performCreate(Activity.java:6041)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2285)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2394)
	at android.app.ActivityThread.access$800(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5276)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

**Comment by CarGuo** [comment]
这是没有对应so，确定你的包所有so文件夹下，so都打包进去了，比如arm64文件夹中存在但是没有ffmpeg的so，或者使用ndk过滤

**Comment by CherryLu** [comment]
额  我直接compile 'com.github.CarGuo:GSYVideoPlayer:v1.4.5'  然后就直接用了  不行吗？

**Comment by CarGuo** [comment]
在你的主app module下，加上
android { 
    ··· 
    defaultConfig { 
         ···
         ndk { 
             //APP的build.gradle设置支持的SO库架构 
            abiFilters 'armeabi', 'armeabi-v7a', 'x86'
         }
     }
 }

文／恋猫月亮（简书作者）
原文链接：http://www.jianshu.com/p/86e4b336c17d

**Comment by CherryLu** [comment]
谢谢大神  搞定了

**Comment by JianHaoZhangHB** [comment]
我已经加上了这段
ndk {
//APP的build.gradle设置支持的SO库架构
abiFilters 'armeabi', 'armeabi-v7a', 'x86'
}
但是仍然报错
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.mrhao.fingermapdemo-1/base.apk", zip file "/data/app/com.example.mrhao.fingermapdemo-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.mrhao.fingermapdemo-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.mrhao.fingermapdemo-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.mrhao.fingermapdemo-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.mrhao.fingermapdemo-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.mrhao.fingermapdemo-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.mrhao.fingermapdemo-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.mrhao.fingermapdemo-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.mrhao.fingermapdemo-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.mrhao.fingermapdemo-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.mrhao.fingermapdemo-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.mrhao.fingermapdemo-1/lib/arm, /data/app/com.example.mrhao.fingermapdemo-1/base.apk!/lib/armeabi-v7a, /data/app/com.example.mrhao.fingermapdemo-1/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/com.example.mrhao.fingermapdemo-1/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/com.example.mrhao.fingermapdemo-1/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/com.example.mrhao.fingermapdemo-1/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/com.example.mrhao.fingermapdemo-1/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/com.example.mrhao.fingermapdemo-1/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/com.example.mrhao.fingermapdemo-1/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/com.example.mrhao.fingermapdemo-1/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/com.example.mrhao.fingermapdemo-1/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/com.example.mrhao.fingermapdemo-1/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/com.example.mrhao.fingermapdemo-1/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libijkffmpeg.so"
找不到libijkffmpeg.so
测试机小米Note
