### ISSUE TITLE
报错：E/HttpProxyCacheDebuger: Error pinging server (attempts: 3, max timeout: 280). 

### ISSUE THREAD

**Issue by sange93** [CarGuo/GSYVideoPlayer#2425]
## 问题描述：

视频播放时 发生了这样的问题！

## 问题机型/系统：

真机 小米9 Android 10.0

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:7.1.1'`

## 问题log

```

E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0
2019-11-22 15:01:28.308 22139-22309/ E/HttpProxyCacheDebuger: Error reading ping response
2019-11-22 15:01:28.308 22139-22309/ W/System.err: com.danikula.videocache.ProxyCacheException: Error opening connection for http://127.0.0.1:40717/ping with offset 0. Version: 7.1.1
2019-11-22 15:01:28.309 22139-22309/ W/System.err:     at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:81)
2019-11-22 15:01:28.309 22139-22309/ W/System.err:     at com.danikula.videocache.Pinger.pingServer(Pinger.java:99)
2019-11-22 15:01:28.309 22139-22309/com.aaa W/System.err:     at com.danikula.videocache.Pinger.access$100(Pinger.java:32)
2019-11-22 15:01:28.309 22139-22309/com.aaa W/System.err:     at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:121)
2019-11-22 15:01:28.309 22139-22309/com.aaa W/System.err:     at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:117)
2019-11-22 15:01:28.309 22139-22309/com.aaa W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-11-22 15:01:28.309 22139-22309/com.aaa W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-11-22 15:01:28.309 22139-22309/com.aaa W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-11-22 15:01:28.309 22139-22309/com.aaa W/System.err:     at java.lang.Thread.run(Thread.java:919)
2019-11-22 15:01:28.309 22139-22309/com.aaa W/System.err: Caused by: java.io.IOException: Cleartext HTTP traffic to 127.0.0.1 not permitted
2019-11-22 15:01:28.309 22139-22309/com.aaa W/System.err:     at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:124)
2019-11-22 15:01:28.309 22139-22309/com.aaa W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:462)
2019-11-22 15:01:28.309 22139-22309/com.aaa W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
2019-11-22 15:01:28.309 22139-22309/com.aaa W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
2019-11-22 15:01:28.309 22139-22309/com.aaa W/System.err:     at com.danikula.videocache.HttpUrlSource.openConnection(HttpUrlSource.java:164)
2019-11-22 15:01:28.309 22139-22309/com.aaa W/System.err:     at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:74)
2019-11-22 15:01:28.309 22139-22309/com.aaa W/System.err: 	... 8 more
2019-11-22 15:01:28.310 22139-22139/com.aaa E/HttpProxyCacheDebuger: Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, report at https://github.com/danikula/AndroidVideoCache/issues/134. Default proxies are: [DIRECT]
2019-11-22 15:01:28.310 22139-22139/com.aaa W/System.err: com.danikula.videocache.ProxyCacheException: Error pinging server (attempts: 3, max timeout: 280). If you see this message, please, report at https://github.com/danikula/AndroidVideoCache/issues/134. Default proxies are: [DIRECT]. Version: 7.1.1
2019-11-22 15:01:28.310 22139-22139/com.aaa W/System.err:     at com.danikula.videocache.Pinger.ping(Pinger.java:71)
2019-11-22 15:01:28.310 22139-22139/com.aaa W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.isAlive(HttpProxyCacheServer.java:181)
2019-11-22 15:01:28.310 22139-22139/com.aaa W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.getProxyUrl(HttpProxyCacheServer.java:118)
2019-11-22 15:01:28.310 22139-22139/com.aaa W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.getProxyUrl(HttpProxyCacheServer.java:99)
2019-11-22 15:01:28.310 22139-22139/com.aaa W/System.err:     at com.shuyu.gsyvideoplayer.cache.ProxyCacheManager.doCacheLogic(ProxyCacheManager.java:70)
2019-11-22 15:01:28.310 22139-22139/com.aaa W/System.err:     at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.initVideoPlayer(IjkPlayerManager.java:78)
2019-11-22 15:01:28.310 22139-22139/com.aaa W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:607)
2019-11-22 15:01:28.310 22139-22139/com.aaa W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:39)
2019-11-22 15:01:28.310 22139-22139/com.aaa W/System.err:     at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:567)
2019-11-22 15:01:28.310 22139-22139/com.aaa W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
2019-11-22 15:01:28.310 22139-22139/com.aaa W/System.err:     at android.os.Looper.loop(Looper.java:223)
2019-11-22 15:01:28.310 22139-22139/com.aaa W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7520)
2019-11-22 15:01:28.310 22139-22139/com.aaa W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-11-22 15:01:28.310 22139-22139/com.aaa W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
2019-11-22 15:01:28.310 22139-22139/com.aaa W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

请问是什么原因引起的？

**Comment by CarGuo** [comment]
close cache

**Comment by sange93** [comment]
OK
