### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/internal/view/ContextThemeWrapper;

### ISSUE THREAD

**Issue by ieewbbwe** [CarGuo/GSYVideoPlayer#245]
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/internal/view/ContextThemeWrapper;
                                                                             at com.shuyu.gsyvideoplayer.utils.CommonUtil.getAppCompActivity(CommonUtil.java:180)
                                                                             at com.shuyu.gsyvideoplayer.utils.CommonUtil.hideSupportActionBar(CommonUtil.java:106)
                                                                             at com.shuyu.gsyvideoplayer.video.GSYBaseVideoPlayer.startWindowFullscreen(GSYBaseVideoPlayer.java:283)
                                                                             at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.startWindowFullscreen(StandardGSYVideoPlayer.java:807)
                                                                             at com.shuyu.gsyvideoplayer.video.CustomGSYVideoPlayer.startWindowFullscreen(CustomGSYVideoPlayer.java:167)
                                                                             at com.beyondsoft.skyworth.increased.ui.CourseDetailActivity$6.onClick(CourseDetailActivity.java:198)
                                                                             at android.view.View.performClick(View.java:4792)
                                                                             at android.view.View$PerformClick.run(View.java:19915)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5298)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708)
                                                                          Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.internal.view.ContextThemeWrapper" on path: DexPathList[[zip file "/data/app/com.beyondsoft.skyworth-2/base.apk"],nativeLibraryDirectories=[/data/app/com.beyondsoft.skyworth-2/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                             at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                             at com.shuyu.gsyvideoplayer.utils.CommonUtil.getAppCompActivity(CommonUtil.java:180) 
                                                                             at com.shuyu.gsyvideoplayer.utils.CommonUtil.hideSupportActionBar(CommonUtil.java:106) 
                                                                             at com.shuyu.gsyvideoplayer.video.GSYBaseVideoPlayer.startWindowFullscreen(GSYBaseVideoPlayer.java:283) 
                                                                             at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.startWindowFullscreen(StandardGSYVideoPlayer.java:807) 
                                                                             at com.shuyu.gsyvideoplayer.video.CustomGSYVideoPlayer.startWindowFullscreen(CustomGSYVideoPlayer.java:167) 
                                                                             at com.beyondsoft.skyworth.increased.ui.CourseDetailActivity$6.onClick(CourseDetailActivity.java:198) 
                                                                             at android.view.View.performClick(View.java:4792) 
                                                                             at android.view.View$PerformClick.run(View.java:19915) 
                                                                             at android.os.Handler.handleCallback(Handler.java:739) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5298) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708) 
                                                                         	Suppressed: java.lang.ClassNotFoundException: android.support.v7.internal.view.ContextThemeWrapper
                                                                             at java.lang.Class.classForName(Native Method)
                                                                             at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                             at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                             		... 17 more
                                                                          Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by CarGuo** [comment]
你的activity是不是v7支持包的ACtivity？请参考demo

**Comment by parcool** [comment]
由于其他原因，无法使用AppCompatActivity，直接用android.app.Activity下的Activity。我在想为毛不用android.view.ContextThemeWrapper而要用android.support.v7.internal.view.ContextThemeWrapper？当然，你这个方法都是返回的AppCompatActivity，也无可厚非了。。。so，这里只能自己去实现咯
