### ISSUE TITLE
混淆问题

### ISSUE THREAD

**Issue by zjjjia** [CarGuo/GSYVideoPlayer#2455]
## 问题描述：

添加文档中的混淆规则之后，混淆打包后的apk会报错：
```
2019-12-06 11:57:26.988 13113-13113/? E/J4A: J4A_FindClass__asGlobalRef__catchAll: failed: tv/danmaku/ijk/media/player/misc/IMediaDataSource
2019-12-06 11:57:26.988 13113-13113/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jcr.android.pocketpro, PID: 13113
    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.jcr.android.pocketpro-BFcmX8RroYNQuPU7aKZ3Xg==/lib/arm64/libijksdl.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.a(:1)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(:1)
        at d.k.a.r.d.a(:1)
        at d.k.a.g.a(:5)
        at d.k.a.g$c.handleMessage(:5)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7094)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
2019-12-06 11:57:27.078 916-2460/? E/NativeSemDvfsCpuManager: release:: Start
2019-12-06 11:57:27.078 916-2460/? E/SemOpenPerfStorageManager: release:: Start
2019-12-06 11:57:27.078 916-2460/? E/SemOpenPerfStorageManager: release:: DVFS lock is already released. Previous lock will be acquire first.
2019-12-06 11:57:27.197 1595-9604/? E/MdnieScenarioControlService: Exception : java.io.FileNotFoundException: /sys/class/mdnie/mdnie/scenario (No such file or directory) , in : null , value : null , length : 0
2019-12-06 11:57:27.525 1595-9398/? E/TaskPersister: File error accessing recents directory (directory doesn't exist?).
2019-12-06 11:57:27.730 1595-9604/? E/MdnieScenarioControlService: Exception : java.io.FileNotFoundException: /sys/class/mdnie/mdnie/scenario (No such file or directory) , in : null , value : null , length : 0
2019-12-06 11:57:27.895 13113-13121/? E/droid.pocketpr: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
2019-12-06 11:57:27.895 13113-13121/? E/System: Uncaught exception thrown by finalizer
2019-12-06 11:57:27.895 13113-13121/? E/System: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(Unknown Source:3)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
        at java.lang.Daemons$Daemon.run(Daemons.java:103)
        at java.lang.Thread.run(Thread.java:764)
2019-12-06 11:57:29.352 16465-6685/? E/MdnsClient: Failed to send a multicast mDNS packet.
    java.io.IOException: sendto failed: EPERM (Operation not permitted)
        at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:576)
        at libcore.io.IoBridge.sendto(IoBridge.java:544)
        at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:125)
        at java.net.DatagramSocket.send(DatagramSocket.java:723)
        at agsr.a(:com.google.android.gms@17455037@17.4.55 (100400-248795830):82)
        at agsq.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:764)

```

## 问题机型/系统：
真机 三星a60

## GSY依赖版本
 'com.shuyu:gsyVideoPlayer-java:7.1.2`
'com.shuyu:gsyVideoPlayer-ex_so:7.1.1'

## Demo中的复现步骤
运行混淆打包之后的apk，打开需要调用VideoPlayer的界面

## 问题log

```
2019-12-06 11:57:26.988 13113-13113/? E/J4A: J4A_FindClass__asGlobalRef__catchAll: failed: tv/danmaku/ijk/media/player/misc/IMediaDataSource
2019-12-06 11:57:26.988 13113-13113/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jcr.android.pocketpro, PID: 13113
    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.jcr.android.pocketpro-BFcmX8RroYNQuPU7aKZ3Xg==/lib/arm64/libijksdl.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.a(:1)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(:1)
        at d.k.a.r.d.a(:1)
        at d.k.a.g.a(:5)
        at d.k.a.g$c.handleMessage(:5)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7094)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
2019-12-06 11:57:27.078 916-2460/? E/NativeSemDvfsCpuManager: release:: Start
2019-12-06 11:57:27.078 916-2460/? E/SemOpenPerfStorageManager: release:: Start
2019-12-06 11:57:27.078 916-2460/? E/SemOpenPerfStorageManager: release:: DVFS lock is already released. Previous lock will be acquire first.
2019-12-06 11:57:27.197 1595-9604/? E/MdnieScenarioControlService: Exception : java.io.FileNotFoundException: /sys/class/mdnie/mdnie/scenario (No such file or directory) , in : null , value : null , length : 0
2019-12-06 11:57:27.525 1595-9398/? E/TaskPersister: File error accessing recents directory (directory doesn't exist?).
2019-12-06 11:57:27.730 1595-9604/? E/MdnieScenarioControlService: Exception : java.io.FileNotFoundException: /sys/class/mdnie/mdnie/scenario (No such file or directory) , in : null , value : null , length : 0
2019-12-06 11:57:27.895 13113-13121/? E/droid.pocketpr: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
2019-12-06 11:57:27.895 13113-13121/? E/System: Uncaught exception thrown by finalizer
2019-12-06 11:57:27.895 13113-13121/? E/System: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(Unknown Source:3)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
        at java.lang.Daemons$Daemon.run(Daemons.java:103)
        at java.lang.Thread.run(Thread.java:764)
2019-12-06 11:57:29.352 16465-6685/? E/MdnsClient: Failed to send a multicast mDNS packet.
    java.io.IOException: sendto failed: EPERM (Operation not permitted)
        at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:576)
        at libcore.io.IoBridge.sendto(IoBridge.java:544)
        at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:125)
        at java.net.DatagramSocket.send(DatagramSocket.java:723)
        at agsr.a(:com.google.android.gms@17455037@17.4.55 (100400-248795830):82)
        at agsq.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:764)


```

**Comment by CarGuo** [comment]
这么奇怪， demo 混淆打包正常呀？

**Comment by zjjjia** [comment]
刚看了一下，demo打包正常，看来应该是我项目里的问题
