### ISSUE TITLE
android4.4不能使用Exo2PlayerManager，播放不了

### ISSUE THREAD

**Issue by shaojiankui** [CarGuo/GSYVideoPlayer#2473]
## 问题描述：

android4.*不能使用Exo2PlayerManager，播放不了，黑屏。log提示AudioFocusRequest不存在，我查了下AudioFocusRequest是Added in API level 26，是不是这问题导致的。

## 问题机型/系统：

Android 4.4

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3`
`com.shuyu:GSYVideoPlayer-exo2:5.0.1`
 
## 问题log（如果有）

12-18 09:27:14.265 5266-5266/org.skyfox.demo E/dalvikvm: Could not find class 'android.media.AudioAttributes$Builder', referenced from method com.google.android.exoplayer2.audio.AudioAttributes.getAudioAttributesV21
12-18 09:27:14.265 5266-5266/org.skyfox.demo W/dalvikvm: VFY: unable to resolve new-instance 323 (Landroid/media/AudioAttributes$Builder;) in Lcom/google/android/exoplayer2/audio/AudioAttributes;
12-18 09:27:14.265 5266-5266/org.skyfox.demo D/dalvikvm: VFY: replacing opcode 0x22 at 0x0004
12-18 09:27:14.265 5266-5266/org.skyfox.demo W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/media/AudioAttributes;)
12-18 09:27:14.265 5266-5266/org.skyfox.demo D/dalvikvm: DexOpt: unable to opt direct call 0x066a at 0x06 in Lcom/google/android/exoplayer2/audio/AudioAttributes;.getAudioAttributesV21
12-18 09:27:14.265 5266-5266/org.skyfox.demo I/ExoPlayerImpl: Init a5aee170 [ExoPlayerLib/2.9.3] [generic_x86, Android SDK built for x86, unknown, 18]
12-18 09:27:14.275 5266-5266/org.skyfox.demo I/dalvikvm: Could not find method android.media.AudioManager.abandonAudioFocusRequest, referenced from method com.google.android.exoplayer2.audio.AudioFocusManager.abandonAudioFocusV26
12-18 09:27:14.275 5266-5266/org.skyfox.demo W/dalvikvm: VFY: unable to resolve virtual method 1666: Landroid/media/AudioManager;.abandonAudioFocusRequest (Landroid/media/AudioFocusRequest;)I
12-18 09:27:14.275 5266-5266/org.skyfox.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x000e
12-18 09:27:14.275 5266-5266/org.skyfox.demo E/dalvikvm: Could not find class 'android.media.AudioFocusRequest$Builder', referenced from method com.google.android.exoplayer2.audio.AudioFocusManager.requestAudioFocusV26
12-18 09:27:14.275 5266-5266/org.skyfox.demo W/dalvikvm: VFY: unable to resolve new-instance 325 (Landroid/media/AudioFocusRequest$Builder;) in Lcom/google/android/exoplayer2/audio/AudioFocusManager;
12-18 09:27:14.275 5266-5266/org.skyfox.demo D/dalvikvm: VFY: replacing opcode 0x22 at 0x000c
12-18 09:27:14.275 5266-5266/org.skyfox.demo E/dalvikvm: Could not find class 'android.media.AudioFocusRequest$Builder', referenced from method com.google.android.exoplayer2.audio.AudioFocusManager.requestAudioFocusV26
12-18 09:27:14.275 5266-5266/org.skyfox.demo W/dalvikvm: VFY: unable to resolve new-instance 325 (Landroid/media/AudioFocusRequest$Builder;) in Lcom/google/android/exoplayer2/audio/AudioFocusManager;
12-18 09:27:14.275 5266-5266/org.skyfox.demo D/dalvikvm: VFY: replacing opcode 0x22 at 0x0014
12-18 09:27:14.275 5266-5266/org.skyfox.demo I/dalvikvm: Could not find method android.media.AudioManager.requestAudioFocus, referenced from method com.google.android.exoplayer2.audio.AudioFocusManager.requestAudioFocusV26
12-18 09:27:14.275 5266-5266/org.skyfox.demo W/dalvikvm: VFY: unable to resolve virtual method 1675: Landroid/media/AudioManager;.requestAudioFocus (Landroid/media/AudioFocusRequest;)I
12-18 09:27:14.275 5266-5266/org.skyfox.demo D/dalvikvm: VFY: replacing opcode 0x6e at 0x004b
12-18 09:27:14.275 5266-5266/org.skyfox.demo D/dalvikvm: DexOpt: unable to opt direct call 0x0676 at 0x10 in Lcom/google/android/exoplayer2/audio/AudioFocusManager;.requestAudioFocusV26
12-18 09:27:14.275 5266-5266/org.skyfox.demo D/dalvikvm: DexOpt: unable to opt direct call 0x0677 at 0x16 in Lcom/google/android/exoplayer2/audio/AudioFocusManager;.requestAudioFocusV26
12-18 09:27:14.285 5266-5266/org.skyfox.demo D/EventLogger: state [0.06, false, B]
12-18 09:27:14.295 5266-5266/org.skyfox.demo D/EventLogger: sourceInfo [periodCount=1, windowCount=1
12-18 09:27:14.295 5266-5266/org.skyfox.demo D/EventLogger:   period [?]
12-18 09:27:14.295 5266-5266/org.skyfox.demo D/EventLogger:   window [?, false, false]
12-18 09:27:14.295 5266-5266/org.skyfox.demo D/EventLogger: ]
12-18 09:27:14.355 5266-5266/org.skyfox.demo D/EventLogger: loading [true]
12-18 09:27:49.685 5266-5313/org.skyfox.demo E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://dev.skyfox.org/test.mp4
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:292)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
        at java.lang.Thread.run(Thread.java:841)
     Caused by: java.net.SocketTimeoutException
        at java.net.PlainSocketImpl.read(PlainSocketImpl.java:491)
        at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
        at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
        at java.io.InputStream.read(InputStream.java:163)
        at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:227)
        at libcore.io.Streams.readAsciiLine(Streams.java:201)
        at libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:579)
        at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:827)
        at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:283)
        at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:288)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
        at java.lang.Thread.run(Thread.java:841) 
12-18 09:27:49.695 5266-5266/org.skyfox.demo E/EventLogger: playerFailed [35.47]
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://dev.skyfox.org/test.mp4
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:354)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:137)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://dev.skyfox.org/test.mp4
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:292)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
        at java.lang.Thread.run(Thread.java:841)
     Caused by: java.net.SocketTimeoutException
        at java.net.PlainSocketImpl.read(PlainSocketImpl.java:491)
        at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
        at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
        at java.io.InputStream.read(InputStream.java:163)
        at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:227)
        at libcore.io.Streams.readAsciiLine(Streams.java:201)
        at libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:579)
        at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:827)
        at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:283)
        at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:288)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
        at java.lang.Thread.run(Thread.java:841) 
12-18 09:27:49.695 5266-5266/org.skyfox.demo D/EventLogger: loading [false]
12-18 09:27:49.695 5266-5266/org.skyfox.demo D/EventLogger: state [35.48, false, I]

xxxxxxx

```

**Comment by CarGuo** [comment]
不支持4.4

**Comment by shaojiankui** [comment]
iJK支持么？
