### ISSUE TITLE
两个Activity都有视频组件 反复切换视频黑屏,播放报错

### ISSUE THREAD

**Issue by CleverSJX** [CarGuo/GSYVideoPlayer#2475]
## 问题机型/系统：

系统5.1.1

## GSY依赖版本

```
    implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'
    implementation 'com.shuyu:GSYVideoPlayer-exo2:6.0.3'
    implementation 'com.shuyu:gsyVideoPlayer-ex_so:6.0.3'
```

## 问题log

```
12-18 16:24:49.675 16077-16507/com.longjing.debug E/ACodec: Unable to instantiate codec 'OMX.hisi.audio.decoder.aac'.
12-18 16:24:49.675 16077-16507/com.longjing.debug E/ACodec: signalError(omxError 0x80001003, internalError -2147483648)
12-18 16:24:49.675 16077-16507/com.longjing.debug E/MediaCodec: Codec reported err 0xfffffffe, actionCode 0, while in state 1
12-18 16:24:49.683 16077-16502/com.longjing.debug E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.hisi.audio.decoder.aac, Format(2, null, null, audio/mp4a-latm, null, -1, und, [-1, -1, -1.0], [2, 44100])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:412)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.hisi.audio.decoder.aac, Format(2, null, null, audio/mp4a-latm, null, -1, und, [-1, -1, -1.0], [2, 44100])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:412) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: java.lang.IllegalArgumentException: Failed to initialize OMX.hisi.audio.decoder.aac, error 0xfffffffe
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:486)
        at android.media.MediaCodec.createByCodecName(MediaCodec.java:470)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:412) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
12-18 16:24:49.684 16077-16077/com.longjing.debug E/EventLogger: playerFailed [0.32]
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.hisi.audio.decoder.aac, Format(2, null, null, audio/mp4a-latm, null, -1, und, [-1, -1, -1.0], [2, 44100])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:412)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.hisi.audio.decoder.aac, Format(2, null, null, audio/mp4a-latm, null, -1, und, [-1, -1, -1.0], [2, 44100])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:412) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: java.lang.IllegalArgumentException: Failed to initialize OMX.hisi.audio.decoder.aac, error 0xfffffffe
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:486)
        at android.media.MediaCodec.createByCodecName(MediaCodec.java:470)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:412) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
12-18 16:24:49.685 16077-16077/com.longjing.debug E/LJ: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
12-18 16:24:49.685 16077-16077/com.longjing.debug E/LJ: │ Thread: main
12-18 16:24:49.685 16077-16077/com.longjing.debug E/LJ: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄��┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
12-18 16:24:49.685 16077-16077/com.longjing.debug E/LJ: │ GSYVideoBaseManager$5.run  (GSYVideoBaseManager.java:302)
12-18 16:24:49.685 16077-16077/com.longjing.debug E/LJ: │    ListGSYVideoComponent.onError  (ListGSYVideoComponent.java:180)
12-18 16:24:49.686 16077-16077/com.longjing.debug E/LJ: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
12-18 16:24:49.686 16077-16077/com.longjing.debug E/LJ: │ 视频播放错误 path=file:///data/data/com.longjing.debug/files/download/3cd037c1b8982b57dc73c45c8036ea35, what=1, extra=1 size=183mb
12-18 16:24:49.686 16077-16077/com.longjing.debug E/LJ: └────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```

**Comment by maytrue** [comment]
切换 Activity 播放器没有释放？

**Comment by CleverSJX** [comment]
> 切换 Activity 播放器没有释放？

开始在onDestroy释放了, 会黑屏,  然后我把release换成了pause 也是黑屏播放播放报错

**Comment by CarGuo** [comment]
release 是异步的在 ffmpeg 层····你必须有一些间隔时间去这样释放

**Comment by CleverSJX** [comment]
我都用的Exoplayer也不可以, 没用到FFmpeg吧, 不用release 用 pause也是同样的情况

**Comment by CarGuo** [comment]
一样的，你要知道默认情况下每个只有一个单例，新的播放都会释放旧的，你需要处理这种多个切换的逻辑。不然你以为B站 app 切换多个页面播放开会的时候为什么会有黑一小段时间？

**Comment by CleverSJX** [comment]
好吧明白了,谢谢~ 那有切换的思路或者Demo啥的嘛

**Comment by CarGuo** [comment]
之前的 issue 其实也有聊过相关的，就是你自己写一个标示位 ，做个延时处理。

**Comment by wangrunxiang** [comment]
release 是异步的在 ffmpeg 层····你必须有一些间隔时间去这样释放


@CarGuo 你们所说的release是在上层的哪个接口

**Comment by wangrunxiang** [comment]
这个延时处理要延时多久？

**Comment by wangrunxiang** [comment]
你需要处理这种多个切换的逻辑。

这个指的是怎么处理
@CarGuo
