### ISSUE TITLE
华为 7.0 播放https视频报错

### ISSUE THREAD

**Issue by qet119** [CarGuo/GSYVideoPlayer#2538]
2020-01-29 20:55:00.227 24366-24588/ W/System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2020-01-29 20:55:00.228 24366-24588/ W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:361)
2020-01-29 20:55:00.228 24366-24588/ W/System.err:     at com.android.okhttp.Connection.connectTls(Connection.java:235)
2020-01-29 20:55:00.228 24366-24588/ W/System.err:     at com.android.okhttp.Connection.connectSocket(Connection.java:199)
2020-01-29 20:55:00.228 24366-24588/ W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:172)
2020-01-29 20:55:00.228 24366-24588/ W/System.err:     at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
2020-01-29 20:55:00.228 24366-24588/ W/System.err:     at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
2020-01-29 20:55:00.228 24366-24588/ W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
2020-01-29 20:55:00.228 24366-24588/ W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
2020-01-29 20:55:00.228 24366-24588/ W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
2020-01-29 20:55:00.228 24366-24588/ W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
2020-01-29 20:55:00.228 24366-24588/ W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
2020-01-29 20:55:00.228 24366-24588/ W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
2020-01-29 20:55:00.228 24366-24588/ W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
2020-01-29 20:55:00.228 24366-24588/ W/System.err:     at com.danikula.videocache.HttpUrlSource.openConnection(HttpUrlSource.java:164)
2020-01-29 20:55:00.228 24366-24588/ W/System.err:     at com.danikula.videocache.HttpUrlSource.fetchContentInfo(HttpUrlSource.java:133)
2020-01-29 20:55:00.228 24366-24588/ W/System.err:     at com.danikula.videocache.HttpUrlSource.getMime(HttpUrlSource.java:191)
2020-01-29 20:55:00.228 24366-24588/ W/System.err:     at com.danikula.videocache.HttpProxyCache.newResponseHeaders(HttpProxyCache.java:60)
2020-01-29 20:55:00.228 24366-24588/ W/System.err:     at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:40)
2020-01-29 20:55:00.229 24366-24588/ W/System.err:     at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
2020-01-29 20:55:00.229 24366-24588/ W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:230)
2020-01-29 20:55:00.229 24366-24588/ W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:51)
2020-01-29 20:55:00.229 24366-24588/ W/System.err:     at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:332)
2020-01-29 20:55:00.229 24366-24588/ W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
2020-01-29 20:55:00.229 24366-24588/ W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
2020-01-29 20:55:00.229 24366-24588/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2020-01-29 20:55:00.229 24366-24588/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2020-01-29 20:55:00.229 24366-24588/ W/System.err:     at java.lang.Thread.run(Thread.java:776)
2020-01-29 20:55:00.229 24366-24588/ W/System.err: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2020-01-29 20:55:00.229 24366-24588/ W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:549)
2020-01-29 20:55:00.230 24366-24588/ W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:401)
2020-01-29 20:55:00.230 24366-24588/ W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375)
2020-01-29 20:55:00.230 24366-24588/ W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:304)
2020-01-29 20:55:00.230 24366-24588/ W/System.err:     at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
2020-01-29 20:55:00.230 24366-24588/ W/System.err:     at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
2020-01-29 20:55:00.230 24366-24588/ W/System.err:     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:178)
2020-01-29 20:55:00.230 24366-24588/ W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:596)
2020-01-29 20:55:00.230 24366-24588/ W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
2020-01-29 20:55:00.230 24366-24588/ W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
2020-01-29 20:55:00.230 24366-24588/ W/System.err: 	... 26 more
2020-01-29 20:55:00.231 24366-24588/ W/System.err: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2020-01-29 20:55:00.231 24366-24588/ W/System.err: 	... 36 more

**Comment by CarGuo** [comment]
证书异常
