### ISSUE TITLE
求助：Android8.0下报错找不到启动的StartPageActivity，9.0是正常的

### ISSUE THREAD

**Issue by dume2007** [CarGuo/GSYVideoPlayer#2551]
## 问题描述：

Android8.0下报错，9.0正常

## 问题机型/系统：

真机 小米6 Android8.0
模拟器 Pixel 2 API 26 Android8.0

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:7.1.2'

## Demo中的复现步骤

debug启动就报错

问题代码：(如果有)
build.gradle
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.dume.web.gifrr"
        minSdkVersion 26
        targetSdkVersion 29
        versionCode 1
        versionName "1.1.2"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
    buildToolsVersion = '29.0.3'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'pl.droidsonroids.gif:android-gif-drawable:1.2.17'
    implementation 'com.shuyu:GSYVideoPlayer:7.1.2'
}
```

## 问题log（如果有）

```
Connected to the target VM, address: 'localhost:8606', transport: 'socket'
I/System.out: waiting for debugger to settle...
I/chatty: uid=10083(u0_a83) com.dume.web.gifrr identical 5 lines
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1499)
W/zygote: Failure to verify dex file '/data/app/com.dume.web.gifrr-7nbWeACPN4rNUAQspxPtQQ==/base.apk': Bad method handle type 7
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dume.web.gifrr, PID: 9194
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.dume.web.gifrr/com.dume.web.gifrr.StartPageActivity}: java.lang.ClassNotFoundException: Didn't find class "com.dume.web.gifrr.StartPageActivity" on path: DexPathList[[zip file "/data/app/com.dume.web.gifrr-7nbWeACPN4rNUAQspxPtQQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.dume.web.gifrr-7nbWeACPN4rNUAQspxPtQQ==/lib/x86, /data/app/com.dume.web.gifrr-7nbWeACPN4rNUAQspxPtQQ==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2718)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.dume.web.gifrr.StartPageActivity" on path: DexPathList[[zip file "/data/app/com.dume.web.gifrr-7nbWeACPN4rNUAQspxPtQQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.dume.web.gifrr-7nbWeACPN4rNUAQspxPtQQ==/lib/x86, /data/app/com.dume.web.gifrr-7nbWeACPN4rNUAQspxPtQQ==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1173)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
    	Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.dume.web.gifrr-7nbWeACPN4rNUAQspxPtQQ==/base.apk because: Failure to verify dex file '/data/app/com.dume.web.gifrr-7nbWeACPN4rNUAQspxPtQQ==/base.apk': Bad method handle type 7
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:676)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:709)
        at android.app.LoadedApk.getResources(LoadedApk.java:936)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2242)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5672)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        		... 6 more
I/Process: Sending signal. PID: 9194 SIG: 9
```

**Comment by dume2007** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.dume.web.gifrr">

    <!-- 请求访问网络状态 -->
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <!-- 请求访问网络 -->
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.WRITE_SETTINGS" tools:ignore="ProtectedPermissions" />

    <application
        android:allowBackup="true"
        android:fullBackupContent="@xml/backup_descriptor"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/MainActivityTheme">
        <activity android:name=".VideoActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize|screenLayout|smallestScreenSize|uiMode"
            android:screenOrientation="portrait" />
        <activity android:name=".MainActivity" />
        <activity android:name=".BaseActivity" />
        <activity
            android:name=".StartPageActivity"
            android:theme="@style/SplashActivityTheme">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <meta-data
            android:name="android.max_aspect"
            android:value="2.1" />
    </application>

</manifest>
```

**Comment by CarGuo** [comment]
not player issue
