### ISSUE TITLE
exo播放m3u8播不出，报错Response code: 302

### ISSUE THREAD

**Issue by pyp163** [CarGuo/GSYVideoPlayer#2555]
## 问题描述：
       播放m3u8 hls, exo播放不出来，系统播放器和ijk都可以播，日志在后面，
帮我看看是什么问题，谢谢！

## 问题机型/系统：

电视盒子 Android7.1

## GSY依赖版本
    implementation 'com.shuyu:gsyVideoPlayer-java:7.1.1'
    implementation 'com.shuyu:gsyVideoPlayer-armv7a:7.1.1'
    implementation 'com.shuyu:gsyVideoPlayer-arm64:7.1.1'
    implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.1'

## 问题log
播放器日志：
I/ExoPlayerImpl: Release 2e81b84 [ExoPlayerLib/2.10.4] [X96W, funtv3, Amlogic, 25] [goog.exo.core, goog.exo.hls]
I/ExoPlayerImpl: Init ba4569 [ExoPlayerLib/2.10.4] [X96W, funtv3, Amlogic, 25]
D/EventLogger: state [0.01, false, B]
E/EventLogger: playerFailed [7.57]
错误日志：
E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 302
        at tv.danmaku.ijk.media.exo2.source.GSYExoHttpDataSource.open(GSYExoHttpDataSource.java:212)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:257)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:170)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)

xxxxxxx

```

**Comment by CarGuo** [comment]
请提供测试url
或者尝试

```
Map<String, String> header = new HashMap<>();
        header.put("allowCrossProtocolRedirects", "true");

 setup or mapHeader

```

https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/UPDATE_VERSION.md#7022019-07-01

**Comment by pyp163** [comment]
我试试，可能要自定义源解密才能播，看是不是这个问题

**Comment by CarGuo** [comment]
allowCrossProtocolRedirects 就是需要重定向

**Comment by pyp163** [comment]
ok，3Q
