### ISSUE TITLE
有一个视频URL无法播放，无论是在EXO模式下还是在IJKplayer模式下，网页浏览器可以播放

### ISSUE THREAD

**Issue by daygoodking** [CarGuo/GSYVideoPlayer#2592]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）
（ps 首页问题集锦和demo请先了解一下！）
问题集锦和demo,已了解，找不到解决方案。

## 提问前建议先看看： https://mp.weixin.qq.com/s/HjSdmAsHuvixCH_EWdvk3Q
已查看，仍然找不到解决方案。

## 问题描述：
此URL（https://pptv.com-h-pptv.com/share/57342f6b95854ad89e9c4088ab94adcf），无论是在EXO模式下还是在IJKplayer模式下都无法播放，网页浏览器可以播放

请教下，是该url的视频格式此播放器不支持，还是我哪里的配置有问题？

## GSY依赖版本
implementation 'com.shuyu:GSYVideoPlayer:7.1.2'

## Demo中的复现步骤
1）.Demo中的detailPlayer页面无法播放此URL(https://pptv.com-h-pptv.com/share/57342f6b95854ad89e9c4088ab94adcf)。

2）.demo“输入URL”界面中输入此URL也无法播放

## 问题代码和log（如果有）
设置EXO模式
代码：
        ExoSourceManager.setSkipSSLChain(true);
        CacheFactory.setCacheManager(ExoPlayerCacheManager.class);//exo缓存模式，支持m3u8，只支持exo
        PlayerFactory.setPlayManager(Exo2PlayerManager.class);//EXO模式
--------------------
播放输出如下log:
03-12 10:40:35.825 524-746/com.atguigu.android E/NativeCrypto: ssl=0x7fab5f5200 cert_verify_callback x509_store_ctx=0x7f987fea88 arg=0x0
03-12 10:40:35.825 524-746/com.atguigu.android E/NativeCrypto: ssl=0x7fab5f5200 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
03-12 10:40:36.381 524-745/com.atguigu.android E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor) could read the stream.
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1059)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:947)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
03-12 10:40:36.382 524-524/com.atguigu.android E/EventLogger: playerFailed [1.01]
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor) could read the stream.
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:386)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:200)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor) could read the stream.
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1059)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:947)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
====================================
设置IjkPlayer
代码如下：        
        PlayerFactory.setPlayManager(IjkPlayerManager.class);
        VideoOptionModel videoOptionModel1 =
                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "enable-accurate-seek", 1);
        VideoOptionModel videoOptionModel =
                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "dns_cache_clear", 1);
        VideoOptionModel videoOptionModel2 =
                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist", "rtmp,crypto,file,http,https,tcp,tls,udp");
        List<VideoOptionModel> list = new ArrayList<>();
        list.add(videoOptionModel);
        list.add(videoOptionModel1);
        list.add(videoOptionModel2);
        GSYVideoManager.instance().setOptionModelList(list)
---------------------------------------
播放输出如下log：
03-12 11:07:23.125 770-967/? E/WifiStateMachine: mWifiOnScanCount: 266
03-12 11:07:23.915 2247-2353/com.atguigu.android E/IJKMEDIA: https://pptv.com-h-pptv.com/share/57342f6b95854ad89e9c4088ab94adcf: Invalid data found when processing input
03-12 11:07:23.916 2247-2247/com.atguigu.android E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by CarGuo** [comment]
这是一个网页链接，如下图所示：

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/10770362/76484229-25a7b600-6454-11ea-82b4-0a0417d2f6dc.png">

**Comment by zouqunli** [comment]
楼主怎么解决的呢？
