### ISSUE TITLE
https TLS 1.2 过期了，jik怎么升到TLS1.3

### ISSUE THREAD

**Issue by pyp163** [CarGuo/GSYVideoPlayer#2594]
## 问题描述：
https TLS 1.2 过期了

## GSY依赖版本
implementation 'com.shuyu:gsyVideoPlayer-java:7.1.2'
    implementation 'com.shuyu:gsyVideoPlayer-armv7a:7.1.2'
    implementation 'com.shuyu:gsyVideoPlayer-arm64:7.1.2'
    implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.2'

## 问题log（如果有）
Suppressed: javax.net.ssl.SSLHandshakeException: Handshake failed
    			... 24 more
    		Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0xea7b6d40: Failure in SSL library, usually a protocol error
    error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (external/boringssl/src/ssl/s3_pkt.c:610 0xd0baa700:0x00000001)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
        			... 23 more
     Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0xea7b6d40: Failure in SSL library, usually a protocol error
    error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (external/boringssl/src/ssl/s3_pkt.c:610 0xd0baa700:0x00000001)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
        		... 23 more
     Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0xea7b6d40: Failure in SSL library, usually a protocol error
    error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (external/boringssl/src/ssl/s3_pkt.c:610 0xd0baa700:0x00000001)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
```

xxxxxxx

```

**Comment by CarGuo** [comment]
看首页编译教程，自己 fork 个 ijk 然后修改配置和源码。

**Comment by pyp163** [comment]
好的，谢谢

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/commit/5ea2021046c9cff2bd18e560d818a95162785d84
https://github.com/CarGuo/GSYVideoPlayer/commit/9e9fd896240413e7340331e151d00730b73b079e
已经升级 openssl 1.1.1w
