### ISSUE TITLE
ijk模式怎么忽略证书

### ISSUE THREAD

**Issue by Marik1225** [CarGuo/GSYVideoPlayer#2608]
#问题描述：
视频播放时 发生了这样的问题！

#问题机型/系统：
真机 三星S10 Android 10.0

#GSY依赖版本
 api 'com.shuyu:gsyVideoPlayer-java:6.0.3'
 api 'com.shuyu:gsyVideoPlayer-ex_so:6.0.3'

#Demo中的复现步骤
请问一下，怎么设置可以忽略证书？看过问题集锦了。。
#问题log
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android E/HttpProxyCacheDebuger: Error fetching info from https://momentfile-pre.im.trafficmanager.net:32000/moment/file/download?height=0&width=0&thumbnail=0&category=2&articleId=5e74937ff3bbb62ce48858d9&url=mN7tpjP8EwUxf%2FgXAZRQ2J1O4xRmHrZ2VNjxeIpzotoK0wCcFNpNLFCNjAjRPQsd
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err: javax.net.ssl.SSLPeerUnverifiedException: Hostname momentfile-pre.im.trafficmanager.net not verified:
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     certificate: sha1//uti5FyU351baMqnPp8HcJ/9VcU=
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     DN: CN=*.im.sasai.mobi,OU=IT,
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     subjectAltNames: [*.im.sasai.mobi]
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:1480)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:1415)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:1359)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:221)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:144)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:106)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:400)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:333)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:483)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:429)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:560)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at com.danikula.videocache.HttpUrlSource.openConnection(HttpUrlSource.java:164)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at com.danikula.videocache.HttpUrlSource.fetchContentInfo(HttpUrlSource.java:133)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at com.danikula.videocache.HttpUrlSource.getMime(HttpUrlSource.java:191)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at com.danikula.videocache.HttpProxyCache.newResponseHeaders(HttpProxyCache.java:60)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:40)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:230)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:51)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:332)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-03-20 19:55:15.971 22331-23124/com.gigaiot.sasa.android W/System.err:     at java.lang.Thread.run(Thread.java:919)
2020-03-20 19:55:15.972 22331-23124/com.gigaiot.sasa.android E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :2
2020-03-20 19:55:15.972 22331-23124/com.gigaiot.sasa.android I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2020-03-20 19:55:15.972 22331-23124/com.gigaiot.sasa.android I/System.out: (HTTPLog)-Static: isSBSettingEnabled false

**Comment by CarGuo** [comment]
ijk模式关闭 cache 就可以了

**Comment by CarGuo** [comment]
下个版本 cache 也支持忽略
