### ISSUE TITLE
IJK内核切换Exo2内核后播放视频出现问题 

### ISSUE THREAD

**Issue by ljchengx** [CarGuo/GSYVideoPlayer#2627]
## 问题描述：

华为的一台pad 分辨率1200*1920 
PlayerFactory.setPlayManager(Exo2PlayerManager.class);
切换Exo2内核后播放视频出现问题 加载不了视频 换成IJK内核可以
另一台华为pad是可以的 分辨率是1600*2560

## 问题机型/系统：

HUAWEI MON-W19 Android 7.0

## GSY依赖版本
‘com.shuyu:GSYVideoPlayer:6.0.1’

## Demo中的复现步骤

https://file.icve.com.cn/ssykt/515/511/80D7FFB19041308BBF3B84DF0A3DE0BF.mp4

这个是文件的预览地址

问题代码：(如果有)
```
 PlayerFactory.setPlayManager(Exo2PlayerManager.class);

```

## 问题log（如果有）

2020-03-28 16:45:59.070 20902-21303/com.zjy.ykt E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:450)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:437)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:929)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:506)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:566)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:156)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, video/avc, -1, null, [2160, 1440, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:437) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:929) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:506) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:566) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1909)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:453)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:427)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:929) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:506) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:566) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
2020-03-28 16:45:59.080 20902-20902/com.zjy.ykt E/VideoFragment.java: [ (VideoFragment.java:294)#OnPlayError ] [Ljava.lang.Object;@2be876c
2020-03-28 16:45:59.082 20902-21201/com.zjy.ykt E/EventLogger: playerFailed [0.90]
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:450)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:437)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:929)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:506)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:566)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:156)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, video/avc, -1, null, [2160, 1440, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:437) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:929) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:506) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:566) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1909)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:453)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:427)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:929) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:506) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:566) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 

xxxxxxx

```

**Comment by CarGuo** [comment]
我这边测试都可以播放，exo 下

Video: h264, 1 reference frame (avc1 / 0x31637661), yuv420p(left), 2160x1440, 0/1, 477 kb/s
Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 139 kb/s

看了下正常应该是都能播放的，除非是exo的硬解码在这台设备上不支持。

**Comment by ljchengx** [comment]
> 我这边测试都可以播放，exo下
> 
> 视频：h264、1个参考帧（avc1 / 0x31637661），yuv420p（左），2160x1440、0 / 1、477 kb / s
> 音频：aac（mp4a / 0x6134706D），48000 Hz，立体声，fltp，139 kb / s
> 
> 看了下正常应该是能够播放的，除非是exo的硬解码在这台设备上不支持。

是的 可能和这个设备有关系 我用了其他几个设备 如 小米Note3 另一台华为pad都是可以的。目前这样有啥方式能够兼容吗？

**Comment by CarGuo** [comment]
硬解码不支持的情况下就用软解呀，常见情况是这样的。

**Comment by ljchengx** [comment]
> 硬解码不支持的情况下就用软解呀，常见情况是这样的。

好的 没这样写过 不大懂具体的方案><

**Comment by CarGuo** [comment]
最简单就是播放失败的时候，提供一个软解播放的选项，选择后记录下来，以后都用软解吗

**Comment by ljchengx** [comment]
> 选择后记录下来

我刚去查了下 就是如何使用软解来播放不太明白 我看提供的GSYVideoType这个设置方式 好像不是这个内核的。

**Comment by CarGuo** [comment]
软解码就是 ffmpeg ，也就是对应 GSY 里面的 IJK 内核

**Comment by ljchengx** [comment]
> 软解码就是 ffmpeg ，也就是对应 GSY 里面的 IJK 内核

那就是说当播放失败后 重新切换下内核播放 大致这个逻辑吗？

**Comment by CarGuo** [comment]
是的，类似这样

**Comment by ljchengx** [comment]
> 是的，类似这样

好的  感谢您。
