### ISSUE TITLE
播放视频 403，其他手机上正常，部分设备上出现这个问题 求指教

### ISSUE THREAD

**Issue by tinoPeng** [CarGuo/GSYVideoPlayer#2669]
com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:844)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:831)
04-16 18:39:58.808 29869-30076/com.jsxfedu.jsbook_android E/EventLogger: playerFailed [4.15]
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:349)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:147)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:844)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:831)

**Comment by tinoPeng** [comment]
用的是这种设置    PlayerFactory.setPlayManager(Exo2PlayerManager.class);
        binding.videoPlay.setUp(videoUrl,false,"");

**Comment by tinoPeng** [comment]
在华为pad上，android 5.1的系统。播放这个403的错误提示

**Comment by CarGuo** [comment]
请提供测试 URL，可以尝试设置 SSL 忽略 ExoSourceManager.setSkipSSLChain(true);

**Comment by tinoPeng** [comment]
> 请提供测试 URL，可以尝试设置 SSL 忽略 ExoSourceManager.setSkipSSLChain(true);
我这边一开始没有配置SSL忽略，所有设备上都不能播放。然后配置了SSL忽略之后，就只有那个华为pad上播放不了，之后通过查找，发现是url地址中存在中文字府导致的，后来将中文字符转Uncode编码后可以播放了。但是纳闷的是带有中文字符的url地址有的设备上可以播放，有的设备上不识别。不知道是不是个别手机系统导致的

**Comment by CarGuo** [comment]
明白了，这个确实遇到过，所以我们规范的时候一样要求不能有中文
