### ISSUE TITLE
exo部分m3u8不能播放 ijk可以

### ISSUE THREAD

**Issue by balaYYYYYYYY** [CarGuo/GSYVideoPlayer#2773]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

部分m3u8不能播放 ijk可以播放但是ijk播放有时候会缓冲卡死 测试url：http://v.qdetyy.com/dianying/69484/leishen2/leishen2_720.m3u8?k=8b2b02d17fb81ee8&t=1591852194

## 问题机型/系统：

例如 真机 一加7tpro

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.4'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

2020-06-11 13:58:21.900 14354-14459/com.example.gsyvideoplayer E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at tv.danmaku.ijk.media.exo2.source.GSYDefaultHttpDataSource.open(GSYDefaultHttpDataSource.java:327)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:170)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2020-06-11 13:58:21.908 14354-14354/com.example.gsyvideoplayer E/EventLogger: playerFailed [3.27]
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:394)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at tv.danmaku.ijk.media.exo2.source.GSYDefaultHttpDataSource.open(GSYDefaultHttpDataSource.java:327)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:170)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

xxxxxxx

```

**Comment by CarGuo** [comment]
setOverrideExtension("m3u8");

**Comment by balaYYYYYYYY** [comment]
> setOverrideExtension("m3u8");

不行 设置了还是一样的错误 用的你demo里面的DetailExoListPlayer

**Comment by balaYYYYYYYY** [comment]
> setOverrideExtension("m3u8");

刚刚爬的那个测试url可能过期了 在爬了一次http://v.qdetyy.com/dianying/69484/leishen2/leishen2_720.m3u8?k=e0e77b07b0812dc0&t=1591866044

**Comment by CarGuo** [comment]
看起来不像是播放器原因，而是流链接本书有问题

**Comment by balaYYYYYYYY** [comment]
> 看起来不像是播放器原因，而是流链接本书有问题

但是ijk内核就可以播 是视频的编码格式问题吗？

**Comment by CarGuo** [comment]
ijk内核播放不了吧，400

**Comment by balaYYYYYYYY** [comment]
> ijk内核播放不了吧，400

能把 我又爬了一次现在url是http://v.qdetyy.com/dianying/69484/leishen2/leishen2_720.m3u8?k=2afc0157d4b508af&t=1591869113  我这个直接塞进simpleplayer里就能播 用的ijk内核

**Comment by CarGuo** [comment]
2020-06-11 16:04:26.054 22967-23028/com.example.gsyvideoplayer E/IJKMEDIA: http://v.qdetyy.com/dianying/69484/leishen2/leishen2_720.m3u8?k=2afc0157d4b508af&t=1591869113: Server returned 400 Bad Request

**Comment by balaYYYYYYYY** [comment]
> 2020-06-11 16:04:26.054 22967-23028/com.example.gsyvideoplayer E/IJKMEDIA: http://v.qdetyy.com/dianying/69484/leishen2/leishen2_720.m3u8?k=2afc0157d4b508af&t=1591869113: Server returned 400 Bad Request

400是不是网络问题 试试流量？
2020-06-11 16:08:47.176 11187-11393/com.example.gsyvideoplayer D/IJKMEDIA: Opening 'http://v.qdetyy.com/dianying/69484/leishen2/leishen2_720.m3u8?k=2afc0157d4b508af&t=1591869113' for reading
2020-06-11 16:08:47.176 11187-11393/com.example.gsyvideoplayer D/IJKMEDIA: Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto,httpproxy'
我这是这样的

**Comment by CarGuo** [comment]
主要 exo 不能播放，要看是 302 导致的，还是编码导致的，还是https导致的

**Comment by balaYYYYYYYY** [comment]
> 主要 exo 不能播放，要看是 302 导致的，还是编码导致的，还是https导致的

我爬了其他视频 发现有些能播有些不能 应该就是编码导致的

**Comment by CarGuo** [comment]
exo 使用的是 mediacodec ，如果不支持那也没啥办法的
