### ISSUE TITLE
本地视频拖动播放oom，有试过issue中提到内存泄漏相关方法，大佬们帮忙看一下

### ISSUE THREAD

**Issue by sweet-guy** [CarGuo/GSYVideoPlayer#2789]
## 问题描述：

第一次播放本地视频有时会oom，但是第二次播放视频发生oom的几率更大，有试过issue中提到内存泄漏相关方法

## 问题机型/系统：

手里机型都会有问题

## GSY依赖版本

最新 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.4'`

## Demo中的复现步骤

gsy播放器播放本地视频

```

## 问题log（如果有）

```
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 0 free bytes and -1824B until OOM, max allowed footprint 402655008, growth limit 402653184
        at libcore.io.IoBridge.closeAndSignalBlockedThreads(IoBridge.java:242)
        at java.io.RandomAccessFile.close(RandomAccessFile.java:706)
        at com.google.android.exoplayer2.upstream.FileDataSource.close(FileDataSource.java:158)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.close(DefaultDataSource.java:200)
        at com.google.android.exoplayer2.upstream.StatsDataSource.close(StatsDataSource.java:111)
        at com.google.android.exoplayer2.util.Util.closeQuietly(Util.java:426)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:995)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:784) 

```

**Comment by CarGuo** [comment]
看起来像是播放本地大文件？理论上应该不会呀 FileDataSource

**Comment by sweet-guy** [comment]
感谢回复，这个是本地视频时长最多为五分钟，来回拖动播放会出现这个问题

**Comment by sweet-guy** [comment]
本地视频使用ijk 播放没问题   exo播放在线视频    Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [540, 960, 29.816275], [-1, -1])

**Comment by CarGuo** [comment]
麻烦提供下 exo 下不能播放的视频 url。

**Comment by sweet-guy** [comment]
谢谢大佬，我这边本地判断视频链接是否为http，http开头就使用exo 播放，本地视频使用ijk模式播放，现在的解决方案还没有复现上边的问题。
