### ISSUE TITLE
exo释放问题

### ISSUE THREAD

**Issue by sweet-guy** [CarGuo/GSYVideoPlayer#2794]
## 问题描述：

多进出几次界面导致无法播放，目前应该是exo没有释放问题

## 问题机型/系统：

手机都复现

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

问题代码：(如果有)
```
在一个viewpager中做图片和视频混合播放，下边是释放代码
     GSYVideoManager.releaseAllVideos();
     videoPlayer.release();
```

## 问题log（如果有）

```

 com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1080, 1920, 28.777905], [-1, -1])
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:561)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1249)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:756)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:810)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:709)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:232)
        at android.os.HandlerThread.run(HandlerThread.java:65)

```

**Comment by CarGuo** [comment]
有可能，多次频繁操作是会有这种情况的，不建议频繁播放和释放····

**Comment by sweet-guy** [comment]
大佬，我这多个地方有播放，指点一下

**Comment by CarGuo** [comment]
多个地方播放？同时播放还是？你可以参考 Demo 中多任务播放的例子，用两个内核来做管理，在 Manager 层每次用一个播放一个备用，当切换新新的播放时，旧的内核 release 但是用备用的去播放，这样循环往复。

如果是默认当个内核的模式下，你需要在播放前确定release 已经结束，比如自己做个延时或者标记为

**Comment by wangrunxiang** [comment]
@CarGuo 同样遇到这个问题，频繁切换不同的集，应该怎么解决？

**Comment by wangrunxiang** [comment]
@CarGuo 这个release指的是上层的哪个接口？

**Comment by Domlaa** [comment]
> 有可能，多次频繁操作是会有这种情况的，不建议频繁播放和释放····

感觉像是没被释放引起的，播放二十左右个视频之后，全部的视频就都不能播放了。必须重新进入app。请问您有没有什么好的解决方法呢
