### ISSUE TITLE
部分视频播放不了

### ISSUE THREAD

**Issue by wangrunxiang** [CarGuo/GSYVideoPlayer#2812]
## 问题描述：

项目中有部分视频播放不了，神奇的是，如果这个视频播放不了的话，去其他播放器播放一次，然后用GSY就能播放了，日志如下

## 问题机型/系统：

小米mix3

## GSY依赖版本

6.0.3

## 问题log（如果有）

```
2020-07-01 15:10:28.878 26198-27273/com.badambiz.kinobazar.zvod.dev E/ExoPlayerImplInternal: Source error.
    java.io.IOException: javax.crypto.IllegalBlockSizeException: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH
        at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:133)
        at javax.crypto.CipherInputStream.read(CipherInputStream.java:249)
        at com.google.android.exoplayer2.source.hls.Aes128DataSource.read(Aes128DataSource.java:100)
        at com.google.android.exoplayer2.upstream.StatsDataSource.read(StatsDataSource.java:91)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:260)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.advancePeekPosition(DefaultExtractorInput.java:135)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:116)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:126)
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.sniff(TsExtractor.java:189)
        at com.google.android.exoplayer2.source.hls.DefaultHlsExtractorFactory.sniffQuietly(DefaultHlsExtractorFactory.java:264)
        at com.google.android.exoplayer2.source.hls.DefaultHlsExtractorFactory.createExtractor(DefaultHlsExtractorFactory.java:110)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:275)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:246)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:195)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: javax.crypto.IllegalBlockSizeException: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH
        at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
        at com.android.org.conscrypt.OpenSSLCipher$EVP_CIPHER.doFinalInternal(OpenSSLCipher.java:602)
        at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:400)
        at javax.crypto.Cipher.doFinal(Cipher.java:2002)
        at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:130)
        at javax.crypto.CipherInputStream.read(CipherInputStream.java:249) 
        at com.google.android.exoplayer2.source.hls.Aes128DataSource.read(Aes128DataSource.java:100) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.read(StatsDataSource.java:91) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:260) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.advancePeekPosition(DefaultExtractorInput.java:135) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:116) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:126) 
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.sniff(TsExtractor.java:189) 
        at com.google.android.exoplayer2.source.hls.DefaultHlsExtractorFactory.sniffQuietly(DefaultHlsExtractorFactory.java:264) 
        at com.google.android.exoplayer2.source.hls.DefaultHlsExtractorFactory.createExtractor(DefaultHlsExtractorFactory.java:110) 
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:275) 
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:246) 
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:195) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
2020-07-01 15:10:28.893 26198-26198/com.badambiz.kinobazar.zvod.dev E/EventLogger: playerFailed [4.86]
    com.google.android.exoplayer2.ExoPlaybackException: java.io.IOException: javax.crypto.IllegalBlockSizeException: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:351)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.io.IOException: javax.crypto.IllegalBlockSizeException: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH
        at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:133)
        at javax.crypto.CipherInputStream.read(CipherInputStream.java:249)
        at com.google.android.exoplayer2.source.hls.Aes128DataSource.read(Aes128DataSource.java:100)
        at com.google.android.exoplayer2.upstream.StatsDataSource.read(StatsDataSource.java:91)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:260)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.advancePeekPosition(DefaultExtractorInput.java:135)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:116)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:126)
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.sniff(TsExtractor.java:189)
        at com.google.android.exoplayer2.source.hls.DefaultHlsExtractorFactory.sniffQuietly(DefaultHlsExtractorFactory.java:264)
        at com.google.android.exoplayer2.source.hls.DefaultHlsExtractorFactory.createExtractor(DefaultHlsExtractorFactory.java:110)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:275)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:246)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:195)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: javax.crypto.IllegalBlockSizeException: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH
        at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
        at com.android.org.conscrypt.OpenSSLCipher$EVP_CIPHER.doFinalInternal(OpenSSLCipher.java:602)
        at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:400)
        at javax.crypto.Cipher.doFinal(Cipher.java:2002)
        at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:130)
        at javax.crypto.CipherInputStream.read(CipherInputStream.java:249) 
        at com.google.android.exoplayer2.source.hls.Aes128DataSource.read(Aes128DataSource.java:100) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.read(StatsDataSource.java:91) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:260) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.advancePeekPosition(DefaultExtractorInput.java:135) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:116) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.peekFully(DefaultExtractorInput.java:126) 
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.sniff(TsExtractor.java:189) 
        at com.google.android.exoplayer2.source.hls.DefaultHlsExtractorFactory.sniffQuietly(DefaultHlsExtractorFactory.java:264) 
        at com.google.android.exoplayer2.source.hls.DefaultHlsExtractorFactory.createExtractor(DefaultHlsExtractorFactory.java:110) 
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:275) 
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:246) 
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:195) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 

```

**Comment by CarGuo** [comment]
如果可以请提供测试链接

**Comment by wangrunxiang** [comment]
但是我们的连接有加密过，要用我们的解密方法

**Comment by wangrunxiang** [comment]
@CarGuo 这个日志代表的是什么意思？

**Comment by wangrunxiang** [comment]
我们是拷了一个OkHttpDataSource，然后修改了一下里面的open方法来做解密的方式

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYVideoPlayer/issues/2803

https://github.com/CarGuo/GSYVideoPlayer/issues/2557
