### ISSUE TITLE
顺序播放几次后 黑屏了

### ISSUE THREAD

**Issue by CleverSJX** [CarGuo/GSYVideoPlayer#2819]
## 问题描述：

顺序播放视频 在onAutoCompletion中设置新的文件 setup,startPlayLogic
播放几次后 黑屏了

## 问题机型/系统：

真机 小米盒子MiBOX3/5.1.1

## GSY依赖版本
```
implementation 'com.shuyu:gsyVideoPlayer-java:7.1.4'
implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.4'
implementation 'com.shuyu:gsyVideoPlayer-ex_so:7.1.4'
```

## 问题log（如果有）

```
07-06 12:46:19.567 5454-6942/com.longjing.debug E/IJKMEDIA: configure acodec:0x100df2 format:0x100d5e: surface:0x100de2
07-06 12:46:19.567 5454-6944/com.longjing.debug E/ACodec: [OMX.amlogic.avc.decoder.awesome] storeMetaDataInBuffers failed w/ err -2147483648
07-06 12:46:19.569 5454-6942/com.longjing.debug D/IJKMEDIA: SDL_AMediaCodecJava_start
07-06 12:46:19.571 5454-6944/com.longjing.debug W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 9 failed: -1010
07-06 12:46:19.571 5454-6944/com.longjing.debug W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 8 failed: -1010
07-06 12:46:19.572 5454-6944/com.longjing.debug W/ACodec: [OMX.amlogic.avc.decoder.awesome] setting nBufferCountActual to 7 failed: -1010
07-06 12:46:19.581 5454-6944/com.longjing.debug E/BufferQueueProducer: [unnamed-5454-11] dequeueBuffer: createGraphicBuffer failed
07-06 12:46:19.581 5454-6944/com.longjing.debug E/ACodec: dequeueBuffer failed: Operation not permitted (1)
07-06 12:46:19.581 5454-6944/com.longjing.debug E/ACodec: Failed to allocate buffers after transitioning to IDLE state (error 0xffffffff)
07-06 12:46:19.581 5454-6944/com.longjing.debug E/ACodec: signalError(omxError 0x80001001, internalError -1)
07-06 12:46:19.589 5454-6943/com.longjing.debug E/MediaCodec: Codec reported err 0xffffffff, actionCode 0, while in state 5
07-06 12:46:19.601 5454-6942/com.longjing.debug W/System.err: android.media.MediaCodec$CodecException: start failed
07-06 12:46:19.603 5454-6942/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_start(Native Method)
07-06 12:46:19.603 5454-6942/com.longjing.debug W/System.err:     at android.media.MediaCodec.start(MediaCodec.java:616)
07-06 12:46:19.603 5454-6942/com.longjing.debug E/IJKMEDIA: SDL_AMediaCodecJava_start: start failed
07-06 12:46:19.603 5454-6942/com.longjing.debug E/IJKMEDIA: reconfigure_codec_l:SDL_AMediaCodec_start: failed
07-06 12:46:19.603 5454-6942/com.longjing.debug E/IJKMEDIA: feed_input_buffer: reconfigure_codec failed
07-06 12:46:19.604 5454-6941/com.longjing.debug W/System.err: java.lang.IllegalStateException
07-06 12:46:19.604 5454-6941/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
07-06 12:46:19.604 5454-6941/com.longjing.debug W/System.err:     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1037)
07-06 12:46:19.604 5454-6941/com.longjing.debug I/IJKMEDIA: SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
07-06 12:46:19.604 5454-6942/com.longjing.debug W/System.err: java.lang.IllegalStateException
07-06 12:46:19.604 5454-6942/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
07-06 12:46:19.604 5454-6942/com.longjing.debug W/System.err:     at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:987)
07-06 12:46:19.604 5454-6942/com.longjing.debug E/IJKMEDIA: SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
07-06 12:46:19.604 5454-6942/com.longjing.debug W/System.err: java.lang.IllegalStateException
07-06 12:46:19.604 5454-6942/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
07-06 12:46:19.604 5454-6942/com.longjing.debug W/System.err:     at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:987)
07-06 12:46:19.604 5454-6942/com.longjing.debug E/IJKMEDIA: SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
07-06 12:46:19.604 5454-6942/com.longjing.debug W/System.err: java.lang.IllegalStateException
07-06 12:46:19.604 5454-6942/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
07-06 12:46:19.604 5454-6942/com.longjing.debug W/System.err:     at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:987)
07-06 12:46:19.604 5454-6942/com.longjing.debug E/IJKMEDIA: SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
07-06 12:46:19.604 5454-6942/com.longjing.debug W/System.err: java.lang.IllegalStateException
07-06 12:46:19.604 5454-6942/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
07-06 12:46:19.604 5454-6942/com.longjing.debug W/System.err:     at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:987)
07-06 12:46:19.604 5454-6942/com.longjing.debug E/IJKMEDIA: SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
07-06 12:46:19.605 5454-6942/com.longjing.debug W/System.err: java.lang.IllegalStateException
07-06 12:46:19.605 5454-6942/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
07-06 12:46:19.605 5454-6942/com.longjing.debug W/System.err:     at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:987)
07-06 12:46:19.605 5454-6942/com.longjing.debug E/IJKMEDIA: SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
07-06 12:46:19.605 5454-6942/com.longjing.debug W/System.err: java.lang.IllegalStateException
07-06 12:46:19.605 5454-6942/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
07-06 12:46:19.605 5454-6942/com.longjing.debug W/System.err:     at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:987)
07-06 12:46:19.605 5454-6942/com.longjing.debug E/IJKMEDIA: SDL_AMediaCodecJava_dequeueInputBuffer: dequeueInputBuffer failed
07-06 12:46:19.605 5454-6942/com.longjing.debug E/IJKMEDIA: feed_input_buffer: SDL_AMediaCodec_getInputBuffer failed
07-06 12:46:19.605 5454-6942/com.longjing.debug I/IJKMEDIA: MediaCodec: enqueue_thread_func: exit: -1
07-06 12:46:19.605 5454-6942/com.longjing.debug I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [6942]
07-06 12:46:20.604 5454-6941/com.longjing.debug W/System.err: java.lang.IllegalStateException
07-06 12:46:20.604 5454-6941/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
07-06 12:46:20.604 5454-6941/com.longjing.debug W/System.err:     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1037)
07-06 12:46:20.604 5454-6941/com.longjing.debug I/IJKMEDIA: SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
07-06 12:46:21.605 5454-6941/com.longjing.debug W/System.err: java.lang.IllegalStateException
07-06 12:46:21.605 5454-6941/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
07-06 12:46:21.605 5454-6941/com.longjing.debug W/System.err:     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1037)
07-06 12:46:21.605 5454-6941/com.longjing.debug I/IJKMEDIA: SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
07-06 12:46:22.605 5454-6941/com.longjing.debug W/System.err: java.lang.IllegalStateException
07-06 12:46:22.605 5454-6941/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
07-06 12:46:22.605 5454-6941/com.longjing.debug W/System.err:     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1037)
07-06 12:46:22.605 5454-6941/com.longjing.debug I/IJKMEDIA: SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
07-06 12:46:23.606 5454-6941/com.longjing.debug W/System.err: java.lang.IllegalStateException
07-06 12:46:23.606 5454-6941/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
07-06 12:46:23.606 5454-6941/com.longjing.debug W/System.err:     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1037)
07-06 12:46:23.606 5454-6941/com.longjing.debug I/IJKMEDIA: SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
07-06 12:46:24.606 5454-6941/com.longjing.debug W/System.err: java.lang.IllegalStateException
07-06 12:46:24.606 5454-6941/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
07-06 12:46:24.606 5454-6941/com.longjing.debug W/System.err:     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1037)
07-06 12:46:24.606 5454-6941/com.longjing.debug I/IJKMEDIA: SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
07-06 12:46:25.607 5454-6941/com.longjing.debug W/System.err: java.lang.IllegalStateException
07-06 12:46:25.607 5454-6941/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
07-06 12:46:25.607 5454-6941/com.longjing.debug W/System.err:     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1037)
07-06 12:46:25.607 5454-6941/com.longjing.debug I/IJKMEDIA: SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
07-06 12:46:26.607 5454-6941/com.longjing.debug W/System.err: java.lang.IllegalStateException
07-06 12:46:26.607 5454-6941/com.longjing.debug W/System.err:     at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
07-06 12:46:26.607 5454-6941/com.longjing.debug W/System.err:     at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1037)
07-06 12:46:26.607 5454-6941/com.longjing.debug I/IJKMEDIA: SDL_AMediaCodecJava_dequeueOutputBuffer: Exception
```

**Comment by CarGuo** [comment]
请测试 Demo 的 DetailListPlayer 或者 DetailExoListPlayer

**Comment by CleverSJX** [comment]
看样子是 IJK 硬解码的问题

**Comment by CarGuo** [comment]
ijk 的硬解码就请无视吧～～
