### ISSUE TITLE
暂停时全屏，重载startWindowFullscreen

### ISSUE THREAD

**Issue by wangrunxiang** [CarGuo/GSYVideoPlayer#2834]
## 问题描述：

暂停时全屏，重载startWindowFullscreen，调用super.startWindowFullscreen(context, actionBar, statusBar)拿到player实例，这一步抛出了角标越界异常，但是正在播放的时候却不会，我去跟踪代码，没跟踪出来是啥情况，跟到cloneParams就跟不下去了。有可能是什么原因导致的异常？

## 问题log（如果有）

```

kotlin.TypeCastException: null cannot be cast to non-null type com.badambiz.module_play_page.KinoVideoPlayer
        at com.badambiz.module_play_page.KinoVideoPlayer.startWindowFullscreen(KinoVideoPlayer.kt:383)
        at com.shuyu.gsyvideoplayer.GSYBaseActivityDetail.showFull(GSYBaseActivityDetail.java:66)
        at com.shuyu.gsyvideoplayer.GSYBaseActivityDetail$1.onClick(GSYBaseActivityDetail.java:43)
        at android.view.View.performClick(View.java:7161)
        at android.view.View.performClickInternal(View.java:7138)
        at android.view.View.access$3500(View.java:811)
        at android.view.View$PerformClick.run(View.java:27419)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

**Comment by CarGuo** [comment]
null cannot be cast to non-null  ？？？

**Comment by wangrunxiang** [comment]
这个是因为super.startWindowFullscreen(context, actionBar, statusBar)里面抛出来异常被捕获了，然后返回值为null，我们代码有as，强转的时候，null不能强转才报的这个

**Comment by wangrunxiang** [comment]
我跟踪到的是GSYBaseVideoPlayer的startWindowFullscreen方法里面调用了cloneParams，最终的角标越界异常是cloneParams抛出来的

**Comment by CarGuo** [comment]
不是很理解的问题，cloneParams 就是一个 to 到 form 的属性赋值而已

**Comment by wangrunxiang** [comment]
我也觉得奇怪，所以才说跟不下去

**Comment by wangrunxiang** [comment]
![Uploading image.png…]()
有没有可能是哪里设置不对导致这个方法抛出了异常

**Comment by CarGuo** [comment]
所以这个只能你自己debug下哪个位置出现的问题了

**Comment by wangrunxiang** [comment]
![WechatIMG1](https://user-images.githubusercontent.com/10829860/87414981-1c477980-c5ff-11ea-828f-e55b17cd651d.png)
有没有可能是哪里设置不对导致这里跑出异常

**Comment by wangrunxiang** [comment]
我再看看

**Comment by wangrunxiang** [comment]
最终查单是因为复写了changeUiToPauseShow，最终异常是changeUiToPauseShow抛出来的
