### ISSUE TITLE
raw视频无法播放

### ISSUE THREAD

**Issue by Ysrfengnull** [CarGuo/GSYVideoPlayer#2896]
## 问题描述：
下载此视频 https://test-static-public-log56-com.oss-cn-hangzhou.aliyuncs.com/kydd_app/video/login_video.mp4
放到demo  raw 目录 替换 test.mp4

1.无法播放此视频
2.视频链接在线播放没问题
3.ios可以本地播放

**Comment by Ysrfengnull** [comment]
> ## 问题描述：
> 下载此视频 https://test-static-public-log56-com.oss-cn-hangzhou.aliyuncs.com/kydd_app/video/login_video.mp4
> 放到demo raw 目录 替换 test.mp4
> 
> 1.无法播放此视频
> 2.视频链接在线播放没问题
3.ios也可以本地播放

**Comment by CarGuo** [comment]
PlayerFactory.setPlayManager(Exo2PlayerManager.class);

**Comment by Ysrfengnull** [comment]
试了还是打不开

**Comment by hxysakura** [comment]
Caused by: android.content.res.Resources$NotFoundException: File res/raw/introdute.mp4 from drawable resource ID #0x7f0f0000
        at android.content.res.ResourcesImpl.openRawResourceFd(ResourcesImpl.java:316)
        at android.content.res.Resources.openRawResourceFd(Resources.java:1293)
        at com.google.android.exoplayer2.upstream.RawResourceDataSource.open(RawResourceDataSource.java:136)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:199)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
        at android.content.res.AssetManager.openNonAssetFdNative(Native Method)
        at android.content.res.AssetManager.openNonAssetFd(AssetManager.java:487)
        at android.content.res.ResourcesImpl.openRawResourceFd(ResourcesImpl.java:314)
        at android.content.res.Resources.openRawResourceFd(Resources.java:1293) 
        at com.google.android.exoplayer2.upstream.RawResourceDataSource.open(RawResourceDataSource.java:136) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:199) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
2020-12-02 13:08:34.271 16329-16329/com.tes.displayboard D/EventLogger: load


概率出现，多播放几次，就会出现这个错误
