### ISSUE TITLE
ExoPlaer 播放本地m3u8失败

### ISSUE THREAD

**Issue by guangmingxiong9999** [CarGuo/GSYVideoPlayer#2897]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

Exo内核播放m3u8文件失败报错 FileNotFoundException，但是ijk内核可以播放，在demo中也能复现
 

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
 

## 问题log（如果有）

 Caused by: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /emulated/0/Android/data/xxx/files/DCIM/image/abc.m3u8: open failed: ENOENT (No such file or directory)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:73)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:257)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:170)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by CarGuo** [comment]
这个得你自己调试下吧，比如改为content协议

**Comment by Ysrfengnull** [comment]
我也是同样问题，视频在线可以播放，本地播放出错

**Comment by Ysrfengnull** [comment]
> 这个得你自己调试下吧，比如改为content协议

#2896 试了你说的，还是打不开

**Comment by guangmingxiong9999** [comment]
@Ysrfengnull 你改成uri模式的试下
Uri uri=Uri.fromFile(new File("/storage/emulated/0/Android/data/xxx/files/DCIM/image/abc.m3u8"));
String path=uri.getPath();
这种普通m3u8可以了，但我的加密，还在看怎么做

**Comment by Ysrfengnull** [comment]
> @Ysrfengnull 你改成uri模式的试下
> Uri uri=Uri.fromFile(new File("/storage/emulated/0/Android/data/xxx/files/DCIM/image/abc.m3u8"));
> String path=uri.getPath();
> 这种普通m3u8可以了，但我的加密，还在看怎么做

我的是首页登录，复制到存储有点慢，不想用这种方式
