### ISSUE TITLE
Exo模式播放m3u8失败 

### ISSUE THREAD

**Issue by guangmingxiong9999** [CarGuo/GSYVideoPlayer#2914]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

 Exo模式播放m3u8失败 
这个视频在其他手机播放没问题，这个不行，
而且这个手机播放其他视频页没发现有问题
链接 http://xkbvideo.xuekuibang.com/20200719/hd/1595160300667c2fb/3e5128aaf6194f6890.m3u8

## 问题机型/系统：

Vivo V1930A 

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.2'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）
 
 2020-08-18 16:42:19.018 5244-6692/com.xkb.education E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(0, null, null, video/avc, avc1.4D4032, -1, null, [2736, 1824, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:512)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1186)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:636)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:733)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:644)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(0, null, null, video/avc, avc1.4D4032, -1, null, [2736, 1824, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:786)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:510)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1186) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:636) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:733) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:644) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:575) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:326) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 

![image](https://user-images.githubusercontent.com/19978284/90491462-88734b00-e172-11ea-90b2-4cc4850fe25e.png)

**Comment by CarGuo** [comment]
我这边测试正常，看了是 crypto 的 m3u8 ，推测和机器的 Cipher.getInstance("AES/CBC/PKCS7Padding"); 加解密有关系。 I have not idea

**Comment by guangmingxiong9999** [comment]
因为是同一批次的，其他都可以，是不是像这个http://www.cocoachina.com/articles/35236 视频本身码率有问题

**Comment by CarGuo** [comment]
看起来像是这个视频的 crypto 有关系，我这边测试几台机器都是正常的

**Comment by guangmingxiong9999** [comment]
视频分辨率问题，视频2736×1824  手机1544×720 视频重新压缩为1920x1080可以了
