### ISSUE TITLE
NullPointerException on MediaSource

### ISSUE THREAD

**Issue by ixiDev** [CarGuo/GSYVideoPlayer#2961]
Hi , Thanks for this awesome library .
I got a null pointer exception when i try to use exo player ExoMediaSourceInterceptListener

**Here is my code** 

```
class App : MultiDexApplication() {
    override fun onCreate() {
        super.onCreate()
        PlayerFactory.setPlayManager(Exo2PlayerManager::class.java)
        ExoSourceManager.setExoMediaSourceInterceptListener(object : ExoMediaSourceInterceptListener {
            override fun getMediaSource(dataSource: String, preview: Boolean, cacheEnable: Boolean, isLooping: Boolean, cacheDir: File): MediaSource {
                val dataSourceFactory: DataSource.Factory = DefaultHttpDataSourceFactory(
                        getString(R.string.app_name)
                )
                return SsMediaSource.Factory(dataSourceFactory)
                        .createMediaSource(dataSource.toUri())

            }

            override fun getHttpDataSourceFactory(userAgent: String?, listener: TransferListener?,
                                                  connectTimeoutMillis: Int, readTimeoutMillis: Int,
                                                  allowCrossProtocolRedirects: Boolean): HttpDataSource.BaseFactory {

                return DefaultHttpDataSourceFactory(getString(R.string.app_name))
            }
        })

    }
}
```

**Here is log  message** 

```
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.android.exoplayer2.source.MediaSource.addEventListener(android.os.Handler, com.google.android.exoplayer2.source.MediaSourceEventListener)' on a null object reference
        at com.google.android.exoplayer2.SimpleExoPlayer.prepare(SimpleExoPlayer.java:1189)
        at com.google.android.exoplayer2.SimpleExoPlayer.prepare(SimpleExoPlayer.java:1178)
        at tv.danmaku.ijk.media.exo2.IjkExo2MediaPlayer$1.run(IjkExo2MediaPlayer.java:375)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6826)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
2020-09-15 23:22:00.289 24397-24397/com.example.iptv I/Process: Sending signal. PID: 24397 SIG: 9

```

**Comment by CarGuo** [comment]
I work well in demo ，you  can refer to the getMediaSource method of ExoSourceManager

**Comment by geeklx** [comment]
我也遇到了demo正常，但是到项目就不行，写了好几个demo都是null 大佬怎么回事
