### ISSUE TITLE
Fragment添加视频报错

### ISSUE THREAD

**Issue by wangpingtaohn** [CarGuo/GSYVideoPlayer#3002]
错误log如下：
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5099)
        at android.view.ViewGroup.addView(ViewGroup.java:4930)
        at android.view.ViewGroup.addView(ViewGroup.java:4870)
        at android.view.ViewGroup.addView(ViewGroup.java:4843)
        at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.resolveThumbImage(GSYVideoControlView.java:1005)
        at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.setThumbImageView(GSYVideoControlView.java:1168)
        at com.shuyu.gsyvideoplayer.builder.GSYVideoOptionBuilder.build(GSYVideoOptionBuilder.java:591)
        at com.shuyu.gsyvideoplayer.builder.GSYVideoOptionBuilder.build(GSYVideoOptionBuilder.java:581)

我的页面就一个简单的Activity+一个Fragment，按照教程(https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/USE.md)配置:

**Comment by CarGuo** [comment]
参考 demo
