### ISSUE TITLE
ExoPlaybackException: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by bichao1986** [CarGuo/GSYVideoPlayer#3014]
## 问题描述：
首先致敬作者，感谢分享代码。
现在问题是这样的，我这边现在是TV上的开发。
逻辑是这样的，我们自己通过移动设备把视频往服务器上切片上传，然后在服务器上通过RandomAccessFile的方法存储成一个视频文件，同时在文件没有全完写完的情况下，生成一个链接给到tv，然后tv通过这个链接去播放，也就是说，这个视频文件边写入数据，边提供给tv的exo播放器播放，这个时候就报错了，下面是报错信息：
10-23 21:24:36.634 2424-4881/com.savor.ads E/ExoPlayerImplInternal: Renderer error: index=0, type=video, format=Format(1, null, null, video/avc, null, -1, null, [2336, 1080, 29.423597], [-1, -1]), rendererSupport=YES
    com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:732)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1515)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:718)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
10-23 21:24:36.634 2424-4881/com.savor.ads E/ExoPlayerImplInternal: Disable failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:1948)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:773)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.flushOrReleaseCodec(MediaCodecVideoRenderer.java:724)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:634)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:569)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:168)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1136)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:891)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:850)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:382)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
10-23 21:24:36.647 2424-4884/com.savor.ads E/Surface: getSlotFromBufferLocked: unknown buffer: 0xab4739b0
10-23 21:24:36.647 2424-4884/com.savor.ads E/Surface: getSlotFromBufferLocked: unknown buffer: 0xab365f48
10-23 21:24:36.690 2424-4881/com.savor.ads E/ExoPlayerImplInternal: Reset failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:1901)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:668)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:714)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onReset(MediaCodecRenderer.java:641)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onReset(MediaCodecVideoRenderer.java:578)
        at com.google.android.exoplayer2.BaseRenderer.reset(BaseRenderer.java:175)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:900)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:850)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:382)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
10-23 21:24:36.695 2424-2424/com.savor.ads E/EventLogger: playerFailed [0.47]
    com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:732)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1515)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:718)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
10-23 21:24:36.696 2424-2424/com.savor.ads E/SetTopBox:GGVideoPlayer.onError(L:149): GGVideoPlayer onError what = 1 extra = 1 244854821

## 问题机型/系统：

TV
如果文件停止写入，虽然这个视频是不完整的，是可以播放的。因为视频文件必须是在边存储边给播放器提供url的情况下才会报错，所以没办法给您这边提供一个测试的链接，抱歉

**Comment by CarGuo** [comment]
为什么我觉得你说的场景是hls直播

**Comment by bichao1986** [comment]
> 为什么我觉得你说的场景是hls直播

意思可能差不多吧，现在我用的是Exo2的内核，请问是否需要切换到其他的试一试？因为Exo2的内核不是使用的FFmpeg

**Comment by CarGuo** [comment]
exo 也是支持 hls 的直播的， 但是你这种场景我还真不好说，可能不是标准协议的原因

**Comment by bichao1986** [comment]
> exo 也是支持 hls 的直播的， 但是你这种场景我还真不好说，可能不是标准协议的原因

请问是否可以给提供一些思路或者我这边怎么去做一些处理？感谢感谢

**Comment by bichao1986** [comment]
我这边换成了IjkPlayer的内核，可以正常播放了,感谢作者

**Comment by CarGuo** [comment]
hls 主要你要看 .hls 下的包，在做 prase 的时候，有什么判断兼容

**Comment by fkl12138** [comment]
我也出现了你这问题 ，我是视频暂停播放等待一段时间后播放状态变成了idle状态，请问你是怎么解决的
