### ISSUE TITLE
使用arm-v7a 格式 播放视频崩溃

### ISSUE THREAD

**Issue by xyggs** [CarGuo/GSYVideoPlayer#3020]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

在视频列表 点击播放视频 后崩溃

## 问题机型/系统：

真机 realmex Android10.0

## GSY依赖版本

implementation 'com.shuyu:GSYVideoPlayer:7.1.8'

## Demo中的复现步骤

代码一直编译不过，没有用demo 跑

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

2020-10-28 17:53:36.985 30047-30047/? E/J4A: J4A_FindClass__catchAll: failed
2020-10-28 17:53:36.985 30047-30047/? E/J4A: J4A_FindClass__asGlobalRef__catchAll: failed: tv/danmaku/ijk/media/player/misc/IMediaDataSource
2020-10-28 17:53:36.986 30047-30047/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.migaomei.jzh, PID: 30047
    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.migaomei.jzh-FhzRJUOWISJ4rt3WmzKjkQ==/lib/arm/libijksdl.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer$a.a(IjkMediaPlayer.java:179)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.U1(IjkMediaPlayer.java:191)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.T1(IjkMediaPlayer.java:231)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:227)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:218)
        at e.h0.b.m.d.l(IjkPlayerManager.java:57)
        at e.h0.b.c.a0(GSYVideoBaseManager.java:607)
        at e.h0.b.c.L(GSYVideoBaseManager.java:39)
        at e.h0.b.c$i.handleMessage(GSYVideoBaseManager.java:567)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:228)
        at android.app.ActivityThread.main(ActivityThread.java:7782)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

**Comment by xyggs** [comment]
......debug 得时候 把混淆打开了 又没添加混淆规则
