### ISSUE TITLE
切换VideoManager播放是会触发cache IllegalStateException

### ISSUE THREAD

**Issue by Kenvin-Fang** [CarGuo/GSYVideoPlayer#3023]
首先感谢作者。在使用中发现了个小问题

## 问题描述：
ExoSourceManager中的mCache是单例子。在切换VideoManager的场景下，release旧的manager会导致新manager播放失败，日志如下，建议ExoSourceManager添加实例计数，当全部release后再释放mCache.

## GSY依赖版本

'com.shuyu:gsyVideoPlayer-java:7.1.5'`

## 代码
```
public void release() {
        isCached = false;
        if (mCache != null) {
            try {
                mCache.release();
                mCache = null;
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
```

## 问题log（如果有）

```

E/EventLogger: playerFailed [0.22]
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: null
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:394)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:245)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: null
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:413)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
        at com.google.android.exoplayer2.upstream.cache.SimpleCache.startReadWriteNonBlocking(SimpleCache.java:382)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:397)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(CacheDataSource.java:321)
        at com.google.android.exoplayer2.upstream.StatsDataSource.read(StatsDataSource.java:91)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:287)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:62)
        at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:183)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:471)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:568)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:192)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:982)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 

```

**Comment by CarGuo** [comment]
什么场景需要这样切换 VideoManager 呀？
现在的 cache manager 应该是独立的一个 CacheManager 呢？
如果是 demo 用无缝切换 manager ，应该是先创建新的 VideoManager ，然后播放成功后再释放旧的吧？

**Comment by Kenvin-Fang** [comment]
> 什么场景需要这样切换 VideoManager 呀？
> 现在的 cache manager 应该是独立的一个 CacheManager 呢？
> 如果是 demo 用无缝切换 manager ，应该是先创建新的 VideoManager ，然后播放成功后再释放旧的吧？

是在demo里面那种无缝切换分辨率的场景额，demo里面是新播放器onSeekComplete的时候释放了，应该是会影响当前的播放器的吧。我是在这一步遇到的这个异常，不知道是不是用法错了。

**Comment by CarGuo** [comment]
我在 demo 中测试好像没看到问题～～
