### ISSUE TITLE
Exo模式无网络状态下拖动进度条到未缓存的进度,APP崩溃

### ISSUE THREAD

**Issue by foreverZou** [CarGuo/GSYVideoPlayer#3078]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

Exo模式下拖动进度条到未缓存的进度崩溃

## 问题机型/系统：

一加7Pro

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer:8.0'`

## Demo中的复现步骤

无网络状态
使用默认缓存管理器
PlayerFactory.setPlayManager(Exo2PlayerManager::class.java)

## 问题log（如果有）
com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:319)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:199)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.IOException: unexpected end of stream on com.android.okhttp.Address@13144f84
        at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:203)
        at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:315)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:199) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: java.io.EOFException: \n not found: size=0 content=...
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:202)
        at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)

**Comment by foreverZou** [comment]
请问下问下#1175的问题,设置了{
   VideoOptionModel videoOptionModel =
                  new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "dns_cache_clear", 1);
          List<VideoOptionModel> list = new ArrayList<>();
          list.add(videoOptionModel);
          VideoOptionModel videoOptionModel2 = new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "dns_cache_timeout", -1);
          list.add(videoOptionModel2);
          GSYVideoManager.instance().setOptionModelList(list);
}切换HTTP和HTTPS播放源依然不行

**Comment by CarGuo** [comment]
dns_cache_clear 是给默认 ijk 模式使用的，exo不支持

**Comment by foreverZou** [comment]
哦哦,那请问我用exo模是拖动进度条到未缓存的进度崩溃是什么原因呢?现在必崩.......

**Comment by CarGuo** [comment]
你用的是默认的 cache ？ 打开了边播边缓存？Demo 怎么复现？

**Comment by foreverZou** [comment]
Exo模式下使用默认的cache并且打开了边播放边缓存,打开网络播放视频,播放一段时间后关闭网络拖动到未缓存的位置 视频崩溃重置

**Comment by CarGuo** [comment]
有点蛋疼，我这边不出现

**Comment by CarGuo** [comment]
没有复现问题，如果有的话可以麻烦提供下出现问题的定位
