### ISSUE TITLE
'boolean com.shuyu.gsyvideoplayer.utils.NetInfoModule$ConnectivityBroadcastReceiver.isRegistered()' on a null object

### ISSUE THREAD

**Issue by xiongkai888** [CarGuo/GSYVideoPlayer#3081]
接入自己项目，点击全屏就会出现这个空指针
 java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.shuyu.gsyvideoplayer.utils.NetInfoModule$ConnectivityBroadcastReceiver.isRegistered()' on a null object reference
        at com.shuyu.gsyvideoplayer.utils.NetInfoModule.unregisterReceiver(NetInfoModule.java:82)
        at com.shuyu.gsyvideoplayer.utils.NetInfoModule.onHostPause(NetInfoModule.java:53)
        at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.releaseNetWorkState(GSYVideoView.java:878)
        at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.setStateAndUi(GSYVideoControlView.java:329)
        at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.onCompletion(GSYVideoView.java:630)
        at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.startPrepare(GSYVideoView.java:322)
        at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.prepareVideo(GSYVideoView.java:317)
        at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.prepareVideo(GSYVideoControlView.java:653)
        at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.startPlayLogic(StandardGSYVideoPlayer.java:137)
        at com.gxttxs.common.activity.VideoPlayerActivity.initVideoView(VideoPlayerActivity.java:129)
        at com.gxttxs.common.activity.VideoPlayerActivity.initView(VideoPlayerActivity.java:79)
        at com.gxttxs.common.activity.VideoPlayerActivity.lambda$onCreate$0$VideoPlayerActivity(VideoPlayerActivity.java:68)
        at com.gxttxs.common.activity.-$$Lambda$VideoPlayerActivity$Rs7zchLbv0eZAYR8rIwju-Ho-cI.onChanged(Unknown Source:4)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:144)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:442)
        at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:394)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:123)
        at androidx.lifecycle.ReportFragment.onStart(ReportFragment.java:83)
        at android.app.Fragment.performStart(Fragment.java:2548)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1334)
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3051)
        at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3008)
        at android.app.FragmentController.dispatchStart(FragmentController.java:193)
        at android.app.Activity.performStart(Activity.java:7272)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3009)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionE

**Comment by xiongkai888** [comment]
不知道哪里没设置好

**Comment by CarGuo** [comment]
demo 怎么复现啊？你是不是没配置 AndroidManifest  增加权限？
