### ISSUE TITLE
项目导入就报错

### ISSUE THREAD

**Issue by hughdev** [CarGuo/GSYVideoPlayer#3085]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

项目在gradle中引入包编译运行就报错，还没写任何代码，已经迁移androidx
    implementation 'com.shuyu:GSYVideoPlayer:8.0.0'

## 问题机型/系统：

例如 真机 pixel 3xl 安卓最新版本11

## GSY依赖版本

    implementation 'com.shuyu:GSYVideoPlayer:8.0.0'

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
无
```

## 问题log（如果有）

```

1608773920.050 14023-14023/com.example.xxx E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "com.example.xxx.1" on path: DexPathList[[zip file "/data/app/~~tbsPcz2xHfl-cIUiZHq2aA==/com.example.xxx-W7Krf1Q-1CWYj2A3iNNanQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~tbsPcz2xHfl-cIUiZHq2aA==/com.example.xxx-W7Krf1Q-1CWYj2A3iNNanQ==/lib/arm64, /data/app/~~tbsPcz2xHfl-cIUiZHq2aA==/com.example.xxx-W7Krf1Q-1CWYj2A3iNNanQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:260)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:905)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:958)
        at android.app.LoadedApk.getResources(LoadedApk.java:1190)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2659)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2651)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6595)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
    	Suppressed: java.io.IOException: Failed to open dex files from /data/app/~~tbsPcz2xHfl-cIUiZHq2aA==/com.example.xxx-W7Krf1Q-1CWYj2A3iNNanQ==/base.apk because: Failure to verify dex file '/data/app/~~tbsPcz2xHfl-cIUiZHq2aA==/com.example.xxx-W7Krf1Q-1CWYj2A3iNNanQ==/base.apk': Bad index for method_handle_item method_idx: ffff >= ffdb
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:367)
        at dalvik.system.DexFile.<init>(DexFile.java:109)
        at dalvik.system.DexFile.<init>(DexFile.java:82)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:439)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:398)
        at dalvik.system.DexPathList.<init>(DexPathList.java:166)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:129)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:104)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:74)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:87)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:116)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:114)
        at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:60)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:901)
        		... 13 more

xxxxxxx

```

**Comment by CarGuo** [comment]
java.lang.ClassNotFoundException: Didn't find class "com.example.xxx.1"

**Comment by hughdev** [comment]
> java.lang.ClassNotFoundException: Didn't find class "com.example.xxx.1"

咋解决呀大佬

**Comment by hughdev** [comment]
运行程序，屏幕一闪就退

**Comment by hughdev** [comment]
tools:replace="android:appComponentFactory"
        android:appComponentFactory="1"
我是安网上说的在application里面添加了上面的两句话 @CarGuo

**Comment by CarGuo** [comment]
你这是类找不到，你确定下是不是包超了，还是冲突了，还是什么的，这个问题不是 gsy 的问题
