### ISSUE TITLE
使用DetailDownloadPlayer的开始缓存 后报错崩溃

### ISSUE THREAD

**Issue by wuyihao99** [CarGuo/GSYVideoPlayer#3088]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

使用DetailDownloadPlayer的开始缓存 后报错崩溃

## 问题机型/系统：

小米note7 Android10.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.0.0'`

## Demo中的复现步骤

进入DetailDownloadPlayer后点击开始缓存

问题代码：(如果有)

## 问题log（如果有）

com.example.gsyvideoplayer E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.gsyvideoplayer, PID: 27088
    java.lang.IllegalArgumentException: unexpected url: file:///data/user/0/com.example.gsyvideoplayer/cache/video-cache/09096f089ee62e47028790742e8e0c1a.mp4
        at okhttp3.Request$Builder.url(Request.java:141)
        at com.zhy.http.okhttp.request.OkHttpRequest.initBuilder(OkHttpRequest.java:49)
        at com.zhy.http.okhttp.request.OkHttpRequest.<init>(OkHttpRequest.java:39)
        at com.zhy.http.okhttp.request.GetRequest.<init>(GetRequest.java:15)
        at com.zhy.http.okhttp.builder.GetBuilder.build(GetBuilder.java:26)
        at com.example.gsyvideoplayer.DetailDownloadPlayer.startDownload(DetailDownloadPlayer.java:274)
        at com.example.gsyvideoplayer.DetailDownloadPlayer.access$400(DetailDownloadPlayer.java:39)
        at com.example.gsyvideoplayer.DetailDownloadPlayer$5.onClick(DetailDownloadPlayer.java:178)
        at android.view.View.performClick(View.java:7250)
        at android.view.View.performClickInternal(View.java:7227)
        at android.view.View.access$3500(View.java:819)
        at android.view.View$PerformClick.run(View.java:27749)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by CarGuo** [comment]
我要怎么在 demo 复现问题？

**Comment by wuyihao99** [comment]
Uploading WeChat_20201225153958.mp4…

**Comment by wuyihao99** [comment]
Uploading WeChat_20201225153958.mp4…

**Comment by wuyihao99** [comment]
视频上传一直是Uploading ....

**Comment by wuyihao99** [comment]
> 我要怎么在demo复现问题？

打开gsy demo 进入缓存下载支持 点击开始缓存 地址就是demo里的"http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4"

**Comment by wuyihao99** [comment]
> 我要怎么在 demo 复现问题？

要不我把视频上传到群里？

**Comment by CarGuo** [comment]
主要是我这边测试正常

**Comment by wuyihao99** [comment]
> 主要是我这边测试正常

我现在试出的结果是从装后第一次缓存下载不会崩溃，但是第二次点就会一直奔溃，下面是第一次开始的日志截图，和第一次结束时的截图，第三张是第二次以后的错误
![QQ图片20201225181928](https://user-images.githubusercontent.com/47774645/103132084-4937a680-46de-11eb-8c67-e11c92278d99.png)
![QQ截图20201225181959](https://user-images.githubusercontent.com/47774645/103132091-4b9a0080-46de-11eb-88de-1534f89fd210.png)
![QQ截图20201225182054](https://user-images.githubusercontent.com/47774645/103132095-4d63c400-46de-11eb-93b7-5bddfc4803c9.png)

**Comment by WaoSan** [comment]
> 我要怎么在 demo 复现问题？

2020-12-26 11:29:38.963 1466-1606/? E/WifiVendorHal: getWifiLinkLayerStats_1_3_Internal(l.936) failed {.code = ERROR_NOT_SUPPORTED, .description = }
2020-12-26 11:29:40.769 15221-15221/com.example.gsyvideoplayer E/GSYVideoPlayer: ###### url file:///data/user/0/com.example.gsyvideoplayer/cache/video-cache/09096f089ee62e47028790742e8e0c1a.mp4
2020-12-26 11:29:40.777 15221-15221/com.example.gsyvideoplayer E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.gsyvideoplayer, PID: 15221
    java.lang.IllegalArgumentException: unexpected url: file:///data/user/0/com.example.gsyvideoplayer/cache/video-cache/09096f089ee62e47028790742e8e0c1a.mp4
        at okhttp3.Request$Builder.url(Request.java:141)
        at com.zhy.http.okhttp.request.OkHttpRequest.initBuilder(OkHttpRequest.java:49)
        at com.zhy.http.okhttp.request.OkHttpRequest.<init>(OkHttpRequest.java:39)
        at com.zhy.http.okhttp.request.GetRequest.<init>(GetRequest.java:15)
        at com.zhy.http.okhttp.builder.GetBuilder.build(GetBuilder.java:26)
        at com.example.gsyvideoplayer.DetailDownloadPlayer.startDownload(DetailDownloadPlayer.java:273)
        at com.example.gsyvideoplayer.DetailDownloadPlayer.access$400(DetailDownloadPlayer.java:39)
        at com.example.gsyvideoplayer.DetailDownloadPlayer$5.onClick(DetailDownloadPlayer.java:178)
        at android.view.View.performClick(View.java:7257)
        at android.view.View.performClickInternal(View.java:7213)
        at android.view.View.access$3800(View.java:828)
        at android.view.View$PerformClick.run(View.java:27921)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7830)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)


在startDownload的时候传入的url是file:///data/user/0/前缀 的,然后用 OkHttpUtils.get().url(url)下载的时候就出问题了

**Comment by wuyihao99** [comment]
> > 我要怎么在 demo 复现问题？
> 
> 2020-12-26 11:29:38.963 1466-1606/? E/WifiVendorHal: getWifiLinkLayerStats_1_3_Internal(l.936) failed {.code = ERROR_NOT_SUPPORTED, .description = }
> 2020-12-26 11:29:40.769 15221-15221/com.example.gsyvideoplayer E/GSYVideoPlayer: ###### url file:///data/user/0/com.example.gsyvideoplayer/cache/video-cache/09096f089ee62e47028790742e8e0c1a.mp4
> 2020-12-26 11:29:40.777 15221-15221/com.example.gsyvideoplayer E/AndroidRuntime: FATAL EXCEPTION: main
> Process: com.example.gsyvideoplayer, PID: 15221
> java.lang.IllegalArgumentException: unexpected url: file:///data/user/0/com.example.gsyvideoplayer/cache/video-cache/09096f089ee62e47028790742e8e0c1a.mp4
> at okhttp3.Request$Builder.url(Request.java:141)
> at com.zhy.http.okhttp.request.OkHttpRequest.initBuilder(OkHttpRequest.java:49)
> at com.zhy.http.okhttp.request.OkHttpRequest.(OkHttpRequest.java:39)
> at com.zhy.http.okhttp.request.GetRequest.(GetRequest.java:15)
> at com.zhy.http.okhttp.builder.GetBuilder.build(GetBuilder.java:26)
> at com.example.gsyvideoplayer.DetailDownloadPlayer.startDownload(DetailDownloadPlayer.java:273)
> at com.example.gsyvideoplayer.DetailDownloadPlayer.access$400(DetailDownloadPlayer.java:39)
> at com.example.gsyvideoplayer.DetailDownloadPlayer$5.onClick(DetailDownloadPlayer.java:178)
> at android.view.View.performClick(View.java:7257)
> at android.view.View.performClickInternal(View.java:7213)
> at android.view.View.access$3800(View.java:828)
> at android.view.View$PerformClick.run(View.java:27921)
> at android.os.Handler.handleCallback(Handler.java:883)
> at android.os.Handler.dispatchMessage(Handler.java:100)
> at android.os.Looper.loop(Looper.java:237)
> at android.app.ActivityThread.main(ActivityThread.java:7830)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)
> 
> 在startDownload的时候传入的url是file:///data/user/0/前缀 的,然后用 OkHttpUtils.get().url(url)下载的时候就出问题了

你也出现的这个问题是吧？

**Comment by WaoSan** [comment]
是的，点击缓存的时候直接崩了，我看好像是用okhttp去下载的时候，传入的url不对，
file:///data/user


---原始邮件---
发件人: "wuyihao99"<notifications@github.com&gt;
发送时间: 2020年12月26日(周六) 下午3:52
收件人: "CarGuo/GSYVideoPlayer"<GSYVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Goshua"<863476604@qq.com&gt;;
主题: Re: [CarGuo/GSYVideoPlayer] 使用DetailDownloadPlayer的开始缓存 后报错崩溃 (#3088)




   
我要怎么在 demo 复现问题？
  
2020-12-26 11:29:38.963 1466-1606/? E/WifiVendorHal: getWifiLinkLayerStats_1_3_Internal(l.936) failed {.code = ERROR_NOT_SUPPORTED, .description = }
 2020-12-26 11:29:40.769 15221-15221/com.example.gsyvideoplayer E/GSYVideoPlayer: ###### url file:///data/user/0/com.example.gsyvideoplayer/cache/video-cache/09096f089ee62e47028790742e8e0c1a.mp4
 2020-12-26 11:29:40.777 15221-15221/com.example.gsyvideoplayer E/AndroidRuntime: FATAL EXCEPTION: main
 Process: com.example.gsyvideoplayer, PID: 15221
 java.lang.IllegalArgumentException: unexpected url: file:///data/user/0/com.example.gsyvideoplayer/cache/video-cache/09096f089ee62e47028790742e8e0c1a.mp4
 at okhttp3.Request$Builder.url(Request.java:141)
 at com.zhy.http.okhttp.request.OkHttpRequest.initBuilder(OkHttpRequest.java:49)
 at com.zhy.http.okhttp.request.OkHttpRequest.(OkHttpRequest.java:39)
 at com.zhy.http.okhttp.request.GetRequest.(GetRequest.java:15)
 at com.zhy.http.okhttp.builder.GetBuilder.build(GetBuilder.java:26)
 at com.example.gsyvideoplayer.DetailDownloadPlayer.startDownload(DetailDownloadPlayer.java:273)
 at com.example.gsyvideoplayer.DetailDownloadPlayer.access$400(DetailDownloadPlayer.java:39)
 at com.example.gsyvideoplayer.DetailDownloadPlayer$5.onClick(DetailDownloadPlayer.java:178)
 at android.view.View.performClick(View.java:7257)
 at android.view.View.performClickInternal(View.java:7213)
 at android.view.View.access$3800(View.java:828)
 at android.view.View$PerformClick.run(View.java:27921)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:237)
 at android.app.ActivityThread.main(ActivityThread.java:7830)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)
 
在startDownload的时候传入的url是file:///data/user/0/前缀 的,然后用 OkHttpUtils.get().url(url)下载的时候就出问题了
  
你也出现的这个问题是吧？

**Comment by wuyihao99** [comment]
> 是的，点击缓存的时候直接崩了，我看好像是用okhttp去下载的时候，传入的url不对， file:///data/user

你可以试下删除重装，第一次好像可以，第二次以后就一直崩溃，这个问题我一个星期前就发现了，但是iss上没有，我都以为只有我这里有问题，我试过两台小米的手机都有这样。

**Comment by CarGuo** [comment]
如果完全缓存了，不应该继续下载，你们看api判断下是否已经缓存成功

**Comment by wuyihao99** [comment]
> 如果完全缓存了，不应该继续下载，你们看api判断下是否已经缓存成功，就是如果这个url已经完全缓存，就不要调用okhttp，因为返回的是一个file了

那个api呢

**Comment by CarGuo** [comment]
GSYVideoManager 有 isCacheFile 方法

**Comment by wuyihao99** [comment]
> GSYVideoManager 有 isCacheFile 方法
我去看看，先谢谢您的解答了

**Comment by wuyihao99** [comment]
> GSYVideoManager 有 isCacheFile 方法

我看到isCacheFile是判断正在播放的视频是否缓存不是指定视频，然后看到cachePreview可以判断指定视频，但是有个问题，这个只能知道是否缓存完成，正在缓存中的并不能判断，我连续点两次他会去下载两次，就会有两种情况1它没有缓存2就是正在缓存但是还没有完成，这个能否完善呢。
另外我还发现个问题，我用指定缓存文件newProxy(Context context, File file)，下载完成后手动删除文件，再次下载会发现有数据下载，但是文件里面没有缓存视频，点几次都是这样会去下载但是没有视频文件，需要我退出activity再进来重新下载才行。

**Comment by CarGuo** [comment]
很简单啊，你看缓存惠泽，缓存中会有 .download 结尾的文件，你直接判断下就行了，你看源码嘛，里面有生产缓存文件的规则。

另外下载缓存主要看的是服务有没有在，拉流服务是否正常。

基本上你的需求看着源码改改就可以了
