### ISSUE TITLE
多内核播放会触发Unexpected IllegalStateException: null异常

### ISSUE THREAD

**Issue by zhangyujiu** [CarGuo/GSYVideoPlayer#3110]
## 问题描述：

我在首页A播放一个视频，然后跳转到页面B播放另外一个视频，最后退出页面B回到首页A，这时首页A继续播放，然后我拖动进度条就报错了。麻烦大佬看一下，感谢

## 问题机型/系统：
所有机型

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.1.4'`

## 问题log（如果有）

```
com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalStateException: null
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:413)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
        at com.google.android.exoplayer2.upstream.cache.SimpleCache.getContentMetadata(SimpleCache.java:512)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.getRedirectedUriOrDefault(CacheDataSource.java:515)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:264)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:956)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by CarGuo** [comment]
我测试没有发现问题····

**Comment by zhangyujiu** [comment]
B页面release掉后A页面继续播放获取缓存失败，感觉和 [#3023](https://github.com/CarGuo/GSYVideoPlayer/issues/3023)这个问题一样

**Comment by CarGuo** [comment]
你是开了cache是吧？？？ 多内核不能用 proxycache 的

**Comment by zhangyujiu** [comment]
是开了cache，那有没有什么方法可以解决呢

**Comment by CarGuo** [comment]
关闭 cache 啊

**Comment by zhangyujiu** [comment]
我们必须要使用cache，那可不可以在ExoSourceManager#release方法最前面判断VideoManager实例的个数，如果只有一个实例才释放？

**Comment by wuyihao99** [comment]
> 我们必须要使用缓存，那可不可以在ExoSourceManager＃release方法最前面判断VideoManager实例的个数，如果只有一个实例才释放？

我也在做类似的功能，只是还没到这步，如果不能缓存就很尴尬了，如果不缓存改成提前下载呢，不过这个我也没做过不知道怎么做，还有问下ExoSourceManager的缓存大小你是怎么修改的，方便加个QQ联系吗

**Comment by zhangyujiu** [comment]
> > 我们必须要使用缓存，那可不可以在ExoSourceManager＃release方法最前面判断VideoManager实例的个数，如果只有一个实例才释放？
> 
> 我也在做类似的功能，只是还没到这步，如果不能缓存就很尴尬了，如果不缓存改成提前下载呢，不过这个我也没做过不知道怎么做，还有问下ExoSourceManager的缓存大小你是怎么修改的，方便加个QQ联系吗

我自己写了个插件解决了，在release前插入代码判断VideoManager实例的个数

**Comment by wuyihao99** [comment]
> 我自己写了个插件解决了，在发布前插入代码判断VideoManager实例的个数

方便的话可以发给我学习下吗，我现在还不知道怎么改多核的播放，还有ExoSourceManager的缓存大小

**Comment by zhangyujiu** [comment]
> > 我自己写了个插件解决了，在发布前插入代码判断VideoManager实例的个数
> 
> 方便的话可以发给我学习下吗，我现在还不知道怎么改多核的播放，还有ExoSourceManager的缓存大小

加QQ：1484288157

**Comment by ssyijiu** [comment]
@zhangyujiu 请问是字节码插桩改的吗？我看 VideoManager 是一个单例啊，如何判断它的实例个数呢？

**Comment by zhangyujiu** [comment]
> @zhangyujiu 请问是字节码插桩改的吗？我看 VideoManager 是一个单例啊，如何判断它的实例个数呢？

字节码插桩修改，我的是多内核可以判断
