### ISSUE TITLE
视频缓存 一半 退出然后断网  再次进入app 能播放么 如何实现  

### ISSUE THREAD

**Issue by aglszz** [CarGuo/GSYVideoPlayer#3116]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

没有缓存完的视频  断网后 能播放吗

## 问题机型/系统：

 真机 小米note2 Android7.0

## GSY依赖版本

 `implementation 'com.shuyu:gsyVideoPlayer-java:8.0.0'`

## Demo中的复现步骤

无

问题代码：(如果有)
```
无
```

## 问题log（如果有）

```
无

```

**Comment by aglszz** [comment]
现在缓存目录 能看到  缓存一半的视频   断网状态下   不能播放   支持  播放不完整的缓存视频吗

**Comment by CarGuo** [comment]
proxyCache 可以的，断网，退出再进来，默认支持

**Comment by aglszz** [comment]
01-27 11:53:35.254 7836-8043/com.welsee.classcard E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0
01-27 11:53:35.295 7836-8043/com.welsee.classcard E/HttpProxyCacheServer error: Error processing request. Version: 6.0.3
01-27 11:53:35.295 7836-8043/com.welsee.classcard I/HttpProxyCacheDebuger: Opened connections: 0
01-27 11:53:35.300 7836-8052/com.welsee.classcard W/Last modified date {} is not set for file {}: Wed Jan 27 11:53:35 GMT+08:00 2021
    /storage/emulated/0/.classcard/.video/2fa70912e85dc103e825470cf32e95c9.mp4.download
01-27 11:53:35.300 7836-8539/com.welsee.classcard E/ExoPlayerImplInternal: Source error
      com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:292)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:962)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.io.EOFException
        at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:95)
        at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:179)
        at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:628)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:500)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:288)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:962) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
01-27 11:53:35.314 7836-7836/com.welsee.classcard E/EventLogger: playerFailed [3.28]
    com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:394)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:292)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:962)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.io.EOFException
        at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:95)
        at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:179)
        at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:628)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:500)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:288)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:962) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818)
