### ISSUE TITLE
缓存问题

### ISSUE THREAD

**Issue by aglszz** [CarGuo/GSYVideoPlayer#3117]
问题描述：
添加CacheFactory.setCacheManager(ProxyCacheManager.class); 
报错
问题样本/系统：
3288A

GSY依赖版本
implementation 'com.shuyu:gsyVideoPlayer-java:6.0.3'

演示中的复现步骤
无

问题代码：(如果有）

无
问题log（如果有）
01-27 13:37:37.108 18797-18797/com.welsee.classcard E/CrashHandler: In thread: Thread[main,5,main]
    UncaughtException detected: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.welsee.classcard-1/base.apk"],nativeLibraryDirectories=[/data/app/com.welsee.classcard-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libijkffmpeg.so"
        at java.lang.Runtime.loadLibrary(Runtime.java:366)
        at java.lang.System.loadLibrary(System.java:988)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:179)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:190)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:231)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:227)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:218)
        at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.initVideoPlayer(IjkPlayerManager.java:55)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:600)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:38)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:564)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5321)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
01-27 13:37:37.137 18797-18809/com.welsee.classcard E/art: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
01-27 13:37:37.137 18797-18809/com.welsee.classcard E/System: Uncaught exception thrown by finalizer
01-27 13:37:37.137 18797-18809/com.welsee.classcard E/System: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(IjkMediaPlayer.java:950)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:191)
        at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
        at java.lang.Thread.run(Thread.java:818)

**Comment by CarGuo** [comment]
参考demo，并使用最新版本
