### ISSUE TITLE
视频加载报错

### ISSUE THREAD

**Issue by ptrtony** [CarGuo/GSYVideoPlayer#3119]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

XXXX发生了这样的问题！

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by ptrtony** [comment]
视频在重复进出的时候有时候会出现这种错误

2021-01-27 16:17:37.419 7621-8800/ E/LoadTask: Unexpected exception loading stream
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:81)
        at com.google.android.exoplayer2.upstream.cache.SimpleCache.releaseHoleSpan(SimpleCache.java:297)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.closeCurrentSource(CacheDataSource.java:476)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.close(CacheDataSource.java:300)
        at com.google.android.exoplayer2.util.Util.closeQuietly(Util.java:265)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:870)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:320)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by CarGuo** [comment]
https://mp.weixin.qq.com/s/HjSdmAsHuvixCH_EWdvk3Q
