### ISSUE TITLE
SystemPlayerManager 的一个奔溃问题

### ISSUE THREAD

**Issue by linkaipeng** [CarGuo/GSYVideoPlayer#3138]
## 问题描述：

使用系统内核和 texture 预览播放，关闭播放器页面的时候出现异常；

## 问题机型/系统：

真机 小米10 Android 11
另外还有一台 Android 10 的平板；

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.0.0'`

## 复现步骤

1、设置系统播放内核 + Texture 预览模式；
2、进入播放页面，进行播放；
3、关闭播放页面；
4、出现异常；

问题代码：SystemPlayerManager 类中的：
```
mediaPlayer.setSurface(null);
```

## 问题log

```

02-23 19:10:59.456 E/AndroidRuntime(18058): java.lang.IllegalStateException
02-23 19:10:59.456 E/AndroidRuntime(18058): 	at android.media.MediaPlayer._setVideoSurface(Native Method)
02-23 19:10:59.456 E/AndroidRuntime(18058): 	at android.media.MediaPlayer.setSurface(MediaPlayer.java:788)
02-23 19:10:59.456 E/AndroidRuntime(18058): 	at tv.danmaku.ijk.media.player.AndroidMediaPlayer.setSurface(AndroidMediaPlayer.java:79)
02-23 19:10:59.456 E/AndroidRuntime(18058): 	at com.shuyu.gsyvideoplayer.player.SystemPlayerManager.showDisplay(SystemPlayerManager.java:74)
02-23 19:10:59.456 E/AndroidRuntime(18058): 	at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.showDisplay(GSYVideoBaseManager.java:671)
02-23 19:10:59.456 E/AndroidRuntime(18058): 	at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.setDisplay(GSYVideoBaseManager.java:232)
02-23 19:10:59.456 E/AndroidRuntime(18058): 	at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.setDisplay(GSYVideoView.java:733)
02-23 19:10:59.456 E/AndroidRuntime(18058): 	at com.shuyu.gsyvideoplayer.video.base.GSYTextureRenderView.onSurfaceDestroyed(GSYTextureRenderView.java:84)
02-23 19:10:59.456 E/AndroidRuntime(18058): 	at com.shuyu.gsyvideoplayer.render.view.GSYTextureView.onSurfaceTextureDestroyed(GSYTextureView.java:93)
02-23 19:10:59.456 E/AndroidRuntime(18058): 	at android.view.TextureView.releaseSurfaceTexture(TextureView.java:259)
02-23 19:10:59.456 E/AndroidRuntime(18058): 	at android.view.TextureView.onDetachedFromWindowInternal(TextureView.java:230)
02-23 19:10:59.456 E/AndroidRuntime(18058): 	at android.view.View.dispatchDetachedFromWindow(View.java:19690)
02-23 19:10:59.456 E/AndroidRuntime(18058): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3866)
02-23 19:10:59.456 E/AndroidRuntime(18058): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3866)
02-23 19:10:59.456 E/AndroidRuntime(18058): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3866)

```

**Comment by CarGuo** [comment]
我在 真机 小米11 Android 11 测试没有出现

**Comment by linkaipeng** [comment]
我写了个我这边可以复现的 demo，你试试能否出现 @CarGuo 

```
class VideoPlayActivity : AppCompatActivity() {

    companion object {
        fun startSelf(context: Context) {
            context.startActivity(Intent(context, VideoPlayActivity::class.java))
        }
    }

    private val binding by lazy {
        ActivityPlayBinding.inflate(layoutInflater)
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(binding.root)
        PlayerFactory.setPlayManager(SystemPlayerManager::class.java)
        GSYVideoType.setRenderType(GSYVideoType.TEXTURE)
        
        val url = "http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4"
        binding.playGSYADPlayView.let { player ->
            player.setUp(url, false, "测试视频")
            player.startPlayLogic()
            player.backButton.setOnClickListener {
                finish()
            }
            player.isShowFullAnimation = false
            player.fullscreenButton.visibility = View.GONE
        }
    }

    override fun onPause() {
        super.onPause()
        binding.playGSYADPlayView.onVideoPause()
    }

    override fun onResume() {
        super.onResume()
        binding.playGSYADPlayView.onVideoResume()
    }

    override fun onDestroy() {
        super.onDestroy()
        binding.playGSYADPlayView.gsyVideoManager?.player?.mediaPlayer?.let {
            it.stop()
            it.release()
        }
    }
}
```

**Comment by CarGuo** [comment]
为什么这样释放？？？？

 binding.playGSYADPlayView.gsyVideoManager?.player?.mediaPlayer?.let {
            it.stop()
            it.release()
        }

**Comment by linkaipeng** [comment]
了解了，改为  GSYVideoManager.releaseAllVideos() 后 OK 了
