### ISSUE TITLE
Widevine 影音播放被強制使用surfaceView

### ISSUE THREAD

**Issue by dendrocyte** [CarGuo/GSYVideoPlayer#3141]
## 问题描述：

播放widevine的影片被強制要使用surfaceView，但影片播完時卻出現找不到xml的surfaceView 而出現error
在m3u8的live 或vod的影片並不會出現這樣的問題

## 问题机型/系统：

Sharp 8.0

## GSY依赖版本

implementation 'com.shuyu:gsyVideoPlayer-java:7.1.8' //支援exoplayer 1.12.1
 implementation 'com.shuyu:GSYVideoPlayer-exo2:7.1.8' //支援exoplayer 1.12.1
//自定義的打包so

## Demo中的复现步骤
參考widevine的測試影片配置，
使用demo裡 standardPlayer的xml佈局，播放widevine的影片播放到影片結束時會出現這問題

问题代码：
```

//must to use SurfaceView not TextureView
//Error Msg:
//E SurfaceUtils: native window cannot handle protected buffers: the consumer should either be a hardware composer or support hardware protection
GSYVideoType.setRenderType(GSYVideoType.SUFRACE)
//硬解開啟
GSYVideoType.enableMediaCodec()
//使用exo內核
PlayerFactory.setPlayManager(Exo2PlayerManager::class.java)


var drmSessionManager: DefaultDrmSessionManager? =
            DefaultDrmSessionManager.Builder()
                .setKeyRequestParameters(mapOf(
                    "MDAwMDAwMDAwMDAwMDAwMQ==" to "eKHcBkYRlwfpA1FNigBzXw==",
                    "MDAwMDAwMDAwMDAwMDAwMw==" to "QkZshCrBxUObHgwJ+7Th0g==",
                    "MDAwMDAwMDAwMDAwMDAwMg==" to "Hzeeo4xw5Af3ayPsZAHK7w==",
                    "MDAwMDAwMDAwMDAwMDAwMA==" to "Pwoz80CYueIrwHjgobXoVA==",
                    "MDAwMDAwMDAwMDAwMDAwNA==" to "IvCfhLVopdAH5LHRFpQ1gQ==",
                    "MDAwMDAwMDAwMDAwMDAwNQ==" to "msMDbgSsnSvpRu1iQFFJvA==",
                    "MDAwMDAwMDAwMDAwMDAwNg==" to "MUWYWCQzTsTLSsS9w+K+7w==",
                    "MDAwMDAwMDAwMDAwMDAwNw==" to "ebhzT7mNJ1qQempaFQEouw=="
                ))
                .build(HttpMediaDrmCallback("https://proxy.staging.widevine.com/proxy", DefaultHttpDataSourceFactory("user-agent")))

    ExoSourceManager.setExoMediaSourceInterceptListener(object :
            ExoMediaSourceInterceptListener {
            /**
             * @param dataSource  链接
             * @param preview     是否带上header，默认有header自动设置为true
             * @param cacheEnable 是否需要缓存
             * @param isLooping   是否循环
             * @param cacheDir    自定义缓存目录
             * @return 返回不为空时，使用返回的自定义mediaSource
             */
            override fun getMediaSource(
                dataSource: String?,
                preview: Boolean,
                cacheEnable: Boolean,
                isLooping: Boolean,
                cacheDir: File?
            ): MediaSource? {
                val httpRequestHeaders = mapOf<String, String>(
                    "Content-Type" to "application/octet-stream"
                )
                val contentUri = Uri.parse("https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd")
                val mediaItem : MediaItem =
                    MediaItem.fromUri(contentUri)
               return DefaultMediaSourceFactory(baseContext) 
                    .setDrmSessionManager(drmSessionManager)
                    .createMediaSource(mediaItem)

            }

            /**
             * 通过自定义的 HttpDataSource ，可以设置自签证书或者忽略证书
             * demo 里的 GSYExoHttpDataSourceFactory 使用的是忽略证书
             * */
            override fun getHttpDataSourceFactory(
                userAgent: String,
                listener: TransferListener?,
                connectTimeoutMillis: Int,
                readTimeoutMillis: Int,
                allowCrossProtocolRedirects: Boolean
            ): HttpDataSource.BaseFactory? {
                println("inteceptor: https source")
                return null
            }
        })
```
 
## 问题log

2021-02-25 12:01:58.244 836-905/? E/SurfaceFlinger: Failed to find layer (SurfaceView - org.noovo.vlc/com.example.noovo_gsyplayer.noovo_v2.ui.DrmTestPlayerActivity#0) in layer parent (no-parent).
2021-02-25 12:01:58.245 21765-22046/org.noovo.vlc E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:564)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: android.media.MediaCodec$CodecException: Error 0xffffffff
        at android.media.MediaCodec.native_setSurface(Native Method)
        at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1954)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1242)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setSurface(MediaCodecVideoRenderer.java:516)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:478)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1402)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:1368)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:1343)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65)

```

**Comment by CarGuo** [comment]
GSYVideoType.setRenderType(GSYVideoType.SUFRACE);  不就使用 surfaceView 了么？

render层是播放时动态添加的

**Comment by dendrocyte** [comment]
是的，被強迫使用了surfaceView，才能正常播放一次。
在播放結束時會出現surfaceView的檢查
要怎麼攔截？還是要怎麼修改xml？
不知道能否提點方向

**Comment by CarGuo** [comment]
这·····主要是我这边不复现这个问题···
