### ISSUE TITLE
在播放视频时播放失败  

### ISSUE THREAD

**Issue by pfyuan** [CarGuo/GSYVideoPlayer#3159]
## 问题描述：

从后台获取的mp4格式的视频播放失败  m3u8的可以播放  看报错日志显示 Response code: 503
这个是播放地址https://streamtape.com/v/16r3rbBZaXUegp1/127_Hours.mp4    我拿浏览器请求就可以访问
## 问题机型/系统：

所有机型都是一样的 

## GSY依赖版本

    implementation 'com.shuyu:GSYVideoPlayer:8.1.0'

## Demo中的复现步骤

引用的是带字幕的那个demo

## 问题log（如果有）

2021-03-07 20:40:25.500 28787-3888/com.dhv3.kgq E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:197)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 503
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:336)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:199)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2021-03-07 20:40:25.507 28787-28787/com.dhv3.kgq E/EventLogger: playerFailed [7.42]
    com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:197)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 503
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:336)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:199)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2021-03-07 20:40:25.508 28787-28787/com.dhv3.kgq D/EventLogger: loading [false]
2021-03-07 20:40:25.509 28787-28787/com.dhv3.kgq D/EventLogger: state [7.42, false, I]
2021-03-07 20:40:25.524 28787-28787/com.dhv3.kgq I/ExoPlayerImpl: Release 5ddcfdc [ExoPlayerLib/2.12.1] [R11, OPPO R11t, OPPO, 27] [goog.exo.core, goog.exo.hls]

**Comment by pfyuan** [comment]
https://streamtape.com/v/16r3rbBZaXUegp1/127_Hours.mp4

**Comment by CarGuo** [comment]
Response code: 503 招后台
