### ISSUE TITLE
在recyclerview中如何记录播放的时间呢

### ISSUE THREAD

**Issue by candrwow** [CarGuo/GSYVideoPlayer#317]
类似新浪微博的视频列表，看后可以记录上次播放的时间，现在的问题是我不知道如何在A视频停止，B视频开始播放时记录A的播放position，因为我暂时没有找到在哪里获取player的播放停止状态的方法，也就没有办法确定时机调用getCurrentPositionWhenPlaying。另外demo中的recyclerview并没有多个视频的例子，不会出现错乱的现象，我自己搞了一个scrollerview里嵌套了多个standplayer，就会出现所有列表项都只播放最后一个视频地址的视频，也就是说全错乱了

**Comment by candrwow** [comment]
而且遇到一个问题，第一次打开视频会黑屏但有声音，报的这个error：
E/HttpProxyCacheServer: HttpProxyCacheServer error
                                                                                 com.danikula.videocache.ProxyCacheException: Error processing request. Version: 2.7.0
                                                                                     at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:241)
                                                                                     at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52)
                                                                                     at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:338)
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                                  Caused by: com.danikula.videocache.ProxyCacheException: Error using file /storage/emulated/0/GSYVideo/09096f089ee62e47028790742e8e0c1a.mp4 as disc cache. Version: 2.7.0
                                                                                     at com.danikula.videocache.file.FileCache.<init>(FileCache.java:39)
                                                                                     at com.danikula.videocache.HttpProxyCacheServerClients.newHttpProxyCache(HttpProxyCacheServerClients.java:83)
                                                                                     at com.danikula.videocache.HttpProxyCacheServerClients.startProcessRequest(HttpProxyCacheServerClients.java:49)
                                                                                     at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:39)
                                                                                     at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:234)
                                                                                     at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) 
                                                                                     at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:338) 
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                     at java.lang.Thread.run(Thread.java:818) 
                                                                                  Caused by: java.io.FileNotFoundException: /storage/emulated/0/GSYVideo/09096f089ee62e47028790742e8e0c1a.mp4.download: open failed: EACCES (Permission denied)
                                                                                     at libcore.io.IoBridge.open(IoBridge.java:452)
                                                                                     at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117)
                                                                                     at com.danikula.videocache.file.FileCache.<init>(FileCache.java:37)
                                                                                     at com.danikula.videocache.HttpProxyCacheServerClients.newHttpProxyCache(HttpProxyCacheServerClients.java:83) 
                                                                                     at com.danikula.videocache.HttpProxyCacheServerClients.startProcessRequest(HttpProxyCacheServerClients.java:49) 
                                                                                     at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:39) 
                                                                                     at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:234) 
                                                                                     at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) 
                                                                                     at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:338) 
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                     at java.lang.Thread.run(Thread.java:818) 
                                                                                  Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
                                                                                     at libcore.io.Posix.open(Native Method)
                                                                                     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                                                     at libcore.io.IoBridge.open(IoBridge.java:438)
                                                                                     at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117) 
                                                                                     at com.danikula.videocache.file.FileCache.<init>(FileCache.java:37) 
                                                                                     at com.danikula.videocache.HttpProxyCacheServerClients.newHttpProxyCache(HttpProxyCacheServerClients.java:83) 
                                                                                     at com.danikula.videocache.HttpProxyCacheServerClients.startProcessRequest(HttpProxyCacheServerClients.java:49) 
                                                                                     at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:39) 
                                                                                     at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:234) 
                                                                                     at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) 
                                                                                     at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:338) 
                                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                     at java.lang.Thread.run(Thread.java:818) 
07-11 17:24:08.992 20473-20691/cn.candrwow.myapplication E/IJKMEDIA: http://127.0.0.1:51863/http%3A%2F%2F9890.vod.myqcloud.com%2F9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4: End of file
07-11 17:24:08.992 20473-20586/cn.candrwow.myapplication E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
07-11 17:24:39.613 20473-21248/cn.candrwow.myapplication E/IJKMEDIA: Option ijkiomanager not found.

**Comment by candrwow** [comment]
上面的问题在清空app所有数据，给予所有权限后再次打开会提示播放地址无效

**Comment by CarGuo** [comment]
不是很理解，demo复现不？

**Comment by candrwow** [comment]
抱歉，上面的问题我找到原因，是我使用时写错了一部分。现在想问下应该怎么得到视频的链接呢？当一个recyclerview滚动停止，我用linearLayoutManager获取到一个itemview并取出其中的StandardGSYVideoPlayer，此时应该如何得到StandardGSYVideoPlayer的播放url呢，如果可以，这个url是我setup时设置的网络地址还是调用缓存的地址呢

**Comment by CarGuo** [comment]
你可以看看回调calback

**Comment by candrwow** [comment]
@CarGuo 
 if (player.getCurrentState() == CURRENT_STATE_PLAYING) {

                        } else {
                            if (mAdapter.videoProgressMap.containsKey(player.getPlayTag().toString()))
                                player.setSeekOnStart(mAdapter.videoProgressMap.get(player.getPlayTag().toString()));
                            player.startPlayLogic();
                        }
在recyclerview里我有个逻辑，是可以记录视频播放的进度，类似新浪微博，但是遇到一个问题，当视频快进播放后比如10分钟/20分钟，开始播放，我上下滑动视频移出屏幕，当再次进入时，视频会出现播放进度（声音/画面）是正确的，但是进度条停在0分钟/20分钟，要播放一会才能出现进度条跟上画面声音的情况，这个是哪里缺少了什么设定还是bug呢

**Comment by CarGuo** [comment]
进度条是按照比例动的，你是在哪个demo页面出现问题

**Comment by CarGuo** [comment]
快进过程中获取到的当前播放进度可能会是0

**Comment by candrwow** [comment]
第一次加载视频时为了测试我快进了几分钟，然后快进完毕正常播放几秒，我将屏幕滚动(recyclerview),视频item移出屏幕外执行了ondetachfromwindow
我在里面写了Video.onpausevideo,并记录了currentposition，当再次滚动进入页面执行了上述方法，有几率出现进度条是0但是画面声音已经进入currentposition的点正常播放，过几秒进度条恢复正常

_Sent from my LGE Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by candrwow** [comment]
上述的map里值是记录的上次视频移出屏幕时的进度key是视频的地址value是进度。这种情况几率出现，频率挺高的下午我测试下看能否截取画面给你

_Sent from my LGE Nexus 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by CarGuo** [comment]
你是通过哪个获取进度的？？不是很理解，会存在0的情况就是未准备好和loading快进中，你可以写下具体流程和代码吗？

**Comment by candrwow** [comment]
@Override
    public void onViewDetachedFromWindow(RecyclerView.ViewHolder holder) {
        if (holder.getItemViewType() == ITEMVIEW_VIDEO_AD) {
            StandardGSYVideoPlayer videoPlayer = ((ADVideoViewHolder) holder).video;
            if (videoProgressMap != null) {
                videoProgressMap.put(videoPlayer.getPlayTag(), videoPlayer.getCurrentPositionWhenPlaying());
            }
            videoPlayer.onVideoPause();
        }
        super.onViewDetachedFromWindow(holder);
    }
这个是在recyclerview的adapter里的，进度的数值是正确的一个五位数好像

**Comment by CarGuo** [comment]
这样只要是你过去播放进度的时候，视频已经正确播放，应该就获取正确。

**Comment by candrwow** [comment]
![qq 20170712140030](https://user-images.githubusercontent.com/14042320/28103852-a00f5eec-670a-11e7-9463-5017d6f8cb21.png)

**Comment by candrwow** [comment]
这个视频是在一个recyclerview里的，当滑动进入屏幕后我执行的是
if (player.getCurrentState() == CURRENT_STATE_PLAYING) {
                    } else {
                        if (mAdapter.videoProgressMap.containsKey(player.getPlayTag().toString()))
                            player.setSeekOnStart(mAdapter.videoProgressMap.get(player.getPlayTag().toString()));
                        player.startPlayLogic();
                    }
这个，断点进入看到setSeekOnStart的值是正常的，然后我就没有进行其他操作，视频开始播放就会偶尔出现这种情况，播放(画面和声音都是正常的，只有进度条有点异常)一会进度条就会跟上画面，圆形指示到2：25分那里

**Comment by CarGuo** [comment]
你试试如果出现这个问题。是不是触摸隐藏在触摸显示就好了

**Comment by candrwow** [comment]
是这样的，触摸隐藏后底部显示蓝色线条进度的时候就是正常的了
