### ISSUE TITLE
更换到8.1.1进入播放页面崩溃，之前一直用8.0.0没问题，现只把版本替换到8.1.1，代码没有任何更改，构建完之后，进入播放页，崩溃，报空指针异常

### ISSUE THREAD

**Issue by wangxiongtao** [CarGuo/GSYVideoPlayer#3190]
崩溃信息 

Process: com.kamridor.treector, PID: 13327
    java.lang.NullPointerException
        at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:147)
        at com.google.android.exoplayer2.ExoPlayerImpl.validateMediaSources(ExoPlayerImpl.java:1143)
        at com.google.android.exoplayer2.ExoPlayerImpl.setMediaSourcesInternal(ExoPlayerImpl.java:1021)
        at com.google.android.exoplayer2.ExoPlayerImpl.setMediaSources(ExoPlayerImpl.java:384)
        at com.google.android.exoplayer2.ExoPlayerImpl.setMediaSources(ExoPlayerImpl.java:379)
        at com.google.android.exoplayer2.ExoPlayerImpl.setMediaSource(ExoPlayerImpl.java:363)
        at com.google.android.exoplayer2.SimpleExoPlayer.setMediaSource(SimpleExoPlayer.java:1499)
        at tv.danmaku.ijk.media.exo2.IjkExo2MediaPlayer$1.run(IjkExo2MediaPlayer.java:374)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by wangxiongtao** [comment]
都是按完整版引入的

**Comment by wangxiongtao** [comment]
经排查是ProxyCacheManager类179行 builder.hostnameVerifier(v);参数v为null,导致的异常，这个v需要我们来赋值么

**Comment by CarGuo** [comment]
```
 ProxyCacheManager.instance().setHostnameVerifier(new HostnameVerifier() {
            @Override
            public boolean verify(String hostname, SSLSession session) {
                return true;
            }
        });
        final TrustManager[] trustAllCerts = new TrustManager[]{
                new X509TrustManager() {
                    @Override
                    public void checkClientTrusted(java.security.cert.X509Certificate[] chain, String authType) throws CertificateException {
                    }

                    @Override
                    public void checkServerTrusted(java.security.cert.X509Certificate[] chain, String authType) throws CertificateException {
                    }

                    @Override
                    public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                        return null;
                    }
                }
        };
        ProxyCacheManager.instance().setTrustAllCerts(trustAllCerts);
```


理论上你需要这个····

**Comment by wangxiongtao** [comment]
我试试

**Comment by wangxiongtao** [comment]
111

**Comment by wangxiongtao** [comment]
加上就好了
