### ISSUE TITLE
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 302

### ISSUE THREAD

**Issue by scottcod** [CarGuo/GSYVideoPlayer#3193]
## 问题描述：
大神请问一下，使用exoplayer内核报这个错误，无法播放视频，怎么解决？
视频 http://gamecenter.tt286.com/app/gamecenter/2021/03/23/19/cb80a54cc2c10ab1a8751cb53a9be9f3.mp4
com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:203)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 302
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:336)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:199)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

**Comment by CarGuo** [comment]
使用 demo 测试这个链接，正常播放

**Comment by scottcod** [comment]
是因为http重定向到https了所以会出现这个问题

**Comment by CarGuo** [comment]
这个exo可以配置的

String, String> header = new HashMap<>();
        header.put("allowCrossProtocolRedirects", "true");

 xxx.setMapHeadData(header)
