### ISSUE TITLE
播放器seekTo()检索到指定位置，发生错误 

### ISSUE THREAD

**Issue by q88qaz** [CarGuo/GSYVideoPlayer#3228]
异常信息如下：
04-23 11:42:28.265 13789-15960/com.test.vvddio E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.findEndOfFirstTsPacketInBuffer(TsExtractor.java:453)
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:320)
        at com.google.android.exoplayer2.source.hls.BundledHlsMediaChunkExtractor.read(BundledHlsMediaChunkExtractor.java:67)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:405)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:375)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:342)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
04-23 11:42:28.358 13789-13789/com.test.vvddio E/EventLogger: playerFailed [13.65]
    com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.findEndOfFirstTsPacketInBuffer(TsExtractor.java:453)
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:320)
        at com.google.android.exoplayer2.source.hls.BundledHlsMediaChunkExtractor.read(BundledHlsMediaChunkExtractor.java:67)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:405)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:375)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:342)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
04-23 11:43:48.155 13789-14060/com.test.vvddio E/Unknow: [local_audio_stream.cpp, SetEncParamsInternal, 630]:AudioEngine:LocalAudioStream no audio encoder create before call SetEncParam
04-23 11:43:48.934 13789-14060/com.test.vvddio E/Unknow: [local_audio_stream.cpp, SetEncParamsInternal, 630]:AudioEngine:LocalAudioStream no audio encoder create before call SetEncParam

**Comment by CarGuo** [comment]
Cannot find sync byte. Most likely not a Transport Stream.

**Comment by q88qaz** [comment]
该怎么理解？

**Comment by q88qaz** [comment]
播放链接是M3U8

**Comment by CarGuo** [comment]
seek 之后找不到可用的流 ts ， 可能是和 exo 的 prase 逻辑不兼容

**Comment by q88qaz** [comment]
目前使用的内核版本是8.1.0
是否更新/回退版本可用解决该问题？
亦或是使用ijk内核来解析？

**Comment by CarGuo** [comment]
更新/回退对 exo 影响不大，这部分exo最近版本更新调整好像不多，你可以试试 ijk 兼不兼容，如果也不行说明视频源有问题

**Comment by CarGuo** [comment]
这个和关键帧有关系，你可以看问题集锦
