### ISSUE TITLE
可能的 NullPointerException：mListItemRect为null

### ISSUE THREAD

**Issue by liyujiang-gzu** [CarGuo/GSYVideoPlayer#3286]
## 问题描述：

可能的 NullPointerException：mListItemRect为null。

## 问题机型/系统：

所有机型，所有系统

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.1.3-jitpack'`

## Demo中的复现步骤

点击视频播放器的全屏按钮全屏后从全屏返回正常页面

问题代码：(如果有)
```
    protected void backToNormal() {

        final ViewGroup vp = getViewGroup();

        final View oldF = vp.findViewById(getFullId());
        final GSYVideoPlayer gsyVideoPlayer;
        if (oldF != null) {
            gsyVideoPlayer = (GSYVideoPlayer) oldF;
            //如果暂停了
            pauseFullBackCoverLogic(gsyVideoPlayer);
            if (mShowFullAnimation) {
                TransitionManager.beginDelayedTransition(vp);

                LayoutParams lp = (LayoutParams) gsyVideoPlayer.getLayoutParams();
                lp.setMargins(mListItemRect[0], mListItemRect[1], 0, 0);
                lp.width = mListItemSize[0];
                lp.height = mListItemSize[1];
                //注意配置回来，不然动画效果会不对
                lp.gravity = Gravity.NO_GRAVITY;
                gsyVideoPlayer.setLayoutParams(lp);

                mInnerHandler.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        resolveNormalVideoShow(oldF, vp, gsyVideoPlayer);
                    }
                }, 400);
            } else {
                resolveNormalVideoShow(oldF, vp, gsyVideoPlayer);
            }

        } else {
            resolveNormalVideoShow(null, vp, null);
        }
    }
```

## 问题log（如果有）

```
2021-06-09 15:07:57.697 15796-15796 W/System.err: java.lang.NullPointerException: Attempt to read from null array
2021-06-09 15:07:57.697 15796-15796 W/System.err:     at com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer.backToNormal(GSYBaseVideoPlayer.java:453)
2021-06-09 15:07:57.697 15796-15796 W/System.err:     at com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer$3.run(GSYBaseVideoPlayer.java:429)
2021-06-09 15:07:57.697 15796-15796 W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
2021-06-09 15:07:57.697 15796-15796 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2021-06-09 15:07:57.697 15796-15796 W/System.err:     at android.os.Looper.loop(Looper.java:223)
2021-06-09 15:07:57.697 15796-15796 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7656)
2021-06-09 15:07:57.697 15796-15796 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-06-09 15:07:57.698 15796-15796 W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
2021-06-09 15:07:57.698 15796-15796 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)


```

**Comment by CarGuo** [comment]
不是很理解，mListItemRect 是有全屏动画的效果下才会有的

**Comment by liyujiang-gzu** [comment]
> 不是很理解，mListItemRect 是有全屏动画的效果下才会有的

估计是我用的不科学吧，设置的全屏动画为false没生效：
![image](https://user-images.githubusercontent.com/16816717/121318599-fa08c980-c93d-11eb-8276-c2aa1c9688e9.png)

**Comment by liyujiang-gzu** [comment]
是不是在调用`init`之后还有其他地方调用`setShowFullAnimation`导致在`init`里设置无效？

**Comment by CarGuo** [comment]
全屏和退出全屏 时的 cloneParams  会有  st.mShowFullAnimation = sf.mShowFullAnimation;

**Comment by liyujiang-gzu** [comment]
> 全屏和退出全屏 时的 cloneParams 会有 st.mShowFullAnimation = sf.mShowFullAnimation;

应该是的，不能通过继承的方式自定义偏好项，只能在最外面调用设置

**Comment by CarGuo** [comment]
问题是 mShowFullAnimation 正常使用下没出现问题啊，我这边测试正常

**Comment by liyujiang-gzu** [comment]
> 问题是 mShowFullAnimation 正常使用下没出现问题啊，我这边测试正常

我不是正常情况下使用，我是自定义`StandardGSYVideoPlayer`了。直接用`StandardGSYVideoPlayer#setShowFullAnimation(false)`是有效果的，但是通过继承的方式自定义`XXX extends StandardGSYVideoPlayer`，在`XXX`的`init`里`setShowFullAnimation(false)`没效果。

**Comment by CarGuo** [comment]
你加多一个 override CloneParams ，在里面把 FullAnimation 也设置成 false 呗
