### ISSUE TITLE
采用exo模拟播放视频时，有时候播放一半报错 com.google.android.exoplayer2.ExoPlaybackException: Source error

### ISSUE THREAD

**Issue by happyBoys92** [CarGuo/GSYVideoPlayer#3319]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

采用exo播放视频时，有时候播放一半报错了，而出错一次后，后面99%会必现。
还有缓冲进度到那个位置之后就停止，没有继续缓冲

## 问题机型/系统：

 小米TV  Android6.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.1.5'`

## Demo中的复现步骤

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

07-02 15:17:14.271 29212-29212/com.twh.tv E/EventLogger: playerFailed [47.11]
    com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:157)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected OutOfMemoryError: Failed to allocate a 65548 byte allocation with 29536 free bytes and 28KB until OOM
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:446)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 65548 byte allocation with 29536 free bytes and 28KB until OOM
        at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:104)
        at com.google.android.exoplayer2.source.SampleDataQueue.preAppend(SampleDataQueue.java:240)
        at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:174)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:579)
        at com.google.android.exoplayer2.extractor.TrackOutput$-CC.$default$sampleData(TrackOutput.java:159)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:615)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:249)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMe

**Comment by CarGuo** [comment]
模拟播放视频？？这个主要看视频编码组成，为什么会 OutOfMemoryError

**Comment by happyBoys92** [comment]
是播放视频，我这里播放的是4k视频

**Comment by CarGuo** [comment]
我这边测试4K正常，难道和机型还有关系？

**Comment by happyBoys92** [comment]
> 模拟播放视频？？这个主要看视频编码组成，为什么会 OutOfMemoryError

试了好几个系统，就小米TV Android6.0,有出现过，其他的系统也没有出现过

**Comment by CarGuo** [comment]
这没办法，你用exo的MediaCodec 是没办法修改的，除非你自己去处理自定义source的逻辑

**Comment by happyBoys92** [comment]
> 这没办法，你用exo的MediaCodec 是没办法修改的，除非你自己去处理自定义source的逻辑

会不会是播放的时候获取时长不对，导致播放一半无法播放，因为我看到有缓冲到一定的进度程度时，就不缓冲了，一直停在那个位置

**Comment by CarGuo** [comment]
所以说去看 source ， exo 里基本用的都是默认的  MediaCodec  ，而 MediaCodec  你是没办法去自定义的，所以能看的只有 MediaSource 层面

**Comment by iuhni** [comment]
这边遇到了同样的问题,有个m3u8播放地址,播放3-5分钟稳会显示一直缓冲中.拖动一下进度条就又能播了. 
用exo官方的demo播放这个链接就一点问题都没有.... 神奇.... 

由于各种原因, 这里就不放视频链接了.
最后切换ijk播放器解决.捂脸
