### ISSUE TITLE
Exo播放本地离线视频报错

### ISSUE THREAD

**Issue by ZhuSky** [CarGuo/GSYVideoPlayer#3384]
## 问题描述：

Exo播放本地离线视频报错
ijk可以播放但是滑动到某个时间，加载很慢

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.5-jitpack'
//是否需要ExoPlayer模式
api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-exo_player2:v8.1.5-jitpack'
//更多ijk的编码支持
api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.1.5-jitpack'

问题代码：(如果有)
```
PlayerFactory.setPlayManager(Exo2PlayerManager.class);
homeOfflinePlayVideo.setUp("/data/user/0/com.app.video/files/video/刑侦日记第3集",false,"");
homeOfflinePlayVideo.startPlayLogic();
```

## 问题log（如果有）

```

2021-09-12 17:04:23.094 13681-13681/com.app.video I/ExoPlayerImpl: Init d5d80d [ExoPlayerLib/2.14.0] [cmi, Mi 10 Pro, Xiaomi, 30]
2021-09-12 17:04:23.234 13681-14528/com.app.video E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:236)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, JpegExtractor) could read the stream.
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1027)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2021-09-12 17:04:23.244 13681-13681/com.app.video E/EventLogger: playerFailed [0.15]
    com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:236)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, JpegExtractor) could read the stream.
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1027)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2021-09-12 17:04:23.266 13681-13681/com.app.video I/ExoPlayerImpl: Release d5d80d [ExoPlayerLib/2.14.0] [cmi, Mi 10 Pro, Xiaomi, 30] [goog.exo.core]

```

## 本地文件

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:11
#EXTINF:10.160000,
/data/user/0/com.app.video/files/video/.刑侦日记第3集_0/0.ts
#EXTINF:10.000000,
/data/user/0/com.app.video/files/video/.刑侦日记第3集_0/1.ts
#EXTINF:10.000000,
/data/user/0/com.app.video/files/video/.刑侦日记第3集_0/2.ts
...
```

[刑侦日记.txt](https://github.com/CarGuo/GSYVideoPlayer/files/7149314/default.txt)

**Comment by CarGuo** [comment]
你应该是需要 setOverrideExtension("m3u8"); 之类的

**Comment by ZhuSky** [comment]
setOverrideExtension("m3u8"); 
可以传递多个类型嘛？
我这里下载的视频 不一定是 m3u8的，也有可能是其他类型

**Comment by CarGuo** [comment]
每次播放前设置

**Comment by ZhuSky** [comment]
实测 setOverrideExtension("m3u8"); 有效
但是我这不确定每次播放的视频格式，所以不太行
有没有类似setOverrideExtension("m3u8,mp4");的功能? 直接设置多种类型

**Comment by CarGuo** [comment]
不行，因为你的播放链接没有后缀，要不就是 setOverrideExtension 制定，要不就是链接后缀指定 ，不然没办法在播放前选择 exo 对应的执行解封装的类

**Comment by ZhuSky** [comment]
好的明白了，🙏
目前暂时改用IJK播放内核，这个可以不用管视频类型
以后确定视频类型了在转exo
