### ISSUE TITLE
IJK播放Mp4报错

### ISSUE THREAD

**Issue by ZhuSky** [CarGuo/GSYVideoPlayer#3386]
## 问题描述：

IJK播放MP4 视频报错，请大神看一下日志
另外EXO内核也不行，报错

## 问题机型/系统：

OPPO android 11 

## GSY依赖版本

 api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.5-jitpack'
//是否需要ExoPlayer模式
api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-exo_player2:v8.1.5-jitpack'
//更多ijk的编码支持
api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.1.5-jitpack'

## 问题log（如果有）

```
2021-09-13 17:42:30.090 18277-18277/com.app.video E/OplusCustomizeRestrictionManager: getInstance
2021-09-13 17:42:30.201 1049-1049/? E/LocSvc_HIDL_DebugReportService: Invalid count: 0
2021-09-13 17:42:30.201 1049-1049/? E/LocSvc_HIDL_DebugReportService: Invalid count: 0
2021-09-13 17:42:30.295 18277-18277/com.app.video E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x7263b91aa0)
2021-09-13 17:42:30.295 18277-18277/com.app.video E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x7263b8ee00)
2021-09-13 17:42:30.295 18277-18277/com.app.video E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x7263b8ee70)
2021-09-13 17:42:31.201 1049-1049/? E/LocSvc_HIDL_DebugReportService: Invalid count: 0
2021-09-13 17:42:31.201 1049-1049/? E/LocSvc_HIDL_DebugReportService: Invalid count: 0
2021-09-13 17:42:31.676 18277-19467/com.app.video E/IJKMEDIA: http%3A%2F%2F50112.gzc.svp.tencent-cloud.com%2Fgzc_1000102_0b53gqaagaaa5maps7jf3bq4angdam4aab2a.f10217.mp4%3Fsdtfrom%3Dv7016%26guid%3D686998692a77e3790c04b553c3fc4a26_11001%26vkey%3D70A2952678EEE5C06ADE8727554034A64C05ACB6CBFA4D339D708A614EA662B3FE80B4B7F279360E149E24C125BFBED6C084C59621D2E192BC15664D295B37B64EB56A69277F91911DE8ACA40F03EE29C518E31FC0798B0BAEAAF880FBC9FA498A15E59C590D2AE4D82F6B926CD481BE83BBE9442A506AE00EDD3CAB7C672086AE368C6AFF5BA69E: File name too long
2021-09-13 17:42:31.679 18277-18277/com.app.video E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
2021-09-13 17:42:31.780 18277-18277/com.app.video E/OplusCustomizeRestrictionManager: getInstance
2021-09-13 17:42:32.201 1049-1049/? E/LocSvc_HIDL_DebugReportService: Invalid count: 0
2021-09-13 17:42:32.201 1049-1049/? E/LocSvc_HIDL_DebugReportService: Invalid count: 0

```

**Comment by CarGuo** [comment]
name too long

**Comment by ZhuSky** [comment]
这个名字的限制 您知道是多少吗？

**Comment by ZhuSky** [comment]
```

2021-09-14 11:56:08.057 2529-2674/? E/OpenID: com.nearme.statistics.rom:DUID:ret:T
2021-09-14 11:56:08.061 2529-2674/? E/OpenID: com.nearme.statistics.rom:OUID:ret:T
2021-09-14 11:56:08.067 2529-2674/? E/OpenID: com.nearme.statistics.rom:GUID:ret:T
2021-09-14 11:56:08.069 2529-2674/? E/OpenID: com.nearme.statistics.rom:OUID_STATUS:ret:T
2021-09-14 11:56:08.070 8030-9443/com.app.video E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:257)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: http:/cache.m.iqiyi.com/mus/4649052441187801/2a5157249a6475c2fa5b9db6bd2e47a9/afbe8fd3d73448c9/1631611956081/20210715/fb/28/f2a481c6715a602b9c87fdb09d4d1b2b.m3u8?qd_time=1631591651714&qd_p=51474947&bossStatus=0&ff=ts&tvid=2768775694867800&vt=0&qd_originate=h5&k_uid=f68956166157db72db0208d339e7c086&tm=1631611956081&bid=500&src=02020031010000000000&code=2&_lnt=0&qd_uri=dash&qd_vip=0&sgti=15_f68956166157db72db0208d339e7c086_1631611956081&vf=319c5f660d786a0fbc2aa92bd6658354: open failed: ENOENT (No such file or directory)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:96)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: http:/cache.m.iqiyi.com/mus/4649052441187801/2a5157249a6475c2fa5b9db6bd2e47a9/afbe8fd3d73448c9/1631611956081/20210715/fb/28/f2a481c6715a602b9c87fdb09d4d1b2b.m3u8?qd_time=1631591651714&qd_p=51474947&bossStatus=0&ff=ts&tvid=2768775694867800&vt=0&qd_originate=h5&k_uid=f68956166157db72db0208d339e7c086&tm=1631611956081&bid=500&src=02020031010000000000&code=2&_lnt=0&qd_uri=dash&qd_vip=0&sgti=15_f68956166157db72db0208d339e7c086_1631611956081&vf=319c5f660d786a0fbc2aa92bd6658354: open failed: ENOENT (No such file or directory)
        at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:165)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:88)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: java.io.FileNotFoundException: http:/cache.m.iqiyi.com/mus/4649052441187801/2a5157249a6475c2fa5b9db6bd2e47a9/afbe8fd3d73448c9/1631611956081/20210715/fb/28/f2a481c6715a602b9c87fdb09d4d1b2b.m3u8?qd_time=1631591651714&qd_p=51474947&bossStatus=0&ff=ts&tvid=2768775694867800&vt=0&qd_originate=h5&k_uid=f68956166157db72db0208d339e7c086&tm=1631611956081&bid=500&src=02020031010000000000&code=2&_lnt=0&qd_uri=dash&qd_vip=0&sgti=15_f68956166157db72db0208d339e7c086_1631611956081&vf=319c5f660d786a0fbc2aa92bd6658354: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:492)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152)
        at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:154)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:88) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8119)
        at libcore.io.IoBridge.open(IoBridge.java:478)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289) 
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152) 
        at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:154) 
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:88) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
2021-09-14 11:56:08.073 8030-8030/com.app.video E/EventLogger: playerFailed [3.04]
    com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:257)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: http:/cache.m.iqiyi.com/mus/4649052441187801/2a5157249a6475c2fa5b9db6bd2e47a9/afbe8fd3d73448c9/1631611956081/20210715/fb/28/f2a481c6715a602b9c87fdb09d4d1b2b.m3u8?qd_time=1631591651714&qd_p=51474947&bossStatus=0&ff=ts&tvid=2768775694867800&vt=0&qd_originate=h5&k_uid=f68956166157db72db0208d339e7c086&tm=1631611956081&bid=500&src=02020031010000000000&code=2&_lnt=0&qd_uri=dash&qd_vip=0&sgti=15_f68956166157db72db0208d339e7c086_1631611956081&vf=319c5f660d786a0fbc2aa92bd6658354: open failed: ENOENT (No such file or directory)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:96)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: http:/cache.m.iqiyi.com/mus/4649052441187801/2a5157249a6475c2fa5b9db6bd2e47a9/afbe8fd3d73448c9/1631611956081/20210715/fb/28/f2a481c6715a602b9c87fdb09d4d1b2b.m3u8?qd_time=1631591651714&qd_p=51474947&bossStatus=0&ff=ts&tvid=2768775694867800&vt=0&qd_originate=h5&k_uid=f68956166157db72db0208d339e7c086&tm=1631611956081&bid=500&src=02020031010000000000&code=2&_lnt=0&qd_uri=dash&qd_vip=0&sgti=15_f68956166157db72db0208d339e7c086_1631611956081&vf=319c5f660d786a0fbc2aa92bd6658354: open failed: ENOENT (No such file or directory)
        at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:165)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:88)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: java.io.FileNotFoundException: http:/cache.m.iqiyi.com/mus/4649052441187801/2a5157249a6475c2fa5b9db6bd2e47a9/afbe8fd3d73448c9/1631611956081/20210715/fb/28/f2a481c6715a602b9c87fdb09d4d1b2b.m3u8?qd_time=1631591651714&qd_p=51474947&bossStatus=0&ff=ts&tvid=2768775694867800&vt=0&qd_originate=h5&k_uid=f68956166157db72db0208d339e7c086&tm=1631611956081&bid=500&src=02020031010000000000&code=2&_lnt=0&qd_uri=dash&qd_vip=0&sgti=15_f68956166157db72db0208d339e7c086_1631611956081&vf=319c5f660d786a0fbc2aa92bd6658354: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:492)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152)
        at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:154)
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:88) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8119)
        at libcore.io.IoBridge.open(IoBridge.java:478)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289) 
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152) 
        at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:154) 
        at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:88) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
2021-09-14 11:56:08.134 2816-4059/? E/OplusCustomizeRestrictionManager: getInstance
2021-09-14 11:56:08.143 2816-3616/? E/OplusCustomizeRestrictionManager: getInstance


```

**Comment by ZhuSky** [comment]
@CarGuo 大佬EXO也是不行，这个报错就我就很迷

**Comment by CarGuo** [comment]
切换到 exo 内核之后，如果视频 url 本身不存在格式封装后缀，需要使用 setOverrideExtension 指定

另外你看log啊， (No such file or directory)  http:/cache.m.iqiyi.com/mus/464 为什么用的是 FileDataSource

```

FileDataSourceException: com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: http:/cache.m.iqiyi.com/mus/4649052441187801/2a5157249a6475c2fa5b9db6bd2e47a9/afbe8fd3d73448c9/1631611956081/20210715/fb/28/f2a481c6715a602b9c87fdb09d4d1b2b.m3u8?qd_time=1631591651714&qd_p=51474947&bossStatus=0&ff=ts&tvid=2768775694867800&vt=0&qd_originate=h5&k_uid=f68956166157db72db0208d339e7c086&tm=1631611956081&bid=500&src=02020031010000000000&code=2&_lnt=0&qd_uri=dash&qd_vip=0&sgti=15_f68956166157db72db0208d339e7c086_1631611956081&vf=319c5f660d786a0fbc2aa92bd6658354: open failed: ENOENT

```

**Comment by ZhuSky** [comment]
“ FileDataSource” 这个我也很迷，不清楚为啥会这样

**Comment by ZhuSky** [comment]
setOverrideExtension
我设置了 mp4，依旧是这个错误

**Comment by CarGuo** [comment]
没明白你是怎么使用成了 upstream.FileDataSource ，明显不对

**Comment by ZhuSky** [comment]
我没修改 没设置😂 exo 播放类型，就是直接
setup
然后 start的。

大佬 IJK的应该怎么改一下 才能避免name too long 呢？

**Comment by CarGuo** [comment]
http:/50112.gzc.svp.tencent-cloud.com/gzc_1000102_0b53gqaagaaa5maps7jf3bq4angdam4aab2a.f10217.mp4?sdtfrom=v7016&guid=686998692a77e3790c04b553c3fc4a26_11001&vkey=70A2952678EEE5C06ADE8727554034A64C05ACB6CBFA4D339D708A614EA662B3FE80B4B7F279360E149E24C125BFBED6C084C59621D2E192BC15664D295B37B64EB56A69277F91911DE8ACA40F03EE29C518E31FC0798B0BAEAAF880FBC9FA498A15E59C590D2AE4D82F6B926CD481BE83BBE9442A506AE00EDD3CAB7C672086AE368C6AFF5BA69E


你看你的视频播放链接这么长，而且没办法打开啊，403

**Comment by ZhuSky** [comment]
http://cache.m.iqiyi.com/mus/4649052441187801/2a5157249a6475c2fa5b9db6bd2e47a9/afbe8fd3d73448c9/1631631591175/20210715/fb/28/f2a481c6715a602b9c87fdb09d4d1b2b.m3u8?qd_time=1631611286137&qd_p=5147790d&bossStatus=0&ff=ts&tvid=2768775694867800&vt=0&qd_originate=h5&k_uid=f68956166157db72db0208d339e7c086&tm=1631631591175&bid=500&src=02020031010000000000&code=2&_lnt=0&qd_uri=dash&qd_vip=0&sgti=15_f68956166157db72db0208d339e7c086_1631631591175&vf=edc60ae9c200df3a4bb241fd41e71395


User-Agent ->  Youku;7.5.2;Android;9;V1631611296A
Referer ->  https://www.iqiyi.com/v_qpn7ytiaes.html
IP ->  40.144.1.20

**Comment by ZhuSky** [comment]
@CarGuo 麻烦您试试这个，我这找到的url 带header

**Comment by CarGuo** [comment]
这个新url是 m3u8 的 ，加了你的 header 

然后使用 exo 内核，配置 setOverrideExtension("m3u8") ，如下所示正常播放：


![image](https://user-images.githubusercontent.com/10770362/133232553-b4b7f0dc-c847-4672-a861-34e83a9cfc2d.png)

**Comment by ZhuSky** [comment]
http://50001.gzc.svp.tencent-cloud.com/gzc_1000102_0b53kaaaiaaazyacrtjo5jq4augdaroaaaca.f10217.mp4?sdtfrom=v7016&guid=686998692a77e3790c04b553c3fc4a26_11001&vkey=5044AEE0D7B45DE96DCF9FBBD35D7C26D62DB57B376E601215C35596DAD678841FB14528A652856A72C9B33BC4830CB4C1206FDBB186062F08EFBC6C8A76A87F3F9AB3CE93275343C5BC51E3403B2B8DC818E31FC0798B0BAEAAF880FBC9FA498A15E59C590D2AE4D82F6B926CD481BE83BBE9442A506AE00EDD3CAB7C672086AE368C6AFF5BA69E


User-Agent ->  Youku;7.5.2;Android;9;V1631613199A
Referer ->  https://v.qq.com/x/cover/mzc00200xzrf1up/f0040q2g5e7.html
IP ->  41.18.23.1

**Comment by ZhuSky** [comment]
@CarGuo  麻烦您在试一下这个呢？

**Comment by ZhuSky** [comment]
URLEncoder.encode(videoUrl, "utf-8")
我的锅，设置url 的时候，转码了一下，导致exo播放出现问题，多谢大佬解惑
