### ISSUE TITLE
gradle 7.0 播放不了本地视频

### ISSUE THREAD

**Issue by Chen-Guilong** [CarGuo/GSYVideoPlayer#3390]
## 问题描述：

gradle 7.0 播放不了本地视频

## 问题机型/系统：

Android 7.1

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.6-jitpack'

## Demo中的复现步骤

build.gradle：dependencies {   classpath 'com.android.tools.build:gradle:7.0.2'  }

gradle-wrapper.properties：distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-bin.zip

问题代码：(如果有)
```
        StandardGSYVideoPlayer player = findViewById(R.id.player);
        player.getBackButton().setVisibility(View.GONE);
        player.getFullscreenButton().setVisibility(View.GONE);
        GSYVideoOptionBuilder builder = new GSYVideoOptionBuilder();
        builder
                .setBottomProgressBarDrawable(ResUtil.getDrawable(this, R.drawable.seekbar_color))
                .setBottomShowProgressBarDrawable(ResUtil.getDrawable(this, R.drawable.seekbar_color), ResUtil.getDrawable(this, R.drawable.seekbar_thumb))
                .setDismissControlTime(5000)
                .setCacheWithPlay(true)
                .setVideoTitle(title)
                .setUrl("/storage/56EF-2F75/视频/战争之王2.mp4")
                .build(player);
        player.startPlayLogic();
```

## 问题log（如果有）

2021-09-15 20:37:33.637 E: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:346)
        at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:774)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:587)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.net.MalformedURLException: no protocol: /storage/56EF-2F75/视频/战争之王2.mp4
        at java.net.URL.<init>(URL.java:589)
        at java.net.URL.<init>(URL.java:486)
        at java.net.URL.<init>(URL.java:435)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:488)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:339)
        at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:774) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:587) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
2021-09-15 20:37:33.645 E: playerFailed [3.05]
    com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:346)
        at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:774)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:587)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.net.MalformedURLException: no protocol: /storage/56EF-2F75/视频/战争之王2.mp4
        at java.net.URL.<init>(URL.java:589)
        at java.net.URL.<init>(URL.java:486)
        at java.net.URL.<init>(URL.java:435)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:488)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:339)
        at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:774) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:587) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)

**Comment by ag2s20150909** [comment]
用``` file:///storage/56EF-2F75/视频/战争之王2.mp4```

**Comment by CarGuo** [comment]
播放本地视频可以参考 demo 里面的 DetailPlayer 页面参考，另外需要用 file:/// 或者 Android SAF 播放

**Comment by Chen-Guilong** [comment]
CacheFactory.setCacheManager(ExoPlayerCacheManager.class); 
使用exo缓存模式，导致无法播放本地视频

**Comment by Chen-Guilong** [comment]
> 播放本地视频可以参考 demo 里面的 DetailPlayer 页面参考，另外需要用 file:/// 或者 Android SAF 播放

CacheFactory.setCacheManager(ExoPlayerCacheManager.class);
使用exo缓存模式，导致无法播放本地视频

**Comment by xiaanming** [comment]
CacheFactory.setCacheManager(ExoPlayerCacheManager.class); 使用exo缓存模式播放本地使用，可以使用如下
`ExoSourceManager.setExoMediaSourceInterceptListener(new ExoMediaSourceInterceptListener() {
            @Override
            public MediaSource getMediaSource(String dataSource, boolean preview, boolean cacheEnable, boolean isLooping, File cacheDir) {
                Uri contentUri = Uri.parse(dataSource);


                if ("file".equals(contentUri.getScheme())) {
                    MediaItem mediaItem = MediaItem.fromUri(contentUri);
                    DataSpec dataSpec = new DataSpec(contentUri);
                    final FileDataSource fileDataSource = new FileDataSource();
                    try {
                        fileDataSource.open(dataSpec);
                    } catch (FileDataSource.FileDataSourceException e) {
                        e.printStackTrace();
                    }
                    DataSource.Factory factory = new DataSource.Factory() {
                        @Override
                        public DataSource createDataSource() {
                            return fileDataSource;
                        }
                    };

                    return new ProgressiveMediaSource.Factory(factory).createMediaSource(mediaItem);

                }

                return null;
            }

            @Override
            public DataSource.Factory getHttpDataSourceFactory(String userAgent, @Nullable TransferListener listener, int connectTimeoutMillis, int readTimeoutMillis, Map<String, String> mapHeadData, boolean allowCrossProtocolRedirects) {
                return null;
            }

            @Override
            public DataSink.Factory cacheWriteDataSinkFactory(String CachePath, String url) {
                return null;
            }
        });`
