### ISSUE TITLE
在StrictMode模式报错

### ISSUE THREAD

**Issue by little3388** [CarGuo/GSYVideoPlayer#3412]
## 问题描述：

在StrictMode模式报错

## 问题机型/系统：

平板 Android5.11

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.6-jitpack'

## Demo中的复现步骤

Demo中的detailPlayer页面打开后，播放一段时间会出现这个问题。

##log

```

E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'release' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:184)
        at android.view.Surface.setNativeObjectLocked(Surface.java:460)
        at android.view.Surface.<init>(Surface.java:145)
        at com.shuyu.gsyvideoplayer.render.view.GSYTextureView.onSurfaceTextureAvailable(GSYTextureView.java:74)
        at android.view.TextureView.getHardwareLayer(TextureView.java:370)
        at android.view.View.updateDisplayListIfDirty(View.java:14274)
        at android.view.View.getDisplayList(View.java:14319)
        at android.view.View.draw(View.java:15089)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at android.view.View.updateDisplayListIfDirty(View.java:14292)
        at android.view.View.getDisplayList(View.java:14319)
        at android.view.View.draw(View.java:15089)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at android.view.View.draw(View.java:15364)
        at android.view.View.updateDisplayListIfDirty(View.java:14297)
        at android.view.View.getDisplayList(View.java:14319)
        at android.view.View.draw(View.java:15089)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at android.view.View.updateDisplayListIfDirty(View.java:14292)
        at android.view.View.getDisplayList(View.java:14319)
        at android.view.View.draw(View.java:15089)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at android.view.View.updateDisplayListIfDirty(View.java:14292)
        at android.view.View.getDisplayList(View.java:14319)
        at android.view.View.draw(View.java:15089)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1975)
        at android.view.View.draw(View.java:15364)
        at android.view.View.updateDisplayListIfDirty(View.java:14297)
        at android.view.View.getDisplayList(View.java:14319)
        at android.view.View.draw(View.java:15089)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at android.view.View.updateDisplayListIfDirty(View.java:14292)
        at android.view.View.getDisplayList(View.java:14319)
        at android.view.View.draw(View.java:15089)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at android.view.View.updateDisplayListIfDirty(View.java:14292)
        at android.view.View.getDisplayList(View.java:14319)
        at android.view.View.draw(View.java:15089)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
        at android.view.View.draw(View.java:15364)
        at android.widget.FrameLayout.draw(FrameLayout.java:600)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2837)
        at android.view.View.updateDisplayListIfDirty(View.java:14297)
        at android.view.View.getDisplayList(View.java:14319)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2646)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2468)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2098)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1161)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6198)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
    	at android.view.Choreographer.doFrame(Choreographer.java:550

```

**Comment by CarGuo** [comment]
不是很理解
