### ISSUE TITLE
播放一个无法访问的mp4地址出现anr

### ISSUE THREAD

**Issue by andyxm** [CarGuo/GSYVideoPlayer#3446]
播放了一个无法访问的mp4地址，在销毁时候ANR
使用demo中ListMultiVideoActivity更换这个地址后，也会出现ANR，一般都是在release，之前在UI线程_release直接卡住了，
在子线程relese后，虽然不影响UI了，但当我在打开这个地址后，还是会卡住主线程最后到达ANR
LOG:
2021-11-01 15:17:18.405 3855-3863/cn.com.shine.app W/art: Method processed more than once: java.lang.ref.Reference java.lang.ref.ReferenceQueue.remove(long)
2021-11-01 15:17:18.940 3855-3863/cn.com.shine.app W/art: Method processed more than once: android.os.Message android.os.MessageQueue.next()
2021-11-01 15:17:18.940 3855-3863/cn.com.shine.app W/art: Method processed more than once: void android.os.HandlerThread.run()
2021-11-01 15:17:18.941 3855-3863/cn.com.shine.app W/art: Method processed more than once: java.lang.ref.Reference java.lang.ref.ReferenceQueue.remove(long)
2021-11-01 15:17:18.956 3855-3863/cn.com.shine.app W/art: Method processed more than once: void java.lang.Thread.parkFor$(long)

/data/anr/traces.txt
"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 obj=0x748fa788 self=0xf5336500
  | sysTid=10046 nice=-4 cgrp=default sched=0/0 handle=0xf7542b34
  | state=S schedstat=( 6717125694 9053914011 18176 ) utm=521 stm=150 core=1 HZ=100
  | stack=0xff4df000-0xff4e1000 stackSize=8MB
  | held mutexes=
  kernel: __switch_to+0x7c/0x88
  kernel: futex_wait_queue_me+0xe8/0x14c
  kernel: futex_wait+0xf8/0x210
  kernel: do_futex+0xdc/0x8ac
  kernel: compat_SyS_futex+0xd4/0x14c
  kernel: cpu_switch_to+0x48/0x4c
  native: #00 pc 00017614  /system/lib/libc.so (syscall+28)
  native: #01 pc 0003fcf1  /system/lib/libc.so (pthread_join+124)
  native: #02 pc 00010151  /data/app/cn.com.shine.app-1/lib/arm/libijksdl.so (SDL_WaitThread+12)
  native: #03 pc 0001438d  /data/app/cn.com.shine.app-1/lib/arm/libijkplayer.so (???)IjkPlayerManager
  native: #04 pc 000197c7  /data/app/cn.com.shine.app-1/lib/arm/libijkplayer.so (ffp_wait_stop_l+14)
  native: #05 pc 0001f849  /data/app/cn.com.shine.app-1/lib/arm/libijkplayer.so (ijkmp_shutdown_l+28)
  native: #06 pc 00023019  /data/app/cn.com.shine.app-1/lib/arm/libijkplayer.so (???)
  native: #07 pc 01c2b36f  /data/app/cn.com.shine.app-1/oat/arm/base.odex (void tv.danmaku.ijk.media.player.IjkMediaPlayer._release()+74)
  native: #08 pc 01c2fb39  /data/app/cn.com.shine.app-1/oat/arm/base.odex (void tv.danmaku.ijk.media.player.IjkMediaPlayer.release()+172)
  native: #09 pc 01ac4e35  /data/app/cn.com.shine.app-1/oat/arm/base.odex (void com.shuyu.gsyvideoplayer.player.IjkPlayerManager.release()+88)
  native: #10 pc 0128961b  /data/app/cn.com.shine.app-1/oat/arm/base.odex (void com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(android.os.Message)+302)
  native: #11 pc 007d99d9  /data/dalvik-cache/arm/system@framework@boot.oat (???)
  at tv.danmaku.ijk.media.player.IjkMediaPlayer._release(Native method)
  at tv.danmaku.ijk.media.player.IjkMediaPlayer.release(IjkMediaPlayer.java:704)
  at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.release(IjkPlayerManager.java:188)
  at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:573)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5424)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:742)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:632)

**Comment by CarGuo** [comment]
看不出什么问题，请提供下测试地址

**Comment by andyxm** [comment]
我设备时无法访问外网的，但是测试时候加载的是一个外网的视频地址（地址也是demo中提供的视频地址），打开后，没问题，当我销毁时，就anr了，等了很久整个ui才不卡

**Comment by andyxm** [comment]
我设备时无法访问外网的，但是测试时候加载的是一个外网的视频地址（地址也是demo中提供的视频地址），打开后，视频虽然加载不出来，但也不会使ui卡顿，当我销毁时，就anr了，等了很久整个ui才不卡顿

**Comment by CarGuo** [comment]
我这边没能复现问题，
