### ISSUE TITLE
突然 EXOPlayer内核 无法播放MP4 链接视频了 

### ISSUE THREAD

**Issue by roger54920** [CarGuo/GSYVideoPlayer#3447]
## 问题描述：

上一分钟还好的，突然 EXOPlayer内核 无法播放MP4 链接视频了  ，直接黑屏了

## 出现问题的视频流

E/EventLogger: playerFailed [52.06]
    com.google.android.exoplayer2.ExoPlaybackException: null error, index=-1, format=null, format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$release$5(ExoPlayerImpl.java:832)
        at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$eZVQ1P4AuRBXX3IBVzj-JmjEs8k.invoke(Unknown Source:2)
        at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:283)
        at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:170)
        at com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$NbKDn9xtItiyMgYZmjIx_Sv1FFQ.run(Unknown Source:6)
        at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:191)
        at com.google.android.exoplayer2.util.ListenerSet.sendEvent(ListenerSet.java:206)
        at com.google.android.exoplayer2.ExoPlayerImpl.release(ExoPlayerImpl.java:828)
        at com.google.android.exoplayer2.SimpleExoPlayer.release(SimpleExoPlayer.java:1616)
        at tv.danmaku.ijk.media.exo2.IjkExo2MediaPlayer.reset(IjkExo2MediaPlayer.java:275)
        at tv.danmaku.ijk.media.exo2.IjkExo2MediaPlayer.release(IjkExo2MediaPlayer.java:346)
        at tv.danmaku.ijk.media.exo2.Exo2PlayerManager.release(Exo2PlayerManager.java:134)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:573)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7551)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
     Caused by: com.google.android.exoplayer2.ExoTimeoutException: Player release timed out.
        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$release$5(ExoPlayerImpl.java:831)
        at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$eZVQ1P4AuRBXX3IBVzj-JmjEs8k.invoke(Unknown Source:2) 
        at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:283) 
        at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:170) 
        at com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$NbKDn9xtItiyMgYZmjIx_Sv1FFQ.run(Unknown Source:6) 
        at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:191) 
        at com.google.android.exoplayer2.util.ListenerSet.sendEvent(ListenerSet.java:206) 
        at com.google.android.exoplayer2.ExoPlayerImpl.release(ExoPlayerImpl.java:828) 
        at com.google.android.exoplayer2.SimpleExoPlayer.release(SimpleExoPlayer.java:1616) 
        at tv.danmaku.ijk.media.exo2.IjkExo2MediaPlayer.reset(IjkExo2MediaPlayer.java:275) 
        at tv.danmaku.ijk.media.exo2.IjkExo2MediaPlayer.release(IjkExo2MediaPlayer.java:346) 
        at tv.danmaku.ijk.media.exo2.Exo2PlayerManager.release(Exo2PlayerManager.java:134) 
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:573) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7551) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995) 

## 问题机型/系统：

真机 小米pro8

## GSY依赖版本

    implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.6-jitpack'

问题代码：(如果有)

        PlayerFactory.setPlayManager(Exo2PlayerManager.class);

## 问题log（如果有）

E/EventLogger: playerFailed [52.06]
    com.google.android.exoplayer2.ExoPlaybackException: null error, index=-1, format=null, format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$release$5(ExoPlayerImpl.java:832)
        at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$eZVQ1P4AuRBXX3IBVzj-JmjEs8k.invoke(Unknown Source:2)
        at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:283)
        at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:170)
        at com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$NbKDn9xtItiyMgYZmjIx_Sv1FFQ.run(Unknown Source:6)
        at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:191)
        at com.google.android.exoplayer2.util.ListenerSet.sendEvent(ListenerSet.java:206)
        at com.google.android.exoplayer2.ExoPlayerImpl.release(ExoPlayerImpl.java:828)
        at com.google.android.exoplayer2.SimpleExoPlayer.release(SimpleExoPlayer.java:1616)
        at tv.danmaku.ijk.media.exo2.IjkExo2MediaPlayer.reset(IjkExo2MediaPlayer.java:275)
        at tv.danmaku.ijk.media.exo2.IjkExo2MediaPlayer.release(IjkExo2MediaPlayer.java:346)
        at tv.danmaku.ijk.media.exo2.Exo2PlayerManager.release(Exo2PlayerManager.java:134)
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:573)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7551)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
     Caused by: com.google.android.exoplayer2.ExoTimeoutException: Player release timed out.
        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$release$5(ExoPlayerImpl.java:831)
        at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$eZVQ1P4AuRBXX3IBVzj-JmjEs8k.invoke(Unknown Source:2) 
        at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:283) 
        at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:170) 
        at com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$NbKDn9xtItiyMgYZmjIx_Sv1FFQ.run(Unknown Source:6) 
        at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:191) 
        at com.google.android.exoplayer2.util.ListenerSet.sendEvent(ListenerSet.java:206) 
        at com.google.android.exoplayer2.ExoPlayerImpl.release(ExoPlayerImpl.java:828) 
        at com.google.android.exoplayer2.SimpleExoPlayer.release(SimpleExoPlayer.java:1616) 
        at tv.danmaku.ijk.media.exo2.IjkExo2MediaPlayer.reset(IjkExo2MediaPlayer.java:275) 
        at tv.danmaku.ijk.media.exo2.IjkExo2MediaPlayer.release(IjkExo2MediaPlayer.java:346) 
        at tv.danmaku.ijk.media.exo2.Exo2PlayerManager.release(Exo2PlayerManager.java:134) 
        at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:573) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7551) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995) 

xxxxxxx

```

**Comment by roger54920** [comment]
E/libc: Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer: [SurfaceTexture-1-32594-0](this:0x7dca0ce800,id:0,api:0,p:-1,c:32594) setConsumerName: SurfaceTexture-1-32594-0
W/ExoPlayer:Dummy: type=1400 audit(0.0:673272): avc: denied { read } for name="u:object_r:debug_bq_dump_prop:s0" dev="tmpfs" ino=12638 scontext=u:r:untrusted_app:s0:c28,c258,c512,c768 tcontext=u:object_r:debug_bq_dump_prop:s0 tclass=file permissive=0
E/GraphicExt: GraphicExtModuleLoader::CreateGraphicExtInstance false
E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0
I/System.out: [okhttp]:check permission begin!
W/System: ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out: [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out: [socket]:check permission begin!
W/System: ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I/System.out: [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I/System.out: [OkHttp] sendRequest>>
    [OkHttp] sendRequest<<
I/HttpProxyCacheDebuger: Opened connections: 0
I/HttpProxyCacheDebuger: Ping response: `ping ok`, pinged? true
I/HttpProxyCacheDebuger: Proxy cache server started. Is it alive? true
E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
    SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
