### ISSUE TITLE
rtmp拉流报错异常

### ISSUE THREAD

**Issue by silveryTitan** [CarGuo/GSYVideoPlayer#3453]
## 问题描述：

将demo的url修改成拉流地址后报错 Error fetching info from。FileNotFoundException:
使用的DetailListPlayer类修改的GSYVideoModel的url

## 出现问题的视频流

rtmp://u.yuezangbao.com:8080/live/1拉流

## 问题机型/系统：

真机，1+8t,小米8

## GSY依赖版本

v8.1.6-jitpack的demo

## Demo中的复现步骤

将demo中的DetailListPlayer类的urls.add中的url替换后运行 点击播放报错

问题代码：(如果有)
```

```

## 问题log（如果有）
把点击播放到结束的所有log都发在下面了
```

2021-11-14 10:56:02.110 2430-2430/com.example.gsyvideoplayer I/GSYVideoPlayer: onClickStartError
2021-11-14 10:56:02.110 2430-2430/com.example.gsyvideoplayer I/GSYVideoPlayer: onStartPrepared
2021-11-14 10:56:02.110 2430-2430/com.example.gsyvideoplayer W/AudioManager: Use of stream types is deprecated for operations other than volume control
2021-11-14 10:56:02.110 2430-2430/com.example.gsyvideoplayer W/AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
2021-11-14 10:56:02.117 2430-2430/com.example.gsyvideoplayer I/GSYVideoPlayer: changeUiToPreparingShow
2021-11-14 10:56:02.129 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_native_setup
2021-11-14 10:56:02.129 2430-2430/com.example.gsyvideoplayer I/IJKMEDIA: av_version_info: ff4.0--ijk0.8.8--20210205--001
2021-11-14 10:56:02.129 2430-2430/com.example.gsyvideoplayer I/IJKMEDIA: ijk_version_info: k0.8.8-32-ge99d640e
2021-11-14 10:56:02.129 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_create_from_android()
2021-11-14 10:56:02.129 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_inject_opaque(0x2ada)
2021-11-14 10:56:02.129 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_inject_opaque()=void
2021-11-14 10:56:02.129 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque(0x2ada)
2021-11-14 10:56:02.129 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_ijkio_inject_opaque()=void
2021-11-14 10:56:02.129 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
2021-11-14 10:56:02.129 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
2021-11-14 10:56:02.129 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
2021-11-14 10:56:02.131 2430-30688/com.example.gsyvideoplayer E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0
2021-11-14 10:56:02.135 2430-30688/com.example.gsyvideoplayer I/HttpProxyCacheDebuger: Ping response: `ping ok`, pinged? true
2021-11-14 10:56:02.136 2430-31182/com.example.gsyvideoplayer I/HttpProxyCacheDebuger: Opened connections: 0
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer D/tv.danmaku.ijk.media.player.IjkMediaPlayer: Couldn't open file on client side, trying server side
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer V/IJKMEDIA: setDataSource: path http://127.0.0.1:38571/http%3A%2F%2Fu.yuezangbao.com%3A8080%2Flive%2F1
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_data_source(url="http://127.0.0.1:38571/http%3A%2F%2Fu.yuezangbao.com%3A8080%2Flive%2F1")
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_data_source(url="http://127.0.0.1:38571/http%3A%2F%2Fu.yuezangbao.com%3A8080%2Flive%2F1")=0
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setOptionLong
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setLoopCount
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_native_setLogLevel(1)
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: moncleanup
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_setVolume
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_android_set_volume(1.000000, 1.000000)
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_set_volume
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_android_set_volume(1.000000, 1.000000)=void
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_prepareAsync
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_prepare_async()
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer I/IJKMEDIA: ===== versions =====
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer I/IJKMEDIA: ijkplayer    : k0.8.8-32-ge99d640e
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer I/IJKMEDIA: FFmpeg       : ff4.0--ijk0.8.8--20210205--001
2021-11-14 10:56:02.136 2430-31183/com.example.gsyvideoplayer I/IJKMEDIA: SDL_RunThread: [31183] ff_msg_loop
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer I/IJKMEDIA: libavutil    : 56.14.100
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer I/IJKMEDIA: libavcodec   : 58.18.100
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer I/IJKMEDIA: libavformat  : 58.12.100
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer I/IJKMEDIA: libswscale   : 5.1.100
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer I/IJKMEDIA: libswresample: 3.1.100
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer I/IJKMEDIA: ===== options =====
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer I/IJKMEDIA: player-opts : loop                         = 1
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer I/IJKMEDIA: format-opts : ijkapplication               = 0xc44dddd0
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer I/IJKMEDIA: format-opts : ijkiomanager                 = 0xe5aa34d0
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer I/IJKMEDIA: ===================
2021-11-14 10:56:02.136 2430-31183/com.example.gsyvideoplayer D/IJKMEDIA: message_loop
2021-11-14 10:56:02.136 2430-31183/com.example.gsyvideoplayer D/IJKMEDIA: FFP_MSG_FLUSH:
2021-11-14 10:56:02.136 2430-31184/com.example.gsyvideoplayer I/IJKMEDIA: SDL_RunThread: [31184] ff_vout
2021-11-14 10:56:02.136 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_prepare_async()=0
2021-11-14 10:56:02.136 2430-31185/com.example.gsyvideoplayer I/IJKMEDIA: SDL_RunThread: [31185] ff_read
2021-11-14 10:56:02.136 2430-31185/com.example.gsyvideoplayer D/IJKMEDIA: Opening 'http://127.0.0.1:38571/http%3A%2F%2Fu.yuezangbao.com%3A8080%2Flive%2F1' for reading
2021-11-14 10:56:02.136 2430-31185/com.example.gsyvideoplayer D/IJKMEDIA: Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto,httpproxy'
2021-11-14 10:56:02.137 2430-31185/com.example.gsyvideoplayer I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 1
2021-11-14 10:56:02.137 2430-31185/com.example.gsyvideoplayer I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131073
2021-11-14 10:56:02.137 2430-31185/com.example.gsyvideoplayer I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 131074
2021-11-14 10:56:02.137 2430-31185/com.example.gsyvideoplayer I/IJKMEDIA: tcp did open uri = tcp://127.0.0.1:38571, ip = 127.0.0.1
2021-11-14 10:56:02.137 2430-31185/com.example.gsyvideoplayer D/IJKMEDIA: request: GET /http%3A%2F%2Fu.yuezangbao.com%3A8080%2Flive%2F1 HTTP/1.1
    User-Agent: Lavf/58.12.100
    Accept: */*
    Range: bytes=0-
    Connection: close
    Host: 127.0.0.1:38571
    Icy-MetaData: 1
2021-11-14 10:56:02.140 2430-30691/com.example.gsyvideoplayer I/GSYVideoPlayer: ****** proxy addHeaders ****** 0
2021-11-14 10:56:02.140 2430-30691/com.example.gsyvideoplayer E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0
2021-11-14 10:56:02.249 2430-30691/com.example.gsyvideoplayer E/HttpProxyCacheDebuger: Error fetching info from http://u.yuezangbao.com:8080/live/1
2021-11-14 10:56:02.250 2430-30691/com.example.gsyvideoplayer W/System.err: java.io.FileNotFoundException: http://u.yuezangbao.com:8080/live/1
2021-11-14 10:56:02.250 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
2021-11-14 10:56:02.250 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpUrlSource.fetchContentInfo(HttpUrlSource.java:151)
2021-11-14 10:56:02.250 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpUrlSource.getMime(HttpUrlSource.java:223)
2021-11-14 10:56:02.250 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpProxyCache.newResponseHeaders(HttpProxyCache.java:61)
2021-11-14 10:56:02.250 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:41)
2021-11-14 10:56:02.251 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
2021-11-14 10:56:02.251 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:233)
2021-11-14 10:56:02.251 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54)
2021-11-14 10:56:02.251 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:335)
2021-11-14 10:56:02.251 2430-30691/com.example.gsyvideoplayer W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
2021-11-14 10:56:02.251 2430-30691/com.example.gsyvideoplayer W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-11-14 10:56:02.251 2430-30691/com.example.gsyvideoplayer W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-11-14 10:56:02.251 2430-30691/com.example.gsyvideoplayer W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-11-14 10:56:02.252 2430-30691/com.example.gsyvideoplayer W/System.err:     at java.lang.Thread.run(Thread.java:923)
2021-11-14 10:56:02.254 2430-30691/com.example.gsyvideoplayer I/GSYVideoPlayer: ****** proxy addHeaders ****** 0
2021-11-14 10:56:02.254 2430-30691/com.example.gsyvideoplayer E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0
2021-11-14 10:56:02.387 2430-30691/com.example.gsyvideoplayer E/HttpProxyCacheDebuger: Error fetching info from http://u.yuezangbao.com:8080/live/1
2021-11-14 10:56:02.387 2430-30691/com.example.gsyvideoplayer W/System.err: java.io.FileNotFoundException: http://u.yuezangbao.com:8080/live/1
2021-11-14 10:56:02.388 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
2021-11-14 10:56:02.388 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpUrlSource.fetchContentInfo(HttpUrlSource.java:151)
2021-11-14 10:56:02.388 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpUrlSource.length(HttpUrlSource.java:81)
2021-11-14 10:56:02.388 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpProxyCache.newResponseHeaders(HttpProxyCache.java:63)
2021-11-14 10:56:02.388 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:41)
2021-11-14 10:56:02.388 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
2021-11-14 10:56:02.388 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:233)
2021-11-14 10:56:02.389 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54)
2021-11-14 10:56:02.389 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:335)
2021-11-14 10:56:02.389 2430-30691/com.example.gsyvideoplayer W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
2021-11-14 10:56:02.389 2430-30691/com.example.gsyvideoplayer W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-11-14 10:56:02.389 2430-30691/com.example.gsyvideoplayer W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-11-14 10:56:02.389 2430-30691/com.example.gsyvideoplayer W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-11-14 10:56:02.389 2430-30691/com.example.gsyvideoplayer W/System.err:     at java.lang.Thread.run(Thread.java:923)
2021-11-14 10:56:02.390 2430-30691/com.example.gsyvideoplayer I/GSYVideoPlayer: ****** proxy addHeaders ****** 0
2021-11-14 10:56:02.391 2430-30691/com.example.gsyvideoplayer E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0
2021-11-14 10:56:02.461 2430-30691/com.example.gsyvideoplayer E/HttpProxyCacheDebuger: Error fetching info from http://u.yuezangbao.com:8080/live/1
2021-11-14 10:56:02.461 2430-30691/com.example.gsyvideoplayer W/System.err: java.io.FileNotFoundException: http://u.yuezangbao.com:8080/live/1
2021-11-14 10:56:02.461 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
2021-11-14 10:56:02.461 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpUrlSource.fetchContentInfo(HttpUrlSource.java:151)
2021-11-14 10:56:02.461 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpUrlSource.length(HttpUrlSource.java:81)
2021-11-14 10:56:02.461 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpProxyCache.isUseCache(HttpProxyCache.java:53)
2021-11-14 10:56:02.462 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpProxyCache.processRequest(HttpProxyCache.java:45)
2021-11-14 10:56:02.462 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpProxyCacheServerClients.processRequest(HttpProxyCacheServerClients.java:42)
2021-11-14 10:56:02.462 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:233)
2021-11-14 10:56:02.462 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:54)
2021-11-14 10:56:02.462 2430-30691/com.example.gsyvideoplayer W/System.err:     at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:335)
2021-11-14 10:56:02.462 2430-30691/com.example.gsyvideoplayer W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
2021-11-14 10:56:02.462 2430-30691/com.example.gsyvideoplayer W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-11-14 10:56:02.462 2430-30691/com.example.gsyvideoplayer W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-11-14 10:56:02.463 2430-30691/com.example.gsyvideoplayer W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-11-14 10:56:02.463 2430-30691/com.example.gsyvideoplayer W/System.err:     at java.lang.Thread.run(Thread.java:923)
2021-11-14 10:56:02.465 2430-31187/com.example.gsyvideoplayer I/GSYVideoPlayer: ****** proxy addHeaders ****** 0
2021-11-14 10:56:02.465 2430-31187/com.example.gsyvideoplayer E/HttpProxyCacheDebuger: ****** injectCustomHeaders ****** :0
2021-11-14 10:56:02.570 2430-31187/com.example.gsyvideoplayer E/ProxyCache error: Error opening connection for http://u.yuezangbao.com:8080/live/1 with offset 0. Version: 8.1.2
2021-11-14 10:56:02.571 2430-30691/com.example.gsyvideoplayer E/HttpProxyCacheServer error: Error processing request. Version: 8.1.2
2021-11-14 10:56:02.572 2430-30691/com.example.gsyvideoplayer I/HttpProxyCacheDebuger: Opened connections: 0
2021-11-14 10:56:02.573 2430-31185/com.example.gsyvideoplayer I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
2021-11-14 10:56:02.574 2430-31185/com.example.gsyvideoplayer E/IJKMEDIA: http://127.0.0.1:38571/http%3A%2F%2Fu.yuezangbao.com%3A8080%2Flive%2F1: End of file
2021-11-14 10:56:02.574 2430-31185/com.example.gsyvideoplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [31185]
2021-11-14 10:56:02.574 2430-31183/com.example.gsyvideoplayer D/IJKMEDIA: FFP_MSG_ERROR: 0
2021-11-14 10:56:02.574 2430-2430/com.example.gsyvideoplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
2021-11-14 10:56:02.574 2430-2430/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer
2021-11-14 10:56:02.575 2430-2430/com.example.gsyvideoplayer I/GSYVideoPlayer: changeUiToError
2021-11-14 10:56:02.579 2430-2430/com.example.gsyvideoplayer E/GSYVideoPlayer: Link Or mCache Error, Please Try Again http://u.yuezangbao.com:8080/live/1
2021-11-14 10:56:02.579 2430-2430/com.example.gsyvideoplayer E/GSYVideoPlayer: mCache Link http://u.yuezangbao.com:8080/live/1
2021-11-14 10:56:02.579 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: IjkMediaPlayer_release
2021-11-14 10:56:02.579 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
2021-11-14 10:56:02.579 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ffpipeline_set_surface()
2021-11-14 10:56:02.579 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
2021-11-14 10:56:02.579 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_shutdown_l()
2021-11-14 10:56:02.579 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: wait for read_tid
2021-11-14 10:56:02.579 2430-31183/com.example.gsyvideoplayer D/IJKMEDIA: message_loop exit
2021-11-14 10:56:02.579 2430-31183/com.example.gsyvideoplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [31183]
2021-11-14 10:56:02.579 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: wait for video_refresh_tid
2021-11-14 10:56:02.582 2430-31184/com.example.gsyvideoplayer I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [31184]
2021-11-14 10:56:02.582 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_shutdown_l()=void
2021-11-14 10:56:02.582 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_dec_ref(): ref=0
2021-11-14 10:56:02.582 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_shutdown_l()
2021-11-14 10:56:02.582 2430-2430/com.example.gsyvideoplayer D/IJKMEDIA: ijkmp_shutdown_l()=void
2021-11-14 10:56:02.582 2430-2430/com.example.gsyvideoplayer E/GSYVideoPlayer: cancelTimeOutBuffer


```

**Comment by silveryTitan** [comment]
麻烦帮我看看是哪里的问题

**Comment by silveryTitan** [comment]
补一下，推流地址是rtmp://u.yuezangbao.com/live/1  拉流地址http://u.yuezangbao.com:8080/live/1

**Comment by bingdu0** [comment]
直播流需要关闭缓存

**Comment by CarGuo** [comment]
直播流需要关闭缓存

**Comment by silveryTitan** [comment]
是setUp方法的第二个参数设置为false嘛？如果是的话，没有生效

**Comment by silveryTitan** [comment]
可以了 谢谢
