### ISSUE TITLE
生成gif图，点击全屏会报错

### ISSUE THREAD

**Issue by lwq321** [CarGuo/GSYVideoPlayer#3467]
## 问题描述：
在生成gif图，点击全屏会报错，报错日志为java.lang.IllegalArgumentException: width and height must be > 0
## 出现问题的视频流
https://res.exexm.com/cw_145225549855002
## 问题机型/系统：
 真机 Redmi 6 Pro   MIUI 12.0.1/android 9

## GSY依赖版本
 `com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.7-release-jitpack`

## Demo中的复现步骤

Demo中的DetailControlActivity页面打开后点击开始GIF,然后再点击全屏操作，就会出现奔溃

问题代码：(如果有)
 mPlayer.saveFrame(file, true, new GSYVideoShotSaveListener() {
            @Override
            public void result(boolean success, final File file) {
                mSaveShotBitmapSuccess = true;
                if (success) {
                    Debuger.printfError(" SUCCESS CREATE FILE " + file.getAbsolutePath());
                    mPicList.add(file.getAbsolutePath());
                    mPicListFile.add(file);
                }
            }
        });

## 问题log（如果有）
 java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1033)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1000)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:950)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:911)
        at com.shuyu.gsyvideoplayer.render.view.GSYTextureView.initCoverHigh(GSYTextureView.java:147)
        at com.shuyu.gsyvideoplayer.render.view.GSYTextureView.saveFrame(GSYTextureView.java:187)
        at com.shuyu.gsyvideoplayer.render.GSYRenderView.saveFrame(GSYRenderView.java:157)
        at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.saveFrame(StandardGSYVideoPlayer.java:874)
        at com.shuyu.gsyvideoplayer.utils.GifCreateHelper.startSaveBitmap(GifCreateHelper.java:132)
        at com.shuyu.gsyvideoplayer.utils.GifCreateHelper.access$800(GifCreateHelper.java:29)
        at com.shuyu.gsyvideoplayer.utils.GifCreateHelper$TaskLocal.run(GifCreateHelper.java:233)
        at java.util.TimerThread.mainLoop(Timer.java:562)
        at java.util.TimerThread.run(Timer.java:512)

**Comment by CarGuo** [comment]
生成gif过程中不能做其他动作

**Comment by lwq321** [comment]
> 生成gif过程中不能做其他动作

大佬，能不能加个录屏的功能

**Comment by CarGuo** [comment]
录屏调系统API就好了

**Comment by lwq321** [comment]
> 录屏调系统API就好了
这边是想录制正在播放的视频，窗口也是当前播放视频的窗口，有看到ijkplayer重新编译底层代码实现的做法

**Comment by CarGuo** [comment]
具体你可以自己编译so替换
