### ISSUE TITLE
Exo内核播放错误: MediaCodecVideoRenderer: Video codec error

### ISSUE THREAD

**Issue by bozuo** [CarGuo/GSYVideoPlayer#3474]
## 问题描述：

EXO内核陆续播放十几个视频后，会偶现播放错误后无法解码，导致应用内所有播放器都无法播放，有声音无画面

注： 播放结束播放器都有回收，exo播放器也有类似错误，还没找到解决方案

## 问题机型/系统：

 中兴机顶盒  B860AV2.1-T S   Android 4.4.2

## 问题log

2021-12-15 10:23:20.763 7631-11834/com.staryea.sclauncher E/BufferQueue: [unnamed-7631-93] dequeueBuffer: SurfaceComposer::createGraphicBuffer failed
2021-12-15 10:23:20.763 7631-11834/com.staryea.sclauncher E/ACodec: dequeueBuffer failed: Operation not permitted (1)
2021-12-15 10:23:20.763 7631-11834/com.staryea.sclauncher E/ACodec: Failed to allocate buffers after transitioning to IDLE state (error 0xffffffff)
2021-12-15 10:23:20.763 7631-11834/com.staryea.sclauncher V/ACodec: [OMX.amlogic.avc.decoder.awesome] Now Loaded
2021-12-15 10:23:20.763 7631-11833/com.staryea.sclauncher E/MediaCodec: Codec reported an error. (omx error 0x80001001, internalError -1)
2021-12-15 10:23:20.763 7631-11834/com.staryea.sclauncher V/ACodec: Now uninitialized
2021-12-15 10:23:20.763 7631-11825/com.staryea.sclauncher E/Surface: [~Surface 82] this:0xab5d9498 mConnectedToCpu:0
2021-12-15 10:23:20.763 7631-11825/com.staryea.sclauncher W/MediaCodecRenderer: Failed to initialize decoder: OMX.amlogic.avc.decoder.awesome
      java.lang.IllegalStateException: start failed
        at android.media.MediaCodec.start(Native Method)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:69)
        at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:124)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1063)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:982)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:540)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:770)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
2021-12-15 10:23:20.763 7631-11825/com.staryea.sclauncher E/MediaCodecVideoRenderer: Video codec error
      com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome, Format(1/100, null, null, video/avc, avc1.4D4028, -1, null, [1920, 1080, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:989)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:540)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:770)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalStateException: start failed
        at android.media.MediaCodec.start(Native Method)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:69)
        at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:124)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1063)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:982)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:540) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:770) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
2021-12-15 10:23:20.763 7631-11825/com.staryea.sclauncher D/MediaCodecInfo: NoSupport [codec.profileLevel, avc1.4D4028, video/avc] [OMX.google.h264.decoder, video/avc] [p200_2G, B860AV2.1-T, ZTE Corporation, 19]
2021-12-15 10:23:20.773 7631-11825/com.staryea.sclauncher E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1/100, null, null, video/avc, avc1.4D4028, -1, null, [1920, 1080, -1.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:562)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.amlogic.avc.decoder.awesome, Format(1/100, null, null, video/avc, avc1.4D4028, -1, null, [1920, 1080, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:989)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:540)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:770)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: java.lang.IllegalStateException: start failed
        at android.media.MediaCodec.start(Native Method)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:69)
        at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:124)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1063)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:982)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:540) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:770) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:982) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:486) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by CarGuo** [comment]
dequeueBuffer failed: Operation not permitted  看起来系统对于内存管理有问题

**Comment by bozuo** [comment]
机顶盒性能比较垃圾，大佬有办法解决吗

**Comment by Guang1234567** [comment]
> 机顶盒性能比较垃圾，大佬有办法解决吗

- 换个机顶盒, 

- 又或者把 exo 的库降低回 android 4.4 同时期的版本,   我知道你想要作者帮你干这个事情,  2千块不知道干不干....

- 期望 ijk 内核的软件解码, 做到内存占用比较低, 低到满足你的android 4.4 的机器

```java
   // 切换方式
    PlayerFactory.setPlayManager(IjkPlayerManager.class); 
```

**Comment by bozuo** [comment]
有用到EXO倍数播放和自适应码率等功能，不能换IJK，如果能够解决这个问题，都可以商量哈

**Comment by bozuo** [comment]
> 

联系方式可以给下吗

**Comment by Guang1234567** [comment]
还没放弃....  就算解决这种问题, 你也得给  库 的作者寄一台硬件..... 我也是醉了

**Comment by bozuo** [comment]
好吧，感谢

**Comment by paofan** [comment]
> 
我也是同样的问题，头疼

**Comment by bozuo** [comment]
> > 
> 
> 我也是同样的问题，头疼

有解决办法吗

**Comment by paofan** [comment]
> > > 
> > 
> > 
> > 我也是同样的问题，头疼
> 
> 有解决办法吗
我换 IjkPlayerManager试下

**Comment by bozuo** [comment]
> dequeueBuffer failed: Operation not permitted 看起来系统对于内存管理有问题
郭哥  方便的话联系15366199757,微信同号，能解决的话费用可以商量
