### ISSUE TITLE
8.1.7版本使用exo类型播放，部分格式会出现内部报错

### ISSUE THREAD

**Issue by zhf99love** [CarGuo/GSYVideoPlayer#3488]
## 问题描述：

8.1.7版本使用exo类型播放，部分格式会出现内部报错
退回版本为8.1.6则正常播放

## 出现问题的视频流

https://www.qycloud.com.cn/api/download/forKey?host=aliyun&fileName=62b97731ecc7cf42fab01cbf09480967.mp4&filePath=qFile%2FqChat%2Fim00000097981640920421746_626_62b97731ecc7cf42fab0.mp4&expires=-1&iosType=qycloudwebchat&sign=MTY0MDkyMDQyMjpKOE5mK3ZWZW9HcDBrN0pnSHlkK0NCN0dURXV3SVZqTDRZYzgzaU44UnArcmRBWXE0Y2ZiSlArSnIxeEgrbzZoUHprcm5lNitKUktoem1oWnZMcGM2dz09OkVoN0dNYkJMN3NIYXFaU3I5azRDc3lJV2x3NFl5K1g5YjRWanVHaFpoWE5kaUFmVEhBMGJUaGEzOHJjN2IzeDVYRTZiWEJ1azRCNW9BWnNoNzlacm9nPT0=&styles=eyJmaWxlSU9Eb21haW4iOiJodHRwczovL3d3dy5xeWNsb3VkLmNvbS5jbiJ9

或者

https://user-images.githubusercontent.com/10767119/147806204-ed38b392-14d0-4917-a95c-53d8a52f8662.mp4

## 问题机型/系统：

全部Android

## GSY依赖版本

    //播放器
    api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.7-jitpack'
    //是否需要ExoPlayer模式
    api 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.1.7-jitpack'
    api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.1.7-jitpack'

## Demo中的复现步骤

播放该视频就直接黑屏

## 问题log（如果有）

2021-12-31 13:53:37.243 15466-15466/com.android.ayplatform W/Settings: Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
2021-12-31 13:53:37.243 15466-15466/com.android.ayplatform V/HiTouch_HiTouchSensor: User setup is finished.
2021-12-31 13:53:37.302 15466-15466/com.android.ayplatform V/AudioManager: playSoundEffect   effectType: 0
2021-12-31 13:53:37.302 15466-15466/com.android.ayplatform V/AudioManager: querySoundEffectsEnabled...
2021-12-31 13:53:37.304 15466-15466/com.android.ayplatform V/AudioManager: unregisterAudioFocusListener...
2021-12-31 13:53:37.304 15466-15466/com.android.ayplatform I/AudioManager: abandonAudioFocus
2021-12-31 13:53:37.314 15466-15466/com.android.ayplatform V/AudioManager: unregisterAudioFocusListener...
2021-12-31 13:53:37.315 15466-15466/com.android.ayplatform I/AudioManager: abandonAudioFocus
2021-12-31 13:53:37.317 15466-15466/com.android.ayplatform I/Window: window clear KeepScreenOnFlag for com.android.ayplatform
2021-12-31 13:53:37.320 15466-15466/com.android.ayplatform V/AudioManager: requestAudioFocus  streamType: 3  durationHint: 2
2021-12-31 13:53:37.320 15466-15466/com.android.ayplatform V/AudioManager: registerAudioFocusListener...
2021-12-31 13:53:37.324 15466-15466/com.android.ayplatform I/Window: window add KeepScreenOnFlag for com.android.ayplatform
2021-12-31 13:53:37.379 15466-15466/com.android.ayplatform I/ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
2021-12-31 13:53:37.442 15466-15466/com.android.ayplatform I/ExoPlayerImpl: Init ee95e2 [ExoPlayerLib/2.15.1] [HWPAR, PAR-AL00, HUAWEI, 28]
2021-12-31 13:53:37.448 15466-15466/com.android.ayplatform V/AudioManager: getStreamVolume  streamType: 3 volume: 0
2021-12-31 13:53:37.448 15466-15466/com.android.ayplatform V/AudioManager: isStreamMute   streamType: 3
2021-12-31 13:53:37.452 15466-15466/com.android.ayplatform V/AudioManager: getStreamMaxVolume  treamType: 3
2021-12-31 13:53:37.469 15466-15466/com.android.ayplatform D/EventLogger: state [0.05, B]
2021-12-31 13:53:37.481 15466-15466/com.android.ayplatform D/EventLogger: loading [true]
2021-12-31 13:53:37.482 15466-15814/com.android.ayplatform E/LoadTask: Unexpected exception loading stream
      java.lang.ArrayIndexOutOfBoundsException: length=162; index=162
        at com.google.android.exoplayer2.util.ParsableByteArray.readUnsignedByte(ParsableByteArray.java:233)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseVideoSampleEntry(AtomParsers.java:1203)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:949)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:308)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTraks(AtomParsers.java:130)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:483)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:442)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:424)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:242)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1047)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
2021-12-31 13:53:37.488 15466-15813/com.android.ayplatform E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:624)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:600)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected ArrayIndexOutOfBoundsException: length=162; index=162
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:430)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=162; index=162
        at com.google.android.exoplayer2.util.ParsableByteArray.readUnsignedByte(ParsableByteArray.java:233)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseVideoSampleEntry(AtomParsers.java:1203)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:949)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:308)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTraks(AtomParsers.java:130)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:483)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:442)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:424)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:242)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1047)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:784) 
2021-12-31 13:53:37.497 15466-15466/com.android.ayplatform E/EventLogger: playerFailed [0.07]
    com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:624)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:600)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected ArrayIndexOutOfBoundsException: length=162; index=162
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:430)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=162; index=162
        at com.google.android.exoplayer2.util.ParsableByteArray.readUnsignedByte(ParsableByteArray.java:233)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseVideoSampleEntry(AtomParsers.java:1203)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStsd(AtomParsers.java:949)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTrak(AtomParsers.java:308)
        at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseTraks(AtomParsers.java:130)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:483)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:442)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:424)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:242)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1047)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:784) 
2021-12-31 13:53:37.498 15466-15466/com.android.ayplatform D/EventLogger: loading [false]
2021-12-31 13:53:37.500 15466-15466/com.android.ayplatform D/EventLogger: state [0.08, I]
2021-12-31 13:53:37.512 15466-15466/com.android.ayplatform I/ExoPlayerImpl: Release ee95e2 [ExoPlayerLib/2.15.1] [HWPAR, PAR-AL00, HUAWEI, 28] [goog.exo.core]

**Comment by CarGuo** [comment]
setOverrideExtension("mp4");

**Comment by seapeak233** [comment]
设置了并没有什么用，最终还是降版本到8.1.6

**Comment by CarGuo** [comment]
我看了下 readUnsignedByte 的时候居然因为 position 越位了·····  我一开始以为是识别不到编码，我下个版本修复下

**Comment by seapeak233** [comment]
OK。感谢大佬

**Comment by 333bkz** [comment]
+1

**Comment by CarGuo** [comment]
@333bkz 请提供你的测试链接

**Comment by LiQinglin007** [comment]
> 设置了并没有什么用，最终还是降版本到8.1.6

这个版本可以？
