### ISSUE TITLE
播放MOV格式视频出现oom错误

### ISSUE THREAD

**Issue by L-X-J** [CarGuo/GSYVideoPlayer#3504]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

播放mov视频出现oom错误

## 出现问题的视频流

https://cos.icxl.xyz/c03328206d894477a3f8c9767a4de5649342908.mov

## 问题机型/系统：

自由设备 原生Android 6.0.1

## GSY依赖版本
```
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-exo_player2:v8.1.5-jitpack'
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer:v8.1.5-jitpack'
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-armv7a:v8.1.6-jitpack'
```
## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

 com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected OutOfMemoryError: Failed to allocate a 65548 byte allocation with 41536 free bytes and 40KB until OOM
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:446)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 65548 byte allocation with 41536 free bytes and 40KB until OOM
        at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:104)
        at com.google.android.exoplayer2.source.SampleDataQueue.preAppend(SampleDataQueue.java:240)
        at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:174)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:579)
        at com.google.android.exoplayer2.extractor.TrackOutput$-CC.$default$sampleData(TrackOutput.java:159)
        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:615)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:249)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1049)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 

```

**Comment by CarGuo** [comment]
![image](https://user-images.githubusercontent.com/10770362/153133044-851cdb8f-7d63-439c-afcb-7d4e995e2871.png)
demo 测试正常

**Comment by L-X-J** [comment]
我现在使用  `SystemPlayerManager`是可以的
```kotlin 
PlayerFactory.setPlayManager(SystemPlayerManager::class.java)
```

**Comment by L-X-J** [comment]
我是下载到本地播放的 不是在线播放
exo模式也是下载本地播放的
