### ISSUE TITLE
视频无法播放403

### ISSUE THREAD

**Issue by 50kg** [CarGuo/GSYVideoPlayer#3512]
视频流：https://player.novipnoad.com/vod/hls/1621988884864_sgclggjcgglg.m3u8

ijk时间轴不对，exo播放403

已经忽略证书
ExoSourceManager.setSkipSSLChain(true);

已设置m3u8
setOverrideExtension("m3u8");

已关闭缓存
setUp(videoUrl, false, title);

版本是v8.1.9-release

demo也是同样的问题

Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:628)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:600)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:257)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
        at com.movie.heaven.widget.video.GSYDefaultHttpDataSource.open(GSYDefaultHttpDataSource.java:354)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:483)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:457)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:432)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:388)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:409)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

感谢，致敬

**Comment by 50kg** [comment]
补充：safari和android qq浏览器正常

**Comment by CarGuo** [comment]
![image](https://user-images.githubusercontent.com/10770362/155914002-cbd05306-e03f-465a-9963-0ad9cc2cce69.png)

**Comment by CarGuo** [comment]
![image](https://user-images.githubusercontent.com/10770362/155916234-67fcbed4-45f5-4294-87c6-56fddf498932.png)
![image](https://user-images.githubusercontent.com/10770362/155916254-a8ae832c-0c70-49fb-9275-4cc3e4fd8006.png)
demo 里 exo 屏蔽了这段就好了
