### ISSUE TITLE
m3u8下载后无法播放，key也下载了的

### ISSUE THREAD

**Issue by cl19881314** [CarGuo/GSYVideoPlayer#3534]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

m3u8下载后无法播放，key也下载了的

## 问题机型/系统：

例如 真机 荣耀8

## GSY依赖版本

com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.1.8-release-jitpack'
com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.1.8-release-jitpack

## Demo中的复现步骤

视频能正常播放，但是用aria,下载后无法播放，ts和秘钥key都下载到本地了

问题代码：(如果有)
PlayerFactory.setPlayManager(Exo2PlayerManager::class.java)

播放
		        val header = HashMap<String, String>()
//        header["ee"] = "33"
        header["allowCrossProtocolRedirects"] = "true"
        gsyVideoOption = GSYVideoOptionBuilder()
        gsyVideoOption!!.setThumbImageView(iv_thumb)
            .setDismissControlTime(2500)
//            .setIsTouchWiget(true)
//            .setRotateViewAuto(false)
//            .setLockLand(true)
//            .setAutoFullWithSize(false)
//            .setNeedLockFull(true)
            .setMapHeadData(header)
            .setUrl(playUrl)
            .setCacheWithPlay(false)
            .setVideoTitle("")
            .setSeekRatio(5f)
            .setShowFullAnimation(false)
            .setOverrideExtension("m3u8") 
			.build(detailPlayer?.currentPlayer)

## 问题log（如果有）
    Unexpected exception handling load completed
      java.lang.NumberFormatException: Invalid BigInteger: null
        at java.math.BigInt.invalidBigInteger(BigInt.java:86)
        at java.math.BigInt.checkString(BigInt.java:140)
        at java.math.BigInt.putHexString(BigInt.java:99)
        at java.math.BigInteger.<init>(BigInteger.java:244)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.getEncryptionIvArray(HlsMediaChunk.java:582)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.createInstance(HlsMediaChunk.java:108)
        at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextChunk(HlsChunkSource.java:440)
        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continueLoading(HlsSampleStreamWrapper.java:740)
        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.onLoadCompleted(HlsSampleStreamWrapper.java:843)
        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.onLoadCompleted(HlsSampleStreamWrapper.java:92)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:475)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.os.HandlerThread.run(HandlerThread.java:65)
  E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:624)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:600)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:166)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected NumberFormatException: Invalid BigInteger: null
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:479)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: java.lang.NumberFormatException: Invalid BigInteger: null
        at java.math.BigInt.invalidBigInteger(BigInt.java:86)
        at java.math.BigInt.checkString(BigInt.java:140)
        at java.math.BigInt.putHexString(BigInt.java:99)
        at java.math.BigInteger.<init>(BigInteger.java:244)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.getEncryptionIvArray(HlsMediaChunk.java:582)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.createInstance(HlsMediaChunk.java:108)
        at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextChunk(HlsChunkSource.java:440)
        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continueLoading(HlsSampleStreamWrapper.java:740)
        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.onLoadCompleted(HlsSampleStreamWrapper.java:843)
        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.onLoadCompleted(HlsSampleStreamWrapper.java:92)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:475)
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
E/EventLogger: playerFailed [0.26]
    com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:624)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:600)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:166)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected NumberFormatException: Invalid BigInteger: null
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:479)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
     Caused by: java.lang.NumberFormatException: Invalid BigInteger: null
        at java.math.BigInt.invalidBigInteger(BigInt.java:86)
        at java.math.BigInt.checkString(BigInt.java:140)
        at java.math.BigInt.putHexString(BigInt.java:99)
        at java.math.BigInteger.<init>(BigInteger.java:244)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.getEncryptionIvArray(HlsMediaChunk.java:582)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.createInstance(HlsMediaChunk.java:108)
        at com.google.android.exoplayer2.source.hls.HlsChunkSource.getNextChunk(HlsChunkSource.java:440)
        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.continueLoading(HlsSampleStreamWrapper.java:740)
        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.onLoadCompleted(HlsSampleStreamWrapper.java:843)
        at com.google.android.exoplayer2.source.hls.HlsSampleStreamWrapper.onLoadCompleted(HlsSampleStreamWrapper.java:92)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.handleMessage(Loader.java:475)
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 

D/M3U8InfoThread: #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1200000,RESOLUTION=720x406
 D/M3U8InfoThread: 新码率url：https://v4.cdtlas.com/20211117/tzDmHfD8/1200kb/hls/index.m3u8
 W/System: Ignoring header Cookie because its value was null.
 I/qtaguid: Tagging socket 105 with tag 713596d600000000(1899337430) for uid -1 failed errno=-24
 I/NetworkManagementSocketTagger: tagSocketFd(105, 1899337430, -1) failed with errno-24
 W/libEGL: EGLNativeWindowType 0xbe96e808 disconnect failed
 D/M3U8InfoThread: #EXTM3U
 D/M3U8InfoThread: #EXT-X-VERSION:3
 D/M3U8InfoThread: #EXT-X-TARGETDURATION:4
 D/M3U8InfoThread: #EXT-X-PLAYLIST-TYPE:VOD
 D/M3U8InfoThread: #EXT-X-MEDIA-SEQUENCE:0
 D/M3U8InfoThread: #EXT-X-KEY:METHOD=AES-128,URI="https://hey07.789zy.cc/20211117/tzDmHfD8/1200kb/hls/key.key"
 D/M3U8InfoThread: 密钥不存在，下载密钥
 I/qtaguid: Tagging socket 152 with tag 713596d600000000(1899337430) for uid -1 failed errno=-24
 I/NetworkManagementSocketTagger: tagSocketFd(152, 1899337430, -1) failed with errno-24
 D/M3U8InfoThread: #EXTINF:2.88,
 D/M3U8InfoThread: https://hey07.789zy.cc/20211117/tzDmHfD8/1200kb/hls/rJg57qy9.ts
 D/M3U8InfoThread: #EXTINF:2,
 D/M3U8InfoThread: https://hey07.789zy.cc/20211117/tzDmHfD8/1200kb/hls/7SfYHjwP.ts
 D/M3U8InfoThread: #EXTINF:2,
 D/M3U8InfoThread: https://hey07.789zy.cc/20211117/tzDmHfD8/1200kb/hls/Un2JHsLQ.ts
 D/M3U8InfoThread: #EXTINF:1.8,
 D/M3U8InfoThread: https://hey07.789zy.cc/20211117/tzDmHfD8/1200kb/hls/UDFysJNM.ts
 D/M3U8InfoThread: #EXTINF:1.64,
 D/M3U8InfoThread: https://hey07.789zy.cc/20211117/tzDmHfD8/1200kb/hls/0pLPdi1E.ts
 D/M3U8InfoThread: #EXTINF:2,
 D/M3U8InfoThread: https://hey07.789zy.cc/20211117/tzDmHfD8/1200kb/hls/NImSmecI.ts

**Comment by CarGuo** [comment]
看问题集锦

**Comment by cl19881314** [comment]
问题集锦没有找到方式
普通的m3u8下载能播放，加密的不行

**Comment by cl19881314** [comment]
@CarGuo

**Comment by CarGuo** [comment]
那就是 AES128 的 key 值在本地有问题呗，你调试下不就知道了
