### ISSUE TITLE
 java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.Player$Listener.onTimelineChanged(com.google.android.exoplayer2.Timeline 解决方案

### ISSUE THREAD

**Issue by iuhni** [CarGuo/GSYVideoPlayer#3549]
## 如果大家也遇到过这样的异常, debug模式下会出现, release 打包不会出现的话.
``` java
handleException: 
    java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.Player$Listener.onTimelineChanged(com.google.android.exoplayer2.Timeline, int)"
        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$12(ExoPlayerImpl.java:1850)
        at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda10.invoke(D8$$SyntheticClass)
        at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:281)
        at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:190)
        at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.run(D8$$SyntheticClass)
        at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:211)
        at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1947)
        at com.google.android.exoplayer2.ExoPlayerImpl.setMediaSourcesInternal(ExoPlayerImpl.java:2159)
        at com.google.android.exoplayer2.ExoPlayerImpl.setMediaSources(ExoPlayerImpl.java:575)
        at com.google.android.exoplayer2.ExoPlayerImpl.setMediaSources(ExoPlayerImpl.java:569)
        at com.google.android.exoplayer2.ExoPlayerImpl.setMediaSource(ExoPlayerImpl.java:550)
        at com.google.android.exoplayer2.SimpleExoPlayer.setMediaSource(SimpleExoPlayer.java:767)
        .....
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

## 解决方案 如下:
删除掉 `IjkExo2MediaPlayer` 类里面的 `protected EventLogger mEventLogger;` 即可.

工期较赶, 问题解决, 原因未知. 作者直接关掉即可

**Comment by CarGuo** [comment]
有没有一种可能，debug 下 exo 版本不对？
