### ISSUE TITLE
It can't run  on Android 6.0 devices

### ISSUE THREAD

**Issue by yangjieK** [CarGuo/GSYVideoPlayer#3563]
## 问题描述：
 I implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.9-release-jitpack'
build app  error :
**AAPT: D:\Gitt\GSYVideoPlayer-release-jitpack\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:7067: error: resource android:attr/lStar not found.**

I see you implementation  androidx.core:core-1.7.0,
 so I had to  try down its version  in app build.gradle

```
configurations.all {
    resolutionStrategy.eachDependency { details ->
        def requested = details.requested
        if (requested.group.contains('androidx.core')) {
            if (requested.name == 'core') {
                details.useVersion '1.3.0'
            }
        }
 if (requested.group.contains('androidx.appcompat')) {
            if (requested.name == 'appcompat') {
                details.useVersion '1.3.0'
            }
        }
    }
}
```

but other error comes up, such as 

**Process: com.example.gsyvideoplayer, PID: 1605
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.gsyvideoplayer/com.example.gsyvideoplayer.PlayActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.example.gsyvideoplayer.video.SampleVideo
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
     Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.example.gsyvideoplayer.video.SampleVideo
        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.example.gsyvideoplayer.databinding.ActivityPlayBinding.inflate(ActivityPlayBinding.java:48)
        at com.example.gsyvideoplayer.databinding.ActivityPlayBinding.inflate(ActivityPlayBinding.java:42)
        at com.example.gsyvideoplayer.PlayActivity.onCreate(PlayActivity.java:46)
        at android.app.Activity.performCreate(Activity.java:6266)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636) 
     Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.example.gsyvideoplayer.video.SampleVideo
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at com.example.gsyvideoplayer.databinding.ActivityPlayBinding.inflate(ActivityPlayBinding.java:48) 
        at com.example.gsyvideoplayer.databinding.ActivityPlayBinding.inflate(ActivityPlayBinding.java:42) 
        at com.example.gsyvideoplayer.PlayActivity.onCreate(PlayActivity.java:46) 
        at android.app.Activity.performCreate(Activity.java:6266) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at android.view.LayoutInflater.createView(LayoutInflater.java:619)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at com.example.gsyvideoplayer.databinding.ActivityPlayBinding.inflate(ActivityPlayBinding.java:48) 
        at com.example.gsyvideoplayer.databinding.ActivityPlayBinding.inflate(ActivityPlayBinding.java:42) 
        at com.example.gsyvideoplayer.PlayActivity.onCreate(PlayActivity.java:46) 
        at android.app.Activity.performCreate(Activity.java:6266) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636) 
     Caused by: java.lang.NoClassDefFoundError: androidx.appcompat.widget.AppCompatEditText
        at androidx.appcompat.widget.AppCompatTextViewAutoSizeHelper.supportsAutoSizeText(AppCompatTextViewAutoSizeHelper.java:932)
        at androidx.appcompat.widget.AppCompatTextViewAutoSizeHelper.loadFromAttributes(AppCompatTextViewAutoSizeHelper.java:205)
        at androidx.appcompat.widget.AppCompatTextHelper.loadFromAttributes(AppCompatTextHelper.java:247)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:110)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:97)
        at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:194)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:115)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1563)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1614)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
    	at android.view.Layout**

## 问题机型/系统：

Android 6.0 devices 

## GSY依赖版本

 implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.1.9-release-jitpack'

**Comment by yangjieK** [comment]
SO Which version can I run on Android 6.0 ?

**Comment by CarGuo** [comment]
complie sdk 31 maybe

**Comment by ag2s20150909** [comment]
If you use compose, check the version of kotlin. This problem will also occur if the kotlin version does not match.

**Comment by yangjieK** [comment]
```
compileSdkVersion 30
    buildToolsVersion "30.0.0"
    defaultConfig {
        applicationId "com.example.gsyvideoplayer"
        minSdkVersion 23
        versionCode 21
        versionName '1.0.3'
        targetSdkVersion 30

        multiDexEnabled true

        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a", "x86"
        }
    }
```

I use it , but this error also can't work 
AAPT: D:\Gitt\GSYVideoPlayer-release-jitpack\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:7067: error: resource android:attr/lStar not found.

**Comment by yangjieK** [comment]
> compose

No, I dont use compose

**Comment by yangjieK** [comment]
> complie sdk 31 maybe

please check it again

**Comment by CarGuo** [comment]
Need complie sdk 31
