### ISSUE TITLE
请问VideoView play error: mpjni: start: null mp, state: RELEASED有解决方案吗，竖屏切换全屏出现如下报错

### ISSUE THREAD

**Issue by adminhaoge** [CarGuo/GSYVideoPlayer#3585]
java.lang.IllegalStateException: mpjni: start: null mp
	at tv.danmaku.ijk.media.player.IjkMediaPlayer._start(Native Method)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.start(IjkMediaPlayer.java:522)
	at xxx.xxx.xxx.xxx.player.VideoPlayer.onVideoResume(VideoPlayer.java:481)
	at xxx.xxx.xxx.xxx.player.VideoPlayer$5.onAudioFocusChange(VideoPlayer.java:173)
	at android.media.AudioManager$FocusEventHandlerDelegate$1.handleMessage(AudioManager.java:2018)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5113)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by CarGuo** [comment]
看 demo 的 Manifest 和 wiki 文档等
