### ISSUE TITLE
Exo2PlayerManager播放mp4失败

### ISSUE THREAD

**Issue by qm921** [CarGuo/GSYVideoPlayer#3598]
## 问题描述：

在红米K30 Ultra上使用Exo2PlayerManager播放mp4的视频，发现无法播放

## 出现问题的视频流

https://www.aliyundrive.com/s/ZQrfWZPLEFS
我是把这个视频扔到我们服务器上，然后进行播放的，不是本地选择路径播放

## 问题机型/系统：

例如 真机 红米K30 Ultra Android11.0

## GSY依赖版本

    //视频播放器
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.0-release-jitpack'
    //是否需要ExoPlayer模式
    implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.3.0-release-jitpack'
    //更多 ijk 的编码支持
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.3.0-release-jitpack'

问题代码：(如果有)
     //EXOPlayer内核，支持格式更多
        PlayerFactory.setPlayManager(Exo2PlayerManager::class.java)
        GSYVideoManager.instance().setTimeOut(60000, false)
        CacheFactory.setCacheManager(ProxyCacheManager::class.java)

        //外部辅助的旋转，帮助全屏
        orientationUtils = OrientationUtils(this, binding.videoPlayer)
//初始化不打开外部的旋转
        orientationUtils?.isEnable = false

        val gsyVideoOption = GSYVideoOptionBuilder()
        gsyVideoOption
            .setIsTouchWiget(true)
            .setRotateViewAuto(false)
            .setLockLand(false)
            .setAutoFullWithSize(true)
            .setShowFullAnimation(false)
            .setNeedLockFull(true)
            .setUrl(loadLink)
           .setCacheWithPlay(true)
            .setNeedShowWifiTip(false)
            .setVideoTitle(viewModel.fileCid)
            .setVideoAllCallBack(object : GSYSampleCallBack() {
                override fun onPrepared(url: String, vararg objects: Any) {
                    super.onPrepared(url, *objects)
                    //开始播放了才能旋转和全屏
                    orientationUtils?.setEnable(true)
                    isPlay = true
                }

                override fun onQuitFullscreen(url: String, vararg objects: Any) {
                    super.onQuitFullscreen(url, *objects)
                    Debuger.printfError("***** onQuitFullscreen **** " + objects[0]) //title
                    Debuger.printfError("***** onQuitFullscreen **** " + objects[1]) //当前非全屏player
                    if (orientationUtils != null) {
                        orientationUtils?.backToProtVideo()
                    }
                }
            }).setLockClickListener { view, lock ->
                if (orientationUtils != null) {
                    //配合下方的onConfigurationChanged
                    orientationUtils?.setEnable(!lock)
                }
            }.build(binding.videoPlayer)

        binding.videoPlayer.fullscreenButton.setOnClickListener { //直接横屏
            orientationUtils?.resolveByClick()

            //第一个true是否需要隐藏actionbar，第二个true是否需要隐藏statusbar
            binding.videoPlayer.startWindowFullscreen(this, true, true)
        }
        }
        binding.videoPlayer.startPlayLogic()
```

## 问题log（如果有）
ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:613)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:396)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1009)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: com.google.android.exoplayer2.upstream.DataSourceException
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:394)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1009) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:920) 
2022-06-14 16:44:30.349 30311-30311/com.fileinandout.csbd.test E/EventLogger: playerFailed [0.28]
    com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:613)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:396)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1009)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: com.google.android.exoplayer2.upstream.DataSourceException
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:394)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1009) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:920) 

xxxxxxx

```

**Comment by qm921** [comment]
> player2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416 理论上 HTTP response code: 416是由于读取文件时设置的 Range 有误造成的

我换成了ijk或者ali的内核就不会出现这个问题就可以正常播放

**Comment by qm921** [comment]
> player2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416 理论上 HTTP response code: 416是由于读取文件时设置的 Range 有误造成的

之前有的视频文件使用ijk播放4k的265.h的视频会特别卡顿，所以只能用exo的内核，这个问题又没有解决的办法？

**Comment by CarGuo** [comment]
不知道你什么情况，我测试你的视频正常

**Comment by qm921** [comment]
> 不知道你什么情况，我测试你的视频正常

找到问题所在了，同样的视频换了个oss位置就可以了😓
