### ISSUE TITLE
Unexpected StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by hc05161** [CarGuo/GSYVideoPlayer#3613]
## 问题描述：

之前使用的版本为v8.1.9,在更新至v8.2.0的本版使用exolayer播放音频出错，也就是update exoplayer  sdk 2.17.1之后无法播放

## GSY依赖版本

`implementation 'com.shuyu:gsyVideoPlayer-java:8.2.0'`

## Demo中的复现步骤

Demo中的AudioDetailPlayer页面打开后也会出现这个问题。

## 问题log
2022-06-22 19:29:26.313 10034-14451/com.txt.bluemanage E/LoadTask: Unexpected exception loading stream
      java.lang.StringIndexOutOfBoundsException: length=65025; regionStart=33; regionLength=1869440324
        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:79)
        at com.google.android.exoplayer2.util.ParsableByteArray.readString(ParsableByteArray.java:431)
        at com.google.android.exoplayer2.util.ParsableByteArray.readString(ParsableByteArray.java:420)
        at com.google.android.exoplayer2.extractor.VorbisUtil.readVorbisCommentHeader(VorbisUtil.java:249)
        at com.google.android.exoplayer2.extractor.ogg.OpusReader.readHeaders(OpusReader.java:77)
        at com.google.android.exoplayer2.extractor.ogg.StreamReader.readHeaders(StreamReader.java:151)
        at com.google.android.exoplayer2.extractor.ogg.StreamReader.readHeadersAndUpdateState(StreamReader.java:161)
        at com.google.android.exoplayer2.extractor.ogg.StreamReader.read(StreamReader.java:112)
        at com.google.android.exoplayer2.extractor.ogg.OggExtractor.read(OggExtractor.java:88)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1042)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
2022-06-22 19:29:26.322 10034-14449/com.txt.bluemanage E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:617)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:219)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected StringIndexOutOfBoundsException: length=65025; regionStart=33; regionLength=1869440324
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:433)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
     Caused by: java.lang.StringIndexOutOfBoundsException: length=65025; regionStart=33; regionLength=1869440324
        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:79)
        at com.google.android.exoplayer2.util.ParsableByteArray.readString(ParsableByteArray.java:431)
        at com.google.android.exoplayer2.util.ParsableByteArray.readString(ParsableByteArray.java:420)
        at com.google.android.exoplayer2.extractor.VorbisUtil.readVorbisCommentHeader(VorbisUtil.java:249)
        at com.google.android.exoplayer2.extractor.ogg.OpusReader.readHeaders(OpusReader.java:77)
        at com.google.android.exoplayer2.extractor.ogg.StreamReader.readHeaders(StreamReader.java:151)
        at com.google.android.exoplayer2.extractor.ogg.StreamReader.readHeadersAndUpdateState(StreamReader.java:161)
        at com.google.android.exoplayer2.extractor.ogg.StreamReader.read(StreamReader.java:112)
        at com.google.android.exoplayer2.extractor.ogg.OggExtractor.read(OggExtractor.java:88)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1042)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:929) 
2022-06-22 19:29:26.324 10034-10034/com.txt.bluemanage E/EventLogger: playerFailed [0.09]
    com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:617)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:219)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected StringIndexOutOfBoundsException: length=65025; regionStart=33; regionLength=1869440324
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:433)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
     Caused by: java.lang.StringIndexOutOfBoundsException: length=65025; regionStart=33; regionLength=1869440324
        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:79)
        at com.google.android.exoplayer2.util.ParsableByteArray.readString(ParsableByteArray.java:431)
        at com.google.android.exoplayer2.util.ParsableByteArray.readString(ParsableByteArray.java:420)
        at com.google.android.exoplayer2.extractor.VorbisUtil.readVorbisCommentHeader(VorbisUtil.java:249)
        at com.google.android.exoplayer2.extractor.ogg.OpusReader.readHeaders(OpusReader.java:77)
        at com.google.android.exoplayer2.extractor.ogg.StreamReader.readHeaders(StreamReader.java:151)
        at com.google.android.exoplayer2.extractor.ogg.StreamReader.readHeadersAndUpdateState(StreamReader.java:161)
        at com.google.android.exoplayer2.extractor.ogg.StreamReader.read(StreamReader.java:112)
        at com.google.android.exoplayer2.extractor.ogg.OggExtractor.read(OggExtractor.java:88)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1042)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:929)

**Comment by CarGuo** [comment]
测试链接

**Comment by CarGuo** [comment]
确实，2.17  exo 开始做了一些调整没，目前看读出来的数据确实有问题

![image](https://user-images.githubusercontent.com/10770362/175275884-0505125a-31c1-4de4-a797-83b9449a231e.png)

**Comment by CarGuo** [comment]
[tt333.opus.zip](https://github.com/CarGuo/GSYVideoPlayer/files/8966346/tt333.opus.zip)

同样格式，我对文件做了一次转换，就可以了

**Comment by hc05161** [comment]
> [tt333.opus.zip](https://github.com/CarGuo/GSYVideoPlayer/files/8966346/tt333.opus.zip)
> 
> 同样格式，我对文件做了一次转换，就可以了
是的，就是读取头部数据长度错误，我对比了两个文件二进制，改变了效验码以及采样率等信息，请问，您这个是通过什么方式转换的呢？，在2.17之前的版本是自动转换这些信息吗？

**Comment by hc05161** [comment]
> [tt333.opus.zip](https://github.com/CarGuo/GSYVideoPlayer/files/8966346/tt333.opus.zip)
> 
> 同样格式，我对文件做了一次转换，就可以了

我对比了两个文件二进制，改变了效验码以及采样率等信息，请问您这个是通过什么方式转换的呢？，在2.17之前的版本是自动转换这些信息吗？

**Comment by hc05161** [comment]
我试了试用第三方工具去转换为同样的格式也是可以播放的，但在程序中没有找到好的方式去转换格式。目前还是在使用v8.1.9的版本上不需要转换。

**Comment by hc05161** [comment]
刚刚我试了试用第三方工具去转换为同样的格式也是可以播放的，但在程序中没有找到好的方式去转换格式，目前还是在使用v8.1.9的版本上不需要转换。

**Comment by CarGuo** [comment]
看了下应该是新的版本做了一些长度检验
