### ISSUE TITLE
ANR Issue

### ISSUE THREAD

**Issue by yangjieK** [CarGuo/GSYVideoPlayer#3623]
Up Code主, 我review了ANR issue挺多的,大于是release造成的,从2019就有anr问题,希望能优化下

您给的建议是转Exo,但这并不合理, 因为Ijk支持更多视频编码

能否设计一个合理的线程参数接口, 由调用的人控制,而非单一主线程.

```
#00 pc 0x89ccc libc.so (syscall + 28)
#01 pc 0xf46a8 libc.so (pthread_join + 260)
#02 pc 0x12bb8 split_config.arm64_v8a.apk!libijksdl.so (SDL_WaitThread + 32)
#03 pc 0x1ab9c split_config.arm64_v8a.apk!libijkplayer.so 
#04 pc 0x2071c split_config.arm64_v8a.apk!libijkplayer.so (ffp_wait_stop_l + 32)
#05 pc 0x2748c split_config.arm64_v8a.apk!libijkplayer.so (ijkmp_shutdown_l + 56)
#06 pc 0x2c2f8 split_config.arm64_v8a.apk!libijkplayer.so 
       at tv.danmaku.ijk.media.player.IjkMediaPlayer._release(IjkMediaPlayer.java)
       at tv.danmaku.ijk.media.player.IjkMediaPlayer.release(IjkMediaPlayer.java:704)
       at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.release(IjkPlayerManager.java:188)
       at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:573)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:257)
       at android.app.ActivityThread.main(ActivityThread.java:8104)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
```

**Comment by CarGuo** [comment]
不知道你们触发的情况是什么，至少从我这边没出现这样的情况，我们主要场景是在手机 app 端

**Comment by lyy90** [comment]
我机顶盒的稳定性都还可以，不知道他是什么场景啊
