### ISSUE TITLE
视频播放 OOM

### ISSUE THREAD

**Issue by yueyueyue123** [CarGuo/GSYVideoPlayer#3634]
//添加视频水印
  GSYVideoType.setRenderType(GSYVideoType.GLSURFACE);
  Bitmap bitmap = BitmapFactory.decodeResource(getResources(), R.mipmap.ic_logo);
    mGSYVideoGLViewCustomRender = new GSYVideoGLViewCustomRender();
   mCustomBitmapIconEffect = new BitmapIconEffect(bitmap, dp2px(50), dp2px(50), 0.6f);
   mGSYVideoGLViewCustomRender.setBitmapEffect(mCustomBitmapIconEffect);
   videoPlayer.setCustomGLRenderer(mGSYVideoGLViewCustomRender);
    videoPlayer.setGLRenderMode(GSYVideoGLView.MODE_RENDER_SIZE);

java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:884)
	at java.util.Timer.<init>(Timer.java:167)
	at java.util.Timer.<init>(Timer.java:139)
	at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.startDismissControlViewTimer(SourceFile:2)
	at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.onTouch(SourceFile:18)
	at android.view.View.dispatchTouchEvent(View.java:14853)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3125)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2798)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3131)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2812)
手机型号：vivo/V2157A，vivo/V2011A
手机型号：Redmi/  M2012K11AC

**Comment by CarGuo** [comment]
如果是内存不够了Bitmap bitmap 部分可能会导致 OOM ，但是为什么会不够呢？
