### ISSUE TITLE
无法播放本地m3u8视频，播放本地视频地址，一直提示URL错误 file://也加了

### ISSUE THREAD

**Issue by ZiiQ18** [CarGuo/GSYVideoPlayer#3653]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

无法播放本地m3u8视频，播放本地视频地址，一直提示URL错误file:///storage/emulated/0/Android/data/cn.org.starVideo/cache/video/demoVideo.m3u8

## 出现问题的视频流

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:13
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=AES-128,URI="https://file.imomo1.com/encrypt.key",IV=0x11d2d77a9582202b079881433a942261
#EXTINF:10.430556,
https://file.imomo1.com/duxiao：moxige.Narcos.Mexico.S02E01.zhongwenzimu.720p_1_ZD/duxiao：moxige.Narcos.Mexico.S02E01.zhongwenzimu.720p_100000.ts
#EXTINF:2.461611,
https://file.imomo1.com/duxiao：moxige.Narcos.Mexico.S02E01.zhongwenzimu.720p_1_ZD/duxiao：moxige.Narcos.Mexico.S02E01.zhongwenzimu.720p_100001.ts
#EXTINF:10.430556,
https://file.imomo1.com/duxiao：moxige.Narcos.Mexico.S02E01.zhongwenzimu.720p_1_ZD/duxiao：moxige.Narcos.Mexico.S02E01.zhongwenzimu.720p_100002.ts
#EXTINF:2.002667,
https://file.imomo1.com/duxiao：moxige.Narcos.Mexico.S02E01.zhongwenzimu.720p_1_ZD/duxiao：moxige.Narcos.Mexico.S02E01.zhongwenzimu.720p_100003.ts
#EXTINF:6.091444,
https://file.imomo1.com/duxiao：moxige.Narcos.Mexico.S02E01.zhongwenzimu.720p_1_ZD/duxiao：moxige.Narcos.Mexico.S02E01.zhongwenzimu.720p_100004.ts
#EXTINF:13.309389,
https://file.imomo1.com/duxiao：moxige.Narcos.Mexico.S02E01.zhongwenzimu.720p_1_ZD/duxiao：moxige.Narcos.Mexico.S02E01.zhongwenzimu.720p_100005.ts
#EXTINF:10.430556,
https://file.imomo1.com/duxiao：moxige.Narcos.Mexico.S02E01.zhongwenzimu.720p_1_ZD/duxiao：moxige.Narcos.Mexico.S02E01.zhongwenzimu.720p_100006.ts
#EXTINF:10.221944,
https://file.imomo1.com/duxiao：moxige.Narcos.Mexico.S02E01.zhongwenzimu.720p_1_ZD/duxiao：moxige.Narcos.Mexico.S02E01.zhongwenzimu.720p_100007.ts
#EXTINF:10.430556,
https://file.imomo1.com/duxiao：moxige.Narcos.Mexico.S02E01.zhongwenzimu.720p_1_ZD/duxiao：moxige.Narcos.Mexico.S02E01.zhongwenzimu.720p_100008.ts
#EXTINF:1.877500,

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.2.0-release-jitpack'
    implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.2.0-release-jitpack'

VideoOptionModel videoOptionModel =
                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "protocol_whitelist", "crypto,file,http,https,tcp,tls,udp,rtmp,rtsp,key");
        list.add(videoOptionModel);
        VideoOptionModel videoOptionModel2 =
                new VideoOptionModel(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "allowed_extensions", "ALL");
        list.add(videoOptionModel2);
        GSYVideoManager.instance().setOptionModelList(list);

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

2022-07-28 11:02:18.549 15829-16054/cn.org.starVideo E/LoadTask: Unexpected exception loading stream
      java.lang.ClassCastException: sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.openConnection(DefaultHttpDataSource.java:644)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:602)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:533)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:359)
        at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:62)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:174)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2022-07-28 11:02:18.566 15829-16053/cn.org.starVideo E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:617)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected ClassCastException: sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:433)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.ClassCastException: sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.openConnection(DefaultHttpDataSource.java:644)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:602)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:533)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:359)
        at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:62)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:174)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
2022-07-28 11:02:18.755 15829-15829/cn.org.starVideo E/EventLogger: playerFailed [0.36]
    com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:617)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected ClassCastException: sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:433)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.ClassCastException: sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.openConnection(DefaultHttpDataSource.java:644)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:602)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:533)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:359)
        at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:62)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:174)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
2022-07-28 11:02:18.803 15829-15829/cn.org.starVideo E/EventLogger: playerFailed [0.30]
    com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:617)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected ClassCastException: sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:433)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.ClassCastException: sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.openConnection(DefaultHttpDataSource.java:644)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:602)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:533)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:359)
        at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:99)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:62)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:174)

```

**Comment by CarGuo** [comment]
本地 m3u8 就本地 ts，你上面这样的不支持

**Comment by ZiiQ18** [comment]
可是本地m3u8文件还没读取到，还没解析到文件里面的ts把

**Comment by ZiiQ18** [comment]
file:///storage/emulated/0Download/132451525666042.mp4  这个地址，一样报上面的错

**Comment by ZiiQ18** [comment]
CacheFactory.setCacheManager(ExoPlayerCacheManager.class);
使用exo缓存模式，导致无法播放本地视频   是因为这个

**Comment by jupitar** [comment]
> CacheFactory.setCacheManager(ExoPlayerCacheManager.class); 使用exo缓存模式，导致无法播放本地视频 是因为这个



>我的也出现了file:///storage/emulated/0/zhsz/videos/站房门口_1692580953107.mp4播放不了，你的解决了吗，你的播放器配置是啥样的
