### ISSUE TITLE
InstantiationError

### ISSUE THREAD

**Issue by farendaibiao** [CarGuo/GSYVideoPlayer#3684]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

⚠️ InstantiationError 

## 出现问题的视频流

无法提供

## 问题机型/系统：

真机 华为 鸿蒙2.0

## GSY依赖版本

 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.4-release-jitpack'
 implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.3.4-release-jitpack'

## Demo中的复现步骤

无

## 问题log（如果有）

java.lang.InstantiationError: com.google.android.exoplayer2.util.LibraryLoader
	at com.google.android.exoplayer2.ext.ffmpeg.FfmpegLibrary.<clinit>(FfmpegLibrary.java:35)
	at com.google.android.exoplayer2.ext.ffmpeg.FfmpegLibrary.isAvailable(FfmpegLibrary.java:55)
	at com.google.android.exoplayer2.ext.ffmpeg.FfmpegAudioRenderer.supportsFormatInternal(FfmpegAudioRenderer.java:94)
	at com.google.android.exoplayer2.audio.DecoderAudioRenderer.supportsFormat(DecoderAudioRenderer.java:232)
	at com.google.android.exoplayer2.trackselection.MappingTrackSelector.findRenderer(MappingTrackSelector.java:506)
	at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:373)
	at com.google.android.exoplayer2.MediaPeriodHolder.selectTracks(MediaPeriodHolder.java:238)
	at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:186)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:2229)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:509)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:219)
	at android.os.HandlerThread.run(HandlerThread.java:67)

请检查一下FfmpegLibrary是否正确！
相关issue：https://github.com/google/ExoPlayer/issues/10218

**Comment by CarGuo** [comment]
测试 exo 内核在鸿蒙播放正常，另外 gsy 的 exo 没有添加 ffmpeg 的 ext 支持，ffmpeg 模式请使用 ijk 内核

**Comment by farendaibiao** [comment]
> 测试 exo 内核在鸿蒙播放正常，另外 gsy 的 exo 没有添加 ffmpeg 的 ext 支持，ffmpeg 模式请使用 ijk 内核

https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg
关于音频的解码，既然编译了ijk，exo也可以加进去吧

**Comment by CarGuo** [comment]
你说反了，而且既然是ijk了，你都可以自己编译so替换原本依赖去支持了，要exo 干啥？
