### ISSUE TITLE
java.io.IOException: Broken pipe

### ISSUE THREAD

**Issue by wzw88486969** [CarGuo/GSYVideoPlayer#3764]
作者你好：
我的问题是这样的，我用了一个3方httpServer，httpServer读我的设备驱动MOV视频。
开始播放就奔溃了，打印报错是
**java.io.IOException: Broken pipe**
这个应该是播放器里面的socket close了由于timeout。
我的代码如下：
` 
                    PlayerFactory.setPlayManager(AliPlayerManager.class);
                    CacheFactory.setCacheManager(ProxyCacheManager.class);
                    GSYVideoType.setRenderType(GSYVideoType.SUFRACE);
                    GSYVideoType.setRenderType(GSYVideoType.GLSURFACE);
                    GSYVideoType.setRenderType(GSYVideoType.TEXTURE);
                    GSYVideoType.setScreenScaleRatio(1);

                    GSYVideoOptionBuilder gsyVideoOption = new GSYVideoOptionBuilder();
                    gsyVideoOption
                            //.setIsTouchWiget(true)
                            //.setRotateViewAuto(false)
                            //.setLockLand(false)
                            //.setAutoFullWithSize(true)
                            //.setShowFullAnimation(false)
                            //.setNeedLockFull(true)
                            .setUrl(finalPath)
                            //.setCacheWithPlay(false)
                            .setVideoTitle("测试视频")
                            .build(videoPlayer);

                    videoPlayer.startPlayLogic();
`

`

2023-03-04 18:39:52.839 20306-20306/com.xx.exfat E/MainActivity: Start File Server /IMG_2671.MOV
2023-03-04 18:39:52.840 20306-20306/com.xx.exfat E/MainActivity: fileServer.start..........
2023-03-04 18:39:52.851 20306-20306/com.xx.exfat E/MainActivity: http://127.0.0.1:8000/IMG_2671.MOV
2023-03-04 18:39:52.857 20306-20306/com.xx.exfat I/AudioManager: requestAudioFocus streamType: 3 durationHint: 2
2023-03-04 18:39:52.857 20306-20306/com.xx.exfat W/AudioManager: Use of stream types is deprecated for operations other than volume control
2023-03-04 18:39:52.857 20306-20306/com.xx.exfat W/AudioManager: See the documentation for what to use instead with android.media.AudioAttributes to qualify your playback use case
2023-03-04 18:39:52.863 20306-20306/com.xx.exfat I/DecorView: navBarColor: fffcfcfc statusBarColor: ff00574b statusInsets: null navInsets: null
2023-03-04 18:39:52.863 20306-20306/com.xx.exfat I/DecorView: updateColorViewInt type:1 size: 0 showView:false color:fffcfcfc
2023-03-04 18:39:52.863 20306-20306/com.xx.exfat I/DecorView: updateColorViewInt type:0 size: 99 showView:true color:ff00574b
2023-03-04 18:39:52.871 20306-20306/com.xx.exfat I/DecorView: navBarColor: fffcfcfc statusBarColor: ff00574b statusInsets: Insets{left=0, top=99, right=0, bottom=0} navInsets: Insets{left=0, top=0, right=0, bottom=0}
2023-03-04 18:39:52.871 20306-20306/com.xx.exfat I/DecorView: updateColorViewInt type:1 size: 0 showView:false color:fffcfcfc
2023-03-04 18:39:52.871 20306-20306/com.xx.exfat I/DecorView: updateColorViewInt type:0 size: 99 showView:true color:ff00574b
2023-03-04 18:39:52.883 20306-20306/com.xx.exfat I/HwViewRootImpl: removeInvalidNode all the node in jank list is out of time
2023-03-04 18:39:52.898 20306-20306/com.xx.exfat V/version: external version is 20220418_10:56:22_fa27c2d1
2023-03-04 18:39:52.905 20306-20306/com.xx.exfat W/AliFrameWork: [15442358] [cloud_config_manager] :cloud config request: appid=, sdk_version=5.4.6.0, brand_name=, device_name=, os_version=, device_id=, network_type=0
2023-03-04 18:39:52.905 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [] :Ffmpeg version v4.3.1.7
2023-03-04 18:39:52.907 20306-20306/com.xx.exfat W/AliFrameWork: [15442358] [PlayerJNI] :JNI_OnLoad
2023-03-04 18:39:52.908 20306-20306/com.xx.exfat I/com.xx.exfat: Thread[1,tid=20306,Native,Thread*=0xb400007b68a4cc00,peer=0x74433988,"main"] recursive attempt to load library "/data/app/~~RsOhgTuRuFzY6NLr1LlBWg==/com.xx.exfat-W2qLKorPmnN8P7Sp1T3m6g==/base.apk!/lib/arm64-v8a/libsaasCorePlayer.so"
2023-03-04 18:39:52.920 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [] :setWorkPath :/data/app/~~RsOhgTuRuFzY6NLr1LlBWg==/com.xx.exfat-W2qLKorPmnN8P7Sp1T3m6g==/lib/arm64/
2023-03-04 18:39:52.920 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [analytics] :mReporter:0xb400007a3df9b320
2023-03-04 18:39:52.920 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [NativeBase] :java_SetLoop(0)
2023-03-04 18:39:52.921 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [JavaJniUrlPlayer] :java_SetDataSource_UrlSource(http://127.0.0.1:8000/IMG_2671.MOV)
2023-03-04 18:39:52.921 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [NativeBase] :java_Prepare()
2023-03-04 18:39:52.921 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [analytics] :mReporter:0xb400007a3df9b380
2023-03-04 18:39:52.922 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [analytics] :eventCode:5004, name: string:li_ki *  *||* li_ri *  *||* li_ti * sdk ret:0
2023-03-04 18:39:52.936 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [analytics] :eventCode:1003, name:GET_URL string:it * urlsource *||* pa * {"bitstream":""} ret:0
2023-03-04 18:39:52.936 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [PlayInfoRequest] :Prepare() urlSource={"mUrl":"http://127.0.0.1:8000/IMG_2671.MOV","base":"{\"mForceQuality\":false,\"mQuality\":\"AUTO\",\"mTitle\":\"\",\"mCoverUrl\":\"\"}"}
2023-03-04 18:39:52.936 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [analytics] :eventCode:1004, name:GET_URL_DONE string:cost * 0 *||* it * urlsource *||* mi * [{"encryption":0,"definition":"AUTO","finalDefinition":"AUTO","format":"","vid":""}] ret:0
2023-03-04 18:39:52.937 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [ApsaraPlayerService] :preferAudio 0
2023-03-04 18:39:52.937 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [ApsaraPlayerService] :preferAudio 0
2023-03-04 18:39:52.937 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [AVPBase] :startBuffer:500, highBuffer:3000, maxBuffer:50000, delay:5000,backwardBuffer:0
2023-03-04 18:39:52.937 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [ApsaraPlayerService] :EnterBackGround APP_FOREGROUND
2023-03-04 18:39:52.938 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [analytics] :eventCode:2047, name:SET_PLAYER_CONFIG string:play_config * {"referer":"","httpProxy":"","userAgent":"","networkTimeout":15000,"networkRetryCount":2,"maxDelayTime":5000,"maxBufferDuration":50000,"highBufferDuration":3000,"startBufferDuration":500,"bClearShowWhenStop":false,"bEnableTunnelRender":false,"pixelBufferOutputFormat":0,"liveStartIndex":-3,"mDisableAudio":false,"mDisableVideo":false,"mEnableLocalCache":true,"mPositionTimerIntervalMs":500,"mMaxBackwardBufferDuration":0,"preferAudio":false,"enableHttpDns":-1} ret:0
2023-03-04 18:39:52.938 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [ApsaraPlayerService] :preferAudio 0
2023-03-04 18:39:52.938 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [AVPBase] :startBuffer:500, highBuffer:3000, maxBuffer:50000, delay:5000,backwardBuffer:0
2023-03-04 18:39:52.938 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [analytics] :eventCode:2028, name:ROTATE string:rotation * 0 ret:0
2023-03-04 18:39:52.939 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [analytics] :eventCode:2029, name:MIRROR string:mirror * 0 ret:0
2023-03-04 18:39:52.939 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [analytics] :eventCode:2026, name:DISABLE_LOOPING string: ret:0
2023-03-04 18:39:52.939 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [analytics] :eventCode:2042, name:BLACK_INFO string:video.dec.h264 * 0 ret:0
2023-03-04 18:39:52.940 20306-20306/com.xx.exfat I/AliFrameWork: [15442358] [analytics] :eventCode:1101, name:PREPARE string:dn * custom *||* play_config * {"referer":"","httpProxy":"","userAgent":"","networkTimeout":15000,"networkRetryCount":2,"maxDelayTime":5000,"maxBufferDuration":50000,"highBufferDuration":3000,"startBufferDuration":500,"bClearShowWhenStop":false,"bEnableTunnelRender":false,"pixelBufferOutputFormat":0,"liveStartIndex":-3,"mDisableAudio":false,"mDisableVideo":false,"mEnableLocalCache":true,"mPositionTimerIntervalMs":500,"mMaxBackwardBufferDuration":0,"preferAudio":false,"enableHttpDns":-1} ret:0
2023-03-04 18:39:52.940 20306-20724/com.xx.exfat I/AliFrameWork: [15442358] [NativeBase] :AliyunCorePlayer callback --> StatusChanged(1)
2023-03-04 18:39:52.941 20306-20724/com.xx.exfat I/AliFrameWork: [15442358] [NativeBase] :AliyunCorePlayer callback --> StatusChanged(-1)
2023-03-04 18:39:52.952 20306-20714/com.xx.exfat E/AsyncHttpServer: 215187591 onRequest:
    Host: 127.0.0.1:8000
    Accept: */*
    
    com.koushikdutta.async.http.server.UnknownRequestBody@6a10bb4
2023-03-04 18:39:52.952 20306-20714/com.xx.exfat D/AsyncHttpServer: Uri: /IMG_2671.MOV
2023-03-04 18:39:52.952 20306-20714/com.xx.exfat D/UsbFileHttpServer: Searching file on USB (URI: /IMG_2671.MOV)
2023-03-04 18:39:52.952 20306-20714/com.xx.exfat D/UsbFileHttpServer: Serving root file
2023-03-04 18:39:52.952 20306-20714/com.xx.exfat D/UsbFileInputStream: 89850845 skip--------1:0
2023-03-04 18:39:52.952 20306-20714/com.xx.exfat D/UsbFileInputStream: 89850845 skip--------2:0
2023-03-04 18:39:52.953 20306-20714/com.xx.exfat D/UsbFileInputStream: 89850845 read--------1:0 8192 0
2023-03-04 18:39:52.953 20306-20714/com.xx.exfat D/UsbFileInputStream: 89850845 read--------2
2023-03-04 18:39:52.955 20306-20714/com.xx.exfat D/UsbFileInputStream: 89850845 read--------1:0 16384 8192
2023-03-04 18:39:52.956 20306-20714/com.xx.exfat D/UsbFileInputStream: 89850845 read--------2
2023-03-04 18:39:52.956 20306-20714/com.xx.exfat D/UsbFileInputStream: 89850845 read--------1:0 32768 24576
2023-03-04 18:39:52.958 20306-20714/com.xx.exfat D/UsbFileInputStream: 89850845 read--------2
2023-03-04 18:39:52.958 20306-20714/com.xx.exfat D/UsbFileInputStream: 89850845 read--------1:0 65536 57344
2023-03-04 18:39:52.959 20306-20727/com.xx.exfat I/AliFrameWork: [15442358] [CurlDataSource2] :short seek failed
2023-03-04 18:39:52.961 20306-20714/com.xx.exfat D/UsbFileInputStream: 89850845 read--------2
2023-03-04 18:39:52.961 20306-20714/com.xx.exfat D/UsbFileInputStream: 89850845 read--------1:0 131072 122880
2023-03-04 18:39:52.967 20306-20714/com.xx.exfat D/UsbFileInputStream: 89850845 read--------2
2023-03-04 18:39:52.969 20306-20714/com.xx.exfat D/UsbFileInputStream: 89850845 close--------1
2023-03-04 18:39:52.969 20306-20714/com.xx.exfat I/exfat : ExFatFile: 1567756271 close file
2023-03-04 18:39:52.969 20306-20714/com.xx.exfat D/UsbFileInputStream: 89850845 close--------2
2023-03-04 18:39:52.970 20306-20714/com.xx.exfat D/UsbFileInputStream: 89850845 read--------1:0 262144 253952
2023-03-04 18:39:52.980 20306-20714/com.xx.exfat D/UsbFileInputStream: 89850845 read--------2
    
    --------- beginning of crash
2023-03-04 18:39:52.982 20306-20714/com.xx.exfat E/AndroidRuntime: FATAL EXCEPTION: AsyncServer
    Process: com.xx.exfat, PID: 20306
    java.lang.AssertionError
        at com.koushikdutta.async.http.server.AsyncHttpServerResponseImpl.write(AsyncHttpServerResponseImpl.java:56)
        at com.koushikdutta.async.Util$2.onWriteable(Util.java:106)
        at com.koushikdutta.async.Util.pump(Util.java:120)
        at com.koushikdutta.async.http.server.AsyncHttpServerResponseImpl.sendStream(AsyncHttpServerResponseImpl.java:293)
        at com.lenovo.httpserver.server.AsyncHttpServer.onRequest(AsyncHttpServer.kt:67)
        at com.koushikdutta.async.http.server.AsyncHttpServer.onRequest(AsyncHttpServer.java:62)
        at com.koushikdutta.async.http.server.AsyncHttpServer$1$1.onHeadersReceived(AsyncHttpServer.java:159)
        at com.koushikdutta.async.http.server.AsyncHttpServerRequestImpl$2.onStringAvailable(AsyncHttpServerRequestImpl.java:75)
        at com.koushikdutta.async.LineEmitter.onDataAvailable(LineEmitter.java:45)
        at com.koushikdutta.async.Util.emitAllData(Util.java:23)
        at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
        at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:821)
        at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
        at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
        at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)

`

**Comment by CarGuo** [comment]
你setup时设置cache为false，因为如果开启了 cache  的话，会有一个 127.0.0.1 服务用来做 cache
