### ISSUE TITLE
IjkExo2MediaPlayer  NoSuchMethodError

### ISSUE THREAD

**Issue by renwfy** [CarGuo/GSYVideoPlayer#3769]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

IjkExo2MediaPlayer  NoSuchMethodError

## 问题机型/系统：

还是魔百盒

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:8.4.3'`

## Demo中的复现步骤

问题代码：(如果有)

## 问题log（如果有）

Thread Name: 'main'
Back traces starts.
java.lang.NoSuchMethodError: No virtual method buildOrThrow()Lcom/google/common/collect/ImmutableMap; in class Lcom/google/common/collect/ImmutableMap$Builder; or its super classes (declaration of 'com.google.common.collect.ImmutableMap$Builder' appears in /system/framework/libsetting.jar)
	at com.google.android.exoplayer2.audio.AudioCapabilities.<clinit>(AudioCapabilities.java:13)
	at com.google.android.exoplayer2.audio.DefaultAudioSink$Builder.<init>(DefaultAudioSink.java:2)
	at com.google.android.exoplayer2.DefaultRenderersFactory.buildAudioSink(DefaultRenderersFactory.java:1)
	at com.google.android.exoplayer2.DefaultRenderersFactory.createRenderers(DefaultRenderersFactory.java:4)
	at com.google.android.exoplayer2.ExoPlayerImpl.<init>(ExoPlayerImpl.java:19)
	at com.google.android.exoplayer2.ExoPlayer$Builder.build(ExoPlayer.java:3)
	at tv.danmaku.ijk.media.exo2.IjkExo2MediaPlayer$1.run(IjkExo2MediaPlayer.java:12)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:915)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
Back traces ends.

**Comment by CarGuo** [comment]
/**
     * Returns a newly-created immutable map, or throws an exception if any key was added more than
     * once. The iteration order of the returned map is the order in which entries were inserted
     * into the builder, unless {@link #orderEntriesByValue} was called, in which case entries are
     * sorted by value.
     *
     * @throws IllegalArgumentException if duplicate keys were added
     * @since 31.0
     */
    @SuppressWarnings("unchecked")
    public ImmutableMap<K, V> buildOrThrow() {

**Comment by renwfy** [comment]
这个没看懂怎么改呢

**Comment by renwfy** [comment]
@CarGuo ，指导下怎么修改。不然用不了啊。切换exo内核就崩溃

**Comment by renwfy** [comment]
@CarGuo

**Comment by renwfy** [comment]
求教

**Comment by CarGuo** [comment]
你问我，我怎么知道

**Comment by renwfy** [comment]
GSYVideoPlayer:v8.1.9 之前的版本没问题，是 exoplayer升级的问题？

**Comment by CarGuo** [comment]
8.2.0开始确实升级了 exoplayer SDK

**Comment by renwfy** [comment]
大佬，可解吗？ 退回去，这几个版本改动挺多吧

**Comment by CarGuo** [comment]
我猜测可能和你的 compileSdk 还有 targetSdk 有关系

**Comment by CarGuo** [comment]
我的意思就是 compileSdk 太低了，改成31试试

**Comment by renwfy** [comment]
就是 31

**Comment by renwfy** [comment]
<img width="652" alt="image" src="https://user-images.githubusercontent.com/6526280/224270082-7734671e-e953-4c48-a9f8-d66b855beae3.png">

**Comment by CarGuo** [comment]
那我很奇怪···为什么demo可以···
