### ISSUE TITLE
ijk播放器，硬解码，全屏切换时出现画面卡住，声音还在播放的问题

### ISSUE THREAD

**Issue by Matcha-xiaobin** [CarGuo/GSYVideoPlayer#3778]
## 问题描述：

⚠️ ijk播放器，硬解码：
GSYVideoType.enableMediaCodec()
GSYVideoType.enableMediaCodecTexture()
全屏切换时出现画面卡住，声音还在播放的问题：
开启硬解码，正在播放的情况下，横竖屏切换，activity添加了
android:configChanges="uiMode|orientation|screenSize|screenLayout|smallestScreenSize|layoutDirection"
通过removeView的方式把播放器移出竖屏布局，然后addView的方式添加到横屏布局，
此时，ijk播放器画面 会出现 卡住、花屏 现象。
不开启硬解码，或者使用exo播放器没有这个问题。

## 出现问题的视频流

任意.m3u8视频

## 问题机型/系统：

真机: 魅族18，小米11

## GSY依赖版本

implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.3.5-release-jitpack'
implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.3.5-release-jitpack'
implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.3.5-release-jitpack'
8.3.4, 8.3.5 都有这个问题

## Demo中的复现步骤

开启硬解码，正在播放的情况下，横竖屏切换，activity添加了
android:configChanges="uiMode|orientation|screenSize|screenLayout|smallestScreenSize|layoutDirection"
通过removeView的方式把播放器移出竖屏布局，然后addView的方式添加到横屏布局，
此时，ijk播放器画面 会出现 卡住、花屏 现象
不开启硬解码，或者使用exo播放器没有这个问题。

问题代码：(如果有)

## 问题log（如果有）

```

IjkMediaPlayer_setVideoSurface
ijkmp_set_android_surface(surface=0x0)
ffpipeline_set_surface()
SDL_AMediaCodec_decreaseReference(): ref=1
ijkmp_set_android_surface(surface=0x0)=void
func_display_overlay_l: NULL native_window
SDL_VoutAndroid_releaseBufferProxy_l: [0] ???????? proxy 0: vout: 0 idx: -1 render: false fake: NO
ffpipeline_set_surface_need_reconfigure_l(0)
SDL_AMediaCodecJava_stop
[c2.qti.avc.decoder#677] MediaCodec discarded an unknown buffer
[c2.qti.avc.decoder#677] MediaCodec discarded an unknown buffer
[c2.qti.avc.decoder#677] MediaCodec discarded an unknown buffer
[c2.qti.avc.decoder#677] MediaCodec discarded an unknown buffer
[c2.qti.avc.decoder#677] MediaCodec discarded an unknown buffer
[c2.qti.avc.decoder#677] MediaCodec discarded an unknown buffer
[c2.qti.avc.decoder#677] MediaCodec discarded an unknown buffer
[c2.qti.avc.decoder#677] MediaCodec discarded an unknown buffer
uid=10284(com.xiaobin.bangumi) MediaCodec_loop identical 27 lines
[c2.qti.avc.decoder#677] MediaCodec discarded an unknown buffer
disconnecting from surface 0xb400006ef699d010, reason disconnectFromSurface
quirk: reconfigure with new codec
SDL_AMediaCodec_decreaseReference(): ref=0
SDL_AMediaCodecJava_delete
SDL_AMediaCodecDummy_create
SDL_AMediaCodec_increaseReference(): ref=1
reconfigure_codec_l:new acodec: 0xb400006ef8206160
SDL_AMediaCodec_increaseReference(): ref=2
onLastStrongRef automatically unlinking death recipients
[SurfaceTexture-0-2613-11](id:a350000000d,api:0,p:-1,c:2613) detachBuffer: BufferQueue has no connected producer
VideoBox::~VideoBox
SDL_VoutAndroid_releaseBufferProxy_l: [0] invalid AMediaCodec buffer index -1
SDL_VoutAndroid_releaseBufferProxy_l: [0] invalid AMediaCodec buffer index -1
SDL_VoutAndroid_releaseBufferProxy_l: [0] invalid AMediaCodec buffer index -1
setScreenOnWhilePlaying(true) is ineffective for Surface
IjkMediaPlayer_setVideoSurface
ijkmp_set_android_surface(surface=0x7fcf4e7498)
ffpipeline_set_surface()
SDL_AMediaCodec_decreaseReference(): ref=1
ijkmp_set_android_surface(surface=0x7fcf4e7498)=void
Unknown Color primary = 2
ffpipeline_set_surface_need_reconfigure_l(0)
quirk: reconfigure with new codec
SDL_AMediaCodec_decreaseReference(): ref=0
SDL_AMediaCodecJava_createByCodecName
VideoBox::VideoBox
FRC is used
AIE is used
AIS is used
allocate(c2.qti.avc.decoder)
setting up 'default' as default (vendor) store
Created component [c2.qti.avc.decoder]
read media type: video/avc
extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_top_field.misr_dpb_luma
extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_top_field.misr_dpb_chroma
extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_top_field.misr_opb_luma
extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_top_field.misr_opb_chroma
extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_bottom_field.misr_dpb_luma
extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_bottom_field.misr_dpb_chroma
extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_bottom_field.misr_opb_luma
extent() != 1 for single value type: vendor.qti-ext-dec-info-misr.misr_info_bottom_field.misr_opb_chroma
ignored struct field vendor.qti-ext-dec-panscan.window
extent() != 1 for single value type: output.buffers.pool-ids.values
ignoring local param raw.size (0xd2001800) as it is already supported
ignoring local param raw.color (0xd2001809) as it is already supported
ignoring local param raw.hdr-static-info (0xd200180a) as it is already supported
query failed after returning 17 values (BAD_INDEX)
c2 config diff is Dict {
  c2::i32 algo.priority.value = 0
  c2::float algo.rate.value = 30
  c2::u32 algo.secure-mode.value = 0
  c2::float coded.frame-rate.value = 30
  c2::u32 coded.pl.level = 0
  c2::u32 coded.pl.profile = 20484
  c2::u32 coded.vui.color.matrix = 255
  c2::u32 coded.vui.color.primaries = 0
  c2::u32 coded.vui.color.range = 0
  c2::u32 coded.vui.color.transfer = 255
  c2::u32 default.color.matrix = 255
  c2::u32 default.color.primaries = 0
  c2::u32 default.color.range = 0
  c2::u32 default.color.transfer = 255
  c2::u32 input.buffers.max-size.value = 7077888
  c2::u32 input.delay.value = 0
  string input.media-type.value = "video/avc"
  c2::u32 output.delay.value = 35
  string output.media-type.value = "video/raw"
  c2::u32 raw.color.matrix = 255
  c2::u32 raw.color.primaries = 0
  c2::u32 raw.color.range = 0
  c2::u32 raw.color.transfer = 255
  c2::float raw.hdr-static-info.mastering.blue.x = 0
  c2::float raw.hdr-static-info.mastering.blue.y = 0
  c2::float raw.hdr-static-info.masterin
expected specified color aspects (0:0:255:255)
SDL_AMediaCodecJava_init
SDL_AMediaCodec_increaseReference(): ref=1
SDL_AMediaCodecJava_configure_surface
configure acodec:0x3366 format:0x38d2: surface:0x377a
video box disabled
connecting to surface 0xb400006f526c2010, reason connectToSurface
[c2.qti.avc.decoder] setting surface generation to 2675731
disconnecting from surface 0xb400006f526c2010, reason connectToSurface(reconnect)
connecting to surface 0xb400006f526c2010, reason connectToSurface(reconnect)
[c2.qti.avc.decoder] buffers are bound to CCodec for this session
no c2 equivalents for native-window
no c2 equivalents for flags
c2 config diff is   c2::u32 raw.size.height = 720
  c2::u32 raw.size.width = 1280
query -- param skipped: index = 1107298332.
setup formats input: AMessage(what = 0x00000000) = {
  int32_t feature-secure-playback = 0
  int32_t frame-rate = 30
  int32_t height = 720
  int32_t max-input-size = 7077888
  string mime = "video/avc"
  int32_t priority = 0
  int32_t profile = 8
  int32_t width = 1280
  Rect crop(0, 0, 1279, 719)
} and output: AMessage(what = 0x00000000) = {
  int32_t android._video-scaling = 1
  Rect crop(0, 0, 1279, 719)
  int32_t color-standard = 130817
  int32_t color-range = 2
  int32_t color-transfer = 65791
  int32_t android._dataspace = 260
  int32_t width = 1280
  int32_t feature-secure-playback = 0
  int32_t frame-rate = 30
  int32_t height = 720
  int32_t max-height = 4320
  int32_t max-width = 8192
  string mime = "video/raw"
  int32_t priority = 0
  int32_t rotation-degrees = 0
  int32_t sar-height = 1
  int32_t sar-width = 1
  Buffer hdr-static-info = {
    00000000:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
    00000010:  00 00 00 00 00 00 00 00  00                       .........
 
SDL_AMediaCodecJava_start
query -- param skipped: index = 1342179345.
query -- param skipped: index = 2415921170.
query -- param skipped: index = 1610614798.
[c2.qti.avc.decoder#40] Query input allocators returned 0 params => BAD_INDEX (6)
grantorIdx must be less than 3
grantorIdx must be less than 3
[c2.qti.avc.decoder#40] Created input block pool with allocatorID 16 => poolID 25 - OK (0)
[c2.qti.avc.decoder#40] start: max output delay 42
[c2.qti.avc.decoder#40] Query output allocators returned 0 params => BAD_INDEX (6)
[c2.qti.avc.decoder#40] Query output surface allocator returned 0 params => BAD_INDEX (6)
[c2.qti.avc.decoder#40] Created output block pool with allocatorID 18 => poolID 41 - OK
[c2.qti.avc.decoder#40] Configured output block pool ids 41 => OK
remote graphic buffer migration 0/0
generation remote change 2675731
[c2.qti.avc.decoder#40] start: updating output delay 35
reconfigure_codec_l:new acodec: 0xb400006ef679fdc0
SDL_AMediaCodec_increaseReference(): ref=2
SDL_VoutAndroid_releaseBufferProxy_l: [0] ???????? proxy 0: vout: 10 idx: -1 render: false fake: NO
SDL_VoutAndroid_releaseBufferProxy_l: [0] ???????? proxy 0: vout: 10 idx: -1 render: true fake: NO
grantorIdx must be less than 3
c2 config diff is   c2::u32 output.delay.value = 24
  c2::u32 raw.crop.height = 720
  c2::u32 raw.crop.left = 0
  c2::u32 raw.crop.top = 0
  c2::u32 raw.crop.width = 1280
[c2.qti.avc.decoder#40] onWorkDone: updating output delay 24
[c2.qti.avc.decoder#40] onWorkDone: updating max output delay 42
SDL_AMediaCodecJava_dequeueOutputBuffer: INFO_OUTPUT_FORMAT_CHANGED
AMEDIACODEC__INFO_OUTPUT_FORMAT_CHANGED
SDL_AMediaFormatJava_init
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at android.media.MediaFormat.getInteger(MediaFormat.java:1283)
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at android.media.MediaFormat.getInteger(MediaFormat.java:1283)
SDL_AMediaFormatJava_getInt32: CallIntMethod: failed
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at android.media.MediaFormat.getInteger(MediaFormat.java:1283)
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at android.media.MediaFormat.getInteger(MediaFormat.java:1283)
SDL_AMediaFormatJava_getInt32: CallIntMethod: failed
AMEDIACODEC__INFO_OUTPUT_FORMAT_CHANGED
    width-height: (1280 x 720)
    color-format: (FormatSurface: 0x7f000789)
    stride:       (0)
    slice-height: (0)
    crop:         (0, 0, 1279, 719)
onInputBufferReleased: frameIndex not found (31); ignored
SDL_VoutAndroid_releaseBufferProxy_l: [0] ???????? proxy 0: vout: 10 idx: -1 render: true fake: NO
SDL_VoutAndroid_releaseBufferProxy_l: [0] ???????? proxy 0: vout: 10 idx: -1 render: true fake: NO
[c2.qti.avc.decoder#40] DEBUG: elapsed: n=28 [in=0 pipeline=0 out=24 smoothness=4]
DEBUG: elapsed 3 / 28
Unknown Color primary = 2
Unknown Color primary = 2
Unknown Color primary = 2
Unknown Color primary = 2
Unknown Color primary = 2
Unknown Color primary = 2
Unknown Color primary = 2
Unknown Color primary = 2
Unknown Color primary = 2
Unknown Color primary = 2
Unknown Color primary = 2
Unknown Color primary = 2
Unknown Color primary = 2
Unknown Color primary = 2
Unknown Color primary = 2
Unknown Color primary = 2
Unknown Color primary = 2
Unknown Color primary = 2

```

**Comment by CarGuo** [comment]
ijk 硬解码时确实会有，参考 demo 的 MediaCodecVideo 会有点改善，但是无法100%解决，因为 GSY 切换模式和 IJK 硬解码不是很匹配
