### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by KunNiu** [CarGuo/GSYVideoPlayer#3801]
## 出现问题的视频流
https://share-ap-northeast-1.dev.anylocal.com/ap-northeast-1/AnyLocal-S3/uploaded/w_1681892688/1682842666666.mp4
## 问题机型/系统：

真机 Google Pixel 6

## GSY依赖版本

v8.3.5-release-jitpack

## Demo中的复现步骤
(没有尝试在demo中复现)
RecyclerView中点击item进入视频详情，在有缓冲前又back回到上一页

## 问题log（如果有）

```
main (native):tid=1 systid=9930 
#00 pc 0xac618 libc.so (__ioctl + 8) (BuildId: dc4001c2ef2dfc23467040797a96840c)
#01 pc 0x5e72c libc.so (ioctl + 156) (BuildId: dc4001c2ef2dfc23467040797a96840c)
#02 pc 0x773d8 libbinder.so (android::IPCThreadState::transact(int, unsigned int, android::Parcel const&, android::Parcel*, unsigned int) + 1000) (BuildId: 5f5bf5a71dd1e5608b2a1611686e5ae9)
#03 pc 0x76d4c libbinder.so (android::BpBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int) + 172) (BuildId: 5f5bf5a71dd1e5608b2a1611686e5ae9)
#04 pc 0x4de24 libmedia.so (android::BpMediaPlayer::setVideoSurfaceTexture(android::sp<android::IGraphicBufferProducer> const&) + 468) (BuildId: d30f2c8a45e9971db01d30015a584a61)
#05 pc 0x3e670 libmedia.so (android::MediaPlayer::setVideoSurfaceTexture(android::sp<android::IGraphicBufferProducer> const&) + 112) (BuildId: d30f2c8a45e9971db01d30015a584a61)
#06 pc 0x6feac libmedia_jni.so (android_media_MediaPlayer_setVideoSurface(_JNIEnv*, _jobject*, _jobject*) + 428) (BuildId: 710623d60d6a6c3632adb8eeaebe5b17)
       at android.media.MediaPlayer._setVideoSurface(Native method)
       at android.media.MediaPlayer.setSurface(MediaPlayer.java:805)
       at tv.danmaku.ijk.media.player.AndroidMediaPlayer.setSurface(AndroidMediaPlayer.java:79)
       at com.shuyu.gsyvideoplayer.player.SystemPlayerManager.showDisplay(SystemPlayerManager.java:74)
       at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.showDisplay(GSYVideoBaseManager.java:688)
       at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.setDisplay(GSYVideoBaseManager.java:246)
       at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.setDisplay(GSYVideoView.java:737)
       at com.shuyu.gsyvideoplayer.video.base.GSYTextureRenderView.onSurfaceDestroyed(GSYTextureRenderView.java:84)
       at com.shuyu.gsyvideoplayer.render.view.GSYTextureView.onSurfaceTextureDestroyed(GSYTextureView.java:93)
       at android.view.TextureView.releaseSurfaceTexture(TextureView.java:325)
       at android.view.TextureView.onDetachedFromWindowInternal(TextureView.java:296)
       at android.view.View.dispatchDetachedFromWindow(View.java:21369)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3949)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3949)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3949)
       at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:5363)
       at android.view.ViewRootImpl.doDie(ViewRootImpl.java:8716)
       at android.view.ViewRootImpl.die(ViewRootImpl.java:8692)
       at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:506)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:447)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:206)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5479)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:179)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7884)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
[issue_9a6cc480a81724640dba5a4dd7502db3_ANR_session_644FFA6F03B0000126CA2B1966F3B2EA_DNE_0_v2_stacktrace.txt](https://github.com/CarGuo/GSYVideoPlayer/files/11367094/issue_9a6cc480a81724640dba5a4dd7502db3_ANR_session_644FFA6F03B0000126CA2B1966F3B2EA_DNE_0_v2_stacktrace.txt)

**Comment by CarGuo** [comment]
没有复现问题
