### ISSUE TITLE
demo -- 类名：DetailDownloadPlayer -- 点击“开始缓存”闪退

### ISSUE THREAD

**Issue by xiaxinqing** [CarGuo/GSYVideoPlayer#3805]
## 问题描述：

缓存demo -- DetailDownloadPlayer -- 点击开始缓存闪退
请大佬解惑，是代理的问题还是

## 问题机型/系统：

 真机 三星Galaxy A13 5G Android13 (我这边其他真机也会闪退)

## GSY依赖版本

最新源码（应该是8.3.5）

## Demo中的复现步骤

Demo中的DetailDownloadPlayer页面点击开始缓存会出现这个问题。

问题代码：(如果有)
```
    private void startDownload(String url) {
        Debuger.printfError("###### url " + url);
        //下载demo然后设置
        requestCall = OkHttpUtils.get().url(url)
            .build();
        requestCall.execute(new MemoryCallBack() {
            @Override
            public void onError(Call call, Exception e, int id) {
            }

            @Override
            public void onResponse(Boolean response, int id) {
                stopDownload();
            }

        });
    }
```

## 问题log（如果有）

```

2023-05-17 10:56:18.850 14150-14180/com.example.gsyvideoplayer D/LeakCanary: Setting up flushing for Thread[queued-work-looper,5,main]
2023-05-17 10:56:21.577 14150-14150/com.example.gsyvideoplayer I/ViewRootImpl@1c2f920[DetailDownloadPlayer]: ViewPostIme pointer 0
2023-05-17 10:56:21.677 14150-14150/com.example.gsyvideoplayer I/ViewRootImpl@1c2f920[DetailDownloadPlayer]: ViewPostIme pointer 1
2023-05-17 10:56:21.682 14150-14150/com.example.gsyvideoplayer E/GSYVideoPlayer: ###### url file:///data/user/0/com.example.gsyvideoplayer/cache/video-cache/bf2977e50cb5ed6a5783d50a39d554b8.mp4
2023-05-17 10:56:21.693 14150-14165/com.example.gsyvideoplayer D/InputTransport: Input channel destroyed: 'ClientS', fd=137
2023-05-17 10:56:21.695 14150-14166/com.example.gsyvideoplayer W/System: A resource failed to call close. 
2023-05-17 10:56:21.726 14150-14150/com.example.gsyvideoplayer D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2023-05-17 10:56:21.728 14150-14150/com.example.gsyvideoplayer E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.gsyvideoplayer, PID: 14150
    java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but was 'file'
        at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1254)
        at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1633)
        at okhttp3.Request$Builder.url(Request.kt:184)
        at com.zhy.http.okhttp.request.OkHttpRequest.initBuilder(OkHttpRequest.java:49)
        at com.zhy.http.okhttp.request.OkHttpRequest.<init>(OkHttpRequest.java:39)
        at com.zhy.http.okhttp.request.GetRequest.<init>(GetRequest.java:15)
        at com.zhy.http.okhttp.builder.GetBuilder.build(GetBuilder.java:26)
        at com.example.gsyvideoplayer.DetailDownloadPlayer.startDownload(DetailDownloadPlayer.java:262)
        at com.example.gsyvideoplayer.DetailDownloadPlayer.access$500(DetailDownloadPlayer.java:33)
        at com.example.gsyvideoplayer.DetailDownloadPlayer$5.onClick(DetailDownloadPlayer.java:165)
        at android.view.View.performClick(View.java:7892)
        at android.widget.TextView.performClick(TextView.java:16219)
        at android.view.View.performClickInternal(View.java:7869)
        at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
        at android.view.View$PerformClick.run(View.java:30880)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8757)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```

**Comment by xiaxinqing** [comment]
我看issue 中有人提过这个问题，但是没看懂最后怎么解决的
