### ISSUE TITLE
使用 Exo 播放内核，源url ，302到新url后，源url过期，导致快进播放失败。有解决302前url失效的方法吗？

### ISSUE THREAD

**Issue by ZhuSky** [CarGuo/GSYVideoPlayer#3844]
## GSY依赖版本
    api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.4.0-release-jitpack'
    //是否需要ExoPlayer模式
    api 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.4.0-release-jitpack'
    //是否需要AliPlayer模式
    api 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-aliplay:v8.4.0-release-jitpack'
    //更多ijk的编码支持
    api 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.4.0-release-jitpack'

使用Exo2PlayerManager 播放视频
url = xx1
302到新的地址xx2
播放 xx2 这个地址，
30秒后 xx1 地址过期 无法使用
拖动快进，请求的还是 xx1 返回错误json码 导致播放失败

**Comment by ZhuSky** [comment]
playerFailed [30.48]
    androidx.media3.exoplayer.ExoPlaybackException: Source error
        at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:684)
        at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:656)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:211)
        at android.os.Looper.loop(Looper.java:300)
        at android.os.HandlerThread.run(HandlerThread.java:67)
    Caused by: androidx.media3.datasource.HttpDataSource$HttpDataSourceException
        at androidx.media3.datasource.DefaultHttpDataSource.skipFully(DefaultHttpDataSource.java:765)
        at androidx.media3.datasource.DefaultHttpDataSource.open(DefaultHttpDataSource.java:489)
        at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:272)
        at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
        at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1006)
        at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)

**Comment by CarGuo** [comment]
木有，不支持这种场景
