### ISSUE TITLE
替换内核，播放不了

### ISSUE THREAD

**Issue by dzghxs** [CarGuo/GSYVideoPlayer#3862]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

之前使用PlayerFactory.setPlayManager(IjkPlayerManager.class)+CacheFactory.setCacheManager(ProxyCacheManager.class)正常播放，没有问题。
但是需要增加m3u8缓存功能，替换为PlayerFactory.setPlayManager(Exo2PlayerManager.class)+CacheFactory.setCacheManager(ExoPlayerCacheManager.class)，播放不了，log提示：
java.lang.UnsupportedOperationException: ExoPlayerCacheManager only support IjkExo2MediaPlayer

## 问题机型/系统：

真机 红米note9 Android12

## GSY依赖版本

com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.3.5-release-jitpack

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)

PlayerFactory.setPlayManager(Exo2PlayerManager::class.java)
CacheFactory.setCacheManager(ExoPlayerCacheManager::class.java)

## 问题log（如果有）

2023-09-25 17:34:08.977 14806-14806 System.err              jiuquaner.app.chen                   W  java.lang.UnsupportedOperationException: ExoPlayerCacheManager only support IjkExo2MediaPlayer
2023-09-25 17:34:08.977 14806-14806 System.err              jiuquaner.app.chen                   W  	at tv.danmaku.ijk.media.exo2.ExoPlayerCacheManager.doCacheLogic(ExoPlayerCacheManager.java:25)
2023-09-25 17:34:08.977 14806-14806 System.err              jiuquaner.app.chen                   W  	at com.shuyu.gsyvideoplayer.player.IjkPlayerManager.initVideoPlayer(IjkPlayerManager.java:84)
2023-09-25 17:34:08.977 14806-14806 System.err              jiuquaner.app.chen                   W  	at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:624)
2023-09-25 17:34:08.977 14806-14806 System.err              jiuquaner.app.chen                   W  	at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:39)
2023-09-25 17:34:08.978 14806-14806 System.err              jiuquaner.app.chen                   W  	at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:581)
2023-09-25 17:34:08.978 14806-14806 System.err              jiuquaner.app.chen                   W  	at android.os.Handler.dispatchMessage(Handler.java:106)
2023-09-25 17:34:08.978 14806-14806 System.err              jiuquaner.app.chen                   W  	at android.os.Looper.loopOnce(Looper.java:210)
2023-09-25 17:34:08.978 14806-14806 System.err              jiuquaner.app.chen                   W  	at android.os.Looper.loop(Looper.java:299)
2023-09-25 17:34:08.978 14806-14806 System.err              jiuquaner.app.chen                   W  	at android.app.ActivityThread.main(ActivityThread.java:8273)
2023-09-25 17:34:08.978 14806-14806 System.err              jiuquaner.app.chen                   W  	at java.lang.reflect.Method.invoke(Native Method)
2023-09-25 17:34:08.978 14806-14806 System.err              jiuquaner.app.chen                   W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
2023-09-25 17:34:08.978 14806-14806 System.err              jiuquaner.app.chen                   W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

xxxxxxx

```

**Comment by CarGuo** [comment]
ExoPlayerCacheManager only support IjkExo2MediaPlayer

**Comment by dzghxs** [comment]
> ExoPlayerCacheManager only support IjkExo2MediaPlayer，说明用的 playermanager 不对

谢谢大佬，解决了
