### ISSUE TITLE
java.lang.InstantiationException: java.lang.Class<com.shuyu.gsyvideoplayer.player.IjkPlayerManager> cannot be instantiated异常

### ISSUE THREAD

**Issue by wangtonggen** [CarGuo/GSYVideoPlayer#3896]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

InstantiationException异常，PlayerFactory.getPlayManager()CacheFactory.getCacheManager和报错

## 出现问题的视频流

demo上是可以复现的，但是集成到APP依赖出现问题

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本
 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.5.0-release-jitpack'
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-arm64:v8.5.0-release-jitpack'
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-armv7a:v8.5.0-release-jitpack'

## Demo中的复现步骤

Demo可以播放

问题代码：(如果有)
public static IPlayerManager getPlayManager() {
        if (sPlayerManager == null) {
            sPlayerManager = IjkPlayerManager.class;
        }
        try {
            return sPlayerManager.newInstance();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
        return null;
    }

## 问题log（如果有）

ava.lang.InstantiationException: java.lang.Class<com.shuyu.gsyvideoplayer.player.IjkPlayerManager> cannot be instantiated
2023-11-28 17:57:58.929 21897-21897 System.err                                  W  	at com.shuyu.gsyvideoplayer.player.PlayerFactory.getPlayManager(PlayerFactory.java:20)
2023-11-28 17:57:58.929 21897-21897 System.err                                 W  	at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.getPlayManager(GSYVideoBaseManager.java:156)
2023-11-28 17:57:58.929 21897-21897 System.err                                 W  	at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:615)
2023-11-28 17:57:58.929 21897-21897 System.err                                 W  	at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:39)
2023-11-28 17:57:58.929 21897-21897 System.err                                 W  	at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:581)

java.lang.InstantiationException: java.lang.Class<com.shuyu.gsyvideoplayer.cache.ProxyCacheManager> cannot be instantiated
2023-11-28 17:57:58.930 21897-21897 System.err                                  W  	at com.shuyu.gsyvideoplayer.cache.CacheFactory.getCacheManager(CacheFactory.java:20)
2023-11-28 17:57:58.930 21897-21897 System.err                                  W  	at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.getCacheManager(GSYVideoBaseManager.java:160)
2023-11-28 17:57:58.930 21897-21897 System.err                                 W  	at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:616)
2023-11-28 17:57:58.930 21897-21897 System.err                                  W  	at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:39)
2023-11-28 17:57:58.930 21897-21897 System.err                                  W  	at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:581)

**Comment by CarGuo** [comment]
不懂，demo 没有发现问题

**Comment by wangtonggen** [comment]
> 不懂，demo 没有发现问题，你是 AGP8 ？ R8 full 下你要配置下混淆规则，看demo或者文档

是的，混淆少加了一些东西
