### ISSUE TITLE
kotlin环境下，ExoSourceManager.setExoMediaSourceInterceptListener下的getMediaSource和cacheWriteDataSinkFactory方法不能返回为空。会直接异常

### ISSUE THREAD

**Issue by MRDHR** [CarGuo/GSYVideoPlayer#3918]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
kotlin环境下，ExoSourceManager.setExoMediaSourceInterceptListener下的getMediaSource和cacheWriteDataSinkFactory方法不能返回为空。会直接异常

### ❗❗❗⚠️⚠️⚠️这个很重要！！！！没有问题流的问题无法处理复现⚠️⚠️⚠️❗❗❗
任意视频或链接

## 问题机型/系统：
华为P30，红米K60至尊

## GSY依赖版本
 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.5.0-release-jitpack'
 implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer-exo2:v8.5.0-release-jitpack'
 implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-ex_so:v8.5.0-release-jitpack'

## Demo中的复现步骤
Demo使用kotlin，加入ExoSourceManager.setExoMediaSourceInterceptListener相关代码

问题代码：(如果有)
```
 ExoSourceManager.setExoMediaSourceInterceptListener(object :
                ExoMediaSourceInterceptListener {
                override fun getMediaSource(
                    dataSource: String, preview: Boolean, cacheEnable: Boolean,
                    isLooping: Boolean, cacheDir: File
                ): MediaSource? {
                    //如果返回 null，就使用默认的
                    return null
                }

                /**
                 * 通过自定义的 HttpDataSource ，可以设置自签证书或者忽略证书
                 * demo 里的 GSYExoHttpDataSourceFactory 使用的是忽略证书
                 */
                override fun getHttpDataSourceFactory(
                    userAgent: String, listener: TransferListener?, connectTimeoutMillis: Int,
                    readTimeoutMillis: Int, mapHeadData: Map<String, String>,
                    allowCrossProtocolRedirects: Boolean
                ): DataSource.Factory {
                    //如果返回 null，就使用默认的
                    val factory = GSYExoHttpDataSourceFactory(
                        userAgent, listener, connectTimeoutMillis, readTimeoutMillis,
                        allowCrossProtocolRedirects
                    )
                    factory.setDefaultRequestProperties(mapHeadData)
                    return factory
                }

                override fun cacheWriteDataSinkFactory(
                    CachePath: String,
                    url: String
                ): DataSink.Factory? {
                    return null
                }
            })
```

## 问题log（如果有）

```
java.lang.NullPointerException: Parameter specified as non-null is null: method com.dhr.test.application.task.GsyVideoPlayerTask$create$1.getMediaSource, parameter cacheDir
	at com.dhr.test.application.task.GsyVideoPlayerTask$create$1.getMediaSource(GsyVideoPlayerTask.kt)
	at tv.danmaku.ijk.media.exo2.ExoSourceManager.getMediaSource(ExoSourceManager.java:107)
	at tv.danmaku.ijk.media.exo2.IjkExo2MediaPlayer.setDataSource(IjkExo2MediaPlayer.java:179)
	at tv.danmaku.ijk.media.exo2.IjkExo2MediaPlayer.setDataSource(IjkExo2MediaPlayer.java:168)
	at tv.danmaku.ijk.media.exo2.Exo2PlayerManager.initVideoPlayer(Exo2PlayerManager.java:68)
	at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:624)
	at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$000(GSYVideoBaseManager.java:39)
	at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:581)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
        at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
```

## 解决方案
ExoMediaSourceInterceptListener类的三个方法
```
/**
     * @param dataSource  链接
     * @param preview     是否带上header，默认有header自动设置为true
     * @param cacheEnable 是否需要缓存
     * @param isLooping   是否循环
     * @param cacheDir    自定义缓存目录
     * @return 返回不为空时，使用返回的自定义mediaSource
     */
    @Nullable MediaSource getMediaSource(String dataSource, boolean preview, boolean cacheEnable, boolean isLooping, File cacheDir);


    /**
     * 一般用户自定义 http 忽略 ssl 证书之类的可用于自定义
     * Demo 有对应例子
     * @return 返回不为空时，使用返回的自定义 HttpDataSource，
     */
    @Nullable DataSource.Factory getHttpDataSourceFactory(
            String userAgent,
            @Nullable TransferListener listener,
            int connectTimeoutMillis,
            int readTimeoutMillis,
            Map<String, String> mapHeadData,
            boolean allowCrossProtocolRedirects);

    /**
     * 一般情况下返回 null 就可以了
     * 如果 getMediaSource 不为 null ，此方法不会被调用
     * 用于每次自定义自己的  {@link CacheDataSink}
     * @return 返回不为空时，使用返回的自定义 Cache DataSink.Factory
     */
    @Nullable DataSink.Factory cacheWriteDataSinkFactory(String CachePath, String url);
```
增加@nullable注解
```
 /**
     * @param dataSource  链接
     * @param preview     是否带上header，默认有header自动设置为true
     * @param cacheEnable 是否需要缓存
     * @param isLooping   是否循环
     * @param cacheDir    自定义缓存目录
     * @return 返回不为空时，使用返回的自定义mediaSource
     */
    @Nullable MediaSource getMediaSource(String dataSource, boolean preview, boolean cacheEnable, boolean isLooping, File cacheDir);


    /**
     * 一般用户自定义 http 忽略 ssl 证书之类的可用于自定义
     * Demo 有对应例子
     * @return 返回不为空时，使用返回的自定义 HttpDataSource，
     */
    @Nullable DataSource.Factory getHttpDataSourceFactory(
            String userAgent,
            @Nullable TransferListener listener,
            int connectTimeoutMillis,
            int readTimeoutMillis,
            Map<String, String> mapHeadData,
            boolean allowCrossProtocolRedirects);

    /**
     * 一般情况下返回 null 就可以了
     * 如果 getMediaSource 不为 null ，此方法不会被调用
     * 用于每次自定义自己的  {@link CacheDataSink}
     * @return 返回不为空时，使用返回的自定义 Cache DataSink.Factory
     */
    @Nullable DataSink.Factory cacheWriteDataSinkFactory(String CachePath, String url);
```
## 当前v8.5.0-release-jitpack版本的临时解决方案
根据ExoSourceManager里的getMediaSource和cacheWriteDataSinkFactory方法，返回个不为空的
或创建Java类，在类中增加setExoMediaSourceInterceptListener相关代码（参考demo），再在kotlin中调用该方法
例子

GsyVideoPlayerExoSetSourceIntercept.java
```
@UnstableApi
public class GsyVideoPlayerExoSetSourceIntercept {

    public static void setExoMediaSourceInterceptListener() {
        ExoSourceManager.setExoMediaSourceInterceptListener(new ExoMediaSourceInterceptListener() {
            @Override
            public MediaSource getMediaSource(String dataSource, boolean preview, boolean cacheEnable, boolean isLooping, File cacheDir) {
                //如果返回 null，就使用默认的
                return null;
            }

            /**
             * 通过自定义的 HttpDataSource ，可以设置自签证书或者忽略证书
             * demo 里的 GSYExoHttpDataSourceFactory 使用的是忽略证书
             * */
            @Override
            public DataSource.Factory getHttpDataSourceFactory(String userAgent, @Nullable TransferListener listener, int connectTimeoutMillis, int readTimeoutMillis,
                                                               Map<String, String> mapHeadData, boolean allowCrossProtocolRedirects) {
                //如果返回 null，就使用默认的
                GSYExoHttpDataSourceFactory factory = new GSYExoHttpDataSourceFactory(userAgent, listener,
                        connectTimeoutMillis,
                        readTimeoutMillis, allowCrossProtocolRedirects);
                factory.setDefaultRequestProperties(mapHeadData);
                return factory;
            }

            @Override
            public DataSink.Factory cacheWriteDataSinkFactory(String CachePath, String url) {
                return null;
            }
        });
    }
}
```
调用方式
```
GsyVideoPlayerExoSetSourceIntercept.setExoMediaSourceInterceptListener()
```

**Comment by CarGuo** [comment]
你用的直接 java covert to kotlin 了吧，你把  `File cacheDir` 改为  `cacheDir: File?` 就好了

**Comment by MRDHR** [comment]
不能问号的。返回值无问号 代码标红，加了问号调用代码出现异常。
就是因为接口没有@Nullable的注解

**Comment by MRDHR** [comment]
再说了 我也不是 java covert to kotlin，是完全新写的

**Comment by CarGuo** [comment]
？？？？你说啥？
![image](https://github.com/CarGuo/GSYVideoPlayer/assets/10770362/fffb6f0a-66d7-4b12-8358-71a692765f7c)

**Comment by MRDHR** [comment]
这个是我手动加的

**Comment by MRDHR** [comment]
![image](https://github.com/CarGuo/GSYVideoPlayer/assets/5576916/f43b2c44-7d56-400c-9720-537beca8713b)


默认的实现是不带问号的

**Comment by CarGuo** [comment]
> ？？？？如图，你说啥？ ![image](https://private-user-images.githubusercontent.com/10770362/295808710-fffb6f0a-66d7-4b12-8358-71a692765f7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTk3MDAsIm5iZiI6MTcwNDk1OTQwMCwicGF0aCI6Ii8xMDc3MDM2Mi8yOTU4MDg3MTAtZmZmYjZmMGEtNjZkNy00YjEyLTgzNTgtNzFhNjkyNzY1ZjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA3NTAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNmE2ODZiMmIzM2E2OTJmYWE4YjZmMjBlNDdlNGJhNWJiMWU0ZGVjM2ZiYzlhNDFmNjAwMjkzZDhiMTQ5ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rjICLgEfAzGSUFbk1vG0htgSjkXHiPz0R96V7IFOYTA)

不是很懂你的意思，但是我想说，如上图这样可以正常运行

**Comment by geeklx** [comment]
kotlin不行的报null我也遇到了
