### ISSUE TITLE
请问一个缓存问题

### ISSUE THREAD

**Issue by candebbs** [CarGuo/GSYVideoPlayer#3928]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

⚠️ 发生了这样的问题！，请务必描述清楚问题

进入app，固定播放几个网上mp4视频，使用` videoHolder.player.setUp(data.getImage(), true, null);`播放视频，观察到在sdsard/Android/data/包名/cache/video_cache下载视频，但是退出app，再次进入app，重新下载视频了，我想如果缓存这几个视频，进入app，不重新下载视频，怎样做啊？使用
`CacheFactory.setCacheManager(ProxyCacheManager.class);`
也无效果。谢谢！
##

## 问题机型/系统：

例如 android主板 Android7.1

## GSY依赖版本

 ` implementation 'com.github.CarGuo.GSYVideoPlayer:gsyVideoPlayer-java:v8.5.0-release-jitpack'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)

```
        
```

## 问题log（如果有）

```

```

**Comment by CarGuo** [comment]
测试 demo 没有这个情况啊····

**Comment by candebbs** [comment]
在SimplePlayer这个测试，发现是一样的问题。

**Comment by CarGuo** [comment]
刚还是在demo测试，没发现问题

**Comment by candebbs** [comment]
也是在SimplePlayer这个测试吗？保存路径是sdsard/Android/data/包名/cache/video_cache？

**Comment by CarGuo** [comment]
对

**Comment by liujingxing** [comment]
demo在`AndroidManifest.xml`文件里关闭明文传输后，缓存将不能工作, 错误如下
```xml
22:07:20.778  4234-7886  com.example.gsyvideoplayer           E  ****** injectCustomHeaders ****** :0
22:07:20.779  4234-7886  com.example.gsyvideoplayer           E  Error reading ping response
22:07:20.779  4234-7886  com.example.gsyvideoplayer           W  com.danikula.videocache.ProxyCacheException: Error opening connection for http://127.0.0.1:34999/ping with offset 0. Version: 10.0.0
22:07:20.779  4234-7886  com.example.gsyvideoplayer           W  	at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:96)
22:07:20.779  4234-7886  com.example.gsyvideoplayer           W  	at com.danikula.videocache.Pinger.pingServer(Pinger.java:99)
22:07:20.779  4234-7886  com.example.gsyvideoplayer           W  	at com.danikula.videocache.Pinger.access$100(Pinger.java:32)
22:07:20.779  4234-7886  com.example.gsyvideoplayer           W  	at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:121)
22:07:20.779  4234-7886  com.example.gsyvideoplayer           W  	at com.danikula.videocache.Pinger$PingCallable.call(Pinger.java:117)
22:07:20.780  4234-7886  com.example.gsyvideoplayer           W  	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
22:07:20.780  4234-7886  com.example.gsyvideoplayer           W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1251)
22:07:20.780  4234-7886  com.example.gsyvideoplayer           W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:668)
22:07:20.780  4234-7886  com.example.gsyvideoplayer           W  	at java.lang.Thread.run(Thread.java:1012)
22:07:20.780  4234-7886  com.example.gsyvideoplayer           W  Caused by: java.io.IOException: Cleartext HTTP traffic to 127.0.0.1 not permitted
22:07:20.780  4234-7886  com.example.gsyvideoplayer           W  	at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:127)
22:07:20.780  4234-7886  com.example.gsyvideoplayer           W  	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:462)
22:07:20.780  4234-7886  com.example.gsyvideoplayer           W  	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
22:07:20.780  4234-7886  com.example.gsyvideoplayer           W  	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
22:07:20.780  4234-7886  com.example.gsyvideoplayer           W  	at com.danikula.videocache.HttpUrlSource.openConnection(HttpUrlSource.java:205)
22:07:20.780  4234-7886  com.example.gsyvideoplayer           W  	at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:89)
22:07:20.780  4234-7886  com.example.gsyvideoplayer           W  	... 8 more
```

**Comment by liujingxing** [comment]
如果不想全局开启明文传输，可通过以下方式解决
```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="false">
        
    </base-config>

    <!--允许部分http明文通信-->
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">127.0.0.1</domain>
    </domain-config>
</network-security-config>
```
