### ISSUE TITLE
我用的v8.5.0版本，oppo应用市场提醒上线审核不通过  ，提示超频次读取DEVICEID +2，需要您帮忙处理下.

### ISSUE THREAD

**Issue by fengfeng1234** [CarGuo/GSYVideoPlayer#3957]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：
我用的v8.5.0版本，oppo应用市场提醒上线审核不通过  ，提示超频次读取DEVICEID +2，需要您帮忙处理下

⚠️ XXXX发生了这样的问题！，请务必描述清楚问题

## 出现问题的视频流
上线审核的时候

## 问题机型/系统：

无

## GSY依赖版本

com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.5.0-release-jitpack

## Demo中的复现步骤
以下是oppo给出的检测回复：

检测详情：第三方SDK以特定频率或者超频次读取DEVICEID +2，不能频繁调用获取，需要联系第三方SDK更新版本或者修改调用方式。
 我在demo里面查看到core有1.7.0和1.8.0的版本  ，getDeviceId()是在哪些场景调用了？看能否处理下，拜托！

问题代码：
oppo 应用市场客服给发的回复：堆载里面的信息
"	at android.telephony.TelephonyManager.getDeviceId()
	at com.tencent.smtt.utils.b.f(Unknown Source:19)
	at com.tencent.smtt.sdk.TbsLogReport.a(Unknown Source:14)
	at com.tencent.smtt.sdk.TbsLogReport.a(Unknown Source:0)
	at com.tencent.smtt.sdk.TbsLogReport$1.handleMessage(Unknown Source:20)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)
"

**Comment by CarGuo** [comment]
这个是腾讯 TBS浏览服务 的 sdk 的 log 啊 com.tencent.smtt.sdk， 你的什么引用用了 x5 浏览器或者什么其他的吧，gys 这边没有这个
