### ISSUE TITLE
APP 上线 提示：第三方SDK以特定频率或者超频次读取DEVICEID +2，不能频繁调用获取，需要联系第三方SDK更新版本或者修改调用方式

### ISSUE THREAD

**Issue by fengfeng1234** [CarGuo/GSYVideoPlayer#3977]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：APP 上线 提示：第三方SDK以特定频率或者超频次读取DEVICEID +2，不能频繁调用获取，需要联系第三方SDK更新版本或者修改调用方式

⚠️ XXXX发生了这样的问题！，请务必描述清楚问题

## 问题机型/系统：oppo 应用市场

例如 真机 小米note2 Android7.0

## GSY依赖版本     com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v8.6.0-release-jitpack

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)   "	at android.telephony.TelephonyManager.getDeviceId()
	at com.tencent.smtt.utils.b.f(Unknown Source:19)
	at com.tencent.smtt.sdk.TbsLogReport.a(Unknown Source:14)
	at com.tencent.smtt.sdk.TbsLogReport.a(Unknown Source:0)
	at com.tencent.smtt.sdk.TbsLogReport$1.handleMessage(Unknown Source:20)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)
"
```
这是oppo 应用市场审核给的堆栈信息
```

## 问题log（如果有）请问这个问题怎么解决

```

xxxxxxx

```

**Comment by CarGuo** [comment]
com.tencent.smtt.sdk.TbsLogReport
