### ISSUE TITLE
视频播放器暂停且没有任何错误输出，请看日志

### ISSUE THREAD

**Issue by liuchuancong** [CarGuo/GSYVideoPlayer#3991]
```
I/AliFrameWork(30437): [30103293] [apsaraDataSourceListener] :network retry 0 times start in new count
E/AliFrameWork(30437): [30103293] [avFormatDemuxer] :avformat_open_input error -1094995529,Invalid data found when processing input,
E/AliFrameWork(30437): [30103293] [SuperMediaPlayer] :SuperMediaPlayer NotifyError code: [-1094995529] [bebbb1b7]
E/AliFrameWork(30437): [30103293] [SuperMediaPlayer] :Player ReadPacket ffmpeg error ?? 0x41444e49 :Invalid data found when processing input
I/AliFrameWork(30437): [30103293] [AVPBase] :API_OUT:apsaraPlayerStatusChanged status from [2] to [99]
I/AliFrameWork(30437): [30103293] [NativeBase] :AliyunCorePlayer callback --> StatusChanged(7)
I/AliFrameWork(30437): [30103293] [analytics] :eventCode:4001, name:ERROR string:encryption_info * {"keyUrl":""} *||* error_code * 20030003 *||* error_msg * Invalid data found when processing input *||* rsi * [{"type":"url"}] *||* vt * 0 ret:0
I/AliFrameWork(30437): [30103293] [AVPBase] :API_OUT:onErrorMsg)
E/AliFrameWork(30437): [30103293] [NativeBase] :AliyunCorePlayer callback --> ErrorCallback(537067523,Invalid data found when processing input)
I/AliFrameWork(30437): [30103293] [NativeBase] :java_SetView(0x0)
I/AliFrameWork(30437): [30103293] [AVPBase] :API_IN:SetView 0x0
I/AliFrameWork(30437): [30103293] [NativeBase] :java_Stop()
I/AliFrameWork(30437): [30103293] [AVPBase] :API_IN:Stop
I/AliFrameWork(30437): [30103293] [SuperMediaPlayer] :Player ReadPacket Stop
I/AliFrameWork(30437): [30103293] [CurlDataSource2] :==> ~CurlDataSource2
I/AliFrameWork(30437): [30103293] [CurlDataSource2] :<== ~CurlDataSource2
I/AliFrameWork(30437): [30103293] [CachedSource2] :~CachedSource2
I/AliFrameWork(30437): [30103293] [analytics] :eventCode:2012, name:STOP string:abr_info * {"autoBitrate":0,"abrWorked":0,"abrAlgo":"","defaultBandWidth":0,"avgBitrate":null,"avgLatency":0,"avgSwitches":null,"avgRebuffering":null,"avgWorkedTime":0,"maxBufferLength":50000} *||* cost * 2 *||* stream_info * {"streamBitrates":"","audioStreamCount":0,"videoStreamCount":0} *||* vdi * [{"url":"https://stream-tianshui-ct-125-74-63-101.edgesrv.com:443/live/288016rlols5_1024p.flv?wsAuth=b31ae9b4124063e70f08ac1a0d347ee2&token=web-h5-0-288016-e9416291174176eec46de3a0292a78fba3b41dad48a00f65&logo=0&expire=0&did=10000000000000000000000000001501&pt=2&st=0&sid=391582183&mcid2=0&vhost=play2&origin=tct&mix=0&isp=scdnctgasts","dropInfo":"0/0"}] *||* vt * 0 ret:0
I/AliFrameWork(30437): [30103293] [NativeBase] :java_Release()
2
I/AliFrameWork(30437): [30103293] [AVPBase] :API_IN:Stop
I/AliFrameWork(30437): [30103293] [] :player count 3
I/AliFrameWork(30437): [30103293] [SuperMediaPlayer] :==>~SuperMediaPlayer
I/AliFrameWork(30437): [30103293] [SuperMediaPlayer] :<==~SuperMediaPlayer
I/AliFrameWork(30437): [30103293] [] :player count 0
I/AliFrameWork(30437): [30103293] [AVPBase] :~AVPBase 0x72042f5000 cost 3
```
onError 未检测到任何错误，播放器卡住，无任何变化

**Comment by liuchuancong** [comment]
ijk
```
V/IJKMEDIA(30437): header='c-via: 400'
V/IJKMEDIA(30437): header='Expires: -1'
V/IJKMEDIA(30437): header='Pragma: no-cache'
V/IJKMEDIA(30437): header=''
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(30437): onNativeInvoke 2
E/IJKMEDIA(30437): Stream ends prematurely at 13, should be 18446744073709551615
D/IJKMEDIA(30437): Statistics: 13 bytes read, 0 seeks
E/IJKMEDIA(30437): https://stream-tianshui-ct-125-74-63-101.edgesrv.com:443/live/288016rlols5_1024p.flv?wsAuth=088dd2635981e44a55e97018ac215cbc&token=web-h5-0-288016-e9416291174176ee5a47527d2640e3ad628cf400ffcc8865&logo=0&expire=0&did=10000000000000000000000000001501&pt=2&st=0&sid=391582183&mcid2=0&vhost=play2&origin=tct&mix=0&isp=scdnctgasts: I/O error
I/IJKMEDIA(30437): SDL_JNI_DetachThreadEnv: [3495]
D/IJKMEDIA(30437): FFP_MSG_ERROR: 0
E/tv.danmaku.ijk.media.player.IjkMediaPlayer(30437): Error (-10000,0)
D/IJKMEDIA(30437): IjkMediaPlayer_release
D/IJKMEDIA(30437): ijkmp_set_android_surface(surface=0x0)
D/IJKMEDIA(30437): ffpipeline_set_surface()
D/IJKMEDIA(30437): ijkmp_set_android_surface(surface=0x0)=void
D/IJKMEDIA(30437): ijkmp_shutdown_l()
D/IJKMEDIA(30437): wait for read_tid
D/IJKMEDIA(30437): message_loop exit
I/IJKMEDIA(30437): SDL_JNI_DetachThreadEnv: [3491]
D/IJKMEDIA(30437): wait for video_refresh_tid
I/IJKMEDIA(30437): SDL_JNI_DetachThreadEnv: [3492]
D/IJKMEDIA(30437): ijkmp_shutdown_l()=void
D/IJKMEDIA(30437): ijkmp_dec_ref(): ref=0
D/IJKMEDIA(30437): ijkmp_shutdown_l()
D/IJKMEDIA(30437): ijkmp_shutdown_l()=void

```

**Comment by liuchuancong** [comment]
Exo
```
W/AudioManager(30437): Use of stream types is deprecated for operations other than volume control
W/AudioManager(30437): See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
W/libc    (30437): Access denied finding property "vendor.display.enable_display_extensions"
W/ExoPlayer:Place(30437): type=1400 audit(0.0:4151128): avc:  denied  { read } for  name="u:object_r:vendor_display_prop:s0" dev="tmpfs" ino=532 scontext=u:r:untrusted_app_30:s0:c185,c257,c512,c768 tcontext=u:object_r:vendor_display_prop:s0 tclass=file permissive=0 app=com.mystyle.purelive
I/ExoPlayerImpl(30437): Init e9ee9cd [AndroidXMedia3/1.3.0] [vermeer, 23113RKC6C, Xiaomi, 34]
D/EventLogger(30437): state [0.01, B]
D/EventLogger(30437): loading [true]
D/TrafficStats(30437): tagSocket(259) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats(30437): tagSocket(155) with statsTag=0xffffffff, statsUid=-1
E/ExoPlayerImplInternal(30437): Playback error
E/ExoPlayerImplInternal(30437):   androidx.media3.exoplayer.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(30437):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:713)
E/ExoPlayerImplInternal(30437):       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:683)
E/ExoPlayerImplInternal(30437):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(30437):       at android.os.Looper.loopOnce(Looper.java:224)
E/ExoPlayerImplInternal(30437):       at android.os.Looper.loop(Looper.java:318)
E/ExoPlayerImplInternal(30437):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(30437):   Caused by: androidx.media3.common.ParserException: Loading finished before preparation is complete.{contentIsMalformed=true, dataType=1}

```

**Comment by jarvan11** [comment]
最后什么问题？@liuchuancong
