### ISSUE TITLE
音频焦点丢失时onLossAudio内有NPE风险

### ISSUE THREAD

**Issue by KamiNoYuki** [CarGuo/GSYVideoPlayer#4019]
## 问题描述：
**在音频焦点丢失时有空指针风险**
```java
java.lang.NullPointerException: Attempt to invoke interface method 'void com.shuyu.gsyvideoplayer.listener.GSYMediaPlayerListener.onVideoPause()' on a null object reference
	at com.shuyu.gsyvideoplayer.video.base.GSYVideoView$2.run(GSYVideoView.java:390)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8389)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)
```

## GSY依赖版本

```groovy
implementation 'com.github.CarGuo.GSYVideoPlayer:GSYVideoPlayer:v9.0.0-release-jitpack'
```

## Demo中的复现步骤

**GSYVideoBaseManager.java#164**
```java
/**
 *  @return 可能返回null
 */
@Override
public GSYMediaPlayerListener listener() {
    if (listener == null)
        return null;
    return listener.get();
}
```

**GSYVideoView.java#390**
```java
protected void onLossAudio() {
        new Handler(Looper.getMainLooper()).post(new Runnable() {
            public void run() {
                if (GSYVideoView.this.mReleaseWhenLossAudio) {
                    GSYVideoView.this.releaseVideos();
                } else {
                    //此处调用listener()有可能返回null，但此处没有判空。
                    getGSYVideoManager().listener().onVideoPause();
                }
            }
        });
     }
```

**Comment by CarGuo** [comment]
get
