### ISSUE TITLE
androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/dolby-vision, hev1.08.04

### ISSUE THREAD

**Issue by JennShiting** [CarGuo/GSYVideoPlayer#4028]
## 问题描述：

视频无法播放，错误提示格式不支持。

## 出现问题的视频流

提供的有视频链接

## 问题机型/系统：

华为手机 nova 9 SE 

## GSY依赖版本

最新版本

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
设置播放引擎
     PlayerFactory.setPlayManager(Exo2PlayerManager.class);

//播放视频 https://oss.kidcastle.cn/manage/202408290959x079178890.mp4
public class SimplePlayer extends AppCompatActivity {

    StandardGSYVideoPlayer videoPlayer;

    OrientationUtils orientationUtils;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_simple_play);
        init();
    }

    private void init() {
        videoPlayer =  (StandardGSYVideoPlayer)findViewById(R.id.video_player);

        String source1= "https://oss.kidcastle.cn/manage/202408290959x079178890.mp4";
//        String source1 = "http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear3/prog_index.m3u8";
        videoPlayer.setUp(source1, true, "测试视频");


```

## 问题log（如果有）

 E  playerFailed [0.32]
                                                                                                    androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/dolby-vision, hev1.08.04, -1, null, [1920, 1080, 29.988556, ColorInfo(BT2020, Limited range, HLG, false, 10bit Luma, 10bit Chroma)], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:640)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:113)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:293)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:110)
                                                                                                    Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: OMX.qcom.video.decoder.hevc
                                                                                                    	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1982)
                                                                                                    	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:893)
                                                                                                    	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1018)
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:113) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205) 
                                                                                                    	at android.os.Looper.loop(Looper.java:293) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:110) 
                                                                                                    Caused by: android.media.MediaCodec$CodecException: Error 0x80001009

```

**Comment by CarGuo** [comment]
<img width="706" alt="image" src="https://github.com/user-attachments/assets/3b47cebf-bb60-4a6d-a2a0-2c30af94b2a7">
如图，看起来是设备的 Mediacodec 不支持 h265，可以通过代码判断看看
```
   public static boolean isH265HardwareDecoderSupport() {
        MediaCodecList codecList = new MediaCodecList();
        MediaCodecInfo[] codecInfos = codecList.getCodecInfos();
        for (int i = 0; i < codecInfos.length; i++) {
            MediaCodecInfo codecInfo = codecInfos[i];
            if (!codecInfo.isEncoder() && (codecInfo.getName().contains("hevc")
                    && !isSoftwareCodec(codecInfo.getName()))) {
                return true;
            }
        }
        return false;
    }
    public boolean isSoftwareCodec(String codecName) {
        if (codecName.startsWith("OMX.google.")) {
            return true;
        }

        if (codecName.startsWith("OMX.")) {
            return false;
        }

        return true;
    }

```
