### ISSUE TITLE
请教大佬关于对于加解密视频的思路

### ISSUE THREAD

**Issue by geeklx** [CarGuo/GSYVideoPlayer#4038]
## （！！！！请务必务必按照issue模板，*修改* 后提交问题！！！！，不按模板提Isuue删除处理）

（ps 首页问题集锦和demo请先了解一下！）

## 问题描述：

需求就是现在本地已经下载了有AES加密的mp4，想通过GSY播放出来，怎么做呢，目前只能解密后播放，这样有人就能通过文件管理器把解密的视频传播出去，无法保证视频的安全，请大佬指点一下思路

⚠️ XXXX发生了这样的问题！，请务必描述清楚问题

## 问题机型/系统：

例如 真机 小米note2 Android7.0

## GSY依赖版本

例如 `implementation 'com.shuyu:gsyVideoPlayer-java:7.0.1'`

## Demo中的复现步骤

Demo中的detailPlayer页面打开后XXXX会出现这个问题。

问题代码：(如果有)
```
xxxxxxx
```

## 问题log（如果有）

```

xxxxxxx

```

**Comment by CarGuo** [comment]
exoplayer 模式 ，然后自定义 source https://stackoverflow.com/questions/62565879/android-exoplayer-play-aes-encrypted-videos-locally

**Comment by geeklx** [comment]
大佬你的意思是修改这部分的内容，利用EncryptedDataSourceFactory2进行加解密吗
ExoSourceManager.setExoMediaSourceInterceptListener(new ExoMediaSourceInterceptListener() {
            @Override
            public MediaSource getMediaSource(String dataSource, boolean preview, boolean cacheEnable, boolean isLooping, File cacheDir) {
                //如果返回 null，就使用默认的
                MediaSource mediaSource = null;
//                mediaSource = (new ProgressiveMediaSource.Factory(
//                this.getDataSourceFactoryCache(this.mAppContext, cacheEnable, preview, cacheDir, uerAgent),
//                new DefaultExtractorsFactory())).createMediaSource(mediaItem);
//                DataSource.Factory dataSourceFactory = new EncryptedDataSourceFactory(new String(AESUtils.ENCRYPT_KEY));
//                ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
//                try {
//                    Uri uri = Uri.fromFile(cacheDir);
//                    mediaSource = new ExtractorMediaSource(uri, dataSourceFactory, extractorsFactory, null, null);
//                } catch (Exception e) {
//                    e.printStackTrace();
//                }
                //
                MediaItem mediaItem = new MediaItem.Builder()
                        .setMimeType(MimeTypes.BASE_TYPE_VIDEO)// or BASE_TYPE_VIDEO BASE_TYPE_AUDIO
                        .setUri(dataSource) // your file's url
                        .build();
                //
                DataSource.Factory dataSourceFactory = new EncryptedDataSourceFactory2(AESUtils.ENCRYPT_KEY, AESUtils.INDEX_KEY);
                mediaSource = new ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(mediaItem);
                //
//                HttpDataSource.Factory defaultHttpDataSourceFactory = new DefaultHttpDataSource.Factory();
//                MediaItem mediaItem = MediaItem.fromUri(dataSource);
//                mediaSource = new ProgressiveMediaSource.Factory(defaultHttpDataSourceFactory).createMediaSource(mediaItem);
                return mediaSource;
            }

            /**
             * 通过自定义的 HttpDataSource ，可以设置自签证书或者忽略证书
             * demo 里的 GSYExoHttpDataSourceFactory 使用的是忽略证书
             * */
            @Override
            public DataSource.Factory getHttpDataSourceFactory(String userAgent, @Nullable TransferListener listener, int connectTimeoutMillis, int readTimeoutMillis,
                                                               Map<String, String> mapHeadData, boolean allowCrossProtocolRedirects) {
                //如果返回 null，就使用默认的
                GSYExoHttpDataSourceFactory2 factory = new GSYExoHttpDataSourceFactory2(userAgent, listener,
                        connectTimeoutMillis,
                        readTimeoutMillis, allowCrossProtocolRedirects);
                factory.setDefaultRequestProperties(mapHeadData);
                return factory;
            }

//            @Override
//            public DataSink.Factory cacheWriteDataSinkFactory(String CachePath, String url) {
//                return null;
//            }
        });

**Comment by geeklx** [comment]
```
val defaultHttpDataSourceFactory = DefaultHttpDataSource.Factory()
      val mediaItem = MediaItem.fromUri(URL)
      val mediaSource = ProgressiveMediaSource.Factory(defaultHttpDataSourceFactory)
            .createMediaSource(mediaItem)
      exoPlayer?.setMediaSource(mediaSource)
```

我用这个加入自定义mediaSource后就播放不了了怎么回事
https://stackoverflow.com/questions/56661984/android-exoplayer-extractormediasource-is-deprecated

**Comment by geeklx** [comment]
这个写法传值怎么传 大佬
https://stackoverflow.com/questions/62565879/android-exoplayer-play-aes-encrypted-videos-locally

第二个值iv传哪个key呢
https://github.com/smmousavi8872/MMPlayer/blob/master/androidApp/src/main/java/com/github/smmousavi/mmplayer/android/service/encryption/util/CipherManagement.kt

**Comment by geeklx** [comment]
大佬 我这样写为啥播放不了视频了（视频未加密）

```
ExoSourceManager.setExoMediaSourceInterceptListener(new ExoMediaSourceInterceptListener() {
            @Override
            public MediaSource getMediaSource(String dataSource, boolean preview, boolean cacheEnable, boolean isLooping, File cacheDir) {
                //如果返回 null，就使用默认的
                MediaSource mediaSource = null;
//                mediaSource = (new ProgressiveMediaSource.Factory(
//                this.getDataSourceFactoryCache(this.mAppContext, cacheEnable, preview, cacheDir, uerAgent),
//                new DefaultExtractorsFactory())).createMediaSource(mediaItem);
//                DataSource.Factory dataSourceFactory = new EncryptedDataSourceFactory(new String(AESUtils.ENCRYPT_KEY));
//                ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
//                try {
//                    Uri uri = Uri.fromFile(cacheDir);
//                    mediaSource = new ExtractorMediaSource(uri, dataSourceFactory, extractorsFactory, null, null);
//                } catch (Exception e) {
//                    e.printStackTrace();
//                }
                //
//                MediaItem mediaItem = new MediaItem.Builder()
//                        .setMimeType(MimeTypes.BASE_TYPE_VIDEO)// or BASE_TYPE_VIDEO BASE_TYPE_AUDIO
//                        .setUri(dataSource) // your file's url
//                        .build();
//                //
//                DataSource.Factory dataSourceFactory = new EncryptedDataSourceFactory2(AESUtils.ENCRYPT_KEY, AESUtils.INDEX_KEY);
//                mediaSource = new ProgressiveMediaSource.Factory(dataSourceFactory).createMediaSource(mediaItem);
                //
                HttpDataSource.Factory defaultHttpDataSourceFactory = new DefaultHttpDataSource.Factory();
                MediaItem mediaItem = MediaItem.fromUri(dataSource);
                mediaSource = new ProgressiveMediaSource.Factory(defaultHttpDataSourceFactory).createMediaSource(mediaItem);
                return mediaSource;
            }

            /**
             * 通过自定义的 HttpDataSource ，可以设置自签证书或者忽略证书
             * demo 里的 GSYExoHttpDataSourceFactory 使用的是忽略证书
             * */
            @Override
            public DataSource.Factory getHttpDataSourceFactory(String userAgent, @Nullable TransferListener listener, int connectTimeoutMillis, int readTimeoutMillis,
                                                               Map<String, String> mapHeadData, boolean allowCrossProtocolRedirects) {
                //如果返回 null，就使用默认的
//                GSYExoHttpDataSourceFactory2 factory = new GSYExoHttpDataSourceFactory2(userAgent, listener,
//                        connectTimeoutMillis,
//                        readTimeoutMillis, allowCrossProtocolRedirects);
//                factory.setDefaultRequestProperties(mapHeadData);
                HttpDataSource.Factory factory = new DefaultHttpDataSource.Factory();
                return factory;
            }

//            @Override
//            public DataSink.Factory cacheWriteDataSinkFactory(String CachePath, String url) {
//                return null;
//            }
        });
```

**Comment by CarGuo** [comment]
这个和你具体加密方式有关系，理论上  ExoPlayer 里是 AES-CBC-PKCS7Padding，也就是你需要了解  AES / CBC / PKCS7Padding  的概念，具体你要先知道你的加密是什么，然后才知道怎么解密，iv 是 初始化向量 ，一般是 0 ，看你加密是的设置

**Comment by geeklx** [comment]
谢谢大佬

这个地方我改了自定义后，播不出来了，视频未加密，应该怎么写自定义这地方
https://blog.csdn.net/u011050607/article/details/78284744


```
package com.geek.appcommon.exosource;

import com.google.android.exoplayer2.extractor.DefaultExtractorsFactory;

import android.content.Context;
import android.net.Uri;

import androidx.annotation.Nullable;

import com.google.android.exoplayer2.MediaItem;
import com.google.android.exoplayer2.source.MediaSource;
import com.google.android.exoplayer2.source.ProgressiveMediaSource;
import com.google.android.exoplayer2.upstream.DataSource;
import com.google.android.exoplayer2.upstream.DefaultBandwidthMeter;
import com.google.android.exoplayer2.upstream.DefaultDataSource;
import com.google.android.exoplayer2.upstream.DefaultHttpDataSource;
import com.google.android.exoplayer2.upstream.HttpDataSource;
import com.google.android.exoplayer2.upstream.TransferListener;
import com.google.android.exoplayer2.upstream.cache.Cache;
import com.google.android.exoplayer2.upstream.cache.CacheDataSource;
import com.google.android.exoplayer2.util.Util;

import java.io.File;
import java.net.URL;
import java.util.Map;

import tv.danmaku.ijk.media.exo2.ExoMediaSourceInterceptListener;
import tv.danmaku.ijk.media.exo2.ExoSourceManager;

public class GsyVideoPlayerExoSetSourceIntercept {

    public static void setExoMediaSourceInterceptListener() {
        ExoSourceManager.setExoMediaSourceInterceptListener(new ExoMediaSourceInterceptListener() {
            @Override
            public MediaSource getMediaSource(String dataSource, boolean preview, boolean cacheEnable, boolean isLooping, File cacheDir) {
                //如果返回 null，就使用默认的
                MediaSource mediaSource = null;
                HttpDataSource.Factory defaultHttpDataSourceFactory = new DefaultHttpDataSource.Factory();
//                URL url= new URL(null, dataSource, new sun.net.www.protocol.https.Handler());
                MediaItem mediaItem = MediaItem.fromUri(Uri.parse(dataSource));
                mediaSource = new ProgressiveMediaSource.Factory(defaultHttpDataSourceFactory).createMediaSource(mediaItem);
                return mediaSource;
            }

            /**
             * 通过自定义的 HttpDataSource ，可以设置自签证书或者忽略证书
             * demo 里的 GSYExoHttpDataSourceFactory 使用的是忽略证书
             * */
            @Override
            public DataSource.Factory getHttpDataSourceFactory(String userAgent, @Nullable TransferListener listener, int connectTimeoutMillis, int readTimeoutMillis,
                                                               Map<String, String> mapHeadData, boolean allowCrossProtocolRedirects) {
                HttpDataSource.Factory factory = new DefaultHttpDataSource.Factory();
                return factory;
            }

        });
    }


}
```


报错信息：
 ```
com.google.android.exoplayer2.ExoPlaybackException: Source error
                                                                                                    	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
                                                                                                    	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:608)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:113)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:293)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:110)
                                                                                                    Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected ClassCastException: sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection
                                                                                                    	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:433)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:933)
                                                                                                    Caused by: java.lang.ClassCastException: sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection
                                                                                                    	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.openConnection(DefaultHttpDataSource.java:652)
                                                                                                    	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:610)
                                                                                                    	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:525)
                                                                                                    	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:367)
                                                                                                    	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
                                                                                                    	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1005)
                                                                                                    	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at java.lang.Thread.run(Thread.java:933) 
```

**Comment by CarGuo** [comment]
没加密你 return null
