### ISSUE TITLE
v10.0.0版本解析字幕报错 Legacy decoding is disabled

### ISSUE THREAD

**Issue by ruoxuanFu** [CarGuo/GSYVideoPlayer#4045]
## 问题描述：

v10.0.0版本解析字幕报错：

```
Caused by: java.lang.IllegalStateException: Legacy decoding is disabled, can't handle application/x-subrip samples (expected application/x-media3-cues).
    at androidx.media3.common.util.Assertions.checkState(Assertions.java:100)
    at androidx.media3.exoplayer.text.TextRenderer.assertLegacyDecodingEnabledIfRequired(TextRenderer.java:589)
    at androidx.media3.exoplayer.text.TextRenderer.onStreamChanged(TextRenderer.java:212)
    at androidx.media3.exoplayer.BaseRenderer.replaceStream(BaseRenderer.java:151)
    at androidx.media3.exoplayer.BaseRenderer.enable(BaseRenderer.java:125)
    at androidx.media3.exoplayer.ExoPlayerImplInternal.enableRenderer(ExoPlayerImplInternal.java:2773)
    at androidx.media3.exoplayer.ExoPlayerImplInternal.enableRenderers(ExoPlayerImplInternal.java:2747)
    at androidx.media3.exoplayer.ExoPlayerImplInternal.enableRenderers(ExoPlayerImplInternal.java:2728)
    at androidx.media3.exoplayer.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:2525)
    at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loopOnce(Looper.java:222) 
    at android.os.Looper.loop(Looper.java:314) 
    at android.os.HandlerThread.run(HandlerThread.java:67) 
```

## 问题机型/系统：

真机 红米k70E Android 14

## GSY依赖版本

implementation "com.github.CarGuo.GSYVideoPlayer:gsyvideoplayer-java:v10.0.0"
implementation "com.github.CarGuo.GSYVideoPlayer:gsyvideoplayer-exo2:v10.0.0"
implementation "com.github.CarGuo.GSYVideoPlayer:gsyvideoplayer-arm64:v10.0.0"
implementation "com.github.CarGuo.GSYVideoPlayer:gsyvideoplayer-armv7a:v10.0.0"

## Demo中的复现步骤

问题代码：
```
Format textFormat = new Format.Builder()
        .setSampleMimeType(MimeTypes.APPLICATION_SUBRIP)
        .setSelectionFlags(C.SELECTION_FLAG_FORCED)
        .setLanguage("en")
        .build();
```

这里setSampleMimeType换成
```
.setSampleMimeType(MimeTypes.APPLICATION_MEDIA3_CUES)
```
后报错：

```
androidx.media3.exoplayer.ExoPlaybackException: Unexpected runtime error
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:720)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.IllegalStateException: Bundle length is not aligned by 4: 808454705
	at android.os.BaseBundle.readFromParcelInner(BaseBundle.java:1881)
	at android.os.BaseBundle.<init>(BaseBundle.java:176)
	at android.os.Bundle.<init>(Bundle.java:103)
	at android.os.Parcel.readBundle(Parcel.java:3359)
	at androidx.media3.extractor.text.CueDecoder.decode(CueDecoder.java:63)
	at androidx.media3.exoplayer.text.TextRenderer.readAndDecodeCuesWithTiming(TextRenderer.java:336)
	at androidx.media3.exoplayer.text.TextRenderer.renderFromCuesWithTiming(TextRenderer.java:295)
	at androidx.media3.exoplayer.text.TextRenderer.render(TextRenderer.java:263)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
	at android.os.Handler.dispatchMessage(Handler.java:102) 
	at android.os.Looper.loopOnce(Looper.java:222) 
	at android.os.Looper.loop(Looper.java:314) 
	at android.os.HandlerThread.run(HandlerThread.java:67) 
```

版本回退到v8.6.0-release-jitpack可以正常播放

**Comment by sky-chy** [comment]
老哥，你用哪个仓库的包？我现在下载包都下不了

**Comment by CarGuo** [comment]
字幕问题 demo 测试正常，已提交 demo 修改


依赖如下所示：


```
implementation 'com.github.CarGuo.GSYVideoPlayer:gsyvideoplayer:v10.0.0'
```

![image](https://github.com/user-attachments/assets/ef350589-d036-494e-beff-fb6c529d33e7)


<img width="919" alt="image" src="https://github.com/user-attachments/assets/a5dc6bb8-b836-4487-a5f9-33d7397b52f6">

**Comment by ruoxuanFu** [comment]
指定了MimeTypes.APPLICATION_MEDIA3_CUES，还是不行
我这边指定的字幕是en
`setLanguage("en")`
否则拿不到字幕

我尝试把srt文件转换为vtt文件，依旧报错
`androidx.media3.exoplayer.ExoPlaybackException: Unexpected runtime error
    at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:720)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loopOnce(Looper.java:222)
    at android.os.Looper.loop(Looper.java:314)
    at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.IllegalStateException: Bundle length is not aligned by 4: 1447183703
    at android.os.BaseBundle.readFromParcelInner(BaseBundle.java:1881)
    at android.os.BaseBundle.<init>(BaseBundle.java:176)
    at android.os.Bundle.<init>(Bundle.java:103)
    at android.os.Parcel.readBundle(Parcel.java:3359)
    at androidx.media3.extractor.text.CueDecoder.decode(CueDecoder.java:63)
    at androidx.media3.exoplayer.text.TextRenderer.readAndDecodeCuesWithTiming(TextRenderer.java:336)
    at androidx.media3.exoplayer.text.TextRenderer.renderFromCuesWithTiming(TextRenderer.java:295)
    at androidx.media3.exoplayer.text.TextRenderer.render(TextRenderer.java:263)
    at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
    at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loopOnce(Looper.java:222) 
    at android.os.Looper.loop(Looper.java:314) 
    at android.os.HandlerThread.run(HandlerThread.java:67) 
`
看起来像是media3解析的问题

**Comment by CarGuo** [comment]
我这边用你的 srt 文件测试正常

<img width="351" alt="image" src="https://github.com/user-attachments/assets/3cc017d8-31a6-46e8-b90e-d22c45822c4a">

<img width="349" alt="image" src="https://github.com/user-attachments/assets/99228ef4-f7a4-42da-8d39-db067072bdfa">

**Comment by ruoxuanFu** [comment]
media3的1.3.0版本的TextRenderer类中legacyDecodingEnabled默认值是 true;
而在1.4.1中默认值是false，且experimentalSetLegacyDecodingEnabled方法被标记过时，导致后续断言不通过，只能解析有限格式字幕文件，我这边还是相同的问题

**Comment by ruoxuanFu** [comment]
现在我的解决办法是继承DefaultRenderersFactory重写buildTextRenderers方法
`@UnstableApi
public class MyRenderersFactory extends DefaultRenderersFactory {

    /**
     * @param context A {@link Context}.
     */
    public MyRenderersFactory(Context context) {
        super(context);
    }

    protected void buildTextRenderers(
            Context context,
            TextOutput output,
            Looper outputLooper,
            @ExtensionRendererMode int extensionRendererMode,
            ArrayList<Renderer> out) {
        TextRenderer textRenderer = new TextRenderer(output, outputLooper);
        textRenderer.experimentalSetLegacyDecodingEnabled(true);
        out.add(textRenderer);
    }
}`

**Comment by CarGuo** [comment]
https://github.com/androidx/media/issues/1516

**Comment by benwangdroid** [comment]
> 我这边用你的 srt 文件测试正常
> 
> <img alt="image" width="351" src="https://private-user-images.githubusercontent.com/10770362/382972529-3cc017d8-31a6-46e8-b90e-d22c45822c4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNzAxMjksIm5iZiI6MTczMjA2OTgyOSwicGF0aCI6Ii8xMDc3MDM2Mi8zODI5NzI1MjktM2NjMDE3ZDgtMzFhNi00NmU4LWI5MGUtZDIyYzQ1ODIyYzRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAyMzAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNTYxZGIwZmVlYWJmZTc2MjEwMGY3MTc0N2JlMGUwOGEwMGU5Y2VjNDRjOTQ3MDUxNGEzNjIwNmI4NDFjNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JdILRemv1f-lNmN_fkchOoVjVjTnOtCNNy_MZMgspp8"> <img alt="image" width="349" src="https://private-user-images.githubusercontent.com/10770362/382972568-99228ef4-f7a4-42da-8d39-db067072bdfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNzAxMjksIm5iZiI6MTczMjA2OTgyOSwicGF0aCI6Ii8xMDc3MDM2Mi8zODI5NzI1NjgtOTkyMjhlZjQtZjdhNC00MmRhLThkMzktZGIwNjcwNzJiZGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAyMzAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2OTk1YjYwZWViOTZlZDRmNTllMTAzNWVjZWQxMzhiODhkNDhkODBmZDAxMDc2MWMyYWE1ZTIyYzRiOGZjNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.14FKLD2Tldp6AJK0KfMdGzL7perhr_o_4H9FVfbUwCI">

大佬 他的字幕文件根本没有你红字里面的那句啊

**Comment by CarGuo** [comment]
@benwangdroid  https://github.com/CarGuo/GSYVideoPlayer/issues/4057
