### ISSUE TITLE
GSYBaseVideoPlayer.backFromWindowFull方法在某些情况下NullPointerException

### ISSUE THREAD

**Issue by AndSync** [CarGuo/GSYVideoPlayer#474]
````
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.app.Activity.findViewById(int)' on a null object reference
	at com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer.backFromWindowFull(GSYBaseVideoPlayer.java:741)
	at com.taoche.qctt.mczs.ui.home.fragment.CommonNewsListFragment.onBackPressed(CommonNewsListFragment.java:207)
	at com.taoche.qctt.mczs.ui.car.activity.CarDetailActivity.onBackPressed(CarDetailActivity.java:121)
	at android.app.Activity.onKeyUp(Activity.java:2744)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2702)
	at android.app.Activity.dispatchKeyEvent(Activity.java:3049)
	at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
	at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:317)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4388)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4359)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3905)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3958)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3924)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4051)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3932)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4108)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3905)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3958)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3924)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3932)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3905)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3958)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3924)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4084)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4250)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2402)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1998)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1989)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2379)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:323)
	at android.os.Looper.loop(Looper.java:139)
	at android.app.ActivityThread.main(ActivityThread.java:6200)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
````

**Comment by CarGuo** [comment]
Acitvity context是空？

**Comment by AndSync** [comment]
是在fragment中使用的 传入的getActivity() 可能为空

**Comment by CarGuo** [comment]
这个外部判空吧，毕竟这个是用在返回按键
