### ISSUE TITLE
ContextThemeWrapper

### ISSUE THREAD

**Issue by chenwentong0** [CarGuo/GSYVideoPlayer#484]
v7包上面的ContextThemeWrapper找不到异常

**Comment by CarGuo** [comment]
不理解

**Comment by chenwentong0** [comment]
就是你这里的编译版本的v7包是22.2.1我们项目的编译
compileSdkVersion 24
buildToolsVersion '25.0.0'
v7包目录结构的不一样这个样怎么解决啊？

**Comment by CarGuo** [comment]
高版本的v7包下可以使用没问题啊，依赖的时候可以exculde点本项目的v7

**Comment by chenwentong0** [comment]
//视频播放
    compile ('com.shuyu:GSYVideoPlayer:2.0.8') {
        exclude group:'com.android.support:appcompat-v7:22.2.1'
    }
加了还是不行呢？还是报错
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.internal.view.ContextThemeWrapper" on path: DexPathList[[zip file "/data/app/.."],nativeLibraryDirectories=[/data/app/../lib/arm64, /data/app/../base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
                                                                    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                    at com.shuyu.gsyvideoplayer.utils.CommonUtil.getAppCompActivity(CommonUtil.java:181) 
                                                                    at com.shuyu.gsyvideoplayer.utils.CommonUtil.hideSupportActionBar(CommonUtil.java:107) 
                                                                    at com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer.startWindowFullscreen(GSYBaseVideoPlayer.java:466) 
                                                                    at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.startWindowFullscreen(StandardGSYVideoPlayer.java:320) 
                                                                    at com.tianxi66.ejc.video.DanmakuVideoPlayer.startWindowFullscreen(DanmakuVideoPlayer.java:155) 
                                                                    at com.tianxi66.ejc.task.test.TestActivity$1.onClick(TestActivity.java:93)

**Comment by chenwentong0** [comment]
只要我一点全屏播放就报这个错误，是我exclude写错了吗？

**Comment by CarGuo** [comment]
compile('com.xxxx.xxxx:1.1.0') {
    exclude group: 'com.android.support', module: 'appcompat-v7'
}  然后你可以再看看是不是超过了64k方法数之类的需要拆包

**Comment by riseLishan** [comment]
我也遇到了这个问题，想问楼主怎么解决的 @chenwentong0

**Comment by chenwentong0** [comment]
之前看到忘记回复了，不好意思，我是直接把项目拉下来，然后直接改里面的v7版本号，上传到自己服务器上依赖的。@riseLishan

**Comment by iwantofun** [comment]
用
compile('com.xxxx.xxxx:1.1.0') {
exclude group: 'com.android.support', module: 'appcompat-v7'
} 

的方法无法解决这个问题
