### ISSUE TITLE
demo出错了

### ISSUE THREAD

**Issue by TuringHuang** [CarGuo/GSYVideoPlayer#560]
FATAL EXCEPTION: GLThread 5549
                                                                            Process: com.example.gsyvideoplayer, PID: 16861
                                                                            java.lang.RuntimeException: glDrawArrays: glError 1282
                                                                                at com.shuyu.gsyvideoplayer.render.GSYVideoGLViewBaseRender.checkGlError(GSYVideoGLViewBaseRender.java:109)
                                                                                at com.shuyu.gsyvideoplayer.render.GSYVideoGLViewSimpleRender.initPointerAndDraw(GSYVideoGLViewSimpleRender.java:245)
                                                                                at com.shuyu.gsyvideoplayer.render.GSYVideoGLViewSimpleRender.onDrawFrame(GSYVideoGLViewSimpleRender.java:112)
                                                                                at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1582)
                                                                                at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1267)

**Comment by CarGuo** [comment]
怎么复现？

**Comment by CarGuo** [comment]
使用GL必须机器支持opengl es2

**Comment by TuringHuang** [comment]
filter里面，在播放的时候，点击切换效果就GG，我的手机肯定是支持opengl es2.0的，我写个es demo,用的就是2.0

**Comment by CarGuo** [comment]
我这边没出现，你可以看看是不是机型兼容问题

**Comment by mohitauappface** [comment]
I am also facing the same issue. Did anyone get a fix?

**Comment by CarGuo** [comment]
如果可能，请提供重现方法，确保机器支持es2.0

**Comment by tigericon** [comment]
华为 mate9 使用滤镜的demo 会出现同样的问题，没有做任何操作，直接使用demo播放

**Comment by CarGuo** [comment]
@tigericon 可以看看新版本dev分支中的，新的针对这个做了优化

**Comment by tigericon** [comment]
@CarGuo 你好，我使用了分支中的版本  但是还是出现了这个错误
![image](https://user-images.githubusercontent.com/19162145/34508523-461f47f8-f07b-11e7-9ded-d50b861dd121.png)
