### ISSUE TITLE
Android低版本适配三星note3 版本4.3

### ISSUE THREAD

**Issue by zhangxu0401** [CarGuo/GSYVideoPlayer#567]
通过compile 'com.shuyu:GSYVdeoPlayer:2.1.1'引入项目。
报错：
FATAL EXCEPTION: main
                                                                 java.lang.NoClassDefFoundError: tv.danmaku.ijk.media.player.IjkMediaPlayer
                                                                     at com.shuyu.gsyvideoplayer.GSYVideoManager.<init>(GSYVideoManager.java:305)
                                                                     at com.shuyu.gsyvideoplayer.GSYVideoManager.instance(GSYVideoManager.java:131)
                                                                     at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.setSpeed(GSYVideoView.java:913)
                                                                     at com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer.cloneParams(GSYBaseVideoPlayer.java:198)
                                                                     at com.shuyu.gsyvideoplayer.video.base.GSYBaseVideoPlayer.startWindowFullscreen(GSYBaseVideoPlayer.java:523)
                                                                     at com.shuyu.gsyvideoplayer.video.StandardGSYVideoPlayer.startWindowFullscreen(StandardGSYVideoPlayer.java:324)
                                                                     at gaosi.com.learn.studentapp.playback.PlayBackActivity.initPlayer(PlayBackActivity.java:53)
                                                                     at gaosi.com.learn.studentapp.playback.PlayBackActivity.onCreate(PlayBackActivity.java:43)
                                                                     at android.app.Activity.performCreate(Activity.java:5372)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2362)
                                                                     at android.app.ActivityThread.access$700(ActivityThread.java:168)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                     at android.os.Looper.loop(Looper.java:177)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5493)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:525)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041)
                                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by CarGuo** [comment]
ndk过滤问题
或者分包问题

**Comment by zhangxu0401** [comment]
有什么解决办法么？
或者提供一个解决思路

**Comment by CarGuo** [comment]
如果demo没有问题。可以参考demo的ndk过滤。
然后看看是否需要分包。

**Comment by zhangxu0401** [comment]
这是我添加的ndk过滤
`ndk {
            abiFilters 'armeabi', 'armeabi-v7a', 'x86'
        }`
这是添加的分包
`
compile 'com.shuyu:gsyVideoPlayer-java:2.1.1'

    compile 'com.shuyu:gsyVideoPlayer-armv5:2.1.1'
    compile 'com.shuyu:gsyVideoPlayer-armv7a:2.1.1'
    compile 'com.shuyu:gsyVideoPlayer-x64:2.1.1'
    compile 'com.shuyu:gsyVideoPlayer-x86:2.1.1'
    compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.8.4'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.8.4'
    compile 'com.shuyu:gsyVideoPlayer-ex_so:2.1.1'`
依然还是报错。

**Comment by CarGuo** [comment]
这样添加so不对的，你要不就我们纯ijk的so，要不就添加gsy的so，要不就单独使用ex so
