### ISSUE TITLE
.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)这个为什么啊

### ISSUE THREAD

**Issue by Lyl521** [CarGuo/GSYVideoPlayer#58]

**Comment by CarGuo** [comment]
请上传完整log，参考 https://github.com/CarGuo/GSYVideoPlayer/blob/master/QUESTION.md 第三条，看看是不是因为没有过滤so导致，或者编译版本过高之类。

**Comment by hujlin** [comment]
我也遇到了这个问题，
System: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(IjkMediaPlayer.java:950)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
        at java.lang.Daemons$Daemon.run(Daemons.java:103)
        at java.lang.Thread.run(Thread.java:764)
请问楼主解决了没
