### ISSUE TITLE
闪退：java.lang.IllegalStateException: mpjni: start: null mp

### ISSUE THREAD

**Issue by Wangct23** [CarGuo/GSYVideoPlayer#654]

**Comment by Wangct23** [comment]
```
java.lang.IllegalStateException: mpjni: start: null mp
	at tv.danmaku.ijk.media.player.IjkMediaPlayer._start(Native Method)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.start(IjkMediaPlayer.java:522)
	at xxx.xxx.xxx.xxx.player.VideoPlayer.onVideoResume(VideoPlayer.java:481)
	at xxx.xxx.xxx.xxx.player.VideoPlayer$5.onAudioFocusChange(VideoPlayer.java:173)
	at android.media.AudioManager$FocusEventHandlerDelegate$1.handleMessage(AudioManager.java:2018)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5113)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
	at dalvik.system.NativeStart.main(Native Method)

```

>搜到ijk的issue，好像没什么帮助
[ijkIssue](https://github.com/Bilibili/ijkplayer/issues/2136)

>重载了onAudioFocusChangeListener

```
onAudioFocusChangeListener = new AudioManager.OnAudioFocusChangeListener() {
            @Override
            public void onAudioFocusChange(int focusChange) {
                int volume;
                switch (focusChange) {
                    // 重新获得焦点
                    case AudioManager.AUDIOFOCUS_GAIN:
                        LogUtil.i("AUDIOFOCUS_GAIN");
                        if (!willPlay() && isPausedByFocusLossTransient) {
                            // 通话结束，恢复播放
                            getCurrentPlayer().onVideoResume();
                        }

                        volume = mAudioManager.getStreamVolume(AudioManager.STREAM_MUSIC);
                        if (mVolumeWhenFocusLossTransientCanDuck > 0 && volume == mVolumeWhenFocusLossTransientCanDuck / 2) {
                            // 恢复音量
                            mAudioManager.setStreamVolume(AudioManager.STREAM_MUSIC, mVolumeWhenFocusLossTransientCanDuck,
                                    AudioManager.FLAG_REMOVE_SOUND_AND_VIBRATE);
                        }

                        isPausedByFocusLossTransient = false;
                        mVolumeWhenFocusLossTransientCanDuck = 0;
                        break;
                    // 永久丢失焦点，如被其他播放器抢占
                    case AudioManager.AUDIOFOCUS_LOSS:
                        LogUtil.i("AUDIOFOCUS_LOSS");
                        if (willPlay()) {
                            forceStop();
                        }
                        break;
                    // 短暂丢失焦点，如来电
                    case AudioManager.AUDIOFOCUS_LOSS_TRANSIENT:
                        LogUtil.i("AUDIOFOCUS_LOSS_TRANSIENT");
                        if (willPlay()) {
                            forceStop();
                            isPausedByFocusLossTransient = true;
                        }
                        break;
                    // 瞬间丢失焦点，如通知
                    case AudioManager.AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK:
                        LogUtil.i("AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK");
                        // 音量减小为一半
                        volume = mAudioManager.getStreamVolume(AudioManager.STREAM_MUSIC);
                        if (willPlay() && volume > 0) {
                            mVolumeWhenFocusLossTransientCanDuck = volume;
                            mAudioManager.setStreamVolume(AudioManager.STREAM_MUSIC, mVolumeWhenFocusLossTransientCanDuck / 2,
                                    AudioManager.FLAG_REMOVE_SOUND_AND_VIBRATE);
                        }
                        break;
                }
            }
        };

```

**Comment by CarGuo** [comment]
ijk内部的问题，代码里应该在大部分catch 了

**Comment by Wangct23** [comment]
@CarGuo 这样说的话只好catch了
