### ISSUE TITLE
遇到了空指针问题

### ISSUE THREAD

**Issue by Wangct23** [CarGuo/GSYVideoPlayer#658]
```
java.lang.NullPointerException
	at android.graphics.Canvas.drawArc(Canvas.java:990)
	at moe.codeest.enviews.ENPlayView.onDraw(ENPlayView.java:140)
	at android.view.View.draw(View.java:13712)
	at android.view.View.draw(View.java:13596)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2928)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797)
	at android.view.View.draw(View.java:13715)
	at android.view.View.draw(View.java:13596)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2928)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797)
	at android.view.View.draw(View.java:13594)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2928)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797)
	at android.view.View.draw(View.java:13715)
	at android.widget.FrameLayout.draw(FrameLayout.java:467)
	at android.view.View.draw(View.java:13596)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2928)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797)
	at android.view.View.draw(View.java:13715)
	at android.widget.FrameLayout.draw(FrameLayout.java:467)
	at android.view.View.draw(View.java:13596)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2928)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797)
	at android.view.View.draw(View.java:13594)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2928)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797)
	at android.view.View.draw(View.java:13594)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2928)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797)
	at android.view.View.draw(View.java:13594)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2928)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2797)
	at android.view.View.draw(View.java:13715)
	at android.widget.FrameLayout.draw(FrameLayout.java:467)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2211)
	at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:2294)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2190)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2058)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1867)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1002)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4400)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
	at android.view.Choreographer.doCallbacks(Choreographer.java:562)
	at android.view.Choreographer.doFrame(Choreographer.java:532)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5041)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
	at dalvik.system.NativeStart.main(Native Method)
```

**# Onda V813s Core4   Android 4.2.2**

**Comment by CarGuo** [comment]
demo中复现？？
