### ISSUE TITLE
我在activity onPause() 的时候调用onVideoPause();  updatePauseCover(); 出现oom

### ISSUE THREAD

**Issue by KomoriWu** [CarGuo/GSYVideoPlayer#784]
我在activity onPause() 的时候调用onVideoPause();  updatePauseCover();
activity一直叠加时，会oom。
log:  at com.shuyu.gsyvideoplayer.render.GSYRenderView.initCover(GSYRenderView.java:77)
                                                     at com.shuyu.gsyvideoplayer.video.base.GSYTextureRenderView.initCover(GSYTextureRenderView.java:184)
                                                     at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.updatePauseCover(GSYVideoView.java:212)
                                                     at com.komoriwu.one.widget.StandardGSYVideoPlayer.changeUiToPauseShow(StandardGSYVideoPlayer.java:487)
                                                     at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.resolveUIState(GSYVideoControlView.java:750)
                                                     at com.shuyu.gsyvideoplayer.video.base.GSYVideoControlView.setStateAndUi(GSYVideoControlView.java:348)
                                                     at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.onVideoPause(GSYVideoView.java:420)
                                                     at com.komoriwu.one.all.detail.VideoCardActivity.onPause(VideoCardActivity.java:258)
                                                     at android.app.Activity.performPause(Activity.java:6996)
                                                     at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1323)

**Comment by CarGuo** [comment]
应该已经加了try  catch 了，应该只有log输出不会影响，你可以选择继承后再重新单独try住oom然后手动GC，或者设置mShowPauseCover为false

**Comment by KomoriWu** [comment]
谢谢，这框架非常好，出现oom跟我的代码也有关系，优化之后，没出现这个问题了。

**Comment by maolubin** [comment]
@KomoriWu 怎么优化的
