### ISSUE TITLE
standardGSYVideoPlayer.startWindowFullscreen(context, true, true);每次切换全屏的时候都会出现这个异常

### ISSUE THREAD

**Issue by xicong** [CarGuo/GSYVideoPlayer#785]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qiuyou.qiuguo/com.qiuyou.qiuguo.ui.MainActivity}: java.lang.ClassCastException: android.view.AbsSavedState$1 cannot be cast to android.widget.HorizontalScrollView$SavedState
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2587)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2659)
                                                                         at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4237)
                                                                         at android.app.ActivityThread.access$1100(ActivityThread.java:169)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:159)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5671)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
                                                                      Caused by: java.lang.ClassCastException: android.view.AbsSavedState$1 cannot be cast to android.widget.HorizontalScrollView$SavedState
                                                                         at android.widget.HorizontalScrollView.onRestoreInstanceState(HorizontalScrollView.java:1667)
                                                                         at android.view.View.dispatchRestoreInstanceState(View.java:13766)
                                                                         at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2899)
                                                                         at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2905)
                                                                         at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2905)
                                                                         at android.view.View.restoreHierarchyState(View.java:13744)
                                                                         at android.support.v4.app.Fragment.restoreViewState(Fragment.java:396)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1445)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                                         at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
                                                                         at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181)
                                                                         at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
                                                                         at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:572)
                                                                         at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
                                                                         at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
                                                                         at android.app.Activity.performStart(Activity.java:6172)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2518)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2659) 
                                                                         at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4237) 
                                                                         at android.app.ActivityThread.access$1100(ActivityThread.java:169) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:159) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5671) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

**Comment by CarGuo** [comment]
1、是否配置了manifest。
2、是否在demo复现。

看起来并不是播放器的问题

**Comment by xicong** [comment]
谢谢提示，是横屏时设置manifest错误导致的
