### ISSUE TITLE
替换了ijk 0.8.4的so文件，报错，targetSdkVersion:25

### ISSUE THREAD

**Issue by Ianstark14** [CarGuo/GSYVideoPlayer#809]
02-07 15:48:55.644 28132-28132/cn.liangzemu.yvieo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: cn.liangzemu.yvieo, PID: 28132
                                                                    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/cn.liangzemu.yvieo-1/lib/arm/libijksdl.so"
                                                                        at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                        at java.lang.System.loadLibrary(System.java:1076)
                                                                        at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(SourceFile:157)
                                                                        at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(SourceFile:169)
                                                                        at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(SourceFile:209)
                                                                        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(SourceFile:205)
                                                                        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(SourceFile:196)
                                                                        at com.shuyu.gsyvideoplayer.GSYVideoManager.<init>(GSYVideoManager.java:203)
                                                                        at com.shuyu.gsyvideoplayer.GSYVideoManager.instance(GSYVideoManager.java:80)
                                                                        at com.shuyu.gsyvideoplayer.GSYVideoPlayer.releaseAllVideos(GSYVideoPlayer.java:1374)
                                                                        at com.shuyu.gsyvideoplayer.utils.ListVideoUtil.start_play(ListVideoUtil.java:157)
                                                                        at cn.liangzemu.yvieo.fragment.FG_Home$10.play_video(FG_Home.java:686)
                                                                        at cn.liangzemu.yvieo.adapter.Adp_Video_Item$ViewHolder$2.onClick(Adp_Video_Item.java:307)
                                                                        at android.view.View.performClick(View.java:5204)
                                                                        at android.view.View$PerformClick.run(View.java:21153)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by CarGuo** [comment]
我在demo中依赖
```
    api "com.shuyu:gsyVideoPlayer-java:4.0.0-beat1"
    api 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.8.4'
    api 'tv.danmaku.ijk.media:ijkplayer-armv5:0.8.4'
    api 'tv.danmaku.ijk.media:ijkplayer-x86:0.8.4'
```

```
 androidTargetSdkVersion = 25
 androidCompileSdkVersion = 25
```
正常工作

**Comment by Ianstark14** [comment]
我刚刚也用了demo,替换之后能正常工作，是我自己的问题，close掉吧
