### ISSUE TITLE
3.0.0升级 4.1.0 播放m3u8文件 报错

### ISSUE THREAD

**Issue by yang0000meng** [CarGuo/GSYVideoPlayer#862]
Build version: 1.0 
Build date: 1979-11-30 00:00:00 
Current date: 2018-03-03 08:05:43 
Device: Unknown Android SDK built for x86 
 
Stack trace:  
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.luren.videocollect-2/base.apk"],nativeLibraryDirectories=[/data/app/com.luren.videocollect-2/lib/x86, /data/app/com.luren.videocollect-2/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libijkffmpeg.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:984)
	at java.lang.System.loadLibrary(System.java:1530)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:179)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:190)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:231)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:227)
	at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:218)
	at com.shuyu.gsyvideoplayer.player.IJKPlayerManager.initVideoPlayer(IJKPlayerManager.java:48)
	at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.initVideo(GSYVideoBaseManager.java:504)
	at com.shuyu.gsyvideoplayer.GSYVideoBaseManager.access$300(GSYVideoBaseManager.java:44)
	at com.shuyu.gsyvideoplayer.GSYVideoBaseManager$MediaHandler.handleMessage(GSYVideoBaseManager.java:469)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by CarGuo** [comment]
demo？？

**Comment by yang0000meng** [comment]
不是demo 
原来正常 
升级版本出现这个错误 
引用so
compile 'com.shuyu:gsyVideoPlayer-java:3.0.0'
    compile 'com.shuyu:gsyVideoPlayer-ex_so:3.0.0'

**Comment by yang0000meng** [comment]
播放这个m3u8 
https://baiduyuan.veryys.com/20180117/NRRCWqm0/index.m3u8 
真实地址是m3u8里面的m3u8文件。

**Comment by CarGuo** [comment]
如果demo没问题，那么你可以clean下你的项目在编译试试
