### ISSUE TITLE
我gif录制了5秒，为啥合成的gif时间这么短啊

### ISSUE THREAD

**Issue by maolubin** [CarGuo/GSYVideoPlayer#886]

**Comment by CarGuo** [comment]
**
     * 生成gif图
     *
     * @param file                    保存的文件路径，请确保文件夹目录已经创建
     * @param pics                    需要转化的bitmap本地路径集合
     * @param delay                   每一帧之间的延时
     * @param inSampleSize            采样率，越大图片越小，越大图片越模糊，需要处理的时长越短
     * @param scaleSize               缩减尺寸比例，对生成的截图进行缩减，越大图片越模糊，需要处理的时长越短
     * @param gsyVideoGifSaveListener 结果回调
     */
    public void createGif(File file, List<String> pics, int delay, int inSampleSize, int scaleSize,
                          final GSYVideoGifSaveListener gsyVideoGifSaveListener)

**Comment by maolubin** [comment]
@CarGuo 我都默认的，我录了多少时间，合成的有多少时间，不能做到吗

**Comment by maolubin** [comment]
@CarGuo  是不是没张图截的时间，@param delay                   每一帧之间的延时  设为一样，时间就一样了

**Comment by CarGuo** [comment]
delay决定快慢长短

**Comment by maolubin** [comment]
@CarGuo 每张截图的时间间隔可以设的把，跟那个延时一样，就时间一样了把

**Comment by maolubin** [comment]
@CarGuo  哥，还有个问题，底部导航栏有音量条吗

**Comment by CarGuo** [comment]
自定义ui可以自行自定义

**Comment by maolubin** [comment]
@CarGuo 哥不要嫌我麻烦，一开始进来怎么让视频比例撑满啊，     /*   GSYVideoType.setShowType(GSYVideoType.SCREEN_MATCH_FULL);
        changeTextureViewShowType();
        if (mTextureView != null)
            mTextureView.requestLayout();*/ 我设了这个，撑满是满了，点下截图奔溃了，获取宽高空指针

**Comment by CarGuo** [comment]
GSYVideoType.setShowType(GSYVideoType.SCREEN_MATCH_FULL); 设置到Application，至于崩溃你可以自己跟踪下

**Comment by maolubin** [comment]
@CarGuo 哥，我延时和截图频率都设成了50还是很快啊

**Comment by maolubin** [comment]
GSYVideoType.setShowType(GSYVideoType.SCREEN_MATCH_FULL);   我这Application 设了，点击截图还是奔溃，我就用demo中的调的，不过我是在播放器类中调的，不是activity中，     at android.graphics.Bitmap.createBitmap(Bitmap.java:815)
                                                           at android.graphics.Bitmap.createBitmap(Bitmap.java:794)
                                                           at android.graphics.Bitmap.createBitmap(Bitmap.java:761)
                                                           at com.shuyu.gsyvideoplayer.render.view.GSYTextureView.initCover(GSYTextureView.java:117)
                                                           at com.shuyu.gsyvideoplayer.render.view.GSYTextureView.taskShotPic(GSYTextureView.java:145)
                                                           at com.shuyu.gsyvideoplayer.render.GSYRenderView.taskShotPic(GSYRenderView.java:140)
                                                           at cn.cntv.app.baselib.pandavideo.video.SampleIpandaVideo.taskShotPic(SampleIpandaVideo.java:1972)
                                                           at cn.cntv.app.baselib.pandavideo.video.SampleIpandaVideo.taskShotPic(SampleIpandaVideo.java:1961)
                                                           at cn.cntv.app.baselib.pandavideo.video.SampleIpandaVideo.shotImage(SampleIpandaVideo.java:933)
                                                           at cn.cntv.app.baselib.pandavideo.video.SampleIpandaVideo.onClick(SampleIpandaVideo.java:701)

**Comment by maolubin** [comment]
@CarGuo 录制gif产生的tmp后缀文件不会自己删除吗

**Comment by CarGuo** [comment]
这个要你自己删除
