### ISSUE TITLE
哥，怎么屏蔽手机旋转视频也旋转啊

### ISSUE THREAD

**Issue by maolubin** [CarGuo/GSYVideoPlayer#918]
orientationUtils.setEnable(false);
    videoPlayer.setRotateViewAuto(false); 我都是设了，全屏时手机点击解锁按钮，奔溃了

                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setImageResource(int)' on a null object reference
                                                                      at com.shuyu.gsyvideoplayer.utils.OrientationUtils$1.onOrientationChanged(OrientationUtils.java:86)
                                                                      at android.view.OrientationEventListener$SensorEventListenerImpl.onSensorChanged(OrientationEventListener.java:143)
                                                                      at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:515)
                                                                      at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                      at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                      at android.os.Looper.loop(Looper.java:144)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5845)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)

**Comment by CarGuo** [comment]
demo中哪里复现
