### ISSUE TITLE
哥，貌似有个大问题，全屏后，然后跳转另一个页面，播放不了

### ISSUE THREAD

**Issue by maolubin** [CarGuo/GSYVideoPlayer#939]

**Comment by maolubin** [comment]
经过验证，跳普通页面是没事的，我是全屏分享时跳qq分享，qq登录页也是个播放视频的，然后返回，视频就放不了了。

日志因为是直播，我注释了 getGSYVideoManager().getMediaPlayer().seekTo(mCurrentPosition); 这句，这句一样会奔溃。
java.lang.IllegalStateException: mpjni: start: null mp
                                                             at tv.danmaku.ijk.media.player.IjkMediaPlayer._start(Native Method)
                                                             at tv.danmaku.ijk.media.player.IjkMediaPlayer.start(IjkMediaPlayer.java:522)
                                                             at com.shuyu.gsyvideoplayer.video.base.GSYVideoView.onVideoResume(GSYVideoView.java:512)
                                                             at cn.cntv.app.baselib.pandavideo.video.SampleIpandaVideo.onVideoResume(SampleIpandaVideo.java:846)
                                                             at cn.cntv.app.baselib.pandavideo.video.SampleIpandaVideo.onClick(SampleIpandaVideo.java:941)
                                                             at android.view.View.performClick(View.java:5226)
                                                             at android.view.View$PerformClick.run(View.java:21266)
                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                             at android.os.Looper.loop(Looper.java:168)
                                                             at android.app.ActivityThread.main(ActivityThread.java:5845)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)

**Comment by maolubin** [comment]
@CarGuo  
    /**
     * 监听是否有外部其他多媒体开始播放
     */
    protected AudioManager.OnAudioFocusChangeListener onAudioFocusChangeListener = new AudioManager.OnAudioFocusChangeListener() {  

是这个监听把视频销毁了吗

**Comment by maolubin** [comment]
@CarGuo 原因就是那个，我把mReleaseWhenLossAudio 直接设为false了
